<td><?php echo $this->escape(($this->required ? '*' : '') . $this->label); ?>:</td>

<td id="<?php echo $this->escape($this->tableId); ?>">
    <img alt="<?php echo $this->escape($this->defaultImageId); ?>"
    src="<?php echo $this->escape($this->defaultImage); ?>">
</td>

<script type="text/javascript">
    YAHOO.util.Event.onDOMReady(function() {
        var imagePicker = new Fisma.ImagePicker(
            <?php echo $this->escape($this->properties, 'json'); ?>
        );
    });
</script>
