<?php

echo $this->escape($this->partial('/incident-report/toolbar.phtml'), 'none');

Fisma_Format_Section::startSection($this->title);
?>
<div id="history">
    <table id="historyTable">
        <thead>
            <tr>
                <th>Incidents</th>
                <?php
                foreach ($this->months as $month):
                ?>
                    <th><?=$this->escape($month) ?></th>
                <?php
                endforeach;
                ?>
            </tr>
        </thead>
    
        <tbody>
            <?php
            foreach ($this->history as $action => $history):
            ?>
                <tr>
                    <td><?=$this->escape($action) ?></td>
                    
                    <?php
                    foreach($this->months as $columnName => $monthName):
                    ?>
                        <td><?=$this->escape($history['i_' . $columnName]) ?></td>
                    <?php
                    endforeach;
                    ?>
                </tr>
            <?php
            endforeach;
            ?>
        </tbody>
    </table>
</div>
<?php
Fisma_Format_Section::stopSection();
?>

<script type="text/javascript">
// Convert the HTML table above into a YUI table
YAHOO.util.Event.onContentReady('history', function() {
    <?php
        $keys = "{key:'incidents', label:'Incidents', sortable: true},";

        foreach ($this->months as $columnName => $monthName) {
            $keys .= "{key: '" . $this->escape($columnName)
                   . "', label:'" . $this->escape($monthName)
                   . "', sortable:true},";
        }
        $keys = rtrim($keys, ',');
    ?>
    var myColumnDefs = [<?=$this->escape($keys, 'none')?>];

    this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("historyTable"));
    this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
    this.myDataSource.responseSchema = {
        fields: [<?=$this->escape($keys, 'none') ?>]
    };

    this.myDataTable = new YAHOO.widget.DataTable("history", myColumnDefs, this.myDataSource, {});
});
</script>
