<div class="searchFilters">
    <div class="left">
        <?php
        $exportXlsButton = new Fisma_Yui_Form_Button_Link(
            'exportXls',
            array(
                'value' => 'Export Excel',
                'href' => Fisma_Url::currentUrl() . '/format/xls',
                'imageSrc' => '/images/xls.gif'
            )
        );
        echo $this->escape($exportXlsButton, 'none');
            
        $exportPdfButton = new Fisma_Yui_Form_Button_Link(
            'exportPdf',
            array(
                'value' => 'Export PDF',
                'href' => Fisma_Url::currentUrl() . '/format/pdf',
                'imageSrc' => '/images/pdf.gif'
            )
        );
        echo $this->escape($exportPdfButton, 'none');
        ?>
    </div>
    <div class="clear">
    </div>        
</div>
