<div class="searchFilters">
    <div class="left">
        <?php 
        $listButton = new Fisma_Yui_Form_Button_Link('listButton', 
                                               array('value' => 'IR Workflow List', 
                                                     'imageSrc' => '/images/view_list.png',                                            
                                                     'href' => '/panel/irworkflow/sub/list'));
        echo $listButton;
        ?>
    
        <?php 
        $listButton = new Fisma_Yui_Form_Button_Link('treetButton', 
                                               array('value' => 'IR Workflow Tree',
                                                     'imageSrc' => '/images/view_tree.png', 
                                                     'href' => '/panel/irworkflow/sub/tree'));
        echo $listButton;
        ?>

        <?php if(Fisma_Acl::hasPrivilege('irworkflow', 'create')) {
        $createButton = new Fisma_Yui_Form_Button_Link('createButton', 
                                               array('value' => 'Add IR Workflow', 
                                                     'imageSrc' => '/images/add.png',
                                                     'href' => '/panel/irworkflow/sub/create'));
        echo $createButton;
        
        $createButton = new Fisma_Yui_Form_Button_Link('subCcreateButton', 
                                               array('value' => 'Add IR Workflow Step', 
                                                     'imageSrc' => '/images/add.png',
                                                     'href' => '/panel/irworkflow/sub/step_create'));
        echo $createButton;
        } 
        ?>
    </div>
    <div class="clear"></div>
</div>
