<script>
$(document).ready(function(){
	switchYear();
});

function switchYear(step){
    if( !isFinite(step) ){
        step = 0;
    }
    var year = $("span[name=gen_shortcut]").attr('year');
    year = Number(year) + Number(step);
	$("span[name=gen_shortcut]").attr('year', year);
    var url = $("span[name=gen_shortcut]").attr('url')+year+'/';
    $("span[name=year]").html( year );
    $("span[name=year]").parent().attr( 'href', url);
    $("span[name=q1]").parent().attr( 'href', url+'q/1/' );
    $("span[name=q2]").parent().attr( 'href', url+'q/2/' );
    $("span[name=q3]").parent().attr( 'href', url+'q/3/' );
    $("span[name=q4]").parent().attr( 'href', url+'q/4/' );
}
</script>
<?php 
    $url ="/panel/report/sub/fisma/s/search";
    if(! empty($this->criteria['systemId'])) {
        $url .='/system/'.$this->criteria['systemId'];
    }
    if(! empty($this->criteria['year'])) {
        $url .='/y/'.$this->criteria['year'];
    }
    if(! empty($this->criteria['quarter'])) {
        $url .='/q/'.$this->criteria['quarter'];
    }
    if(! empty($this->criteria['startdate'])) {
        $url .='/startdate/'.$this->criteria['startdate'];
    }
    if(! empty($this->criteria['enddate'])) {
        $url .='/enddate/'.$this->criteria['enddate'];
    }
?>
<?php //Fisma_Format_Section::startSection("FISMA Report to OMB"); ?>

<form name="filter" method="post" action="/panel/report/sub/fisma/s/search">
<table class="searchFilters">
    <tr>
        <td >
            <?php 
                $this->system_list[0] = 'All Systems';
                echo $this->formSelect('system',
                                       isset($this->criteria['systemId'])?$this->criteria['systemId']:0,
                                       null,$this->system_list);
            ?>
        </td>
        <td>From:<input type="text" class="date" name="startdate" value="<?php 
            echo isset($this->criteria['startdate'])?$this->criteria['startdate']:'';
            ?>" size="10" maxlength="10" url="">
        </td>
        <td>To:
        <input type="text" class="date" name="enddate" value="<?php 
            echo isset($this->criteria['enddate'])?$this->criteria['enddate']:'';
            ?>" size="10" maxlength="10" url=""></td>
        <td>
            <?php echo new Fisma_Yui_Form_Button_Submit('generateFismaReport', array('value' => 'Generate Report')); ?>
        </td>
    </tr>
    <tr>
        <td colspan="4">
            Generate Report shortcut:
                    <span name="gen_shortcut" url="/panel/report/sub/fisma/s/search/y/" year="<?php echo $this->year;?>">
                        <a href="javascript:switchYear(-1);" style="text-decoration: none;" ><<</a>&nbsp
                        <a href="" style="text-decoration: none;" ><span name="year"></span></a>&nbsp;
                        <a href="" style="text-decoration: none;" ><span name="q1">Q1</span></a>&nbsp;
                        <a href="" style="text-decoration: none;" ><span name="q2">Q2</span></a>&nbsp;
                        <a href="" style="text-decoration: none;" ><span name="q3">Q3</span></a>&nbsp;
                        <a href="" style="text-decoration: none;" ><span name="q4">Q4</span></a>&nbsp;
                        <a href="javascript:switchYear(1);" style="text-decoration: none;">>></a>
                    </span>
        </td>
    </tr>
</table>
</form>

<?php //Fisma_Format_Section::stopSection(); ?>
<?php
    if(isset($this->summary)){
        echo $this->partial('report/fismasearch.phtml',array('summary'=>&$this->summary,'url'=>&$url));
    }
?>
