<div class="barleft">
<div class="barright">
<p><b>FISMA Report to OMB:<?php echo $this->startdate;?>throw <?php echo $this->enddate;?></b>    <span>
    Export to:
    <a target='_blank' href="<?php echo $this->url.'/format/pdf'; ?>"><img src="/images/pdf.gif" border="0"></a>
    <a href="<?php echo $this->url.'/format/xls'; ?>"><img src="/images/xls.gif" border="0"></a>
    </span>
</div>
</div>
<br>
<table align="center" class="tipframe" style="width:95%">
    <tr align="center">
        <td colspan="5"  bgcolor="#DFE5ED"><b>FISMA Report to OMB: POA&amp;M Status Report</b></td>
    </tr>
    <tr align="center">
        <td colspan="5"  bgcolor="#DFE5ED">
            <table width="100%" border="0" cellspacing="0" cellpadding="4">
                <tr align="center">
                    <th width="50%">POA&amp;M Status Information
                    <th width="15%">Agency Wide
                    <th width="15%">System
                    <th width="15%">Total
                    <th width="15%" nowrap>Brief Explanation</tr>
                <tr>
                    <td width="50%" class="tdc">
                        A. Total number of weaknesses identified at the start of the reporting period
                    </td>
                    <td width="15%" class="tdc"><?php echo $this->summary['AAW'];?></td>
                    <td width="15%" class="tdc"><?php echo $this->summary['AS'];?></td>
                    <td width="15%" class="tdc"><?php echo $this->summary['AAW']+$this->summary['AS'];?></td>
                    <td width="15%" bgcolor="#DFDFDF" class="tdc">&nbsp;</td>
                </tr>
                <tr>
                    <td width="50%" class="tdc">
                        B. Number of weaknesses for which corrective action was completed on time(including testing) by the end of the reporting period
                    </td>
                    <td width="15%" class="tdc"><?php echo $this->summary['BAW'];?></td>
                    <td width="15%" class="tdc"><?php echo $this->summary['BS'];?></td>
                    <td width="15%" class="tdc"><?php echo $this->summary['BAW']+$this->summary['BS'];?></td>
                    <td width="15%" bgcolor="#DFDFDF" class="tdc">&nbsp;</td>
                </tr>
                <tr>
                    <td width="50%" class="tdc">
                        C. Number of weaknesses for which corrective action is ongoing and is on track to complete as originally scheduled
                    </td>
                    <td width="15%" class="tdc"><?php echo $this->summary['CAW'];?></td>
                    <td width="15%" class="tdc"><?php echo $this->summary['CS'];?></td>
                    <td width="15%" class="tdc"><?php echo $this->summary['CAW']+$this->summary['CS'];?></td>
                    <td width="15%" bgcolor="#DFDFDF" class="tdc">&nbsp;</td>
                </tr>
                <tr>
                    <td width="50%" class="tdc">
                        D. Number of weaknesses for which corrective action has been delayed including a brief explanation for the delay
                    </td>
                    <td width="15%" class="tdc"><?php echo $this->summary['DAW'];?></td>
                    <td width="15%" class="tdc"><?php echo $this->summary['DS'];?></td>
                    <td width="15%" class="tdc"><?php echo $this->summary['DAW']+$this->summary['DS'];?></td>
                    <td width="15%" class="tdc">&nbsp;</td>
                </tr>
                <tr>
                    <td width="50%" class="tdc">
                        E. Number of weaknesses discovered following the last POA&amp;M update and a brief Explanation of how they were identified (e.g., agency review, IG evaluation, etc.)
                    </td>
                    <td width="15%" class="tdc"><?php echo $this->summary['EAW'];?></td>
                    <td width="15%" class="tdc"><?php echo $this->summary['ES'];?></td>
                    <td width="15%" class="tdc"><?php echo $this->summary['EAW']+$this->summary['ES'];?></td>
                    <td width="15%" class="tdc">&nbsp;</td>
                </tr>
                <tr>
                    <td width="50%" class="tdc" nowrap>
                        Total number of weaknesses remaining at the end of the reporting period
                    </td>
                    <td width="15%" class="tdc"><?php echo $this->summary['FAW'];?></td>
                    <td width="15%" class="tdc"><?php echo $this->summary['FS'];?></td>
                    <td width="15%" class="tdc"><?php echo $this->summary['FAW']+$this->summary['FS'];?></td>
                    <td width="15%" bgcolor="#DFDFDF" class="tdc">&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
</table>
