<?php 
$type_list = array('' =>'Please Select Report',
                   '1'=>'NIST Baseline Security Controls Report',
                   '2'=>'FIPS 199 Categorization Breakdown',
                   '3'=>'Products with Open Vulnerabilities',
                   '4'=>'Software Discovered Through Vulnerability Assessments',
                   '5'=>'Total # of Systems /w Open Vulnerabilities');
$action_list = array(1=>'blscr',2=>'fips',3=>'prods',4=>'swdisc',5=>'total');
?>
<form name="filter" method="post" action="/panel/report/sub/general/s/search">

<table cellpadding="5" class="searchFilters">
    <tr>
        <td>Report:</td>
        <td>
            <?php echo $this->formSelect('type',$this->type,null,$type_list);?>
        </td>
        <td>
            <?php echo new Fisma_Yui_Form_Button_Submit('generateGeneralReport', array('value' => 'Generate Report')); ?>
        </td>
    </tr>
</table>

</form>

<?php
    if(!empty($this->type)){
        $url = "/report/".$action_list[$this->type];
?>
<?php Fisma_Format_Section::startSection("Report: {$type_list[$this->type]}"); ?>

<span>
<a target='_blank' href="<?php echo $url.'/format/pdf'; ?>"><img src="/images/pdf.gif" border="0"></a>
<a href="<?php echo $url.'/format/xls'; ?>"><img src="/images/xls.gif" border="0"></a>
</span>

<?php } ?>

