<?php
	$currentYear = date('Y');
	$year_list[0] = 'All Fiscal Year';
	for ($year=2005;$year<=$currentYear;$year++) {
		$year_list[$year] = $year;
	}
    $overdue['type'] = array( 'sso' =>'SSO Approval overdue',
                         'action'   =>'Course of Action overdue');
    $overdue['day'] = array('1' => '0-29 days',
                            '2' => '30-59 days',
                            '3' => '60-89 days',
                            '4' => '90-119 days',
                            '5' => '120 and greater days');
    $this->system_list[0] ='--Any--';
    $this->source_list[0] ='--Any--';
    $url = "/panel/report/sub/overdue/s/search";
?>
<?php //Format_Section::startSection("Overdue Reports"); ?>

<form name="overdue_report" method="post" action="/panel/report/sub/overdue/s/search">
<table class="searchFilters">
    <tr>
        <td><b>System </b></td>
        <td>
        <?php echo $this->formSelect('system_id',
                                     isset($this->params['system_id'])?$this->params['system_id']:0, 
                                     null,$this->system_list);
              if( !empty($this->params['system_id']) ) {
                  $url .= '/system_id/'.$this->params['system_id'];
              }
        ?>
        </td>
        <td><b>Source</b></td>
        <td>
        <?php echo $this->formSelect('source_id',
                                     isset($this->params['source_id'])?$this->params['source_id']:0, 
                                     null,$this->source_list);
              if( !empty($this->params['source_id']) ) {
                  $url .= '/source_id/'.$this->params['source_id'];
              }
        ?>
        </td>
        <td><b>Fiscal Year</b></td>
        <td>
        <?php echo $this->formSelect('year',
                                     isset($this->params['year'])?$this->params['year']:0, 
                                     null,$year_list);
              if( !empty($this->params['year']) ) {
                  $url .= '/year/'.$this->params['year'];
              }
        ?>
        </td>
    </tr>
    <tr>
        <td><b>Overdue type</b></td>
        <td >
        <?php echo $this->formSelect('overdue_type',
                                    isset($this->params['overdue_type'])?$this->params['overdue_type']:0,
                                    null,$overdue['type']);
        ?>
        </td>
        <td><b>Overdue </b></td>
        <td> 
        <?php echo $this->formSelect('overdue_day',
                                    isset($this->params['overdue_day'])?$this->params['overdue_day']:0,
                                    null,$overdue['day']);
        ?>
        </td>
        <td height="39" colspan="2">
            <?php echo new Yui_Form_Button_Submit('generateOverdueReport', array('value' => 'Generate Report')); ?>
        </td>
    </tr>
</table>
</form>

<?php Format_Section::stopSection(); ?>

<?php if( !empty($this->poam_list) ) { ?>
<?php Format_Section::startSection("Poam Search Results"); ?>
    <span>
    <?php echo $this->links['all']; ?>
    <a target='_blank' href="<?php echo $this->url.'/format/pdf'; ?>"><img src="/images/pdf.gif" border="0"></a>
    <a href="<?php echo $this->url.'/format/xls'; ?>"><img src="/images/xls.gif" border="0"></a>
    </span>
<table width="95%" align="center" border="0" cellpadding=5" cellspacing="0" class="tbframe">
    <tr align="center">
        <th class="tdc">System</th>
        <th class="tdc">ID#</th>
        <th class="tdc">Description</th>
        <th class="tdc">Type</th>
        <th class="tdc">Status</th>
        <th class="tdc">Source</th>
        <th class="tdc">Server/Database</th>
        <th class="tdc">Location</th>
        <th class="tdc">Risk Level</th>
        <th class="tdc">Recommendation</th>
        <th class="tdc">Corrective Action</th>
        <th class="tdc">ECD</th>
    </tr>
    <?php foreach($this->poam_list as  $row){ ?>
    <tr>
        <td class="tdc" align="center"><?php echo $this->system_list[$row['system_id']];?></td>
        <td class="tdc" align="center"><?php echo $row['id'];?></td>
        <td class="tdc"><?php echo $row['finding_data'];?></td>
        <td class="tdc" ><?php echo $row['type'];?></td>
        <td class="tdc" align="center"><?php echo $row['status'];?></td>
        <td class="tdc" align="center">
        <?php $id = &$row['source_id'];
            if( empty($id) ){
                echo 'N/A';
            }else{ 
                echo $this->source_list[$id];
            }
        ?>
        </td>
        <td class="tdc"><?php echo $row['ip'];?></td>
        <td class="tdc" >
        <?php $id = &$row['network_id'];
            if( empty($id) ){
                echo 'N/A';
            }else{ 
                echo $this->network_list[$id];
            }
        ?>
        </td>
        <td class="tdc" align="center"><?php echo $row['threat_level'];?></td>
        <td class="tdc"><?php echo $row['action_suggested'];?></td>
        <td class="tdc"><?php echo $row['action_planned'];?></td>
        <td class="tdc" align="center"><?php echo $row['action_current_date'];?></td>
    </tr>
    <?php } ?>
</table>

<?php } ?>

<?php Format_Section::stopSection(); ?>
