<?php
$output_cols = array(
'System',
'Overdue Action Type',
'<30 Days',
'30+ Days',
'60+ Days',
'90+ Days',
'120+ Days',
'Total Overdue',
'Average Overdue Amount (days)',
'Maximum Overdue Amount (days)');

$count_cols = count($output_cols);

require_once ('Spreadsheet/Excel/Writer.php'); // need fix 

$workbook  = new Spreadsheet_Excel_Writer();
$workbook->setVersion(8); // fixes 255 char truncation issue

$worksheet =& $workbook->addWorksheet();

$format_header =& $workbook->addFormat(array('Size' => 10,
    'Align' => 'center',
    'Color' => 'white',
    'FgColor' => 'black',
    ));
$format_header->setFontFamily('Times New Roman');

$format_times =& $workbook->addFormat(array('Size' => 10,
    'Align' => 'center',
    'Color' => 'black',
    'BorderColor '=> 'blue',
    'Bottom'=>1,'Top'=>1,'Left'=>1,'Right'=>1
    ));
$format_times->setFontFamily('Times New Roman');

$rowi=0;
$headinfo="Report run time: ".date("Y-m-d H:i:s");
$worksheet->write($rowi++, 0, $headinfo,$format_times);
$worksheet->mergeCells($rowi,0,$rowi,2);
$worksheet->write($rowi++, 0, 'Results',$format_header);
$worksheet->setColumn(0,1,20);
$worksheet->setColumn(2,6,10);
$worksheet->setColumn(7,7,20);
$worksheet->setColumn(8,9,30);
//inject the titles
$worksheet->writeRow($rowi++,0,$output_cols,$format_times);

foreach( $this->poam_list as $p) {
    $totalOverdue = $p['lessThan30'] + $p['moreThan30'] + $p['moreThan60']
         + $p['moreThan90'] + $p['moreThan120'];
    $data = array(
        $p['systemNickname'] . ' - ' .$p['systemName'],
        $p['type'],
        $p['lessThan30'],
        $p['moreThan30'],
        $p['moreThan60'],
        $p['moreThan90'],
        $p['moreThan120'],
        $totalOverdue,
        sprintf('%.1f', array_sum($p['diffDay'])/$totalOverdue),
        max($p['diffDay']));
    $worksheet->writeRow($rowi++,0,$data,$format_times); 
}

$worksheet->setHeader("                            ".$headinfo);
$workbook->send('report.xls');
$workbook->close();

?>
