<?php
	$currentYear = date('Y');
	$year_list[0] = 'All Fiscal Year';
	for ($year=2005;$year<=$currentYear;$year++) {
		$year_list[$year] = $year;
	}
    $overdue['type'] = array('any' => '--Any--',
                         'sso' =>'Mitigation Strategy',
                         'action'   =>'Corrective Action');
    $overdue['day'] = array('1' => '< 30 days',
                            '2' => '30+ days',
                            '3' => '60+ days',
                            '4' => '90+ days',
                            '5' => '120+ days');
    $this->system_list[0] ='--Any--';
    $this->source_list[0] ='--Any--';
    $url = "/panel/report/sub/overdue/s/search";
?>
<?php //Format_Section::startSection("Overdue Reports"); ?>

<form name="overdue_report" method="post" action="/panel/report/sub/overdue/s/search">
<table class="searchFilters">
    <tr>
        <td><b>System </b></td>
        <td>
        <?php echo $this->formSelect('system_id',
                                     isset($this->params['system_id'])?$this->params['system_id']:0, 
                                     null,$this->system_list);
              if( !empty($this->params['system_id']) ) {
                  $url .= '/system_id/'.$this->params['system_id'];
              }
        ?>
        </td>
        <td><b>Source</b></td>
        <td>
        <?php echo $this->formSelect('source_id',
                                     isset($this->params['source_id'])?$this->params['source_id']:0, 
                                     null,$this->source_list);
              if( !empty($this->params['source_id']) ) {
                  $url .= '/source_id/'.$this->params['source_id'];
              }
        ?>
        </td>
        <td><b>Fiscal Year</b></td>
        <td>
        <?php echo $this->formSelect('year',
                                     isset($this->params['year'])?$this->params['year']:0, 
                                     null,$year_list);
              if( !empty($this->params['year']) ) {
                  $url .= '/year/'.$this->params['year'];
              }
        ?>
        </td>
    </tr>
    <tr>
        <td><b>Overdue type</b></td>
        <td >
        <?php echo $this->formSelect('overdue_type',
                                    isset($this->params['overdue_type'])?$this->params['overdue_type']:0,
                                    null,$overdue['type']);
        ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td height="39" colspan="2">
            <?php echo new Yui_Form_Button_Submit('generateOverdueReport', array('value' => 'Generate Report')); ?>
        </td>
    </tr>
</table>
</form>

<?php Format_Section::stopSection(); ?>

<?php if( !empty($this->poam_list) ) { ?>
<?php Format_Section::startSection("Poam Search Results"); ?>
    <span>
    <?php echo $this->links['all']; ?>
    <a target='_blank' href="<?php echo $this->url.'/format/pdf'; ?>"><img src="/images/pdf.gif" border="0"></a>
    <a href="<?php echo $this->url.'/format/xls'; ?>"><img src="/images/xls.gif" border="0"></a>
    </span>
<table width="95%" align="center" border="0" cellpadding=5" cellspacing="0" class="tbframe">
        <tr align="center">
        <th class="tdc">System</th>
        <th class="tdc">Overdue Action Type</th>
        <th class="tdc"><30 Days</th>
        <th class="tdc">30+ Days</th>
        <th class="tdc">60+ Days</th>
        <th class="tdc">90+ Days</th>
        <th class="tdc">120+ Days</th>
        <th class="tdc">Total Overdue</th>
        <th class="tdc">Average Overdue Amount (days)</th>
        <th class="tdc">Maximum Overdue Amount (days)</th>
    
    <?php 

    foreach($this->poam_list as $row) {
    ?>
    <tr>
        <td class="tdc" align="center"><?php echo $row['systemName'];?></td>
        <td class="tdc" align="center"><?php echo $row['type'];?></td>
        <td class="tdc" align="center"><?php echo $row['lessThan30'];?></td>
        <td class="tdc" align="center"><?php echo $row['moreThan30'];?></td>
        <td class="tdc" align="center"><?php echo $row['moreThan60'];?></td>
        <td class="tdc" align="center"><?php echo $row['moreThan90'];?></td>
        <td class="tdc" align="center"><?php echo $row['moreThan120'];?></td>
        <td class="tdc" align="center">
        <?php $totalOverdue = $row['lessThan30'] + $row['moreThan30'] 
        + $row['moreThan60'] + $row['moreThan90'] + $row['moreThan120'];
        echo $totalOverdue;?>
        </td>
        <td class="tdc" align="center"><?php echo sprintf('%.1f', array_sum($row['diffDay'])/$totalOverdue);?></td>
        <td class="tdc" align="center"><?php echo max($row['diffDay']) ;?></td>
    </tr>
    <?php } ?>
</table>

<?php } ?>

<?php Format_Section::stopSection(); ?>
