<?php Fisma_Format_Section::startSection("Plug-in Reports"); ?>

<div id="container">
    <table id='reportTable'>
        <thead>
            <tr>
                <th>Report</th>
                <th>Description</th>
                <th>Roles</th>
            </tr>
        </thead>
        <?php
            foreach ($this->reports as $reportName => $reportParams) {
                // Use the @ operator to suppress any warnings about undefined indexes. 
                // This data is defined in the reports.conf file, so it may not have every index defined.
                @print "<tr><td class='tdc'>
                        <a href=\"/panel/report/sub/plugin-report/name/{$reportName}\">{$reportParams['title']}</a></td>
                        <td class='tdc'>{$reportParams['description']}</td>";
                $rolesString = implode(', ', $reportParams['roles']);
                @print "<td class='tdc'>$rolesString</td></tr>";
            }
        ?>
    </table>
</div>

<?php Fisma_Format_Section::stopSection(); ?>

<script type="text/javascript">
// Convert the HTML table above into a YUI table
YAHOO.util.Event.onContentReady('container', function() {
    var myColumnDefs = [
        {key:"report", label:"Report", sortable:true},
        {key:"description", label:"Description", sortable:false},
        {key:"roles", label:"Roles", sortable:false}
    ];

    this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("reportTable"));
    this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
    this.myDataSource.responseSchema = {
        fields: [{key:"report"},
                {key:"description"},
                {key:"roles"}
        ]
    };

    this.myDataTable = new YAHOO.widget.DataTable("container", myColumnDefs, this.myDataSource, {});
});
</script>
