<div class="barleft">
    <div class="barright">
        <p><b>Plug-in Reports</b></p>
    </div>
</div>


<table class="tbframe">
    <tr>
        <th>Report</th>
        <th>Description</th>
        <th>Roles</th>
    </tr>
<?php
foreach ($this->reports as $reportName => $reportParams) {
    // Use the @ operator to suppress any warnings about undefined indexes. This data is defined in the reports.conf
    // file, so it may not have every index defined.
    @print "<tr><td class='tdc'>
            <a href=\"/panel/report/sub/plugin-report/name/{$reportName}\">{$reportParams['title']}</a></td>
            <td class='tdc'>{$reportParams['description']}</td>";
    $rolesString = implode(', ', $reportParams['roles']);
    @print "<td class='tdc'>$rolesString</td></tr>";
}
?>
</table>