<?php Fisma_Format_Section::startSection($this->title); ?>

<div class="toolbar">
    <?php
    $exportPdfButton = new Fisma_Yui_Form_Button_Link('exportPdf',
                                  array('value' => 'Export PDF',
                                        'href' => "$this->url/format/pdf",
                                        'imageSrc' => '/images/pdf.gif'));
    echo $this->escape($exportPdfButton, 'none');
    $exportExcelButton = new Fisma_Yui_Form_Button_Link('exportExcel',
                                  array('value' => 'Export Excel',
                                        'href' => "$this->url/format/xls",
                                        'imageSrc' => '/images/xls.gif'));
    echo $this->escape($exportExcelButton, 'none');
    ?>
</div>

<div id="container">
    <table id="reportTable">
        <thead>
            <tr>
                <?php foreach ($this->columns as $column) : ?>
                <th class="tdc"><?php echo $this->escape($column)?></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->rows as $row) : ?>
        <tr>
            <?php foreach($row as $cell) : ?>
                <td><?php echo $this->escape($cell)?></td>
            <?php endforeach; ?>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php Fisma_Format_Section::stopSection(); ?>

<script type="text/javascript">
// Convert the HTML table above into a YUI table
YAHOO.util.Event.onContentReady('container', function() {
    <?php
        $defs = array();
        $fields = array();
        foreach ($this->columns as $column) {
            $defs[] = "{key:'" . $this->escape($column, 'javascript')
                      . "', label:'" . $this->escape($column, 'javascript')
                      . "', sortable:true}";
            $fields[] = "{key:'" . $this->escape($column, 'javascript') . "'}";
        }
        $defs = implode(',', $defs);
        $fields = implode(',', $fields);
    ?>
    var myColumnDefs = [<?php echo $this->escape($defs, 'none')?>];

    this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("reportTable"));
    this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
    this.myDataSource.responseSchema = {
        fields: [<?php echo $this->escape($fields, 'none')?>]
    };

    this.myDataTable = new YAHOO.widget.DataTable("container", myColumnDefs, this.myDataSource, {});
});
</script>
