<?php Fisma_Format_Section::startSection($this->title); ?>
    <p>
        <a href="<?php echo $_SERVER['REQUEST_URI']; ?>/format/pdf"><img src="/images/pdf.gif" border="0"></a>
        <a href="<?php echo $_SERVER['REQUEST_URI']; ?>/format/xls"><img src="/images/xls.gif" border="0"></a>
    </p>

<table class="tbframe">
    <tr>
<?php  
    foreach ($this->columns as $column) {
        print "<th class=\"tdc\">$column</td>";
    }
?>
    </tr>
<?php
    foreach ($this->rows as $row) {
        print '<tr>';
        foreach ($row as $cell) {
            print "<td>$cell</td>";
        }
        print '</tr>';
    }
?>
</table>

<?php Fisma_Format_Section::stopSection(); ?>
