<form action="/report/rafs" method="post">
<script type="text/javascript">
var clearWarning = function(){
    var ele = document.getElementById('msgbar');
    ele.parentNode.removeChild(ele);
}
</script>

<div class="searchFilters">
<b>
    Organization/System:
</b>
    <?php echo $this->formSelect('system_id',
                                 $this->sid,
                                 null,
                                 $this->organizations);?>

    <?php $submitBtn = new Fisma_Yui_Form_Button_Submit('generateRafsSubmit', 
                                                  array('label' => 'Generate RAFS',
                                                        'onClickFunction' => 'clearWarning'));
          echo $submitBtn;
     ?>
</div>
