<?php Format_Section::startSection("Generate Risk Analysis Forms (RAFs)"); ?>

<form action="/report/rafs" method="post">

<table class="searchFilters">
<tr>
    <td><b>System:</b></td>
    <td>
    <?php echo $this->formSelect('system_id',
                                 $this->sid,
                                 null,
                                 $this->system_list);?>

    <?php echo new Yui_Form_Button_Submit('Generate RAFS', 'generateRafsSubmit'); ?>
   <!-- @yui review: <input type="submit" onclick="$('#msgbar').remove()"> -->
    </td>
</tr>
</table>
</form>

<?php Format_Section::stopSection(); ?>
