<?php Fisma_Format_Section::startSection("Generate Risk Analysis Forms (RAFs)"); ?>

<form action="/report/rafs" method="post">
<script type="text/javascript">
var clearWarning = function(){
    var ele = document.getElementById('msgbar');
    ele.parentNode.removeChild(ele);
}
</script>
<table class="searchFilters">
<tr>
    <td><b>System:</b></td>
    <td>
    <?php echo $this->formSelect('system_id',
                                 $this->sid,
                                 null,
                                 $this->system_list);?>

    <?php $submitBtn = new Fisma_Yui_Form_Button_Submit('generateRafsSubmit', 
                                                  array('label' => 'Generate RAFS',
                                                        'onClickFunction' => 'clearWarning'));
          echo $submitBtn;
     ?>
    </td>
</tr>
</table>
</form>
<?php Fisma_Format_Section::stopSection(); ?>
