<?php
foreach ($this->partialViews as $script => $args):
    echo $this->partial($script, $args);
endforeach;
?>

<div class="searchFilters">
    <div class="left">
        <?php
        if (isset($this->exportXlsButton)):
            echo $this->escape($this->exportXlsButton, 'none');
        endif;

        if (isset($this->exportPdfButton)):            
            echo $this->escape($this->exportPdfButton, 'none');
        endif;
        ?>
    </div>
    
    <?php if (isset($this->form)): ?>
        <div class="right">
            <?php echo $this->escape($this->form, 'none'); ?>
        </div>
    <?php endif; ?>
    
    <div class="clear"></div>        
</div>

<?php
Fisma_Format_Section::startSection($this->title);

echo $this->escape($this->dataTable, 'none');

Fisma_Format_Section::stopSection();
?>
