<div class="searchFilters">
    <div class="left">
        <?php
        if (isset($this->exportXlsButton)):
            echo $this->escape($this->exportXlsButton, 'none');
        endif;

        if (isset($this->exportPdfButton)):            
            echo $this->escape($this->exportPdfButton, 'none');
        endif;
        ?>
    </div>
    <div class="clear"></div>        
</div>

<?php
Fisma_Format_Section::startSection($this->title);

echo $this->escape($this->dataTable, 'none');

Fisma_Format_Section::stopSection();
?>
