<?php if ($organization = $this->organization): ?>
    <table class="keyValues" style="background-color: white; width: 100%;">
        <tr>
            <td>Type</td>
            <td>
                <img
                    src='/icon/get/id/<?php
                        echo $this->escape($organization->OrganizationType->Icon->id);
                    ?>/size/small'
                    style='vertical-align:middle'
                    alt='<?php echo $this->escape($organization->OrganizationType->name); ?>'
                />
                <?php echo $this->escape($organization->OrganizationType->name); ?>
            </td>
        </tr>
        <tr>
            <td>Full name</td>
            <td><?php echo $this->escape($organization->name); ?></td>
        </tr>
    <?php if ($parentOrganization = $organization->getNode()->getParent()): ?>
        <tr>
            <td>Parent</td>
            <td>
                <img
                    src='/icon/get/id/<?php
                        echo $this->escape($parentOrganization->OrganizationType->Icon->id);
                    ?>/size/small'
                    style='vertical-align:middle'
                    alt='<?php echo $this->escape($parentOrganization->OrganizationType->name); ?>'
                />
                <a href='/organization/view/id/<?php echo $this->escape($parentOrganization->id); ?>'>
                    <?php echo $this->escape($parentOrganization->nickname); ?> -
                    <?php echo $this->escape($parentOrganization->name); ?>
                </a>
            </td>
        </tr>
    <?php endif; ?>
    <?php if ($this->organization->pocId): ?>
        <tr>
            <td><?php echo $this->escape($this->translate('Organization_Point_of_Contact')); ?></td>
            <td><a href='/user/view/id/<?php echo $this->escape($organization->pocId); ?>'>
                <?php echo $this->escape($organization->Poc->displayName); ?>
            </a></td>
        </tr>
    <?php endif; ?>
    </table>
    <?php if ($organization->description): echo $this->escape($organization->description, 'none'); endif; ?>
<?php elseif ($system = $this->system): ?>
    <?php $organization = $system->Organization; ?>
    <table class="keyValues" style="background-color: white; width: 100%;">
        <tr>
            <td>Type</td>
            <td>
                <img
                    src='/icon/get/id/<?php
                        echo $this->escape($system->SystemType->Icon->id);
                    ?>/size/small'
                    style='vertical-align:middle'
                    alt='<?php echo $this->escape($system->SystemType->name); ?>'
                />
                <?php echo $this->escape($system->SystemType->name); ?>
            </td>
        </tr>
        <tr>
            <td>Full name</td>
            <td><?php echo $this->escape($organization->name); ?></td>
        </tr>
    <?php if ($parentOrganization = $organization->getNode()->getParent()): ?>
        <tr>
            <td>Parent</td>
            <td>
                <img
                    src='/icon/get/id/<?php
                        echo $this->escape($parentOrganization->OrganizationType->Icon->id);
                    ?>/size/small'
                    style='vertical-align:middle'
                    alt='<?php echo $this->escape($parentOrganization->OrganizationType->name); ?>'
                />
                <a href='/organization/view/id/<?php echo $this->escape($parentOrganization->id); ?>'>
                    <?php echo $this->escape($parentOrganization->nickname); ?> -
                    <?php echo $this->escape($parentOrganization->name); ?>
                </a>
            </td>
        </tr>
    <?php endif; ?>
    <?php if ($organization->pocId): ?>
        <tr>
            <td><?php echo $this->escape($this->translate('Organization_Point_of_Contact')); ?></td>
            <td><a href='/user/view/id/<?php echo $this->escape($organization->pocId); ?>'>
                <?php echo $this->escape($organization->Poc->displayName); ?>
            </a></td>
        </tr>
    <?php endif; ?>
    </table>
    <?php if ($organization->description): echo $this->escape($organization->description, 'none'); endif; ?>
<?php else: ?>
    <p>No organization/system found.</p>
<?php endif; ?>
