<div class="column66 left">
<?php
Fisma_Format_Section::startSection('Details');
?>
<table class="keyValues">
    <tr>
        <td>Organization Name: </td>
        <td>
            <?php
            if ($this->editable) {
            ?>
            <span id="name" class="editable" target="name" name="name" type="text">
                <?php echo $this->escape($this->organization->name); ?>
            </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->escape($this->organization->name); ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>Organization Nickname: </td>
        <td>
            <?php
            if ($this->editable) {
            ?>
            <span id="nickname" class="editable" target="nickname" name="nickname" type="text">
                <?php echo $this->escape($this->organization->nickname); ?>
            </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->escape($this->organization->nickname); ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
       <td>Organization Type: </td>
        <td>
            <span id="organizationType"
                          type="select"
                          name="orgTypeId"
                          href="/metainfo/list/o/organizationType/format/html/">
        <?php
            echo $this->escape($this->organization->OrganizationType->nickname);
        ?>
        <?php if ($this->editable) : ?>
            <span class="editable" target="organizationType">&nbsp;</span>
        <?php endif ?>
        </td>
    </tr>
    <tr>
       <td>Parent Organization/System: </td>
        <td>
            <span id="organization"
                          type="select"
                          name="parent"
                          href="/metainfo/list/o/organization/format/html/">
        <?php
            $parentOrganization = $this->organization->getNode()->getParent();
            if (!empty($parentOrganization)) {
                $organizationTypeNickname = $parentOrganization->OrganizationType->nickname;
                $parentOrganizationName = $parentOrganization->nickname . ' - ' . $parentOrganization->name;
                if ($this->acl()->hasPrivilegeForObject('read', $parentOrganization)) {
                    $parentOrgType = 'system' == $organizationTypeNickname ? 'system' : 'organization';
                    $parentOrganizationId = 'system' == $parentOrgType ?
                                            $parentOrganization->systemId : $parentOrganization->id;
                    echo $this->escape('<a href="/' . $parentOrgType . '/view/id/', 'none');
                    echo $this->escape($parentOrganizationId, 'url');
                    echo $this->escape('">', 'none');
                    echo $this->escape($parentOrganizationName);
                    echo $this->escape('</a>', 'none');
                } else {
                    echo $this->escape($parentOrganizationName);
                }
            } else {
                echo $this->escape('<i>None</i>', 'none');
            }
        ?>
        <?php if ($this->editable) : ?>
            <span class="editable" target="organization">&nbsp;</span>
        <?php endif ?>
        </td>
    </tr>
</table>
<?php
Fisma_Format_Section::stopSection();

if ($this->editable) {
    Fisma_Format_Section::startSection('Organization Description', 'organization_description');
} else {
    Fisma_Format_Section::startSection('Organization Description');
}
?>
<div name="description" id="organization_description" type="textarea" rows="3" cols="120">
    <?php echo $this->escape($this->organization->description, 'none'); ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>
</div>

<div class="column33 right">
    <?php Fisma_Format_Section::startSection('Dates'); ?>
        <table class="keyValues">
            <tr>
                <td>Created:</td>
                <td>
                    <?php echo $this->escape($this->createdDate)?>
                </td>
            </tr>
            <tr>
                <td>Updated:</td>
                <td>
                    <?php echo $this->escape($this->updatedDate)?>
                </td>
            </tr>
        </table>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php Fisma_Format_Section::startSection('People'); ?>
        <table class="keyValues">
            <tr>
                <td>Point of Contact:</td>
                <td  class="autocomplete-width"><span id="pointOfContact"
                    type="autocomplete"
                    xhr="/user/autocomplete/format/json"
                    queryPrepend="/keyword/"
                    schemaObject="pointsOfContact"
                    schemaField="name"
                    name="pocId"
                <?php if ($this->acl()->hasPrivilegeForClass('create', 'User')): ?>
                    setupCallback="Fisma.Finding.setupPocAutocomplete"
                <?php endif; ?>
                    value="<?php echo $this->escape($this->organization->pocId); ?>"
                    defaultValue="<?php echo $this->escape($this->organization->Poc->username); ?>"><?php
                    if (!empty($this->organization->pocId)) {
                        echo $this->escape(
                            $this->userInfo(
                                $this->organization->Poc->displayName,
                                $this->organization->pocId
                            ),
                            'none'
                        );
                    }
                    ?></span>
                <?php if ($this->editable): ?>
                    <span class="editable" target="pointOfContact">&nbsp;</span>
                <?php endif; ?>
                </td>
            </tr>
        </table>
    <?php Fisma_Format_Section::stopSection(); ?>
</div>
