<?php

echo $this->escape($this->searchBox($this->toolbarButtons, $this->searchForm), 'none');

Fisma_Format_Section::startSection("Organizations: Hierarchy View"); 

?>

<div id="orgTreeContainer" class="draggableTreeContainer"></div>

<script type="text/javascript">
YAHOO.util.Event.onDOMReady(
    function () {
        var treeView = new Fisma.OrganizationTreeView("orgTreeContainer");
        
        treeView.render();
        
        //attach button events here
    }
);
</script>

<?php Fisma_Format_Section::stopSection(); ?>
