<div class="hd">
    <?php echo $this->escape(Fisma::configuration()->getConfig('system_name'));?>
</div>

<div class="bd">
    <?php echo $this->escape(Fisma::configuration()->getConfig('use_notification'), 'none');?>
        
    <p class="message">
        <?php 
            if (isset($this->error)) {
                $dateString = Zend_Date::now()->toString(Fisma_Date::FORMAT_TIME);
                echo $this->escape($dateString);
                echo $this->escape(' ', 'none');
                echo $this->escape($this->error); 
            }
        ?>
    </p>

    <form id='loginForm' method="post" action="/auth/login">
        <table>
            <tr>
                <td><label for="username">Username:</label></td>
                <td>
                    <input type="text" 
                           name="username" 
                           id="username"
                           autocomplete="off"
                           value="<?php echo $this->escape(isset($this->username) ? $this->username : '')?>">
                </td>
            </tr>
            <tr>
                <td><label for="userpass">Password:</label></td>
                <td>
                    <input type="password" 
                           name="userpass" 
                           id="userpass"
                           autocomplete="off"
                           value="<?php echo $this->escape(isset($this->password)?$this->password:'')?>">
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <?php 
                    $loginButton = new Fisma_Yui_Form_Button_Submit('loginButton', array('label' => 'Log In')); 
                    echo $this->escape($loginButton, 'none');
                    ?>
                </td>
            </tr>
        </table>
        <?php
        if ($this->showReportIncidentButton):
        ?>
            <hr>
            <table>
                <tr>
                    <td colspan="2">
                        <?php 
                        $reportIncidentButton = new Fisma_Yui_Form_Button_Link(
                            'reportIncident', 
                            array(
                                'value' => 'Report A Security Incident',
                                'href' => '/incident/report',
                                'imageSrc' => '/images/report_incident.png'
                            )
                        ); 
                        echo $this->escape($reportIncidentButton, 'none');
                        ?>
                    </td>
                </tr>
            </table>
        <?php
        endif;
        ?>
    </form>
</div>
