<form id="login" _lpchecked="1" method="post" action="/auth/login" onsubmit="return login(this);">
    <input type='hidden' name='timezoneOffset' value='' />
    <div id='banner'>
        <h1 class='banner'>Warning</h1>
        <div id='bannerContent'>
            <?php echo $this->escape(Fisma::configuration()->getConfig('use_notification'), 'none');?>
        </div>
        <fieldset class="actions">
            <input type="submit" class="submit" name="submit" value="Accept"/>
            <a href="" onclick="return decline();">Decline</a>
        </fieldset>
    </div>
    <div id='form'>
        <h1 class='banner'>Log In</h1>
        <fieldset id="inputs">
            <input
                id="username"
                type="text"
                name="username"
                placeholder="Username"
                title="Username"
                autofocus=""
                required=""
                autocomplete="off"
                onkeypress="capLock(event)"
                value="<?php echo $this->escape(isset($this->username) ? $this->username : '')?>"
            >
            <input
                id="password"
                type="password"
                name="userpass"
                placeholder="Password"
                title="Password"
                required=""
                autocomplete="off"
                onkeypress="capLock(event)"
                value="<?php echo $this->escape(isset($this->password)?$this->password:'')?>"
            >
            <?php if (isset($this->error)): ?><div class="message"><?php
                $dateString = Zend_Date::now()->toString(Fisma_Date::FORMAT_TIME);
                echo $this->escape('[' . $dateString . ']');
                echo $this->escape(' ', 'none');
                echo $this->escape($this->error);
            ?></div><?php endif; ?>
            <div id="divCapsLock" class="divCapsLockOFF divCapsLock">
                <img style="vertical-align: middle; margin-top:-3px; width:16px; height:16px"
                     src="/images/alert.png" alt="Caps Lock On" />
                <strong>Caps Lock is On</strong>
            </div>
        </fieldset>
        <fieldset class="actions">
            <input type="submit" class="submit" name="submit" value="Log in"/>
            <a href="/auth/recover">Cannot login?</a>
        <?php if ($this->showReportIncidentButton): ?>
            <a href="/incident/report">Report a Security Incident</a>
        <?php endif; ?>
        </fieldset>
    </div>
</form>
<script type="text/javascript">
function login(formElement) {
    if ($('#banner').css('display') === 'none') {
        var validation = true;
        var focusCallback = function(){$(this).focus();}
        $('input[required]').each(function(index, element){
            if (!element.value) {
                $(element).fadeOut().fadeIn(focusCallback);
                focusCallback = null;
                validation = false;
            }
        });
        if (validation) {
            $('#form').slideToggle();
            $('#banner').slideToggle();
            $('input.submit[value="Accept"]').focus();
        }
        return false;
    }
}
function decline() {
    $('#form').slideToggle();
    $('#banner').slideToggle();
    $('input.submit[value="Log in"]').focus();
    return false;
}
function capLock(e) {
    kc = e.keyCode ? e.keyCode : e.which;
    sk = e.shiftKey ? e.shiftKey : ((kc == 16) ? true : false);

    if(((kc >= 65 && kc <= 90) && !sk)||((kc >= 97 && kc <= 122) && sk)) {
        $('#divCapsLock').removeClass('divCapsLockOFF');
    }
    else {
        $('#divCapsLock').addClass('divCapsLockOFF');
    }
}

$(function(){
    $('input[autofocus]').focus();
    $('input[name=timezoneOffset]').val(jstz.determine().name());
});
</script>
