<div id='workflowTabContent'>
<?php
$object = $this->object;
$model = $this->model;
$completedSteps = (array)$object->completedSteps;
$step = $object->CurrentStep;
$organization = $object->Organization;
?>

<?php Fisma_Format_Section::startSection('Overview'); ?>
<p>
    <b><?php echo $this->escape($this->translate(ucfirst($model) . '_Status')); ?></b>:
    <?php echo $this->escape(($object->isResolved) ? 'YES' : 'NO'); ?>
</p>
<p>
    <b>Current Workflow Step:</b>
    <span title='<?php echo $this->escape($step->Workflow->description); ?>'>
        <?php echo $this->escape($step->Workflow->name); ?>
    </span>
    -
    <span title='<?php echo $this->escape($step->label); ?>'>
        <?php echo $this->escape($step->name); ?>
    </span>
    <?php
    if (strpos($this->workflowOnTimeState, 'On Time') === 0) {
        ?>(<font color='green'><?php echo $this->escape($this->workflowOnTimeState); ?></font>)<?php
    } else if (strpos($this->workflowOnTimeState, 'Due Today') === 0) {
        ?>(<font color='orange'>Due Today</font>)<?php
    } else if (strpos($this->workflowOnTimeState, 'Overdue') === 0) {
        ?>(<font color='red'><?php echo $this->escape($this->workflowOnTimeState); ?></font>)<?php
    }
    ?>
</p>
<?php
$restrictedFields = (array)$step->restrictedFields;
$table = Doctrine::getTable(ucfirst($model));
foreach ($restrictedFields as $key => $value):
    $restrictedFields[$key] = $this->translate($table->getLogicalName($value));
endforeach;
if (!$step->attachmentEditable):
    $restrictedFields[] = $this->translate(ucfirst($model) . '_Attachments');
endif;
if (count($restrictedFields) > 0):
?>
<p>
    The following items cannot be modified during this current workflow step:
    <?php echo $this->escape(implode(', ', $restrictedFields)); ?>.
</p>
<?php endif; ?>
<?php Fisma_Format_Section::stopSection(); ?>

<?php Fisma_Format_Section::startSection('Workflow Steps'); ?>
<?php foreach ($completedSteps as $completedStep): ?>
<div class='workflowStep'>
    <table class='keyValues'>
        <tr>
            <th scope='row'>Step</th>
            <td>
                <span title='<?php echo $this->escape($completedStep['workflow']['description']); ?>'>
                    <?php echo $this->escape($completedStep['workflow']['name']); ?>
                </span>
                -
                <span title='<?php echo $this->escape($completedStep['step']['label']); ?>'>
                    <?php echo $this->escape($completedStep['step']['name']); ?>
                </span>
            </td>
        </tr>
        <tr>
            <th scope='row'>Instruction(s)</th>
            <td><?php echo $this->escape($completedStep['step']['description'], 'none'); ?></td>
        </tr>
        <tr>
            <th scope='row'>Comment</th>
            <td><?php echo $this->escape($completedStep['comment']); ?></td>
        </tr>
        <tr>
            <th scope='row'>Action</th>
            <td><?php echo $this->escape($completedStep['transitionName']); ?></td>
        </tr>
        <tr>
            <th scope='row'>Completed by</th>
            <td><?php
                $user = Doctrine::getTable('User')->find($completedStep['userId']);
                echo $this->escape($this->userInfo($user->displayName, $user->id), 'none');
            ?></td>
        </tr>
        <tr>
            <th scope='row'>Completed on</th>
            <td><?php echo $this->escape($completedStep['timestamp']); ?></td>
        </tr>
    </table>
</div>
<?php endforeach; ?>
<div class='workflowStep current'>
    <table class='keyValues'>
        <tr>
            <th scope='row'>Step</th>
            <td>
                <span title='<?php echo $this->escape($step->Workflow->description); ?>'>
                    <?php echo $this->escape($step->Workflow->name); ?>
                </span>
                -
                <span title='<?php echo $this->escape($step->label); ?>'>
                    <?php echo $this->escape($step->name); ?>
                </span>
            </td>
        </tr>
        <tr>
            <th scope='row'>Instruction(s)</th>
        <?php
        $actions = '';
        if ($organization):
            $currentRoles = $organization->getPocs()->fetchAllPositions(CurrentUser::getAttribute('id'));

            foreach ($step->transitions as $index => $transition):
                $transitionRoles = array_intersect(
                    $currentRoles,
                    Zend_Json::decode($transition['roles'])
                );
                if (count($transitionRoles) > 0):
                    $actions .= new Fisma_Yui_Form_Button(
                        'transitionButton' . $index,
                        array(
                            'label' => $transition['name'],
                            'onClickFunction' => 'Fisma.Workflow.completeStep',
                            'onClickArgument' => array(
                                'objectId' => $object->id,
                                'stepId' => $step->id,
                                'transitionName' => $transition['name'],
                                'url' => '/workflow/complete-step/format/json/model/' . $model
                            )
                        )
                    );
                endif;
            endforeach;
        endif;

        if ($actions !== ''):
        ?>
            <td><?php echo $this->escape($step->description, 'none'); ?></td>
        </tr>
        <tr>
            <th scope='row'>Comment</th>
            <td><textarea rows='8' cols='60' name='stepComment'></textarea></td>
        </tr>
        <tr>
            <th scope='row'>Action</th>
            <td>
                <?php echo $this->escape($actions, 'none'); ?>
                <input name='stepExpirationDate' type='hidden' />
            </td>
        </tr>
        <?php else: ?>
            <td>You don't have permission to perform any actions in this step</td>
        <?php endif; ?>
        </tr>
    </table>
</div>
<?php Fisma_Format_Section::stopSection(); ?>
</div>
