<?php
foreach ($this->partialViews as $script => $args):
    echo $this->partial($script, $args);
endforeach;
?>

<div class="searchBox">
    <div class="left">
        <?php
        echo $this->escape(new Fisma_Yui_Form_Button(
            'backButton',
            array(
                'label' => 'Back',
                'imageSrc' => '/images/back.png',
                'onClickFunction' => 'Fisma.Util.goBack'
            )
        ), 'none');
        if (isset($this->exportXlsButton)):
            echo $this->escape($this->exportXlsButton, 'none');
        endif;

        if (isset($this->exportPdfButton)):
            echo $this->escape($this->exportPdfButton, 'none');
        endif;
        ?>
    </div>

    <div class="right">
        <?php if (isset($this->form)): ?>
            <?php echo $this->escape($this->form, 'none'); ?>
        <?php endif; ?>

        <?php if (isset($this->orgTypeId)): ?>
            <?php echo $this->escape($this->organizationTypeForm, 'none'); ?>
        <?php endif; ?>
    </div>
    <div class="clear"></div>
</div>

<?php
Fisma_Format_Section::startSection($this->title);

echo $this->escape($this->dataTable, 'none');

Fisma_Format_Section::stopSection();
?>

<?php if (isset($this->orgTypeId)): ?>

<script type="text/javascript">
    YAHOO.util.Event.onDOMReady(function () {
        Fisma.Storage.onReady(function() {
            var config = {namespace : "<?php echo $this->escape($this->namespace); ?>",
                          url : "<?php echo $this->escape($this->url); ?>"};
            Fisma.Organization.typeSelector = function(event) {
                Fisma.Organization.typeHandle(event, config);
            }
        });
    });
</script>

<?php endif; ?>
