<?php
foreach ($this->partialViews as $script => $args):
    echo $this->partial($script, $args);
endforeach;
?>

<div class="searchBox">
    <div class="left">
        <?php
        if (isset($this->exportXlsButton)):
            echo $this->escape($this->exportXlsButton, 'none');
        endif;

        if (isset($this->exportPdfButton)):            
            echo $this->escape($this->exportPdfButton, 'none');
        endif;
        ?>
    </div>

    <?php if (isset($this->form)): ?>
        <div class="right">
            <?php echo $this->escape($this->form, 'none'); ?>
        </div>
    <?php endif; ?>
    
    <div class="clear"></div>        
</div>

<?php if (isset($this->orgTypeId)): ?> 
<div  class="searchBox">
         <?php echo $this->escape($this->organizationTypeForm, 'none'); ?>
    <div class="clear"></div>        
</div>
<?php endif; ?>


<?php
Fisma_Format_Section::startSection($this->title);

echo $this->escape($this->dataTable, 'none');

Fisma_Format_Section::stopSection();
?>

<?php if (isset($this->orgTypeId)): ?>

<script type="text/javascript">
    YAHOO.util.Event.onDOMReady(function () {
        Fisma.Storage.onReady(function() {
            var organizationTypeElement = YAHOO.util.Dom.get('orgTypeFilter');
            var orgTypeId = "<?php echo $this->escape($this->orgTypeId); ?>"; 

            var config = {namespace : "<?php echo $this->escape($this->namespace); ?>",
                          url : "<?php echo $this->escape($this->url); ?>"}; 
            YAHOO.util.Event.addListener("orgTypeFilter", "change", Fisma.Organization.typeHandle, config);
        });
    });
</script>

<?php endif; ?>
