<?php
foreach ($this->partialViews as $script => $args):
    echo $this->partial($script, $args);
endforeach;
?>

<div class="searchBox">
    <div class="left">
        <?php
        if (isset($this->exportXlsButton)):
            echo $this->escape($this->exportXlsButton, 'none');
        endif;

        if (isset($this->exportPdfButton)):            
            echo $this->escape($this->exportPdfButton, 'none');
        endif;
        ?>
    </div>

    <?php if (isset($this->form)): ?>
        <div class="right">
            <?php echo $this->escape($this->form, 'none'); ?>
        </div>
    <?php endif; ?>
    
    <div class="clear"></div>        
</div>

<?php if (isset($this->orgTypeFilter)): ?> 
<div  class="searchBox">
         <?php echo $this->escape($this->organizationTypeForm, 'none'); ?>
    <div class="clear"></div>        
</div>
<?php endif; ?>


<?php
Fisma_Format_Section::startSection($this->title);

echo $this->escape($this->dataTable, 'none');

Fisma_Format_Section::stopSection();
?>

<?php if (isset($this->orgTypeFilter)): ?>

<script type="text/javascript">
    YAHOO.util.Event.onDOMReady(function () {
        var organizationTypeElement = YAHOO.util.Dom.get('orgTypeFilter');
        var storageNamespace = "<?php echo $this->escape($this->namespace); ?>";
        var orgTypeStorage = new Fisma.PersistentStorage(storageNamespace);
        var orgTypeId = orgTypeStorage.get('orgType');

        if (!YAHOO.lang.isUndefined(orgTypeId) && orgTypeId) {
            for (var i=0; i < organizationTypeElement.options.length; i++) {
                if (organizationTypeElement.options[i].value === orgTypeId) {
                    organizationTypeElement.options[i].selected = true;
                    break;
                }
            }
        }        

        var config = {namespace : storageNamespace, 
                      url : "<?php echo $this->escape($this->url); ?>"}; 
        YAHOO.util.Event.addListener("orgTypeFilter", "change", Fisma.Util.organizationTypeHandle, config);
    });

</script>

<?php endif; ?>
