ALTER TABLE `POAM_COMMENTS` ADD `ev_id` INT( 10 ) UNSIGNED NOT NULL DEFAULT '0' AFTER `user_id` ;

ALTER TABLE `POAM_COMMENTS` ADD INDEX ( `ev_id` ) ;

ALTER TABLE `POAM_COMMENTS` CHANGE `comment_type` `comment_type` ENUM( 'EST', 'SSO', 'NONE', 'EV_SSO', 'EV_FSA', 'EV_IVV' ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT 'NONE' 