<?php Fisma_Format_Section::startSection("Security Control Tree View"); ?>

<div class="buttonBar">
<?php
$goBack = new Fisma_Yui_Form_Button_Link('goBack', 
                                       array('value' => 'Go Back', 
                                             'imageSrc' => '/images/left_arrow.png',
                                             'href' => '/sa/security-authorization/view/id/' . $this->id));
echo $this->escape($goBack, 'none');

$expandAll = new Fisma_Yui_Form_Button('expandAll', 
                                       array('label' => 'Expand All', 
                                             'imageSrc' => '/images/expand.png',
                                             'onClickFunction' => 'expandAll'));
echo $this->escape($expandAll, 'none');

$collapseAll = new Fisma_Yui_Form_Button('collapseAll', 
                                         array('label' => 'Collapse All', 
                                             'imageSrc' => '/images/collapse.png',
                                             'onClickFunction' => 'collapseAll'));
echo $this->escape($collapseAll, 'none');

$addControl = new Fisma_Yui_Form_Button('addControl', 
                                       array('label' => 'Add Control', 
                                             'onClickFunction' => 'addControl'));
echo $this->escape($addControl, 'none');
?>
</div>

<div id="controlTree"></div>

<script type="text/javascript">
var controlTree = null;
YAHOO.util.Event.onDOMReady(function () {
    var base = '/sa/select-controls/',
        params = '/id/<?php echo $this->escape($this->id); ?>';
    controlTree = new Fisma.ControlTree(
        'controlTree',
        {
            controlTreeData: base + 'control-tree-data/format/json' + params,
            removeControl: base + 'remove-control/format/json' + params,
            addEnhancements: base + 'add-enhancements/format/html' + params,
            removeEnhancement: base + 'remove-enhancement/format/json' + params,
            editCommonControl: base + 'edit-common-control/format/html' + params
        }
    );
});
// Expand all tree nodes
function expandAll() {
    controlTree.treeView.getRoot().expandAll();
}

// Collapse all tree nodes
function collapseAll() {
    controlTree.treeView.getRoot().collapseAll();
}

// show Add Control dialog
function addControl() {
    var panel = Fisma.HtmlPanel.showPanel("Add Security Control", null, null, { modal : true }),
        url = "/sa/select-controls/add-control/id/<?php echo $this->escape($this->id); ?>/format/html";
    var callbacks = {
            success: function(o) {
                var panel = o.argument;
                panel.setBody(o.responseText);
                panel.center();
            },
            failure: function(o) {
                alert('Error getting "add control" form: ' + o.statusText);
                var panel = o.argument;
                panel.destroy();
            },
            argument: panel
        };
    YAHOO.util.Connect.asyncRequest( 'GET', url, callbacks, null);
}
</script>

<?php Fisma_Format_Section::stopSection(); ?>
