<?php Fisma_Format_Section::startSection("Security Control Tree View"); ?>

<div class="buttonBar">
<?php
echo $this->escape($this->goBack, 'none');
echo $this->escape($this->expandAll, 'none');
echo $this->escape($this->collapseAll, 'none');
echo $this->escape($this->addControl, 'none');
echo $this->escape($this->completeSelection, 'none');
echo $this->escape($this->completeForm, 'none');
?>
</div>

<div id="controlTree"></div>

<script type="text/javascript">
var controlTree = null;
YAHOO.util.Event.onDOMReady(function () {
    var base = '/sa/select-controls/',
        params = '/id/<?php echo $this->escape($this->id); ?>';
    controlTree = new Fisma.ControlTree(
        'controlTree',
        {
            controlTreeData: base + 'control-tree-data/format/json' + params,
            removeControl: base + 'remove-control/format/json' + params,
            addEnhancements: base + 'add-enhancements/format/html' + params,
            removeEnhancement: base + 'remove-enhancement/format/json' + params,
            editCommonControl: base + 'edit-common-control/format/html' + params
        }
    );
});
// Expand all tree nodes
function expandAll() {
    controlTree.treeView.getRoot().expandAll();
}

// Collapse all tree nodes
function collapseAll() {
    controlTree.treeView.getRoot().collapseAll();
}

// show Add Control dialog
function addControl() {
    var panel = Fisma.HtmlPanel.showPanel("Add Security Control", null, null, { modal : true }),
        url = "/sa/select-controls/add-control/id/<?php echo $this->escape($this->id); ?>/format/html";
    var callbacks = {
            success: function(o) {
                var panel = o.argument;
                panel.setBody(o.responseText);
                panel.center();
            },
            failure: function(o) {
                alert('Error getting "add control" form: ' + o.statusText);
                var panel = o.argument;
                panel.destroy();
            },
            argument: panel
        };
    YAHOO.util.Connect.asyncRequest( 'GET', url, callbacks, null);
}

// submit the form to mark the selection step as complete
function completeSelect()
{
    document.getElementById('completeForm').submit();
}
</script>

<?php Fisma_Format_Section::stopSection(); ?>
