<form id="acceptRob" _lpchecked="1" method="post" action="/user/accept-rob">
        <h1 class='banner'>Rules</h1>
        <div id='bannerContent'>
            <div>
                <i>
                    System policy states that you must review and accept the Rules of Behavior every
                    <?php echo $this->escape(Fisma::configuration()->getConfig('rob_duration'))?> days.
                </i>
            </div>
            <?php echo $this->escape(Fisma::configuration()->getConfig('behavior_rule'), 'none'); ?>
        </div>
        <fieldset class="actions">
            <input type="submit" class="submit" name="accept" value="Accept" autofocus />
            <a href="/auth/logout">Decline</a>
        </fieldset>
</form>
<script type="text/javascript">
$(function(){
    $('input[autofocus]').focus();
})
</script>