<div id='loginForm'>
    <form id="login" _lpchecked="1" method="post" action="/user/accept-rob">
            <h1>ROB</h1>
            <div id='bannerContent'>
                <div>
                    <i>
                        System policy states that you must review and accept the Rules of Behavior every
                        <?php echo $this->escape(Fisma::configuration()->getConfig('rob_duration'))?> days.
                    </i>
                </div>
                <?php echo $this->escape(Fisma::configuration()->getConfig('behavior_rule'), 'none'); ?>
            </div>
            <fieldset class="actions">
                <input type="submit" class="submit" name="accept" value="Accept" />
                <a href="/auth/logout">Decline</a>
            </fieldset>
    </form>
</div>
<script type="text/javascript">
function a(formElement){
    if ($('#banner').css('display') === 'none') {
        var validation = true;
        var focusCallback = function(){$(this).focus();}
        $('input[required]').each(function(index, element){
            if (!element.value) {
                $(element).fadeOut('fast').fadeIn('fast', focusCallback);
                focusCallback = null;
                validation = false;
            }
        });
        if (validation) {
            $('#form').slideToggle();
            $('#banner').slideToggle();
        }
        return false;
    }
}
function b(){
    $('#form').slideToggle();
    $('#banner').slideToggle();
    return false;
}
</script>