<?php 
$operation = "[<a href='{$this->escape($this->viewLink)}'>Back To User View</a>]";

Fisma_Format_Section::startSection(
    sprintf('User Comments (%s)&nbsp;&nbsp;%s', $this->escape($this->username), $operation)
);
?>
<div class="buttonBar">
    <?php echo $this->escape($this->commentButton, 'none'); ?>
</div>
<?php
echo $this->escape($this->dataTable, 'none');

Fisma_Format_Section::stopSection();
