<?php

echo $this->escape($this->searchBox($this->toolbarButtons, $this->searchForm, $this->searchButtons), 'none');

Fisma_Format_Section::startSection('User Account Information');

if (!empty($this->requirements)) {
?>
    <p>The password must meet the following complexity criteria:</p>
    <ul>
        <?php foreach ($this->requirements as $requirement): ?>
            <li>
                 <?php echo $this->escape($requirement); ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php
}
?>

<div class="form_box" id="userForm">
    <form method="post" action="<?php $this->escape($this->form->getAction(), 'none'); ?>">
        <?php
        echo $this->escape($this->form, 'none');
        echo $this->escape($this->tabView, 'none');
        ?>
    </form>
</div>

<?php
Fisma_Format_Section::stopSection();
echo $this->partial('yui/roles.phtml', array('roles' => $this->roles, 'id' => $this->id, 'readOnly' => 0));
?>