<?php if ($this->user): ?>
    <table class="keyValues table-hover" style="background-color: white; width: 100%;">
        <tr>
            <td>Name</td>
            <td><?php echo $this->escape("{$this->user->nameFirst} {$this->user->nameLast}"); ?></td>
        </tr>
        <?php if (!empty($this->user->title)): ?>
        <tr>
            <td>Title</td>
            <td><?php echo $this->escape($this->user->title); ?></td>
        </tr>
        <?php endif; ?>
        <?php if (!empty($this->user->reportingOrganizationId)) : ?>
        <tr>
            <td>Reporting Organization</td>
            <td>
                <a href="/organization/view/id/<?php echo $this->escape($this->user->reportingOrganizationId); ?>">
                    <?php echo $this->escape($this->user->ReportingOrganization->nickname); ?>
                    -
                    <?php echo $this->escape($this->user->ReportingOrganization->name); ?>
                </a>
            </td>
        </tr>
        <?php endif; ?>
        <tr>
            <td>E-mail</td>
            <td>
                <a href="mailto:<?php echo $this->escape($this->user->email); ?>">
                    <?php echo $this->escape($this->user->email); ?>
                </a>
            </td>
        </tr>
        <tr>
            <td>Work Phone</td>
            <td><?php echo $this->escape($this->user->phoneOffice); ?></td>
        </tr>
        <?php if (!empty($this->user->phoneMobile)): ?>
        <tr>
            <td>Mobile Phone</td>
            <td><?php echo $this->escape($this->user->phoneMobile); ?></td>
        </tr>
        <?php endif; ?>
    </table>

    <?php if ($this->user->locked): ?>
        <img src="/images/alert.png" class="userInfoAlert" alt='Alert'>
        <p><em>This user account is locked and may be inactive.</em></p>
    <?php endif; ?>
    <?php if ($this->user->deleted_at): ?>
        <img src="/images/alert.png" class="userInfoAlert" alt='Alert'>
        <p><em>This user account has been removed from the system.</em></p>
    <?php endif; ?>
<?php else: ?>
    <p>No user information found.</p>
<?php endif; ?>
