<?php 
$operation = "[<a href='{$this->viewLink}'>Back To User View</a>]";

Fisma_Format_Section::startSection(
    sprintf('User Audit Log (%s)&nbsp;&nbsp;%s', $this->escape($this->username), $operation)
);
?>

<div id="container">
    <table id="reportTable">
        <thead>
            <tr>
                <?php foreach ($this->columns as $column) : ?>
                <th class="tdc"><?php echo $this->escape($column)?></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->rows as $row) : ?>
        <tr>
            <td><?php echo $this->escape($row['o_createdTs']) ?></td>
            <td><?php echo $this->escape($row['u_username']) ?></td>
            <td><?php echo $this->escape($row['o_message']) ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php
    Fisma_Format_Section::stopSection();

    $defKeys = array();
    $responseKeys = array();
    foreach ($this->columns as $column) {
        $defKeys[] = "{key:'$column', label:'$column', sortable:true}";
        $responseKeys[] = "{key:'$column'}";
    }
    $defKeys = implode(',', $defKeys);
    $responseKeys = implode(',', $responseKeys);
?>
<script type="text/javascript">
// Convert the HTML table above into a YUI table
YAHOO.util.Event.onContentReady('container', function() {
    var myColumnDefs = [<?php echo $this->escape($defKeys, 'none')?>];
    this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("reportTable"));
    this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
    this.myDataSource.responseSchema = {
        fields: [<?php echo $this->escape($responseKeys, 'none')?>]
    };

    this.myDataTable = new YAHOO.widget.DataTable("container", myColumnDefs, this.myDataSource, {});
});
</script>
