<form method='post'>
<?php echo $this->escape($this->searchBox($this->toolbar), 'none'); ?>
<div class='column left'>
    <?php if ($this->adminEvents): Fisma_Format_Section::startSection(
        'Administration Alerts ' .
        " (<a href='#' onclick='return checkAll(this);'>all</a> | " .
        "<a href='#' onclick='return checkNone(this);'>none</a>)"
    ); ?>
    <table class='keyValues'>
        <tr>
            <td>Email me whenever</td>
            <td><?php foreach($this->adminEvents as $event): ?>
                <input
                    type='checkbox'
                    name='event[<?php echo $this->escape($event->id); ?>]'
                    id='chkEvent[<?php echo $this->escape($event->id); ?>]'
                    <?php if (in_array($this->user, $event->Users->getData())): ?>checked<?php endif; ?>
                />
                <label for='chkEvent[<?php echo $this->escape($event->id); ?>]'>
                    <?php echo $this->escape($event->description); ?>
                </label>
                <br/>
            <?php endforeach; ?></td>
        </tr>
    </table>
    <?php Fisma_Format_Section::stopSection(); endif; ?>

    <?php if ($this->scriptEvents): Fisma_Format_Section::startSection(
        'Background Task Alerts ' .
        " (<a href='#' onclick='return checkAll(this);'>all</a> | " .
        "<a href='#' onclick='return checkNone(this);'>none</a>)"
    ); ?>
    <table class='keyValues'>
        <tr>
            <td>Email me whenever</td>
            <td><?php foreach($this->scriptEvents as $event): ?>
                <input
                    type='checkbox'
                    name='event[<?php echo $this->escape($event->id); ?>]'
                    id='chkEvent[<?php echo $this->escape($event->id); ?>]'
                    <?php if (in_array($this->user, $event->Users->getData())): ?>checked<?php endif; ?>
                />
                <label for='chkEvent[<?php echo $this->escape($event->id); ?>]'>
                    <?php echo $this->escape($event->description); ?>
                </label>
                <br/>
            <?php endforeach; ?></td>
        </tr>
    </table>
    <?php Fisma_Format_Section::stopSection(); endif; ?>

    <?php if ($this->userEvents): Fisma_Format_Section::startSection(
        'User Alerts ' .
        " (<a href='#' onclick='return checkAll(this);'>all</a> | " .
        "<a href='#' onclick='return checkNone(this);'>none</a>)"
    ); ?>
    <table class='keyValues'>
        <tr>
            <td>Email me whenever</td>
            <td><?php foreach($this->userEvents as $event): ?>
                <input
                    type='checkbox'
                    name='event[<?php echo $this->escape($event->id); ?>]'
                    id='chkEvent[<?php echo $this->escape($event->id); ?>]'
                    <?php if (in_array($this->user, $event->Users->getData())): ?>checked<?php endif; ?>
                />
                <label for='chkEvent[<?php echo $this->escape($event->id); ?>]'>
                    <?php echo $this->escape($event->description); ?>
                </label>
                <br/>
            <?php endforeach; ?></td>
        </tr>
    </table>
    <?php Fisma_Format_Section::stopSection(); endif; ?>

    <?php if ($this->inventoryEvents): Fisma_Format_Section::startSection(
        'System Inventory Alerts ' .
        " (<a href='#' onclick='return checkAll(this);'>all</a> | " .
        "<a href='#' onclick='return checkNone(this);'>none</a>)"
    ); ?>
    <table class='keyValues'>
        <tr>
            <td>Email me whenever</td>
            <td><?php foreach($this->inventoryEvents as $event): ?>
                <input
                    type='checkbox'
                    name='event[<?php echo $this->escape($event->id); ?>]'
                    id='chkEvent[<?php echo $this->escape($event->id); ?>]'
                    <?php if (in_array($this->user, $event->Users->getData())): ?>checked<?php endif; ?>
                />
                <label for='chkEvent[<?php echo $this->escape($event->id); ?>]'>
                    <?php echo $this->escape($event->description); ?>
                </label>
                <br/>
            <?php endforeach; ?></td>
        </tr>
    </table>
    <?php Fisma_Format_Section::stopSection(); endif; ?>
</div>
<div class='column right'>
    <?php if ($this->findingEvents): Fisma_Format_Section::startSection(
        'Findings Alerts ' .
        " (<a href='#' onclick='return checkAll(this);'>all</a> | " .
        "<a href='#' onclick='return checkNone(this);'>none</a>)"
    ); ?>
    <table class='keyValues'>
        <tr>
            <td>Email me whenever</td>
            <td><?php foreach($this->findingEvents as $event): ?>
                <input
                    type='checkbox'
                    name='event[<?php echo $this->escape($event->id); ?>]'
                    id='chkEvent[<?php echo $this->escape($event->id); ?>]'
                    <?php if (in_array($this->user, $event->Users->getData())): ?>checked<?php endif; ?>
                />
                <label for='chkEvent[<?php echo $this->escape($event->id); ?>]'>
                    <?php echo $this->escape($event->description); ?>
                </label>
                <br/>
            <?php endforeach; ?></td>
        </tr>
    </table>
    <?php Fisma_Format_Section::stopSection(); endif; ?>

    <?php if ($this->vulnerabilityEvents): Fisma_Format_Section::startSection(
        'Vulnerabilities Alerts ' .
        " (<a href='#' onclick='return checkAll(this);'>all</a> | " .
        "<a href='#' onclick='return checkNone(this);'>none</a>)"
    ); ?>
    <table class='keyValues'>
        <tr>
            <td>Email me whenever</td>
            <td><?php foreach($this->vulnerabilityEvents as $event): ?>
                <input
                    type='checkbox'
                    name='event[<?php echo $this->escape($event->id); ?>]'
                    id='chkEvent[<?php echo $this->escape($event->id); ?>]'
                    <?php if (in_array($this->user, $event->Users->getData())): ?>checked<?php endif; ?>
                />
                <label for='chkEvent[<?php echo $this->escape($event->id); ?>]'>
                    <?php echo $this->escape($event->description); ?>
                </label>
                <br/>
            <?php endforeach; ?></td>
        </tr>
    </table>
    <?php Fisma_Format_Section::stopSection(); endif; ?>

    <?php if ($this->incidentEvents): Fisma_Format_Section::startSection(
        'Incidents Alerts ' .
        " (<a href='#' onclick='return checkAll(this);'>all</a> | " .
        "<a href='#' onclick='return checkNone(this);'>none</a>)"
    ); ?>
    <table class='keyValues'>
        <tr>
            <td>Email me whenever</td>
            <td><?php foreach($this->incidentEvents as $event): ?>
                <input
                    type='checkbox'
                    name='event[<?php echo $this->escape($event->id); ?>]'
                    id='chkEvent[<?php echo $this->escape($event->id); ?>]'
                    <?php if (in_array($this->user, $event->Users->getData())): ?>checked<?php endif; ?>
                />
                <label for='chkEvent[<?php echo $this->escape($event->id); ?>]'>
                    <?php echo $this->escape($event->description); ?>
                </label>
                <br/>
            <?php endforeach; ?></td>
        </tr>
    </table>
    <?php Fisma_Format_Section::stopSection(); endif; ?>
</div>
</form>
<script>
function checkAll(linkElement) {
    $(linkElement).parents('.sectionContainer').find('input[type=checkbox]').attr('checked', true);
    return false;
}
function checkNone(linkElement) {
    $(linkElement).parents('.sectionContainer').find('input[type=checkbox]').attr('checked', false);
    return false;
}
</script>
