<?php echo $this->escape($this->searchBox($this->toolbarButtons), 'none'); ?>
<?php Fisma_Format_Section::startSection("Change Password"); ?>

<p>For security reasons, you must enter your old password in order to create a new password.</p>
<p>The new password must meet the following complexity criteria:</p>
<ul>
<?php foreach ($this->requirements as $requirement): ?>
    <li>
        <?php echo $this->escape($requirement); ?>
    </li>
<?php endforeach; ?>
</ul>

<?php
    $this->form->setAction('/user/password');
    echo $this->escape($this->form, 'none');
?>

<?php Fisma_Format_Section::stopSection(); ?>
