<div class="searchFilters">
    <div class="left">
        <?php
        $listButton = new Fisma_Yui_Form_Button_Link('listButton', 
                                               array('value' => 'Account List', 
                                                     'href' => '/user/list'));
        echo $this->escape($listButton, 'none');

        if ($this->acl()->hasPrivilegeForClass('create', 'User')) {
            $createButton = new Fisma_Yui_Form_Button_Link('createButton', 
                                                   array('value' => 'Add Account', 
                                                         'href' => '/user/create'));
            echo $this->escape($createButton, 'none');
        } 
        ?>
    </div>
    <div class="right">
        <form name="query" method="post" action="/user/list" style="display:inline">
        <span class="searchField">
            <b><label for="keywords">Search:</label>&nbsp;</b>
            <input id="keywords"
                   name="keywords" 
                   value="<?php echo  $this->escape($this->keywords)?>" 
                   title="Input your query value" 
                   size="20" 
                   maxlength="40" 
                   type="text">
        </span>
        <span id="searchContainer"></span>
        <script type='text/javascript'>
           var save = new YAHOO.widget.Button({
               type: "submit",
               label: "Search",
               value: "Search",
               container: "searchContainer",
               disabled: false
           });
        </script>
        </form>
    </div>
    <div class="clear"></div>
</div>
