<?php Fisma_Format_Section::startSection("User Account Information"); ?>

<?php
if (!empty($this->requirements)) {
?>
    <p>The password must meet the following complexity criteria:</p>
    <ul>
    <?php foreach ($this->requirements as $requirement): ?>
        <li>
            <?php echo $this->escape($requirement, 'none'); ?>
        </li>
    <?php endforeach; ?>
    </ul>
<?php
}
?>

<div class="form_box" id="userForm">
    <?php
        echo $this->escape($this->form, 'none');
        echo $this->escape($this->tabView, 'none');
    ?>
</div>
<?php
Fisma_Format_Section::stopSection();
$opts = array('roles' => $this->roles, 'id' => $this->id, 'readOnly' => 0);
echo $this->partial('yui/roles.phtml', $opts);
unset($opts);
?>