<?php Fisma_Format_Section::startSection("User Account Administration"); ?>

<table class="tipframe" align="center"  width="98%" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <th>[<a id="user_list" href="/panel/account/sub/list">User List</a>] (total: <?php echo $this->total;?>)</th>
            <th>[<a id="add_user" href="/panel/account/sub/create" title="add new Users">Add User</a>]</th>
            <th>[<a id="user_log" href="/panel/log/sub/view" title="Review user logs">User Logs</a>]</th>
            <th>
                <table align="center">
                    <tbody>
                        <tr height="22">
                            <td><b>Page:&nbsp;</b></td>
                            <td><?php echo $this->links['all'];?></td>
                        </tr>
                    </tbody>
                </table>
            </th>
            <th>
                
                <form name="query" method="post" action="<?php echo $this->postAction;?>">
                    <table align="center">
                        <tr>
                            <td><b>Query:&nbsp;</b></td>
                            <td><select name="fid">
                            <?php foreach($this->criteria as $k=>$v){
                                if($k == $this->fid){
                                    $selected = " selected";
                                }
                                else {
                                    $selected = "";
                                }
                                echo'<option value="'.$k.'" '.$selected.'>'.$v.'</option>';
                            }
                            ?>
                            </select></td>
                            <td><input name="qv" value="<?php echo $this->qv;?>" size="10" maxlength="40" type="text"></td>

                             <td><input value="Search" type="submit"></td>
                        </tr>
                    </table>
                </form>
            </th>
        </tr>
    </tbody>
</table>

<?php Fisma_Format_Section::stopSection(); ?>
