<div class="approvalHeader">
    <b>File: </b>

    <a href='/finding/remediation/downloadevidence/id/<?php echo $this->escape($this->artifact->id)?>' target='_blank'>
        <?php echo $this->escape($this->artifact->Attachments[0]->fileName); ?>
    </a>

    submitted by 

    <?php 
        $user = $this->artifact->Attachments[0]->User;
        $fullName = $user->nameFirst . ' ' . $user->nameLast;
        
        echo $this->escape($this->userInfo($fullName, $user->username), 'none');
    ?> 
    on 
    <?php echo $this->escape($this->artifact->createdTs); ?>
</div>
