<?php
Fisma_Format_Section::startSection('Finding ' . $this->escape($this->translate('Finding_Attachments')));
?>

<?php
if (!(
    $this->finding->isDeleted() ||
    ($this->finding->CurrentStep && !$this->finding->CurrentStep->attachmentEditable) ||
    !$this->acl()->hasPrivilegeForObject('upload_evidence', $this->finding)
)):
    $uploadEvidenceButton = new Fisma_Yui_Form_Button(
        'uploadEvidenceButton',
        array(
            'label' => 'Upload New ' . $this->escape($this->translate('Finding_Attachment')),
            'onClickFunction' => 'Fisma.Remediation.uploadEvidence',
            'onClickArgument' => array(
               'title' => 'Upload New ' . $this->escape($this->translate('Finding_Attachment'))
            )
        )
    );
?>
<div class='buttonBar'>
    <?php echo $this->escape($uploadEvidenceButton, 'none');  ?>
</div> <!-- end of div.buttonBar -->
<?php endif; ?>

<?php
// Print the evidence package table (if not empty)
if ($this->finding->Attachments->count() > 0):
    echo $this->escape($this->evidencePackage, 'none');
else: ?>
    The evidence package is empty.
<?php
endif;

Fisma_Format_Section::stopSection();
?>
