<?php
Fisma_Format_Section::startSection('Latest Evidence');
$addToEvidenceButton = new Fisma_Yui_Form_Button(
    'addToEvidenceButton',
    array(
        'label' => 'Add More Files',
        'onClickFunction' => 'Fisma.Remediation.uploadEvidence'
    )
);
if (
    $this->artifact->Finding->isDeleted() ||
    'EA' != $this->artifact->Finding->status ||
    !$this->acl()->hasPrivilegeForObject('upload_evidence', $this->artifact->Finding)
):
    $addToEvidenceButton->readOnly = true;
endif;
echo "<div class='buttonBar'>" . $this->escape($addToEvidenceButton, 'none') . "</div>";

echo $this->partial('remediation/artifact-header.phtml', array('artifact' => $this->artifact, 'isLatest' => true));
?>

<div class="approval">
    <?php
    $activeEvaluation = $this->finding->CurrentEvaluation; // <-- an Evaluation class, not a FindingEvaluation instance

    /**
     * This is used to track which evaluations have been completed for this artifact. After the first loop completes,
     * any evaluation (i.e. the Evaluation table) which is not on this list can be inferred to be pending or skipped.
     */
    $distinctEvaluationQuery = new Doctrine_RawSql(); // Cannot use subqueries in DQL joins
    $distinctEvaluationQuery
        ->select('{fe1.*}, {f.*}, {e.*}, {u.*}')
        ->from(
            "finding_evaluation fe1 " .
            "INNER JOIN (" .
                "SELECT MAX(createdts) AS updatedts " .
                "FROM finding_evaluation fe2 " .
                "WHERE fe2.evidenceid = {$this->artifact->id} " .
                "GROUP BY evaluationid" .
            ") fe3 ON fe1.createdts = fe3.updatedts " .
            "LEFT JOIN finding f ON fe1.findingid = f.id " .
            "LEFT JOIN evaluation e ON fe1.evaluationid = e.id " .
            "LEFT JOIN poc u ON fe1.userid = u.id " .
            "WHERE fe1.evidenceid = {$this->artifact->id} " .
            "ORDER BY fe1.createdts ASC"
        )
        ->addComponent('fe1', 'FindingEvaluation fe1')
        ->addComponent('e', 'fe1.Evaluation e')
        ->addComponent('f', 'fe1.Finding f')
        ->addComponent('u', 'fe1.User u');
    $distinctEvaluations = $distinctEvaluationQuery->execute();

    // First: display all of the completed evaluations for the artifact.
    foreach ($distinctEvaluations as $findingEvaluation):
        // Only evaluations preceeding to the CurrentEvaluation are marked as completed

        $user = $findingEvaluation->User;
        $fullName = $user->nameFirst . ' ' . $user->nameLast;

        $decision = $findingEvaluation->decision;
        $spanClass = strtolower($decision);
    ?>
        <div class="approvalStep">
            <p>
                <b><?php echo $this->escape($findingEvaluation->Evaluation->name); ?></b>

                <span class="<?php echo $this->escape($spanClass)?>">
                    <b><?php echo $this->escape($decision)?></b>
                    <?php echo $this->escape($this->userInfo($fullName, $user->username), 'none'); ?>
                    at <?php echo $this->escape($findingEvaluation->createdTs)?>
                </span>
            </p>
        <?php
            if (!empty($findingEvaluation->comment)):
                    echo $this->escape($this->textToHtml($this->escape($findingEvaluation->comment)), 'none');
            endif;
        ?>
        </div>
    <?php
    endforeach;
    ?>

<?php
/**
 * If the current status is 'EN', the current evidence must have been rejected.
 */
if ($this->finding->status == 'EA'):

    /**
     * Second: Show approval buttons for the current evaluation if the user has the required privileges.
     */
    if ($this->acl()->hasPrivilegeForObject($activeEvaluation->Privilege->action, $this->finding)):
    ?>
        <div class="approvalStep">
            <p>
                <b><?php echo $this->escape($activeEvaluation->name)?></b>
                <input type="hidden" name="comment" value="" />
                <input type="hidden" name="decision" value="APPROVED" />
<?php
        $message = 'WARNING: You are about to approve the evidence package. This action cannot be undone.'
                 . ' Are you sure that you want to continue?';

        $approveButton = new Fisma_Yui_Form_Button(
            'approveButton',
            array(
                'label' => 'APPROVE',
                'onClickFunction' => 'Fisma.Remediation.remediationAction',
                'onClickArgument' => array(
                    'action' => "APPROVED",
                    'formId' => "finding_detail",
                    'panelTitle' => "Evidence Approval",
                    'findingId' => $this->finding->id
                )
            )
        );
        echo $this->escape($approveButton, 'none');

        $denyButton = new Fisma_Yui_Form_Button(
            'denyButton',
            array(
                'label' => 'REJECT',
                'onClickFunction' => 'Fisma.Remediation.remediationAction',
                'onClickArgument' => array(
                    'action' => "REJECTED",
                    'formId' => "finding_detail",
                    'panelTitle' => "Evidence Denial",
                    'findingId' => $this->finding->id
                )
            )
        );

        echo $this->escape($denyButton, 'none');
?>

            </p>
        </div>
    <?php
    endif;

    /*
     * Third: If there are any evaluations beyond the current one, then they are listed here. For artifacts which are
     * already denied, the status is listed as 'SKIPPED' because those evaluation will never be performed. For artifacts
     * which are still under review, the status is listed as 'PENDING'.
     */
    foreach ($this->evaluations as $evaluation):
        if ($evaluation->precedence > $activeEvaluation->precedence):
//        if (!in_array($evaluation->id, $completedEvaluations)):
    ?>
            <div class='approvalStep'>
                <p><b><?php echo $this->escape($evaluation->name)?></b>PENDING</p>
            </div>
    <?php
        endif;
    endforeach;
endif;
    ?>
</div>
<?php
    Fisma_Format_Section::stopSection();
?>
