<?php
/**
 * Get artifact data as Doctrine Collection. Loop over to get icon URLs and file size, then convert to array
 * for view binding.
 */
$attachmentCollection = $this->artifact->Attachments;
$attachmentRows = array();

foreach ($attachmentCollection as $attachment) {
    $baseUrl = '/finding/remediation/';
    $currentUrl = '/evidenceId/' . $this->artifact->id . '/attachmentId/' . $attachment->id;
    $attachmentRows[] = array(
        'iconUrl'  => "<a href={$baseUrl}download-evidence{$currentUrl}><img src={$attachment->getIconUrl()}></a>",
        'fileName' => "<a href={$baseUrl}download-evidence{$currentUrl}><div>"
                    . $this->escape($attachment->fileName) . "</div></a>",
        'fileSize' => $attachment->getFileSize(),
        'user'     => $this->userInfo($attachment->User->username),
        'date'     => $attachment->createdTs,
        'action'   => "<a href={$baseUrl}delete-evidence{$currentUrl}>Delete</a>"
    );
}

$dataTable = new Fisma_Yui_DataTable_Local();

$dataTable->addColumn(
    new Fisma_Yui_DataTable_Column(
        'Icon',
        false,
        'Fisma.TableFormat.formatHtml',
        null,
        'icon'
    )
);

$dataTable->addColumn(
    new Fisma_Yui_DataTable_Column(
        'File Name',
        true,
        'Fisma.TableFormat.formatHtml',
        null,
        'fileName'
    )
);

$dataTable->addColumn(
    new Fisma_Yui_DataTable_Column(
        'Size',
        true,
        'Fisma.TableFormat.formatFileSize',
        null,
        'size',
        false,
        'number'
    )
);

$dataTable->addColumn(
    new Fisma_Yui_DataTable_Column(
        'Uploaded By',
        true,
        'Fisma.TableFormat.formatHtml',
        null,
        'uploadedBy'
    )
);

$dataTable->addColumn(
    new Fisma_Yui_DataTable_Column(
        'Upload Date',
        true,
        null,
        null,
        'uploadDate'
    )
);

if (
    $this->acl()->hasPrivilegeForObject('upload_evidence', $this->artifact->Finding) &&
    !$this->artifact->Finding->isDeleted() &&
    $this->isLatest &&
    in_array($this->artifact->Finding->status, array('EN', 'EA'))
):
    $dataTable->addColumn(
        new Fisma_Yui_DataTable_Column(
            'Action',
            true,
            'Fisma.TableFormat.formatHtml',
            null,
            null
        )
    );
endif;

$dataTable->setData($attachmentRows);
echo $this->escape($dataTable, 'none');
?>

<div class="approvalHeader">
    <b>Approval Status</b>
</div>
