<?php
echo $this->partial('remediation/artifact-header.phtml', array('artifact' => $this->artifact));
?>

<div class="approval">
    <?php
    /*
     * This is used to track which evaluations have been completed for this artifact. After the first loop completes,
     * any evaluation (i.e. the Evaluation table) which is not on this list can be inferred to be pending or skipped.
     */
    $completedEvaluations = array();
    
    // First: display all of the completed evaluations for the artifact.
    foreach ($this->artifact->FindingEvaluations as $findingEvaluation):
        $completedEvaluations[] = $findingEvaluation->Evaluation->id;

        $user = $findingEvaluation->User;
        $fullName = $user->nameFirst . ' ' . $user->nameLast;
        
        $decision = $findingEvaluation->decision;
        $spanClass = strtolower($decision);
    ?>
        <div class="approvalStep">
            <p>
                <b><?php echo $this->escape($findingEvaluation->Evaluation->name); ?></b>
                
                <span class="<?php echo $this->escape($spanClass)?>">
                    <b><?php echo $this->escape($decision)?></b>
                    <?php echo $this->escape($this->userInfo($fullName, $user->username), 'none'); ?> 
                    at <?php echo $this->escape($findingEvaluation->createdTs)?>
                </span>
            </p>
        <?php 
            if (!empty($findingEvaluation->comment)):
                    echo $this->escape($this->textToHtml($this->escape($findingEvaluation->comment)), 'none');
            endif;
        ?>
        </div>
    <?php
    endforeach;
    ?>

    <?php
    $activeEvaluation = $this->finding->CurrentEvaluation;

    /*
     * Second: Show approval buttons for the current evaluation if the user has the required privileges.
     */
    if ($this->acl()->hasPrivilegeForObject($activeEvaluation->Privilege->action, $this->finding)):
        $completedEvaluations[] = $activeEvaluation->id;
    ?>
        <div class="approvalStep">
            <p>
                <b><?php echo $this->escape($activeEvaluation->name)?></b>
                <input type="hidden" name="comment" value="" />
                <input type="hidden" name="decision" value="APPROVED" />
<?php
        $message = 'WARNING: You are about to approve the evidence package. This action cannot be undone.'
                 . ' Are you sure that you want to continue?';
    
        $approveButton = new Fisma_Yui_Form_Button(
            'approveButton',
             array(
                  'label' => 'APPROVED', 
                  'onClickFunction' => 'Fisma.Util.showConfirmDialog',
                  'onClickArgument' => array(
                      'text' => $message, 
                      'func' => 'Fisma.Remediation.remediationAction',
                      'args' => array("APPROVED", "finding_detail", "Evidence Approval")
                 )
            )    
        );
        echo $this->escape($approveButton, 'none');
    
        $message = 'WARNING: You are about to deny the evidence package. This action cannot be undone.'
                 . ' Are you sure that you want to continue?';
    
        $denyButton = new Fisma_Yui_Form_Button(
            'denyButton',
            array(
                  'label' => 'DENIED', 
                  'onClickFunction' => 'Fisma.Util.showConfirmDialog',
                  'onClickArgument' => array(
                      'text' => $message, 
                      'func' => 'Fisma.Remediation.remediationAction',
                      'args' => array("DENIED", "finding_detail", "Evidence Denial")
                  )
            )
        );

        echo $this->escape($denyButton, 'none');
?>

            </p>
        </div>
    <?php
    endif;

    /*
     * Third: If there are any evaluations beyond the current one, then they are listed here. For artifacts which are 
     * already denied, the status is listed as 'SKIPPED' because those evaluation will never be performed. For artifacts
     * which are still under review, the status is listed as 'PENDING'.
     */
    foreach ($this->evaluations as $evaluation):
        if (!in_array($evaluation->id, $completedEvaluations)):
    ?>
            <div class='approvalStep'>
                <p><b><?php echo $this->escape($evaluation->name)?></b>PENDING</p>
            </div>
    <?php
        endif;
    endforeach;
    ?>
</div>
