<?php
Fisma_Format_Section::startSection('Comments');
?>
    <div class="buttonBar">
        <?php echo $this->escape($this->commentButton, 'none'); ?>
    </div>
    
    <div id="comments">
        <table id="commentsTable">
            <thead>
                <tr>
                    <th>Timestamp</th>
                    <th>User</th>
                    <th>Comment</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->comments as $comment):
                ?>
                    <tr>
                        <td><?php echo $this->escape($comment['createdTs']) ?></td>
                        <td><?php echo $this->escape($this->userInfo($comment['User']['username']), 'none') ?></td>
                        <td>
                            <?php 
                                echo $this->escape(
                                    Fisma_String::textToHtml($this->escape($comment['comment'])),
                                    'none'
                                )
                            ?>
                        </td>
                    </tr>                
                <?php
                endforeach;
                ?>
            </tbody>
        </table>
    </div>
<?php
Fisma_Format_Section::stopSection();
?>

<script type="text/javascript">
// Convert comments table to YUI table
YAHOO.util.Event.onContentReady('comments', function() {
    var columnDefs = [
        {key:'timestamp', label:'Timestamp', sortable:true, formatter: "text"},
        {key:'username', label:'User', sortable:true, formatter: "html"},
        {key:'comment', label:'Comment', sortable:false}
    ];

    var dataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("commentsTable"));
    dataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
    dataSource.responseSchema = {
        fields: [
            {key:'timestamp'},
            {key:'username'},
            {key:'comment'}
        ]
    };

    var commentTable = new YAHOO.widget.DataTable("comments", columnDefs, dataSource, {});
    
    Fisma.Finding.commentTable = commentTable;
});
</script>
