<?php $finding = $this->finding; $orgId = $finding->Organization->nickname; $status  = $finding->getStatus(); ?>

<div class="column66 left">
    <?php Fisma_Format_Section::startSection("Details"); ?>
        <table class="keyValues">
        <?php if (Fisma::configuration()->getConfig('use_legacy_finding_key')): ?>
            <tr>
                <td>Legacy Finding Key:</td>
                <td>
                    <span
                        <?php if ($this->isLegacyFindingKeyEditable): ?>
                            id="legacyFindingKey"
                            class="editable"
                            target="legacyFindingKey"
                            name="finding[legacyFindingKey]"
                            type="text"
                        <?php endif; ?>>
                        <?php echo $this->escape($finding->legacyFindingKey); ?>&nbsp;
                    </span>
                </td>
            </tr>
        <?php endif; ?>
            <tr>
                <td>Source:</td>
                <td>
                    <span id="source"
                          type="select"
                          name="finding[sourceId]"
                          href="/metainfo/list/o/source/format/html/"
                          value="<?php echo $this->escape($finding->Source->id); ?>">
                          <?php
                          $sourceName = $finding->Source->nickname . ' - ' . $finding->Source->name;
                          if ($this->acl()->hasPrivilegeForObject('read', $finding->Source)):
                          ?>
                              <a href="/finding/source/view/id/<?php echo $this->escape($finding->Source->id); ?>">
                                 <?php echo $this->escape($sourceName);?>
                              </a>
                          <?php
                          else:
                              echo $this->escape($sourceName);
                          endif;
                          ?>
                    </span>

                    <?php
                    if ($this->isSourceEditable):
                    ?>
                        <span class="editable" target="source">&nbsp;</span>
                    <?php
                    endif;
                    ?>

                <?php if ($finding->uploadId): ?>
                    <br><?php echo $this->escape($finding->Upload->fileName
                        . ', uploaded on ' . $finding->Upload->createdTs .'.')?>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <td>Status:</td>
                <td title="<?php echo $this->escape($status); ?>">
                    <?php echo $this->escape($finding->getLongStatus()); ?>
                </td>
            </tr>
            <?php
            if ($status != 'CLOSED') {
            ?>
            <tr>
                <td>On Time:</td>
                <td>
                <?php echo $this->escape($this->onTimeState); ?>
                </td>
            </tr>
            <?php
            }
            ?>
            <tr>
                <td>
                    <div>
                        Organization/System:
                    </div>
                </td>
                <td>
                    <span id="organization"
                          type="select"
                          name="finding[responsibleOrganizationId]"
                          href="/metainfo/list/o/system/format/html/"
                          value="<?php echo $this->escape($finding->responsibleOrganizationId); ?>">
                    <a href="<?php echo $this->escape($this->organizationViewUrl); ?>">
                         <?php echo $this->escape($finding->Organization->nickname);?>
                         - <?php echo $this->escape($finding->Organization->name);?>
                    </a>
                    </span>

                    <?php
                    if ($this->isOrganizationEditable):
                    ?>
                        <span class="editable" target="organization">&nbsp;</span>
                    <?php
                    endif;
                    ?>
                </td>
            </tr>
        </table>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php if ($this->isDescriptionEditable):
        Fisma_Format_Section::startSection('Description', 'finding_description');
    else:
        Fisma_Format_Section::startSection('Description');
    endif; ?>
        <div name="finding[description]" id="finding_description" type="textarea" rows="3" cols="160">
            <?php echo $this->escape($finding->description, 'none'); ?>
        </div>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php if ($this->isRecommendationEditable):
        Fisma_Format_Section::startSection('Recommendation', 'recommendation');
    else:
        Fisma_Format_Section::startSection('Recommendation');
    endif; ?>
        <div name="finding[recommendation]" id="recommendation" type="textarea" rows="3" cols="160">
            <?php echo $this->escape($finding->recommendation, 'none'); ?>
        </div>
    <?php Fisma_Format_Section::stopSection(); ?>
</div>

<div class="column33 right">
    <?php Fisma_Format_Section::startSection('Dates'); ?>
        <table class="keyValues">
            <tr>
                <td>Date Discovered:</td>
                <td><?php echo $this->escape($finding->discoveredDate)?></td>
            </tr>
            <tr>
                <td>Date Opened:</td>
                <td><?php echo $this->escape($finding->createdTs)?></td>
            </tr>
            <tr>
                <td>Date Closed:</td>
                <td>
                    <?php
                    if (!is_null($finding->closedTs)) {
                        echo $this->escape($finding->closedTs);
                    } else {
                        echo $this->escape("<i>Not closed</i>", 'none');
                    }
                    ?>
                </td>
            </tr>
        </table>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php Fisma_Format_Section::startSection('People'); ?>
        <table class="keyValues">
            <tr>
                <td>Opened By:</td>
                <td><?php echo $this->escape($this->userInfo($finding->CreatedBy->username), 'none'); ?></td>
            </tr>
            <tr>
                <td>Point Of Contact:</td>
                <td><span
                    id="pointOfContact"
                    type="autocomplete"
                    xhr="/contact/autocomplete/format/json"
                    queryPrepend="/keyword/"
                    schemaObject="pointsOfContact"
                    schemaField="name"
                    name="finding[pocId]"
                <?php if ($this->acl()->hasPrivilegeForClass('create', 'Poc')): ?>
                    setupCallback="Fisma.Finding.setupPocAutocomplete"
                <?php endif; ?>
                    value="<?php echo $this->escape($finding->pocId); ?>"
                    defaultValue="<?php echo $this->escape($finding->PointOfContact->username); ?>"
                    ><?php echo $this->escape($this->userInfo($finding->PointOfContact->username), 'none');?>
                </span>
            <?php if ($this->isPocEditable): ?>
                <span class="editable" target="pointOfContact">&nbsp;</span>
            <?php endif; ?>
            </tr>
        </table>
    <?php Fisma_Format_Section::stopSection(); ?>
</div>

<div class="clear"></div>