<?php
    $finding = $this->finding;
    $orgId = $finding->ResponsibleOrganization->nickname;
    $status  = $finding->getStatus();
?>
<div>
    <?php Fisma_Format_Section::startSection("Details"); ?>
    <table class="keyValues">
        <tr>
            <td>Finding ID:</td>
            <td><?php echo $this->escape($finding->id)?></td>
        </tr>
        <tr>
            <td>Date Discovered:</td>
            <td><?php echo $this->escape($finding->discoveredDate)?></td>
        </tr>
        <tr>
            <td>Date Opened:</td>
            <td><?php echo $this->escape($finding->createdTs)?></td>
        </tr>
        <tr>
            <td>Date Closed:</td>
            <td>
                <?php 
                if (!is_null($finding->closedTs)) {
                    echo $this->escape($finding->closedTs);
                } else {
                    echo $this->escape("<i>Not closed</i>", 'none');
                }
                ?>
            </td>
        </tr>
        <tr>
            <td>Source:</td>
            <td>
                (<?php echo $this->escape($finding->Source->nickname)?>)
                <?php echo $this->escape($finding->Source->name)?>
            <?php if ($finding->uploadId): ?>
                <br><?php echo $this->escape($finding->Upload->fileName)?>
            <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td>Status:</td>
            <td><?php echo $this->escape($status)?></td>
        </tr>
        <?php 
        if ($status != 'CLOSED') { 
        ?>
        <tr>
            <td>On Time:</td>
            <td>
            <?php if (is_null($finding->nextDueDate)): ?>
                N/A
            <?php elseif (date('Ymd', time()) <= date('Ymd', strtotime($finding->nextDueDate))): ?>
                On Time
            <?php else: ?>
                Overdue
            <?php endif; ?>
            </td>
        </tr>
        <?php 
        } 
        ?>
        <tr>
            <td>
                <div>
                    Responsible Organization:
                </div>
            </td>
            <td>
                <span id="organization" 
                      type="select" 
                      name="finding[responsibleOrganizationId]" 
                      href="/metainfo/list/o/system/format/html/"
                      value="<?php echo $this->escape($finding->responsibleOrganizationId); ?>">
                     <a href="/organization/view/id/<?php echo $this->escape($finding->responsibleOrganizationId); ?>">
                         <?php echo $this->escape($finding->ResponsibleOrganization->nickname);?> 
                         - <?php echo $this->escape($finding->ResponsibleOrganization->name);?>
                    </a>
                </span>

                <?php
                if (('NEW' == $status || 'DRAFT' == $status)
                     && $this->acl()->hasPrivilegeForObject('update_assignment', $finding)):
                ?>
                    <span class="editable" target="organization">&nbsp;</span>
                <?php 
                endif; 
                ?>
            </td>
        </tr>
    </table>
    <?php Fisma_Format_Section::stopSection(); ?>
</div>

<div class="clear"></div>

<?php 
if ($this->acl()->hasPrivilegeForObject('update_description', $finding)
    && ('NEW' == $status || 'DRAFT' == $status)) {
    Fisma_Format_Section::startSection('Description', 'finding_description');
} else {
    Fisma_Format_Section::startSection('Description');
}
?>
<div name="finding[description]" id="finding_description" type="textarea" rows="3" cols="160"> 
    <?php echo $this->escape($finding->description, 'none'); ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>

<?php
if (('NEW' == $status || 'DRAFT' == $status)
    && $this->acl()->hasPrivilegeForObject('update_recommendation', $finding)) {
    Fisma_Format_Section::startSection('Recommendation', 'recommendation');
} else {
    Fisma_Format_Section::startSection('Recommendation');
}
?>
<div name="finding[recommendation]" id="recommendation" type="textarea" rows="3" cols="160">
    <?php echo $this->escape($finding->recommendation, 'none'); ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>

