<?php
    $finding = $this->finding;
    $orgId = $finding->ResponsibleOrganization->nickname;
    $status  = $finding->getStatus();
?>
<div class="column left">
    <?php Fisma_Format_Section::startSection("Details"); ?>
    <table class="keyValues">
        <tr>
            <td>Finding ID:</td>
            <td><?php echo $this->escape($finding->id)?></td>
        </tr>
        <tr>
            <td>Legacy Finding Key:</td>
            <td>
                <span 
                    <?php
                    if (!$this->finding->isDeleted() && ('NEW' == $status || 'DRAFT' == $status) &&
                        $this->acl()->hasPrivilegeForObject('update_legacy_finding_key', $finding)) {
                    ?>
                        id="legacyFindingKey" 
                        class="editable" 
                        target="legacyFindingKey" 
                        name="finding[legacyFindingKey]" 
                        type="text"
                    <?php 
                    }
                    ?>>
                    <?php echo $this->escape($finding->legacyFindingKey); ?>&nbsp;
                </span>
            </td>
        </tr>
        <tr>
            <td>Date Discovered:</td>
            <td><?php echo $this->escape($finding->discoveredDate)?></td>
        </tr>
        <tr>
            <td>Date Opened:</td>
            <td><?php echo $this->escape($finding->createdTs)?></td>
        </tr>
        <tr>
            <td>Date Closed:</td>
            <td>
                <?php 
                if (!is_null($finding->closedTs)) {
                    echo $this->escape($finding->closedTs);
                } else {
                    echo $this->escape("<i>Not closed</i>", 'none');
                }
                ?>
            </td>
        </tr>
        <tr>
            <td>Source:</td>
            <td>
                <span id="source" 
                      type="select" 
                      name="finding[sourceId]" 
                      href="/metainfo/list/o/source/format/html/"
                      value="<?php echo $this->escape($finding->Source->id); ?>">
                      <?php
                      $sourceName = $finding->Source->nickname . ' - ' . $finding->Source->name;
                      if ($this->acl()->hasPrivilegeForObject('read', $finding->Source)):
                      ?>
                          <a href="/finding/source/view/id/<?php echo $this->escape($finding->Source->id); ?>">
                             <?php echo $this->escape($sourceName);?>
                          </a>
                      <?php
                      else:
                          echo $this->escape($sourceName);
                      endif;
                      ?>
                </span>

                <?php
                if (!$this->finding->isDeleted() && ('NEW' == $status || 'DRAFT' == $status)
                     && $this->acl()->hasPrivilegeForObject('update_finding_source', $finding)):
                ?>
                    <span class="editable" target="source">&nbsp;</span>
                <?php 
                endif;
                ?>
                
            <?php if ($finding->uploadId): ?>
                <br><?php echo $this->escape($finding->Upload->fileName)?>
            <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td>Status:</td>
            <td><?php echo $this->escape($status)?></td>
        </tr>
        <?php 
        if ($status != 'CLOSED') { 
        ?>
        <tr>
            <td>On Time:</td>
            <td>
            <?php if (is_null($finding->nextDueDate)): ?>
                N/A
            <?php elseif (date('Ymd', time()) <= date('Ymd', strtotime($finding->nextDueDate))): ?>
                On Time
            <?php else: ?>
                Overdue
            <?php endif; ?>
            </td>
        </tr>
        <?php 
        } 
        ?>
        <tr>
            <td>
                <div>
                    Responsible Organization:
                </div>
            </td>
            <td>
                <span id="organization" 
                      type="select" 
                      name="finding[responsibleOrganizationId]" 
                      href="/metainfo/list/o/system/format/html/"
                      value="<?php echo $this->escape($finding->responsibleOrganizationId); ?>">
                     <a href="/organization/view/id/<?php echo $this->escape($finding->responsibleOrganizationId); ?>">
                         <?php echo $this->escape($finding->ResponsibleOrganization->nickname);?> 
                         - <?php echo $this->escape($finding->ResponsibleOrganization->name);?>
                    </a>
                </span>

                <?php
                if (!$this->finding->isDeleted() && ('NEW' == $status || 'DRAFT' == $status)
                     && $this->acl()->hasPrivilegeForObject('update_assignment', $finding)):
                ?>
                    <span class="editable" target="organization">&nbsp;</span>
                <?php 
                endif; 
                ?>
            </td>
        </tr>
    </table>
    <?php Fisma_Format_Section::stopSection(); ?>
</div>

<div class="column right">
    <?php 
        Fisma_Format_Section::startSection("Asset");
        if (is_null($finding->assetId)):
    ?>
        <p><i>No asset associated with this finding.</i></p>
    <?php
        elseif ($this->acl()->hasPrivilegeForObject('read', $finding->Asset)):
    ?>
    <table class="keyValues">
        <tr>
            <td>
                Asset Owner:
            </td>
            <td>
                <?php
                    if (isset($finding->Asset->Organization->name)) {
                        echo $this->escape($finding->Asset->Organization->name);
                    } else {
                        echo $this->escape('n/a', 'none');
                    }
                ?>
            </td>
        </tr>
        <tr>
            <td>
                Asset Name:
            </td>
            <td>
                <?php echo $this->escape(isset($finding->Asset->name) ? $finding->Asset->name : 'n/a');?>
            </td>
        </tr>
        <tr>
            <td>
                Network:
            </td>
            <td>
                <?php
                    if (isset($finding->Asset->Network->name)) {
                        echo $this->escape($finding->Asset->Network->name);
                    } else {
                        echo $this->escape('n/a', 'none');
                    }
                ?>
            </td>
        </tr>
        <tr>
            <td>
                IP Address:
            </td>
            <td>
                <?php
                    if (isset($finding->Asset->Network->name)) {
                        echo $this->escape($finding->Asset->addressIp . ':' . $finding->Asset->addressPort);
                    } else {
                        echo $this->escape('n/a', 'none');
                    }
                ?>
            </td>
        </tr>
        <tr>
            <td>
                Product Information:
            </td>
            <td>
                <?php  
                    if (!empty($finding->Asset->Product->name)) {
                        echo $this->escape(
                            $finding->Asset->Product->vendor . ' ' .
                            $finding->Asset->Product->name . ' ' .
                            $finding->Asset->Product->version
                        );
                    } else {
                        echo $this->escape('n/a');
                    }
                ?>
            </td>
        </tr>
    </table>
    <?php
        else:
    ?>
        <i>Asset information cannot be displayed because you do not have the privileges required.</i>
    <?php
        endif;
        Fisma_Format_Section::stopSection(); 
    ?>
</div>

<div class="clear"></div>

<?php 
if (!$this->finding->isDeleted() && $this->acl()->hasPrivilegeForObject('update_description', $finding)
    && ('NEW' == $status || 'DRAFT' == $status)) {
    Fisma_Format_Section::startSection('Description', 'finding_description');
} else {
    Fisma_Format_Section::startSection('Description');
}
?>
<div name="finding[description]" id="finding_description" type="textarea" rows="3" cols="160"> 
    <?php echo $this->escape($finding->description, 'none'); ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>

<?php
if (!$this->finding->isDeleted() && ('NEW' == $status || 'DRAFT' == $status)
    && $this->acl()->hasPrivilegeForObject('update_recommendation', $finding)) {
    Fisma_Format_Section::startSection('Recommendation', 'recommendation');
} else {
    Fisma_Format_Section::startSection('Recommendation');
}
?>
<div name="finding[recommendation]" id="recommendation" type="textarea" rows="3" cols="160">
    <?php echo $this->escape($finding->recommendation, 'none'); ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>

<?php 
Fisma_Format_Section::startSection("Cross-References");
?>
    <p>
        Cross-references are typically provided by automated scanners. These cross-references link to external websites
        which may be able to provide additional context and/or technical detail for this finding.
    </p>
    <table class="keyValues">
        <?php 
        if ($this->finding->Bugtraqs->count() > 0): 
            foreach ($this->finding->Bugtraqs as $bugtraq):
        ?>
                <tr>
                    <td>
                        Bugtraq:
                    </td>
                    <td>
                        <a href="<?php echo $this->escape($bugtraq->getUrl(), 'none'); ?>">
                            <?php echo $this->escape($bugtraq->value); ?>
                        </a>
                    </td>
                </tr>
        <?php 
            endforeach;
        else: 
        ?>
            <tr>
                <td>
                    Bugtraq:
                </td>
                <td>
                    <i>No Bugtraq cross-references available</i>
                </td>
            </tr>
        <?php
        endif;
        ?>

        <?php 
        if ($this->finding->Cves->count() > 0): 
            foreach ($this->finding->Cves as $cve):
        ?>
                <tr>
                    <td>
                        CVE:
                    </td>
                    <td>
                        <a href="<?php echo $this->escape($cve->getUrl(), 'none'); ?>">
                            <?php echo $this->escape($cve->value); ?>
                        </a>
                    </td>
                </tr>
        <?php 
            endforeach;
        else: 
        ?>
            <tr>
                <td>
                    CVE:
                </td>
                <td>
                    <i>No CVE cross-references available</i>
                </td>
            </tr>
        <?php
        endif;
        ?>

        <?php 
        if ($this->finding->Xrefs->count() > 0): 
            foreach ($this->finding->Xrefs as $xref):
                $url = $xref->getUrl();
        ?>
                <tr>
                    <td>
                        Xref:
                    </td>
                    <td>
                        <?php if (!is_null($url)): ?>
                        <a href="<?php echo $this->escape($url, 'none'); ?>">
                            <?php echo $this->escape($xref->value); ?>
                        </a>
                        <?php else: ?>
                            <?php echo $this->escape($xref->value); ?> (No link available)
                        <?php endif; ?>
                    </td>
                </tr>
        <?php 
            endforeach;
        else: 
        ?>
            <tr>
                <td>
                    Xref:
                </td>
                <td>
                    <i>No Xref cross-references available</i>
                </td>
            </tr>
        <?php
        endif;
        ?>
    </table>
<?php
Fisma_Format_Section::stopSection(); 
?>
