<?php
    $finding = $this->finding;
    $orgId = $finding->Organization->nickname;
    if (!$optionalFields = Fisma::configuration()->getConfig('optionalFields')) {
        $optionalFields = array();
    }
    $step = $finding->CurrentStep;
?>

<div class="column66 left">
    <?php Fisma_Format_Section::startSection("Summary"); ?>
        <table class="keyValues">
        <?php if (in_array('legacyFindingKey', $optionalFields)): ?>
            <tr>
                <td>Legacy Finding Key:</td>
                <td>
                    <span
                        <?php if ($this->isLegacyFindingKeyEditable): ?>
                            id="legacyFindingKey"
                            class="editable"
                            target="legacyFindingKey"
                            name="finding[legacyFindingKey]"
                            type="text"
                        <?php endif; ?>>
                        <?php echo $this->escape($finding->legacyFindingKey); ?>&nbsp;
                    </span>
                </td>
            </tr>
        <?php endif; ?>
        <?php if (in_array('findingAuditYear', $optionalFields)): ?>
            <tr>
                <td>Audit Year:</td>
                <td>
                    <span
                        <?php if ($this->isAuditYearEditable): ?>
                            id="auditYear"
                            class="editable"
                            target="auditYear"
                            name="finding[auditYear]"
                            type="text"
                        <?php endif; ?>>
                        <?php echo $this->escape($finding->auditYear); ?>&nbsp;
                    </span>
                </td>
            </tr>
        <?php endif; ?>
            <tr>
                <td>Source:</td>
                <td>
                    <span id="source"
                          type="select"
                          name="finding[sourceId]"
                          href="/metainfo/list/o/source/format/html/"
                          value="<?php echo $this->escape($finding->Source->id); ?>">
                          <?php
                          $sourceName = $finding->Source->nickname . ' - ' . $finding->Source->name;
                          if ($this->acl()->hasPrivilegeForObject('read', $finding->Source)):
                          ?>
                              <a href="/finding/source/view/id/<?php echo $this->escape($finding->Source->id); ?>">
                                 <?php echo $this->escape($sourceName);?>
                              </a>
                          <?php
                          else:
                              echo $this->escape($sourceName);
                          endif;
                          ?>
                    </span>

                    <?php
                    if ($this->isSourceEditable):
                    ?>
                        <span class="editable" target="source">&nbsp;</span>
                    <?php
                    endif;
                    ?>

                <?php if ($finding->uploadId): ?>
                    <br><?php echo $this->escape($finding->Upload->fileName
                        . ', uploaded on ' . $finding->Upload->createdTs .'.')?>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <td><?php echo $this->escape($this->translate('Finding_Status')); ?></td>
                <td><?php echo $this->escape(($finding->isResolved) ? 'YES' : 'NO'); ?></td>
            <tr>
                <td>Workflow Step:</td>
                <td>
                    <span title='<?php echo $this->escape($step->Workflow->description); ?>'>
                        <?php echo $this->escape($step->Workflow->name); ?>
                    </span>
                    -
                    <span title='<?php echo $this->escape($step->label); ?>'>
                        <?php echo $this->escape($step->name); ?>
                    </span>
                    <?php
                    if (strpos($this->workflowOnTimeState, 'On Time') === 0) {
                        ?>(<font color='green'><?php echo $this->escape($this->workflowOnTimeState); ?></font>)<?php
                    } else if (strpos($this->workflowOnTimeState, 'Due Today') === 0) {
                        ?>(<font color='orange'>Due Today</font>)<?php
                    } else if (strpos($this->workflowOnTimeState, 'Overdue') === 0) {
                        ?>(<font color='red'><?php echo $this->escape($this->workflowOnTimeState); ?></font>)<?php
                    }
                    ?>
                </td>
            </tr>
        <?php if (!$finding->isResolved && !empty($finding->currentEcd)): ?>
            <tr>
                <td>ECD:</td>
                <td><?php
                    $currentEcd = new Zend_Date($finding->currentEcd, Fisma_Date::FORMAT_DATE);
                    $currentEcd->setTimezone(CurrentUser::getAttribute('timezone'));
                    echo $this->escape($currentEcd->toString(Fisma_Date::FORMAT_MONTH_DAY_YEAR));
                    ?> (<?php
                    if (strpos($this->onTimeState, 'On Time') === 0) {
                        ?><font color='green'><?php echo $this->escape($this->onTimeState); ?></font><?php
                    } else if (strpos($this->onTimeState, 'Due Today') === 0) {
                        ?><font color='orange'>Due Today</font><?php
                    } else if (strpos($this->onTimeState, 'Overdue') === 0) {
                        ?><font color='red'><?php echo $this->escape($this->onTimeState); ?></font><?php
                    }
                ?>)</td>
            </tr>
        <?php endif; ?>
            <tr>
                <td>
                    <div>
                        Organization/System:
                    </div>
                </td>
                <td>
                    <span id="organization"
                          type="select"
                          name="finding[responsibleOrganizationId]"
                          affected="parentOrganization"
                          href="/metainfo/list/o/system/format/html/"
                          value="<?php echo $this->escape($finding->responsibleOrganizationId); ?>">
                        <?php if (!empty($this->finding->Organization)): ?>
                            <?php
                                echo $this->escape(
                                    $this->organizationInfo(
                                        $this->finding->Organization->nickname
                                            . " - "
                                            . $this->finding->Organization->name,
                                        $this->finding->Organization->id
                                    ),
                                    'none'
                                );
                            ?>
                        <?php else: ?>
                            &nbsp;
                        <?php endif; ?>
                    </span>

                    <?php
                    if ($this->isOrganizationEditable):
                    ?>
                        <span class="editable" target="organization">&nbsp;</span>
                    <?php
                    endif;
                    ?>
                </td>
            </tr>
            <tr>
                <td>Parent Organization:</td>
                <td>
                    <span id="parentOrganization">
                        <?php if (!empty($this->finding->denormalizedParentOrganizationId)): ?>
                            <?php
                                echo $this->escape(
                                    $this->organizationInfo(
                                        $this->finding->ParentOrganization->nickname
                                            . " - "
                                            . $this->finding->ParentOrganization->name,
                                        $this->finding->ParentOrganization->id
                                    ),
                                    'none'
                                );
                            ?>
                        <?php else: ?>
                            &nbsp;
                        <?php endif; ?>
                    </span>
                </td>
            </tr>
        </table>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php if ($this->isDescriptionEditable):
        Fisma_Format_Section::startSection('Description', 'finding_description');
    else:
        Fisma_Format_Section::startSection('Description');
    endif; ?>
        <div name="finding[description]" id="finding_description" type="textarea" rows="3" cols="160">
            <?php echo $this->escape($finding->description, 'none'); ?>
        </div>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php if ($this->isRecommendationEditable):
        Fisma_Format_Section::startSection('Recommendation', 'recommendation');
    else:
        Fisma_Format_Section::startSection('Recommendation');
    endif; ?>
        <div name="finding[recommendation]" id="recommendation" type="textarea" rows="3" cols="160">
            <?php echo $this->escape($finding->recommendation, 'none'); ?>
        </div>
    <?php Fisma_Format_Section::stopSection(); ?>
</div>

<div class="column33 right">
    <?php Fisma_Format_Section::startSection('Dates'); ?>
        <table class="keyValues">
            <tr>
                <td>Discovered:</td>
                <td><?php echo $this->escape($this->discoveredDate)?></td>
            </tr>
            <tr>
                <td>Created:</td>
                <td><?php echo $this->escape($this->createdTs)?></td>
            </tr>
            <?php if (!is_null($finding->closedTs)): ?><tr>
                <td>Resolved:</td>
                <td><?php echo $this->escape($this->closedTs); ?></td>
            </tr><?php endif; ?>
        </table>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php Fisma_Format_Section::startSection('People'); ?>
        <table class="keyValues">
            <tr>
                <td>Creator:</td>
                <td>
                    <?php echo $this->escape(
                        $this->userInfo($finding->CreatedBy->displayName, $finding->CreatedBy->id),
                        'none'
                    ); ?>
                </td>
            </tr>
            <tr>
                <td><?php echo $this->escape($this->translate('Finding_Point_of_Contact')); ?>:</td>
                <td class="autocomplete-width"><span
                    id="pointOfContact"
                    type="autocomplete"
                    xhr="/user/autocomplete/format/json"
                    queryPrepend="/keyword/"
                    schemaObject="pointsOfContact"
                    schemaField="name"
                    name="finding[pocId]"
                <?php if ($this->acl()->hasPrivilegeForClass('create', 'User')): ?>
                    setupCallback="Fisma.Finding.setupPocAutocomplete"
                <?php endif; ?>
                    value="<?php echo $this->escape($finding->pocId); ?>"
                    defaultValue="<?php echo $this->escape($finding->PointOfContact->username); ?>">
                    <?php
                        if (!empty($finding->pocId)) {
                            echo $this->escape(
                                $this->userInfo($finding->PointOfContact->displayName, $finding->pocId),
                                'none'
                            );
                        }
                    ?>
                    </span>
                <?php if ($this->isPocEditable): ?>
                    <span class="editable" target="pointOfContact">&nbsp;</span>
                <?php endif; ?>
                </td>
            </tr>
        <?php if ($finding->responsibleOrganizationId): ?>
        <?php
            $roleQuery = Doctrine_Query::create()
                ->from('Role r, r.UserRoles ur, ur.User u, ur.Organizations uro')
                ->where('r.type = ?', 'USER_GROUP')
                ->andWhere('uro.id = ?', $finding->Organization->id);

            foreach ($roleQuery->execute() as $r):
        ?>
            <tr>
                <th scope='row'><?php echo $this->escape($r->name); ?>:</th>
                <td><?php foreach ($r->UserRoles as $ur): ?>
                    <div>
                        <?php echo $this->escape($this->userInfo($ur->User->displayName, $ur->User->id), 'none'); ?>
                    </div>
                <?php endforeach; ?></td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?></table>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php Fisma_Format_Section::startSection('Finding Links'); ?>
    <?php if ($this->relationshipEditable): ?>
        <a href='#' onclick='Fisma.Remediation.addRelationship(<?php
            echo $this->escape($finding->id);
        ?>)'><img src='/images/add.png' style='vertical-align:top'/> Add a new link</a>
    <?php endif; ?>
        <ul>
        <?php foreach($finding->StartRelationships as $relationship): $endFinding = $relationship->EndFinding; ?>
            <li class='noQuestionMark'>
                This finding
                <?php echo $this->escape($relationship->getDirectAction()); ?>
                <?php echo $this->escape(new Fisma_Yui_Tooltip(
                    'finding' . $endFinding->id,
                    (($endFinding->isResolved) ? '<strike>' : '') .
                    "<a href='/finding/remediation/view/id/{$endFinding->id}'>Finding #{$endFinding->id}</a>" .
                    (($endFinding->isResolved) ? '</strike>' : ''),
                     "<b>" . $this->escape($this->translate('Finding_Status')) ."</b>: " .
                    (($finding->isResolved) ? 'YES' : 'NO') .
                    "<p>" . $this->escape($endFinding->description, 'javascript') . "</p>",
                    'none'
                ), 'none'); ?>
            <?php if ($this->relationshipEditable): ?>
                <img onclick='Fisma.Remediation.removeRelationship(<?php
                        echo $this->escape($relationship->id);
                    ?>, <?php
                        echo $this->escape($finding->id);
                    ?>)' src='/images/trash_recyclebin_empty_closed.png' style='vertical-align:top;cursor:pointer'/>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
        <?php foreach($finding->EndRelationships as $relationship): $startFinding = $relationship->StartFinding; ?>
            <li class='noQuestionMark'>
                This finding
                <?php echo $this->escape($relationship->getReverseAction()); ?>
                <?php echo $this->escape(new Fisma_Yui_Tooltip(
                    'finding' . $startFinding->id,
                    (($startFinding->isResolved) ? '<strike>' : '') .
                    "Finding #{$startFinding->id}</a>" .
                    (($startFinding->isResolved) ? '</strike>' : ''),
                    "<b>" . $this->escape($this->translate('Finding_Status')) ."</b>: " .
                    (($finding->isResolved) ? 'YES' : 'NO') .
                    "<p>" . $this->escape($startFinding->description, 'javascript') . "</p>",
                    'none'
                ), 'none'); ?>
            <?php if ($this->relationshipEditable): ?>
                <img onclick='Fisma.Remediation.removeRelationship(<?php
                        echo $this->escape($relationship->id);
                    ?>, <?php
                        echo $this->escape($finding->id);
                    ?>)' src='/images/trash_recyclebin_empty_closed.png' style='vertical-align:top;cursor:pointer'/>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ul>
    <?php Fisma_Format_Section::stopSection(); ?>
</div>

<div class="clear"></div>
