<?php
    Fisma_Format_Section::startSection("Mitigation Strategy");
    $finding = $this->finding;
    $this->table = $finding->getTable();
    $organization = $finding->Organization->nickname;
    $fromSearchUrl = $this->fromSearchUrl;
?>
<p>
    <b target="mitigation_strategy"
        <?php
            if ($this->isMitigationStrategyEditable) {
               echo $this->escape('class="editable"', 'none');
            }
        ?>>
        <?php $this->column('mitigationStrategy'); ?>:
    </b>
</p>
<div name="finding[mitigationStrategy]" id="mitigation_strategy" type="textarea">
    <?php echo $this->escape($finding->mitigationStrategy, 'none'); ?>
</div>

<p>
    <b
        <?php
            if ($this->isResourcesEditable) {
                echo $this->escape('class="editable" target="resources_required"', 'none');
            }
        ?>>
        <?php $this->column('resourcesRequired'); ?>:
    </b>
</p>
<div name="finding[resourcesRequired]" id="resources_required" type="textarea">
    <?php echo $this->escape($finding->resourcesRequired, 'none'); ?>
</div>

<?php if (!$finding->ecdLocked): ?>
    <p>
        <div><!-- Rendering calendar depends on this div -->
            <b><?php $this->column('currentEcd'); ?>:</b>
            <span name="finding[currentEcd]" id="currentEcd" type="text"
                <?php
                    if ($finding->canEdit('currentEcd')) {
                        echo $this->escape(' class="date editable" target="currentEcd"', 'none');
                    }
                    echo $this->escape('>', 'none');
                    echo $this->escape((empty($finding->currentEcd) ? 'NONE' : $finding->currentEcd), 'none');
                ?>
            </span>
        </div>
    </p>
<?php else: ?>
    <p>
        <i>
            The original ECD indicates the estimated completion date that was agreed upon when the finding
            was first approved, and it cannot be changed.
            The current ECD can be changed, but you must provide a written justification for the change.
        </i>
    </p>

    <p>
        <b><?php $this->column('originalEcd'); ?>:</b>
        <span><?php echo $this->escape($finding->originalEcd); ?></span>
    </p>

    <p>
        <div><!-- Rendering calendar depends on this div -->
            <b>Current ECD:</b>
            <span name="finding[currentEcd]" id="currentEcd" type="text"
                <?php
                    if ($finding->canEdit('currentEcd')) {
                        echo $this->escape(' class="date editable" target="currentEcd"', 'none');
                        $onclick = "Fisma.Finding.editEcdJustification();";
                        echo $this->escape('onclick="', 'none');
                        echo $this->escape($onclick, 'none');
                        echo $this->escape('"', 'none');
                    }
                    echo $this->escape('>', 'none');
                    echo $this->escape((empty($finding->currentEcd) ? 'NONE' : $finding->currentEcd));
                ?>
            </span>
        </div>
    </p>

    <p>
        <b><?php $this->column('ecdChangeDescription'); ?>: </b>
        <span id="currentChangeDescription"><?php echo $this->escape($finding->ecdChangeDescription); ?></span>
    </p>
<?php endif; ?>
<?php Fisma_Format_Section::stopSection(); ?>
