<?php
    Fisma_Format_Section::startSection("Mitigation Strategy"); 
    $finding = $this->finding;
    $organization = $finding->ResponsibleOrganization->nickname;
?>
<p>
    <b>Type:</b>

    <span type="select" name="finding[type]" href="/metainfo/list/o/type/format/html/" id="type"
        <?php 
            if (!$this->finding->isDeleted() && ('NEW' == $finding->status || 'DRAFT' == $finding->status) 
                && $this->acl()->hasPrivilegeForObject('update_type', $finding)) {
                echo $this->escape('class="editable" target="type"', 'none');
            }
        ?>>
        <?php echo $this->escape($finding->type)?>&nbsp;&nbsp;
    </span>
</p>
            
<p>
    <b target="mitigation_strategy"
        <?php 
            if (!$this->finding->isDeleted() && in_array($finding->status, array('NEW', 'DRAFT'))
                && $this->acl()->hasPrivilegeForObject('update_course_of_action', $finding)) {
               echo $this->escape('class="editable"', 'none');
            }
        ?>>
        Description:
    </b>
</p>
<div name="finding[mitigationStrategy]" id="mitigation_strategy" type="textarea">
    <?php echo $this->escape($finding->mitigationStrategy, 'none'); ?> 
</div>

<p>
    <b
        <?php
            if (!$this->finding->isDeleted() && in_array($finding->status, array('NEW', 'DRAFT'))
                && $this->acl()->hasPrivilegeForObject('update_resources', $finding)) {
                echo $this->escape('class="editable" target="resources_required"', 'none');
            } 
        ?>>
        Resources Required:
    </b>
</p>
<div name="finding[resourcesRequired]" id="resources_required" type="textarea"> 
    <?php echo $this->escape($finding->resourcesRequired, 'none'); ?> 
</div>

<?php if (!$finding->ecdLocked): ?>
    <p>
        <b>Expected Completion Date:</b>
        <span name="finding[currentEcd]" id="currentEcd" type="text"
            <?php 
                if ($finding->isEcdEditable()) {
                    echo $this->escape(' class="date editable" target="currentEcd"', 'none');
                }
                echo $this->escape('>', 'none');
                echo $this->escape((empty($finding->currentEcd) ? 'NONE' : $finding->currentEcd), 'none');
            ?>
        </span>
    </p>
<?php else: ?>
    <p>
        <i>
            The original ECD indicates the estimated completion date that was agreed upon when the finding 
            was first approved, and it cannot be changed.
            The current ECD can be changed, but you must provide a written justification for the change.
        </i>
    </p>
    
    <p>
        <b>Original ECD:</b>
        <span><?php echo $this->escape($finding->originalEcd); ?></span>
    </p>
    
    <p>
        <b>Current ECD:</b>
        <span name="finding[currentEcd]" id="currentEcd" type="text"
            <?php 
                if ($finding->isEcdEditable()) {
                    echo $this->escape(' class="date editable" target="currentEcd"', 'none');
                    $onclick = "Fisma.Finding.editEcdJustification();";
                    echo $this->escape('onclick="', 'none');
                    echo $this->escape($onclick, 'none');
                    echo $this->escape('"', 'none');
                }
                echo $this->escape('>', 'none');
                echo $this->escape((empty($finding->currentEcd) ? 'NONE' : $finding->currentEcd));
            ?>
        </span>
    </p>
    
    <p>
        <b>Justification for changing the ECD: </b>
        <span id="currentChangeDescription"><?php echo $this->escape($finding->ecdChangeDescription); ?></span>
    </p>
<?php endif; ?>

<p>
    <b>Actual Completion Date: </b>
    <span>
        <?php 
            if (empty($finding->actualCompletionDate)) {
                echo $this->escape('(not completed)', 'none');
            } else {
                echo $this->escape($finding->actualCompletionDate, 'none');
            }
        ?>
    </span>
</p>
    
<?php Fisma_Format_Section::stopSection(); ?>

<?php 
Fisma_Format_Section::startSection("Mitigation Strategy Approval");
$postAction = "/finding/remediation/msa/id/" . $finding->id;

$array = array('type'                   => $finding->type,
               'description'            => $finding->description,
               'recommendation'         => $finding->recommendation,
               'resources'              => $finding->resourcesRequired,
               'ECD'                    => $finding->currentEcd,
               'blscr'                  => $finding->securityControlId,
               'threat_level'           => $finding->threatLevel,
               'threat_source'          => $finding->threat,
               'cmeasure_effectiveness' => $finding->countermeasuresEffectiveness,
               'cmeasure'               => $finding->countermeasures);
$complete = true;
foreach ($array as $row) {
    $row = strip_tags($row);
    if ($row == '' || $row == 'NONE' || $row == '0000-00-00') {
        $complete = false;
        continue;
    }
}
$warning = "WARNING: You are about to submit mitigation strategy. This action cannot be undone. "
           . 'Please click "YES" to confirm your action or click "No" to stop.';
$url = "$postAction/do/submitmitigation";

if ('NEW' == $finding->status || 'DRAFT' == $finding->status) {
    $submitMitigationButton = new Fisma_Yui_Form_Button(
        'submitMitigation', 
        array(
              'label' => 'Submit Mitigation Strategy', 
              'onClickFunction' => 'Fisma.Util.showConfirmDialog',
              'onClickArgument' => array(
                  'url' =>  $url,
                  'text' => $warning 
              )
        )
    );

    if (
        $this->finding->isDeleted() || 
        false == $complete || 
        !$this->acl()->hasPrivilegeForObject('mitigation_strategy_submit', $finding)
    ) {
        $submitMitigationButton->readOnly = true;
    }
?>
    <p><i>The mitigation strategy, security control, and risk analysis sections must
          be fully completed before this can be submitted for approval.</i></p>

    <div class='buttonBar'><?php echo $this->escape($submitMitigationButton, 'none')?></div>
<?php
}

if (
    !$this->finding->isDeleted() && 
    'EN' == $finding->status && 
    $this->acl()->hasPrivilegeForObject('mitigation_strategy_revise', $finding)
) {
    $message = 'The revised mitigation strategy must be fully approved before evidence can be re-submitted.'
             . ' Are you sure that you want to continue?';
    $url = "$postAction/do/revisemitigation";
    $reviseMitigationButton = new Fisma_Yui_Form_Button(
        'reviseMitigationButton',
        array(
              'label' => 'Revise Mitigation Strategy', 
              'onClickFunction' => 'Fisma.Util.showConfirmDialog',
              'onClickArgument' => array(
                  'url' =>  $url,
                  'text' => $message, 
                  'isLink' => false
              )
        )
    );
?>
    <div class='buttonBar'><?php echo $this->escape($reviseMitigationButton, 'none')?></div>
<?php
}  

if ($finding->status != 'NEW' 
    && ($finding->status != 'DRAFT' || $finding->FindingEvaluations->count() > 0)) {
    echo $this->escape('<div class="approval">', 'none');
    foreach ($findingEvaluations = $finding->getFindingEvaluations('action') as $k => $findingEvaluation) {
        $user = $findingEvaluation->User;
        $fullName = $user->nameFirst . ' ' . $user->nameLast;
        
        $decision = $findingEvaluation->decision;
        echo $this->escape('<div class="approvalStep"><p><b>', 'none');
        echo $this->escape($findingEvaluation->Evaluation->name);
        echo $this->escape(':</b>', 'none');
        if ('APPROVED' == $decision) {
            echo $this->escape('<span class="approved"><b>', 'none');
            echo $this->escape($decision);
            echo $this->escape('</b>', 'none');
            echo $this->escape($this->userInfo($fullName, $user->username), 'none');
            echo $this->escape(' at ', 'none');
            echo $this->escape($findingEvaluation->createdTs);
            echo $this->escape('</span></p>', 'none');
            if (!empty($findingEvaluation->comment)) {
                echo $this->escape($this->textToHtml(htmlspecialchars($findingEvaluation->comment)), 'none');
            }
        } elseif ('DENIED' == $decision) {
            echo $this->escape('<span class="denied"><b>', 'none');
            echo $this->escape($decision);
            echo $this->escape('</b>', 'none');
            echo $this->escape($this->userInfo($fullName, $user->username), 'none');
            echo $this->escape(' at ', 'none');
            echo $this->escape($findingEvaluation->createdTs);
            echo $this->escape('</span></p>', 'none');
            if (!empty($findingEvaluation->comment)) {
                echo $this->escape($this->textToHtml(htmlspecialchars($findingEvaluation->comment)), 'none');
            }
        }
        echo $this->escape('</div>', 'none');
        if ($findingEvaluation->Evaluation->nextId == null || 'DENIED' == $decision) {
            echo $this->escape('</div>', 'none');
            if ($k != count($findingEvaluations)-1 || 'MSA' == $finding->status) {
                echo $this->escape('<div class="approval">', 'none');
            }
        }
    }

    $activeEvaluation = $finding->CurrentEvaluation;
    if ($activeEvaluation->id != null && $activeEvaluation->approvalGroup == 'action') {
        echo $this->escape('<div class="approvalStep"><p><b>', 'none');
        echo $this->escape($activeEvaluation->name);
        echo $this->escape('</b>', 'none');
        if (
            !$this->finding->isDeleted() && 
            $this->acl()->hasPrivilegeForObject($activeEvaluation->Privilege->action, $finding)
        ) {
            echo $this->escape('<input type="hidden" name="comment" value="" />', 'none');
            echo $this->escape('<input type="hidden" name="decision" value="APPROVED" />', 'none');

            $message = 'WARNING: You are about to approve the mitigation strategy. This action cannot be undone.'
                      . ' Are you sure that you want to continue?';
    
            $approveButton = new Fisma_Yui_Form_Button(
                'approveButton',
                array(
                      'label' => 'APPROVED', 
                      'onClickFunction' => 'Fisma.Util.showConfirmDialog',
                      'onClickArgument' => array(
                          'text' => $message, 
                          'func' => 'Fisma.Remediation.remediationAction',
                          'args' => array("APPROVED", "finding_detail", "Mitigation Strategy Approval") 
                      )
                )
            );
            echo $this->escape($approveButton, 'none');
    
            $message = 'WARNING: You are about to deny the mitigation strategy. This action cannot be undone.'
                      . ' Are you sure that you want to continue?';
            $denyButton = new Fisma_Yui_Form_Button(
                'denyButton',
                array(
                      'label' => 'DENIED', 
                      'onClickFunction' => 'Fisma.Util.showConfirmDialog',
                      'onClickArgument' => array(
                          'text' => $message, 
                          'func' => 'Fisma.Remediation.remediationAction',
                          'args' => array("DENIED", "finding_detail", "Mitigation Strategy Denial")
                      )
                )
            );

            echo $this->escape($denyButton, 'none');
        } else {
            echo $this->escape("PENDING", 'none');
        }
        echo $this->escape('</div>', 'none');
    }

    $disableEvaluations = array();
    $currentEvaluation  = $finding->CurrentEvaluation;
    if ($currentEvaluation->approvalGroup == 'action') {
        while ($currentEvaluation->nextId != null) {
            $currentEvaluation    = $currentEvaluation->NextEvaluation;
            $disableEvaluations[] = $currentEvaluation;
        }
    }

    foreach ($disableEvaluations as $evaluation) {
        echo $this->escape('<div class="approvalStep"><p><b>', 'none');
        echo $this->escape($evaluation->name);
        echo $this->escape('</b>N/A</div>', 'none');
    }
    echo $this->escape('</div>', 'none');
}
Fisma_Format_Section::stopSection(); 
?>
