<form
    id="finding_detail_reject_evidence"
    name="finding_detail_reject_evidence"
    method="post"
    enctype="multipart/form-data"
    onsubmit="return Fisma.Remediation.rejectEvidenceValidate();"
>
    <div class="messageBox attention">
        WARNING: You are about to deny the evidence package. This action cannot be undone.
    </div>
    <p><b>Which status do you want to send this finding to?</b></p>
    <p>
        <input type="radio" name="target_status" value="0" checked> Evidence Needed (EN)<br/>
    <?php
        foreach($this->previousEvaluations as $evaluation)
        {
            $id = $evaluation->id;
            echo "<input type='radio' name='target_status' value='{$id}' id='target_status_{$id}'> "
               . "<label for='target_status_{$id}'>{$evaluation->name} ($evaluation->nickname)</label><br/>";
        }
    ?>
    </p>
    <p>
        <label for="finding_detail_reject_evidence_comment"><b>Comments (REQUIRED):</b></label><br/>
        <textarea id="finding_detail_reject_evidence_comment" name="comment" rows=5 cols=60></textarea>
    </p>
    <div class="buttonBar">
        <input type="hidden" name="decision" value="REJECTED"/>
        <input type="submit" name="reject_evidence" value="Confirm"/>
        <button id="dialog_close">Cancel</button>
    </div>
</form>
