<?php
/** @codingStandardsIgnoreFile */
$outputCols = array();
$i = 0;
foreach ($this->columns as $k => $v) {
    if ($this->columnPreference & (1 << $i)) {
        $outputCols[$k] = $v['label'];
    }
    $i++;
}

$count_cols = count($outputCols);
// Taking Spreadsheet_Excel_Writer to generate the excel file
// Refer to http://pear.php.net/package/Spreadsheet_Excel_Writer
require_once ('Spreadsheet/Excel/Writer.php');
$workbook  = new Spreadsheet_Excel_Writer();
$workbook->setVersion(8); // fixes 255 char truncation issue

$worksheet =& $workbook->addWorksheet();

$format_header =& $workbook->addFormat(array('Size' => 10,
    'Align' => 'center',
    'Color' => 'white',
    'FgColor' => 'black',
    ));
$format_header->setFontFamily('Times New Roman');

$format_times =& $workbook->addFormat(array('Size' => 10,
    'Align' => 'center',
    'Color' => 'black',
    'BorderColor '=> 'blue',
    'Bottom'=>1,'Top'=>1,'Left'=>1,'Right'=>1));
$format_times->setFontFamily('Times New Roman');
$format_times->setAlign('left');
$format_times->setAlign('top');
$format_times->setTextWrap();
$rowi=0;
$worksheet->setColumn(0,0,20);
$worksheet->mergeCells($rowi, 0, $rowi, $count_cols-1);
$headinfo="Report run time: " . Fisma::now();
$worksheet->write($rowi++, 0, $headinfo,$format_times);

$worksheet->mergeCells($rowi,0,$rowi,$count_cols-1);
$worksheet->write($rowi++, 0, 'Results',$format_header);
// Set the width of a single column or a range of columns.
$worksheet->setColumn(0,0,10);
$worksheet->setColumn(2,2,50);
$worksheet->setColumn(3,8,10);
$worksheet->setColumn(9,10,50);
$worksheet->setColumn(11,14,15);
//inject the titles


$worksheet->writeRow($rowi++,0,$outputCols,$format_times);

foreach( $this->list as $p) {
    $data = array();
    foreach ($outputCols as $key => $val) {
        if (isset($p[$key])) {
            array_push($data, $p[$key]);
        } else {
            array_push($data, '');
        }
    }
    $worksheet->writeRow($rowi++,0,$data,$format_times); 
}

// IE has a bug where it can't display certain mimetypes if a no-cache header is sent,
// so we need to switch the header right before we stream the PDF.
header('Pragma: private');
header('Cache-Control: private');

$workbook->close();
?>
