<?php
/** @codingStandardsIgnoreFile */
define('REPORT_FOOTER_WARNING', "WARNING: This report is for internal, official use only.  This report contains sensitive computer security related information. Public disclosure of this information would risk circumvention of the law. Recipients of this report must not, under any circumstances, show or release its contents for purposes other than official action. This report must be safeguarded to prevent improper disclosure. Staff reviewing this document must hold a minimum of Public Trust Level 5C clearance.");

define('FONTS', Fisma::getPath('library') . '/pdf/fonts');

require_once( 'pdf/class.ezpdf.php');

$pdf = new Cezpdf('LEGAL', 'landscape');
$pdf->selectFont(FONTS . "/Helvetica.afm");
$horiz_margin = 50;
$bottom_margin = 100;
$top_margin = 50;
$page_width = 1000;
$warning_size = 8;

$left_top = array('x'=>$horiz_margin,'y'=>'585');
$right_bottom = array('x'=>$page_width-$horiz_margin,'y'=>$bottom_margin);
$content_width = $right_bottom['x'] - $left_top['x'];

$all = $pdf->openObject();
$pdf->saveState();

$head_height = 5;

$pdf->addTextWrap($left_top['x'], $left_top['y'], $content_width, 8, 'Report run time: ' . Fisma::now(), 'right');
$tmp_y = $left_top['y'] - $head_height;
$pdf->line($left_top['x'],$tmp_y,$right_bottom['x'],$tmp_y);
$pdf->setStrokeColor(0,0,0,1);

$y = $right_bottom['y'];
$pdf->line($left_top['x'],$y,$right_bottom['x'],$y);

// Add footer
$text = REPORT_FOOTER_WARNING;
$x = $left_top['x'];
$line_height = 8;
$y -= $line_height;
while(!empty($text)){
    $y -= $line_height;
    $text = $pdf->addTextWrap($x,$y,$content_width,$line_height,$text,'left');  
}

$pdf->restoreState();
$pdf->closeObject();

$pdf->addObject($all,'all');
$pdf->ezSetMargins($top_margin,$bottom_margin,$horiz_margin,$horiz_margin);

// we need to escape the syste/organization names in the first column.
$tableData = $this->tableData;
foreach ($tableData as &$tableRow) {
    $tableRow[0] = htmlentities($tableRow[0]);
}

$pdf->ezTable($tableData, $this->columns,'Finding Summary',
    array('fontSize'=>8, 'maxWidth'=>$content_width, 'titleFontSize'=>'12' ));

// IE has a bug where it can't display certain mimetypes if a no-cache header is sent,
// so we need to switch the header right before we stream the PDF.
header('Pragma: private');
header('Cache-Control: private');

echo $pdf->ezOutput();
?>
