<?php
// phpcs requires php tags or it generates warnings
?>

<form id="finding_detail_upload_evidence"
      name="finding_detail_upload_evidence" method="post" enctype="multipart/form-data">
<p>
    <b>Select File(s):&nbsp;</b><br/>
    <input type="hidden" name="MAX_FILE_SIZE" value="10485760"/>
    <input type='file' name='evidence[]'/>
    <button onclick='this.outerHTML="<br/><input type=file name=evidence[] />"+this.outerHTML'>Add more file</button>
    <input type="submit" name='upload_evidence' value="Upload"/>
</p>
<ul>
    <li>Please submit <b>all evidence</b> for the finding in a <b>single package</b> (eg, zip file)</li>
    <li>Evidence submissions must be <b>under 10 megabytes</b> in size</li>
    <li>Please ensure no <b>Personally Identifiable Information</b> is included (eg, SSN, DOB)</li>
</ul>
</form>
