<?php
// phpcs requires php tags or it generates warnings
?>

<form id="finding_detail_upload_evidence"
      name="finding_detail_upload_evidence" method="post" enctype="multipart/form-data">
<fieldset id="evidence_upload_file_list">
    <legend>Select File(s):</legend>
    <input type="hidden" name="MAX_FILE_SIZE" value="10485760"/>
    <input type="file" name="evidence[]" multiple title="No files selected."/>
</fieldset>
<p>
    <button onclick="return Fisma.Remediation.add_upload_evidence();">Add another file</button>
    <input type="submit" name="upload_evidence" value="Upload"/>
</p>
<ul>
    <li>Each evidence submission must be <b>under 10 megabytes</b> in size</li>
    <li>Please ensure no <b>Personally Identifiable Information</b> is included (eg, SSN, DOB)</li>
</ul>
</form>
