<form enctype="multipart/form-data"
      action="/finding/remediation/modify/id/<?php echo $this->escape($this->finding->id . $this->fromSearchUrl)?>"
      method="post"
      id="finding_detail"
      name="finding_detail">

    <div class="searchBox">
        <div class="left">
            <?php
                foreach ($this->toolbarButtons as $button) {
                    echo $this->escape($button, 'none');
                }
            ?>
        </div>

        <div class="right">
            <?php
                foreach ($this->searchButtons as $button) {
                    echo $this->escape($button, 'none');
                }
            ?>
        </div>

        <div class="clear"> </div>
    </div>

    <?php echo $this->escape($this->tabView, 'none'); ?>
</form>
