<?php $active = (isset($this->config['checked'])); ?>
<fieldset class='criterion ui-accordion'>
    <legend class='header ui-accordion-header ui-state-default
    <?php if ($active): ?>ui-corner-top ui-accordion-header-active<?php else: ?>ui-corner-all<?php endif; ?>
    '>
        <input
            type='checkbox'
            <?php if ($active): ?>checked<?php endif; ?>
            onChange='Fisma.Search.Criterion.legendHandler(this)'
            id='<?php echo $this->escape($this->config['name']); ?>_legend'
        />
        <label for='<?php echo $this->escape($this->config['name']); ?>_legend'>
            <?php echo $this->escape($this->config['label']); ?>
        </label>
    </legend>
    <div class='content ui-accordion-content ui-corner-bottom ui-widget-content
    <?php if ($active): ?>ui-accordion-content-active<?php endif; ?>
    '>
        <?php echo $this->partial($this->viewscript, $this->config); ?>
    </div>
</fieldset>
