<label for='<?php echo $this->escape($this->name); ?>_from'>From</label>
<input
	type='text'
	id='<?php echo $this->escape($this->name); ?>_from'
    name='<?php echo $this->escape($this->name); ?>_from'
	value='<?php echo $this->escape($this->value['from']); ?>'
	placeholder='lowest target <? echo $this->escape($this->unit) ?>'
/>
<br/>
<label for='<?php echo $this->escape($this->name); ?>_to'>To</label>
<input
    type='text'
    id='<?php echo $this->escape($this->name); ?>_to'
    name='<?php echo $this->escape($this->name); ?>_to'
    value='<?php echo $this->escape($this->value['to']); ?>'
    placeholder='highest target <? echo $this->escape($this->unit) ?>'
/>
