<p><b>Organization Hierarchy</b></p>

<p>
    This view shows findings against any information system <i>or organization</i> that has an audit conducted. 
    You can rollup audits to see how various parts of the organization are performing.
</p>

<p><b>Point Of Contacts</b></p>

<p>
    This view shows findings for each Point Of Contact (including all registered users). Users are grouped by their
    reporting organizations, so you can also rollup to see statistics for all points of contact within
    various parts of the organization.
</p>

<p><b>System Aggregation</b></p>

<p>
    If your systems are grouped by system aggregation, then this option will allow you to view findings for each 
    system and rollup subsystems that are nested underneath it. This view does not show any organizations.
</p>
