<div>
    <div id="sourceMessageBar"></div>
<?php
    if ($this->acl()->hasPrivilegeForClass('create', 'Source')) :
?>
    Required fields are denoted by an asterisk (*)
    <?php echo $this->escape($this->form, 'none'); ?>
    <?php foreach ($this->toolbarButtons as $button):
        echo $this->escape($button, 'none');
    endforeach; ?>
<?php
    else:
        $mailurl = 'mailto:' . $this->escape(Fisma::configuration()->getConfig('contact_email'))
                 . '?Subject='. $this->escape(Fisma::configuration()->getConfig('contact_subject'), 'url');

?>
    <div class='messageBox well text-error'><div> <!-- use a double divs to simulate the usual setup of Fisma warning message -->
        You do not have sufficient privileges to add a new finding source.<br/>
        Please <a href="<?php echo $this->escape($mailurl, 'none'); ?>">contact the administrator</a> for assistance.
    </div></div>
<?php
    endif;
?>
</div>
