<div>
    <div id="sourceMessageBar"></div>
<?php
    if ($this->acl()->hasPrivilegeForClass('create', 'Source')) :
?>
    Required fields are denoted by an asterisk (*)
    <?php echo $this->escape($this->form, 'none');?>
<?php
    else:
?>
    <script type='text/javascript'>
        var privilegeErrorMessage = 'You do not have sufficient privileges to add a new finding source.<br/>'
                                  + 'Please contact the administrator for assistance.';
        Fisma.Util.message(privilegeErrorMessage, 'warning', true);
    </script>
<?php
    endif;
?>
</div>
