<?php
echo $this->escape($this->partial('source/searchbox.phtml', 'finding'), 'none');
$operation = '';

if ($this->acl()->hasPrivilegeForObject('update', $this->subject)) {
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
}

if ($this->acl()->hasPrivilegeForObject('delete', $this->subject)) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}

Fisma_Format_Section::startSection("Finding Source Information $operation"); 
?>

<div>
    <?php echo $this->escape($this->form, 'none') ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
