<?php
echo $this->escape($this->searchBox($this->toolbarButtons), 'none');

$sectionName = "{$this->escape($this->document->DocumentType->name)} "
             . "for {$this->escape($this->document->System->Organization->name)}";
Fisma_Format_Section::startSection($sectionName);
?>
    
<table class="keyValues">
    <tr>
        <td>File Name:</td>
        <td>
            <a href="/system-document/download/id/<?php echo $this->escape($this->document->id) ?>">
                <?php echo $this->escape($this->document->fileName); ?>
            </a>
        </td>
    </tr>
    <tr>
        <td>Creation Date:</td>
        <td><?php echo $this->escape($this->document->createdTs); ?></td>
    </tr>
    <tr>
        <td>Last Modification Date:</td>
        <td><?php echo $this->escape($this->document->updated_at); ?></td>
    </tr>
    <tr>
        <td>Document Type:</td>
        <td><?php echo $this->escape($this->document->DocumentType->name); ?></td>
    </tr>
    <tr>
        <td>Size:</td>
        <td><?php echo $this->escape($this->document->getSizeKb()); ?></td>
    </tr>
    <tr>
        <td>System:</td>
        <td>
            <a href="/system/view/oid/<?php echo $this->escape($this->document->System->Organization->id) ?>">
                <?php echo $this->escape($this->document->System->Organization->name); ?>
            </a>
        </td>
    </tr>
    <tr>
        <td>Version:</td>
        <td><?php echo $this->escape($this->document->version); ?></td>
    </tr>
    <tr>
        <td>Version Notes:</td>
        <td><?php echo $this->escape($this->textToHtml($this->escape($this->document->description)), 'none'); ?></td>
    </tr>
</table>


<?php 
    Fisma_Format_Section::stopSection(); 
    Fisma_Format_Section::startSection('Version History'); 

    echo $this->escape($this->dataTable, 'none');

    Fisma_Format_Section::stopSection();
