<?php
echo $this->escape($this->searchBox($this->toolbarButtons), 'none');

$sectionName = "{$this->escape($this->document->DocumentType->name)} "
             . "for {$this->escape($this->document->System->Organization->name)}";
Fisma_Format_Section::startSection($sectionName);
?>
    
<table class="keyValues">
    <tr>
        <td>File Name:</td>
        <td>
            <a href="/system-document/download/id/<?php echo $this->escape($this->document->id) ?>">
                <?php echo $this->escape($this->document->fileName); ?>
            </a>
        </td>
    </tr>
    <tr>
        <td>Creation Date:</td>
        <td><?php echo $this->escape($this->document->createdTs); ?></td>
    </tr>
    <tr>
        <td>Last Modification Date:</td>
        <td><?php echo $this->escape($this->document->updated_at); ?></td>
    </tr>
    <tr>
        <td>Document Type:</td>
        <td><?php echo $this->escape($this->document->DocumentType->name); ?></td>
    </tr>
    <tr>
        <td>Size:</td>
        <td><?php echo $this->escape($this->document->getSizeKb()); ?></td>
    </tr>
    <tr>
        <td>System:</td>
        <td>
            <a href="/system/view/oid/<?php echo $this->escape($this->document->System->Organization->id) ?>">
                <?php echo $this->escape($this->document->System->Organization->name); ?>
            </a>
        </td>
    </tr>
    <tr>
        <td>Version:</td>
        <td><?php echo $this->escape($this->document->version); ?></td>
    </tr>
    <tr>
        <td>Version Notes:</td>
        <td><?php echo $this->escape($this->textToHtml($this->escape($this->document->description)), 'none'); ?></td>
    </tr>
</table>


<?php 
    Fisma_Format_Section::stopSection(); 
    Fisma_Format_Section::startSection('Version History'); 
?>

<div id='systemDocumentHistory'>
    <table class="systemDocuments" id='systemDocumentHistoryTable'>
    <?php
        foreach ($this->versionHistory as $history) {
            $url = '/system-document/download/id/' . $history->id . '/version/' . $history->version;
    ?>
        <tr>
            <td>
                <a href="<?php echo $this->escape($url)?>">
                <?php echo $this->escape($history->fileName); ?>
                </a>
           </td>
           <td>
               <?php echo $this->escape($history->version); ?>
           </td>
           <td>
               <?php echo $this->escape($this->textToHtml($this->escape($history->description)), 'none'); ?>
           </td>
        </tr>
    <?php
        }
    ?>
    </table>
</div>

<?php 
    Fisma_Format_Section::stopSection();
?>

<script type="text/javascript">
YAHOO.util.Event.onContentReady('systemDocumentHistory', function() {
    var myColumnDefs = [
        {key:'fileName', label:'File Name', sortable:true},
        {key:'version', label:'Version', sortable:true},
        {key:'description', label:'Version Notes', sortable:false}
    ];

    this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("systemDocumentHistoryTable"));
    this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
    this.myDataSource.responseSchema = {
        fields: [
            {key:'fileName'},
            {key:'version'},
            {key:'description'}
        ]
    };

    var myDataTable = new YAHOO.widget.DataTable("systemDocumentHistory", myColumnDefs, this.myDataSource, {});
});
</script>

