<div id="logo">
    <a href="/"><img alt="Logo" src="/images/logo.png"></a>
</div>
<div id="logout">
    <?php 
    $logoutButton = new Fisma_Yui_Form_Button_Link(
        'logoutButton', 
        array(
            'value' => 'Log Out',
            'imageSrc' => $this->serverUrl('/images/logout.png'),
            'href' => '/auth/logout'
        )
    ); 
    echo $this->escape($logoutButton, 'none');
    ?>
    <p>
        <b>
            <?php 
                $user = CurrentUser::getInstance();
                
                echo $this->escape($this->userInfo("{$user->nameFirst} {$user->nameLast}", $user->username), 'none');
            ?>
        </b>
        is currently logged in
    </p>
</div>

<div id="menubar"><!-- YUI renders the menubar into this div --></div>
<script type="text/javascript">
YAHOO.util.Event.onDOMReady(function () {
    //Constructs the YUI menu bar for OpenFISMA
    var jsonMenuData = '<?php 
        echo $this->escape(Fisma_Menu::getMainMenu(CurrentUser::getInstance())->getMenus(), 'json') 
    ?>';
    var menuData = YAHOO.lang.JSON.parse(jsonMenuData);
    for (var i in menuData) {
        Fisma.Menu.resolveOnClickObjects(menuData[i]);
    }
    var menuBar = new YAHOO.widget.MenuBar("mainmenu", {autosubmenudisplay: true});
    YAHOO.util.Dom.addClass(menuBar.element, "yuimenubarnav");
    menuBar.addItems(menuData);
    menuBar.render('menubar');
});
</script>
<div id="msgbar"></div>
