<?php
if (count($this->messages)):
    foreach ($this->messages as $severity => $messages):
?>
    <script type="text/javascript" class='priority-messenger-<?php echo $this->escape($severity); ?>'>
        YAHOO.util.Event.onDOMReady(function () {
    <?php
        if (count($messages)):
            foreach ($messages as $message):
                echo $this->escape('Fisma.Util.message("', 'none');
                echo $this->escape($message, 'javascript');
                echo $this->escape('", "', 'none');
                echo $this->escape($severity, 'javascript');
                echo $this->escape("\");\n", 'none');
            endforeach;
        endif;
    ?>
        });
    </script>
<?php endforeach; ?>
<?php endif; ?>
