<?php
$request = Zend_Controller_Front::getInstance()->getRequest();
$moduleName = ucwords(str_replace('-', ' ', $request->getModuleName()));
$controllerName = ucwords(str_replace('-', ' ', $request->getControllerName()));
$actionName = ucwords(str_replace('-', ' ', $request->getActionName()));
$systemName = Fisma::configuration()->getConfig('system_name');

$moduleNameMap = array('Default' => '', 'Vm' => 'Vulnerability Management');

$moduleName = isset($moduleNameMap[$moduleName]) ? $moduleNameMap[$moduleName] : $moduleName;
$controllerName = ($controllerName == 'Index') ? '' : $controllerName;
$actionName = ($actionName == 'Index') ? '' : $actionName;

$this->headTitle()->prepend($systemName);
$this->headTitle($moduleName)
     ->headTitle($controllerName)
     ->headTitle($actionName);

$this->headTitle()->setSeparator(' - ');
echo $this->escape($this->headTitle(), 'none');
?>
