<?php if (!empty($this->agencyContractor)) : ?>
<chart>
    <license>FTA9HNF7P2O.H4X5CWK-2XOI1X0-7L</license>

    <context_menu about='false'
                  print='false'
                  full_screen='true'
                  save_as_bmp='false'
                  save_as_jpeg='true'
                  save_as_png='true' />

    <chart_data>
        <row>
            <null />
            <?php
            foreach ($this->agencyContractor as $system):
            ?>
                <string><?php echo $this->escape($system['s_controlled_by']); ?></string>
            <?php
            endforeach;
            ?>
        </row>
        <row>
            <string>count</string>
            <?php
            foreach ($this->agencyContractor as $system):
                $tooltip = "{$system['s_count']} {$system['s_controlled_by']} System"
                         . ($system['s_count'] > 1 ? 's' : '');
            ?>
            <number tooltip="<?php echo $this->escape($tooltip)?>">
                <?php echo $this->escape($system['s_count']); ?></number>
            <?php
            endforeach;
            ?>
        </row>
    </chart_data>

    <chart_type>pie</chart_type>
    
    <chart_label font='arial'
                 bold='true'
                 size='12'
                 position='outside'
                 as_percentage='true' />

    <legend layout='vertical'
            bullet='circle' />

    <series_color>
        <color>66ff66</color>
        <color>7197e1</color>
        <color>b3b3b3</color>
    </series_color>
</chart>
<?php else:
echo $this->partial('chart/nodata.xml.phtml', array('width' => '350', 'height' => '200'));
endif; ?>
