<?php if(!empty($this->categories)) : ?>
<chart>
    <license>FTA9HNF7P2O.H4X5CWK-2XOI1X0-7L</license>

    <chart_data>
        <row>
            <null />
            <?php
            foreach ($this->categories as $category):
            ?>
                <string><?php echo $this->escape($category['s_fips_category']); ?></string>
            <?php
            endforeach;
            ?>
        </row>
        <row>
            <string>count</string>
            <?php
            foreach ($this->categories as $category):
                $tooltip = "{$category['s_fips_count']} {$category['s_fips_category']} System"
                         . ($category['s_fips_count'] > 1 ? 's' : '');
            ?>
            <number tooltip="<?php echo $this->escape($tooltip)?>">
                <?php echo $this->escape($category['s_fips_count']); ?></number>
            <?php
            endforeach;
            ?>
        </row>
    </chart_data>

    <chart_type>pie</chart_type>
    
    <chart_label font='arial'
                 bold='true'
                 size='12'
                 position='outside'
                 as_percentage='true' />

    <legend layout='vertical'
            bullet='circle' />

    <series_color>
        <color>ff3333</color>
        <color>ff9933</color>
        <color>eaed1e</color>
        <color>b3b3b3</color>
    </series_color>
</chart>
<?php else:
echo $this->partial('chart/nodata.xml.phtml', array('width' => '350', 'height' => '200'));
endif; ?>
