<?php Fisma_Format_Section::startSection('Email validation message&hellip;'); ?>
<b><?php echo $this->msg; ?></b>
<p>
    Technical Support Contact: <?php echo Configuration::getConfig('contact_name');?><br>
    Contact Phone: <?php echo Configuration::getConfig('contact_phone');?><br>
    Contact E-mail: <a href="mailto:<?php echo Configuration::getConfig('contact_email');?>">
            <?php echo Configuration::getConfig('contact_email');?></a>
</p>

<?php Fisma_Format_Section::stopSection(); ?>
