<?php Fisma_Format_Section::startSection('Email validation message&hellip;'); ?>
<b><?=$this->escape($this->msg, 'none') ?></b>
<p>
    Technical Support Contact: <?=$this->escape(Fisma::configuration()->getConfig('contact_name'))?><br>
    Contact Phone: <?=$this->escape(Fisma::configuration()->getConfig('contact_phone'))?><br>
    Contact E-mail: <a href="mailto:<?=$this->escape(Fisma::configuration()->getConfig('contact_email'))?>">
            <?php echo $this->escape(Fisma::configuration()->getConfig('contact_email'));?></a>
</p>

<?php Fisma_Format_Section::stopSection(); ?>
