<div class="hd">
    <?php echo Fisma::configuration()->getConfig('system_name');?>
</div>

<div class="bd">
    <?php echo Fisma::configuration()->getConfig('use_notification');?>
    
    <p class="message">
        <?php 
            if (isset($this->error)) {
                $dateString = date('H:i:s');
                echo "$dateString $this->error"; 
            }
        ?>
    </p>

    <form id='loginForm' method="post" action="/auth/login">
        <table>
            <tr>
                <td><label for="username">Username:</label></td>
                <td>
                    <input type="text" 
                           name="username" 
                           id="username"
                           autocomplete="off"
                           value="<?php echo isset($this->username) ? $this->username : ''; ?>">
                </td>
            </tr>
            <tr>
                <td><label for="userpass">Password:</label></td>
                <td>
                    <input type="password" 
                           name="userpass" 
                           id="userpass"
                           autocomplete="off"
                           value="<?php echo isset($this->password)?$this->password:'';?>">
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <?php echo new Fisma_Yui_Form_Button_Submit('loginButton', array('label' => 'Log In')); ?>
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td nowrap><br /><a href="/incident/report">Report Security Incident</a></td>
            </tr> 
        </table>
    </form>
</div>
