<div>
    <i>
        System policy states that you must review and accept the Rules of Behavior
        for <?php echo Configuration::getConfig('system_name');?> every
        <?php echo Configuration::getConfig('rob_duration');?> days. If you do not accept these
        rules then you will be logged off.
    </i>
</div>

<?php Fisma_Format_Section::startSection(Configuration::getConfig('system_name') . ' Rules of Behavior'); ?>
<div>
    <?php print(Configuration::getConfig('behavior_rule')); ?>
</div>

<div>
    <?php
    echo new Fisma_Yui_Form_Button_Link('cancel', 
                                  array('value' => 'Cancel', 
                                        'href' => '/user/logout'));
    echo new Fisma_Yui_Form_Button_Link('accept', 
                                  array('value' => 'Accept', 
                                        'href' => '/auth/accept-rob'));
    ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>

