<?php 
// @codingStandardsIgnoreFile - not checking XLS template files
$xmltag = '<?xml version="1.0"?>'.
          '<?mso-application progid="Excel.Sheet"?>';
echo $this->escape($xmltag, 'none');
?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">
 <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
  <Title>Finding Injection Template</Title>
  <Subject>Finding Injection Template</Subject>
  <Company>Endeavor Systems, Inc.</Company>
  <Version>11.9999</Version>
 </DocumentProperties>
 <CustomDocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
  <FismaTemplateVersion dt:dt="float"><?php echo $this->escape($this->templateVersion) ?></FismaTemplateVersion>
  <SecurityControlCatalogId dt:dt="float"><?php echo $this->escape($this->securityControlCatalogId) ?></SecurityControlCatalogId>
 </CustomDocumentProperties>
 <Styles>
  <Style ss:ID="Default" ss:Name="Normal">
   <Alignment ss:Vertical="Bottom"/>
   <Borders/>
   <Font x:Family="Swiss"/>
   <Interior/>
   <NumberFormat/>
   <Protection/>
  </Style>
  <Style ss:ID="m43958186">
   <Alignment ss:Horizontal="Left" ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font x:Family="Swiss" ss:Bold="1"/>
   <Interior ss:Color="#C0C0C0" ss:Pattern="Solid"/>
   <NumberFormat ss:Format="00000"/>
  </Style>
  <Style ss:ID="s21">
   <Alignment ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
  </Style>
  <Style ss:ID="s22">
   <Alignment ss:Horizontal="Center" ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <NumberFormat ss:Format="@"/>
  </Style>
  <Style ss:ID="s24">
   <Alignment ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <NumberFormat ss:Format="@"/>
  </Style>
  <Style ss:ID="s27">
   <Alignment ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
  </Style>
  <Style ss:ID="s29">
   <Alignment ss:Horizontal="Left" ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font x:Family="Swiss" ss:Size="20" ss:Bold="1"/>
   <Interior ss:Color="#C0C0C0" ss:Pattern="Solid"/>
   <NumberFormat ss:Format="@"/>
  </Style>
  <Style ss:ID="s39">
   <Alignment ss:Horizontal="Center" ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font x:Family="Swiss" ss:Bold="1"/>
   <Interior ss:Color="#CCCCFF" ss:Pattern="Solid"/>
   <NumberFormat ss:Format="@"/>
  </Style>
  <Style ss:ID="s41">
   <Alignment ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font x:Family="Swiss" ss:Bold="1"/>
   <Interior ss:Color="#CCCCFF" ss:Pattern="Solid"/>
   <NumberFormat ss:Format="@"/>
  </Style>
  <Style ss:ID="s46">
   <Alignment ss:Horizontal="Center" ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font x:Family="Swiss" ss:Bold="1"/>
   <Interior ss:Color="#CCCCFF" ss:Pattern="Solid"/>
   <NumberFormat ss:Format="yyyy\-mm\-dd"/>
  </Style>
  <Style ss:ID="s47">
   <Alignment ss:Horizontal="Center" ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <NumberFormat ss:Format="yyyy\-mm\-dd"/>
  </Style>
 </Styles>
 <Names>
  <NamedRange ss:Name="controls" ss:RefersTo="=ControlIDs!C1"/>
  <NamedRange ss:Name="systems"  ss:RefersTo="=Systems!C1"/>
  <NamedRange ss:Name="sources"  ss:RefersTo="=Sources!C1"/>
  <NamedRange ss:Name="networks" ss:RefersTo="=Networks!C1"/>
 </Names>
 <Worksheet ss:Name="Findings">
  <Table ss:ExpandedColumnCount="21" ss:ExpandedRowCount="8" x:FullColumns="1"
   x:FullRows="1" ss:StyleID="s21">
   <Column ss:StyleID="s22" ss:AutoFitWidth="0" ss:Width="49.5"/>
   <Column ss:StyleID="s47" ss:AutoFitWidth="0" ss:Width="60.75"/>
   <Column ss:Index="10" ss:StyleID="s22" ss:AutoFitWidth="0" ss:Width="78.75"/>
   <Column ss:StyleID="s24" ss:AutoFitWidth="0" ss:Width="180" ss:Span="1"/>
   <Column ss:Index="13" ss:StyleID="s24" ss:AutoFitWidth="0" ss:Width="49.5"/>
   <Column ss:StyleID="s24" ss:AutoFitWidth="0" ss:Width="156"/>
   <Column ss:StyleID="s47" ss:AutoFitWidth="0" ss:Width="78"/>
   <Column ss:StyleID="s22" ss:AutoFitWidth="0" ss:Width="84.75"/>
   <Column ss:StyleID="s22" ss:AutoFitWidth="0" ss:Width="90.75"/>
   <Column ss:StyleID="s24" ss:AutoFitWidth="0" ss:Width="177"/>
   <Column ss:StyleID="s22" ss:AutoFitWidth="0" ss:Width="90.75"/>
   <Column ss:StyleID="s24" ss:AutoFitWidth="0" ss:Width="177"/>
   <Column ss:StyleID="s24" ss:AutoFitWidth="0" ss:Width="126.75"/>
   <Row ss:AutoFitHeight="0" ss:Height="26.25" ss:StyleID="s27">
    <Cell ss:MergeAcross="13" ss:StyleID="s29"><Data ss:Type="String"><?php echo $this->escape(Fisma::configuration()->getConfig('system_name'));?> - Injection Template</Data></Cell>
   </Row>
   <Row ss:AutoFitHeight="0" ss:Height="129.75" ss:StyleID="s27">
    <Cell ss:MergeAcross="13" ss:StyleID="m43958186"><Data ss:Type="String">Security Catalog: <?php echo $this->escape($this->securityControlCatalogName); ?>&#10;Instructions: &#10;1) Required fields are indicated by an asterix (*). &#10;2) Leave optional fields blank if you do not have that information.&#10;3) Do not modify the format of this template, or it may not upload into <?php echo $this->escape(Fisma::configuration()->getConfig('system_name'));?>. You may hide rows and columns using Excel's menu option: Format-&gt;Row-&gt;Hide&#10;4) To enter an asset for a finding, complete the Network, Asset IP Address, and Asset Port fields. If you do not enter all 3 of these fields, then the asset will be omitted.&#10;5) To enter a product, complete the Product Name, Product Vendor, and Product Version. If you do not enter all 3 of these fields, then the product will be omitted.&#10;&#10;</Data></Cell>
   </Row>
   <Row ss:AutoFitHeight="0" ss:Height="38.25">
    <Cell ss:StyleID="s39"><Data ss:Type="String">System*</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000"> The system that this finding affects.         </Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s46"><Data ss:Type="String">Date Discovered*</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000"> The date that this finding was discovered.         </Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s39"><Data ss:Type="String">Finding Source*</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000"> The type of evaluation which was used to discover this finding.          </Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s41"><Data ss:Type="String">Finding Description*</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000"> Description of the vulnerability or weakness.          </Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s41"><Data ss:Type="String">Finding Recommendation*</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000"> Auditor's recommendation to remediate the finding.          </Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s41"><Data ss:Type="String">Course of Action Type</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000"> AR = 'Accepted Risk', CAP = 'Corrective Action Plan', FP = 'False Positive'         </Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s41"><Data ss:Type="String">Course of Action&#10;Description</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000"> The course of action planned to address a CAP; the business case justifying an AR.         </Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s46"><Data ss:Type="String">Expected Completion Date</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000"> The date by which the course of action will be completed AND evidence uploaded         </Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s39"><Data ss:Type="String">NIST 800-53 Security Control</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000"> The related NIST 800-53 security control.         </Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s39"><Data ss:Type="String">Threat Level*</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000"> The threat imposed by an exploit of this vulnerability.         </Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s41"><Data ss:Type="String">Threat Description*</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000"> Describe the source and nature of the threat.         </Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s39"><Data ss:Type="String">Countermeasures Effectiveness</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000"> The effectiveness of in-place countermeasures for mitigating the threat.         </Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s41"><Data ss:Type="String">Description of Countermeasures</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000"> Describe what countermeasures are in place.         </Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s41"><Data ss:Type="String">Point of Contact (Name, Number, Email)</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000"> Describe what countermeasures are in place.         </Font></ss:Data></Comment></Cell>
   </Row>
  </Table>
  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
   <Print>
    <ValidPrinterInfo/>
    <Scale>45</Scale>
    <HorizontalResolution>600</HorizontalResolution>
    <VerticalResolution>600</VerticalResolution>
   </Print>
   <PageBreakZoom>60</PageBreakZoom>
   <Selected/>
   <Panes>
    <Pane>
     <Number>3</Number>
    </Pane>
   </Panes>
   <ProtectObjects>False</ProtectObjects>
   <ProtectScenarios>False</ProtectScenarios>
  </WorksheetOptions>
  <DataValidation xmlns="urn:schemas-microsoft-com:office:excel">
   <Range>R4C10:R65536C10,R4C12:R65536C12</Range>
   <Type>List</Type>
   <CellRangeList/>
   <Value>&quot;<?php echo $this->escape(implode(',', $this->risk))?>&quot;</Value>
  </DataValidation>
  <DataValidation xmlns="urn:schemas-microsoft-com:office:excel">
   <Range>R4C3:R65536C3</Range>
   <Type>List</Type>
   <Value>sources</Value>
  </DataValidation>
  <DataValidation xmlns="urn:schemas-microsoft-com:office:excel">
   <Range>R4C6:R65536C6</Range>
   <Type>List</Type>
   <CellRangeList/>
   <Value>&quot;AR,CAP,FP&quot;</Value>
  </DataValidation>
  <DataValidation xmlns="urn:schemas-microsoft-com:office:excel">
   <Range>R4C9:R65536C9</Range>
   <Type>List</Type>
   <Value>controls</Value>
  </DataValidation>
  <DataValidation xmlns="urn:schemas-microsoft-com:office:excel">
   <Range>R4C1:R65536C1</Range>
   <Type>List</Type>
   <Value>systems</Value>
  </DataValidation>
  <DataValidation xmlns="urn:schemas-microsoft-com:office:excel">
   <Range>R4C2:R65536C2</Range>
   <Type>Date</Type>
   <Min>36526</Min>
   <Max>50041</Max>
  </DataValidation>
 </Worksheet>
 <Worksheet ss:Name="ControlIDs">
  <Names>
   <NamedRange ss:Name="_FilterDatabase" ss:RefersTo="=ControlIDs!C1" ss:Hidden="1"/>
  </Names>
  <Table ss:ExpandedColumnCount="1" x:FullColumns="1" x:FullRows="1">
   <Column ss:AutoFitWidth="0" ss:Width="54.75"/>
<?php
    foreach ($this->securityControls as $securityControl) {
?>
<Row>
<Cell>
<Data ss:Type="String"><?php echo $this->escape($securityControl) ?></Data>
<NamedCell ss:Name="controls"/>
<NamedCell ss:Name="_FilterDatabase"/>
</Cell>
</Row>
<?php
    }
?>
  </Table>
  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
   <Visible>SheetHidden</Visible>
   <Print>
    <ValidPrinterInfo/>
    <HorizontalResolution>600</HorizontalResolution>
    <VerticalResolution>0</VerticalResolution>
   </Print>
   <Panes>
    <Pane>
     <Number>3</Number>
    </Pane>
   </Panes>
   <ProtectObjects>True</ProtectObjects>
   <ProtectScenarios>False</ProtectScenarios>
  </WorksheetOptions>
 </Worksheet>
 <Worksheet ss:Name="Systems">
  <Table ss:ExpandedColumnCount="1" x:FullColumns="1" x:FullRows="1">
   <Column ss:AutoFitWidth="0" ss:Width="54.75"/>
<?php
    foreach ($this->systems as $system) {
?>
<Row>
<Cell>
<Data ss:Type="String"><?php echo $this->escape($system) ?></Data>
<NamedCell ss:Name="systems"/>
</Cell>
</Row>
<?php
    }
?>
  </Table>
  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
   <Visible>SheetHidden</Visible>
   <Print>
    <ValidPrinterInfo/>
    <HorizontalResolution>600</HorizontalResolution>
    <VerticalResolution>0</VerticalResolution>
   </Print>
   <Panes>
    <Pane>
     <Number>3</Number>
    </Pane>
   </Panes>
   <ProtectObjects>True</ProtectObjects>
   <ProtectScenarios>False</ProtectScenarios>
  </WorksheetOptions>
 </Worksheet> 
 <Worksheet ss:Name="Sources">
  <Table ss:ExpandedColumnCount="1" x:FullColumns="1" x:FullRows="1">
   <Column ss:AutoFitWidth="0" ss:Width="54.75"/>
<?php
    foreach ($this->sources as $source) :
?>
   <Row>
    <Cell>
     <Data ss:Type="String"><?php echo $this->escape($source) ?></Data>
     <NamedCell ss:Name="sources"/>
    </Cell>
   </Row>
<?php
    endforeach;
?>
  </Table>
  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
   <Visible>SheetHidden</Visible>
   <Print>
    <ValidPrinterInfo/>
    <HorizontalResolution>600</HorizontalResolution>
    <VerticalResolution>0</VerticalResolution>
   </Print>
   <Panes>
    <Pane>
     <Number>3</Number>
    </Pane>
   </Panes>
   <ProtectObjects>True</ProtectObjects>
   <ProtectScenarios>False</ProtectScenarios>
  </WorksheetOptions>
 </Worksheet> 
</Workbook>
