<chart>
    <chart_data>
		<row>
			<null/>
			<string></string>
		</row>	
		<?php foreach ($this->summary AS $status=>$statusCount) { ?>
		<row>
			<string><?php echo $status; ?></string>
			<number tooltip='<?php echo $statusCount; ?> findings'><?php echo $statusCount; ?></number>
		</row>
		<?php } ?>
	</chart_data>

	<chart_type><?php echo $this->chart_type; ?></chart_type>

    <chart_grid_h thickness='0' />

	<axis_value alpha='0' />

	<chart_label font='arial'
                 bold='true'
                 size='12'
                 position='over' />

	<chart_pref rotation_x='30'
                rotation_y='40'
                min_x='20'
                max_x='70'
                min_y='30'
                max_y='80' />

	<chart_rect x='0' y='0' width='480' height='240' positive_alpha='0' negative_alpha='25' />

	<filter>
		<shadow id='low' distance='2' angle='45' alpha='50' blurX='2' blurY='2' />
	</filter>

    <legend layout='vertical'
            bullet='square'
            font='arial'
            bold='true'
            size='10'
            x='0'
            y='50'
            width='100'
            height='150' />


	<series_color>
<?php
    // Figure out which colors are MSA colors and which are EP colors
    unset($this->summary['NEW']);
    unset($this->summary['OPEN']);
    $msaColors = array();
    foreach ($this->summary as $status => $filler) {
        if ($status == 'EN') {
            break;
        }
        $msaColors[] = $status;
        unset($this->summary[$status]);
    }
    unset($this->summary['EN']);
    $epColors = array();
    foreach ($this->summary as $status => $filler) {
        $epColors[] = $status;
    }
    
    // Colors for NEW & OPEN
    print '<!-- NEW --><color>cccccc</color>';
    print '<!-- OPEN --><color>66ff66</color>';
    
    // Colors for MSA
    define('START_COLOR', 200); // These constants are used for creating a gradient
    define('STOP_COLOR', 25); // The range of these constants sets the high and low gradient value
    $colorStep = (STOP_COLOR - START_COLOR) / (count($msaColors) - 1);
	for ($i = 0; $i < count($msaColors); $i++) {
        $hex = dechex(START_COLOR + ($colorStep * $i));
        print "<!-- MSA --><color>ff{$hex}{$hex}</color>";
	}
	
	// Color for EN
	print '<!-- EN --><color>ff9933</color>';
	
	// Colors for EP
    $colorStep = (STOP_COLOR - START_COLOR) / (count($epColors) - 1);
	for ($i = 0; $i < count($epColors); $i++) {
        $hex = dechex(START_COLOR + ($colorStep * $i));
        print "<!-- EP --><color>{$hex}{$hex}ff</color>";
	}
?>
	</series_color>
</chart>
