<chart>
    <chart_data>
		<row>
			<null/>
			<string></string>
		</row>	
		<?php foreach ($this->summary AS $status=>$statusCount) { ?>
		<row>
			<string><?php echo $status; ?></string>
			<number><?php echo $statusCount; ?></number>
		</row>
		<?php } ?>
	</chart_data>

	<chart_type><?php echo $this->chart_type; ?></chart_type>
                
	<chart_rect  width='150'
                 height='200' />
                 
	<chart_value color='000000'
                 alpha='90'
                 font='arial'
                 bold='true'
                 size='10'
                 position='over' />

	<legend_label layout='vertical'
                  bullet='square'
                  font='arial'
                  bold='true'
                  size='9'
                  color='000000'
                  alpha='100' />
                  
	<legend_rect y='190' />

	<series_color>
<?php
    // Figure out which colors are MSA colors and which are EP colors
    unset($this->summary['NEW']);
    unset($this->summary['OPEN']);
    $msaColors = array();
    foreach ($this->summary as $status => $filler) {
        if ($status == 'EN') {
            break;
        }
        $msaColors[] = $status;
        unset($this->summary[$status]);
    }
    unset($this->summary['EN']);
    $epColors = array();
    foreach ($this->summary as $status => $filler) {
        $epColors[] = $status;
    }
    
    // Colors for NEW & OPEN
    print '<!-- NEW --><color>cccccc</color>';
    print '<!-- OPEN --><color>66ff66</color>';
    
    // Colors for MSA
    define('START_COLOR', 200); // These constants are used for creating a gradient
    define('STOP_COLOR', 25); // The range of these constants sets the high and low gradient value
    $colorStep = (STOP_COLOR - START_COLOR) / (count($msaColors) - 1);
	for ($i = 0; $i < count($msaColors); $i++) {
        $hex = dechex(START_COLOR + ($colorStep * $i));
        print "<!-- MSA --><color>ff{$hex}{$hex}</color>";
	}
	
	// Color for EN
	print '<!-- EN --><color>ff9933</color>';
	
	// Colors for EP
    $colorStep = (STOP_COLOR - START_COLOR) / (count($epColors) - 1);
	for ($i = 0; $i < count($epColors); $i++) {
        $hex = dechex(START_COLOR + ($colorStep * $i));
        print "<!-- EP --><color>{$hex}{$hex}ff</color>";
	}
?>
	</series_color>
</chart>
