<?php Fisma_Format_Section::startSection('Dashboard'); ?>

<div class="panel">
    <p><em>Alerts</em></p>
    <ul>
        <li>
            There are <b>
            <a href="<?=$this->escape($this->url, 'none')?>NEW"><?=$this->escape($this->alert['NEW'])?></a>
            </b> NEW findings (findings that do not have a mitigation strategy).
        </li>
        <li>
            There are <b>
            <a href="<?=$this->escape($this->url, 'none')?>DRAFT"><?=$this->escape($this->alert['DRAFT'])?></a>
            </b> DRAFT findings (findings that have a mitigation strategy but have not been submitted for approval).
        </li>
<?php if (Fisma_Acl::hasPrivilegeForClass('approve', 'Finding')) : ?>
        <li>
            There are <b>
            <a href="<?=$this->escape($this->pendingUrl, 'none')?>"><?=$this->escape($this->alert['PEND'])?></a>
            </b> PENDING findings awaiting approval.
        </li>
<?php endif; ?>
        <li>
            There are <b>
            <a href="<?=$this->escape($this->url, 'none')?>EN/ontime/ontime"><?=$this->escape($this->alert['EN'])?></a>
            </b> findings awaiting evidence.
        </li>
        <li>
            There are <b>
            <a href="<?=$this->escape($this->url, 'none')?>EN/ontime/overdue"><?=$this->escape($this->alert['EO'])?></a>
            </b> overdue findings awaiting evidence.    
        </li>
    </ul>
</div>
<div class="panel">
    <p><em>Last Login</em></p>
    <?php 
    if (!empty($this->lastLoginIp)) { 
    ?>
        <ul>
            <li>Last Logged in at <b><?=$this->escape($this->lastLoginTs)?></b></li>
            <li>From IP address <b><?=$this->escape($this->lastLoginIp)?></b></li>
            <?php if ('database' == Fisma::configuration()->getConfig('auth_type')): ?>
                <li>
                    There were 
                    <b><?=$this->escape($this->failureCount)?></b>
                    bad login attempts since your last login.
                </li>
            <?php endif; ?>
        </ul>
    <?php 
    } else { 
    ?>
        <p>
            This is the first time you have logged into
            <?=$this->escape(Fisma::configuration()->getConfig('system_name'))?>. 
            We will begin tracking your login attempts moving forward.
        </p>
    <?php 
    } 
    ?>
</div>

<?php
if (isset($this->notifications)) {
?>
    <div class="panel clear">
        <p><em>Notifications</em></p>
        <p>
            You have new notifications that you have not received in e-mail yet.
            Click <a href="<?=$this->escape($this->dismissUrl, 'none')?>">here</a> to dismiss these notifications.
        </p>
        <ol>
            <?php
            foreach ($this->notifications as $notification) {
            ?>
                <li>
                    <b>
                        <?php 
                        echo $this->escape($notification['eventText'], 'none');
                        ?></b>&nbsp;at&nbsp;<b><?php
                        echo $this->escape($notification['createdTs']);
                        ?>
                    </b>
                </li>
            <?php
            }
            ?>
        </ol>
    </div>
<?php
}
?>

<script type="text/javascript">
    function barChartClick(status) {
        document.location = "/panel/remediation/sub/searchbox/status/" + $P.urlencode(status);
    }
    function pieChartClick(columnNumber) {
        // Lookup table for converting the column number to the remediation type code
        var columns = ['NONE', 'CAP', 'FP', 'AR'];
        var type = columns[columnNumber-1];
        document.location = "/panel/remediation/sub/searchbox/type/" + $P.urlencode(type);
    }
</script>
<?php 
if ( !empty( $this->alert['TOTAL'] ) ) { 
?>
    <div class="panel clear">
        <table width="100%">
            <tr><td colspan="2"><b>&nbsp;&nbsp;&nbsp;Management Overview </b></td></tr>
            <tr>
                <td align="center">
                <?php echo $this->escape($this->statusChart, 'none'); ?>
                </td>
                <td align="center">
                <?php echo $this->escape($this->typeChart, 'none'); ?>
                </td>
            </tr>
            <tr>
                <td align="center"><b>Finding Status<br>Distribution</b></td>
                <td align="center"><b>Mitigation Strategy<br>Distribution</b></td>
            </tr>
        </table>
    </div>
<?php 
} 
?>

<div class="clear"></div>

<?php Fisma_Format_Section::stopSection(); ?>
