<i>By selecting a user below, you will be able to temporarily inherit the permissions of the user.
    This is helpful for validating what a user has access to view and edit. While in "View As" mode,
    a message is displayed on every page indicating you are in "View As" mode,
    you may exit "View As" mode at any time to restore normal permissions.</i>
<?php echo $this->escape($this->form, 'none'); ?>