<?php 
$goBack = new Fisma_Yui_Form_Button_Link('goBack',
                                       array('value' => 'Go Back',
                                             'imageSrc' => '/images/left_arrow.png',
                                             'href' => '/sa/security-authorization/view/id/' . $this->id));
echo $this->escape($goBack, 'none');

Fisma_Format_Section::startSection("Security Authorizations <span id='searchResultsTotalFound'></span>"); ?>
<div id="list"></div>
<script type="text/javascript">
    var operation = function(elCell, oRecord, oColumn, sData) {
        elCell.innerHTML = "<a href='/sa/assessment-plan-entry/view/id/"+oRecord.getData("id")+"'>"
                         + "<img src='/images/view.gif' /></a>";
    };
    // Column definitions
    var myColumnDefs = [
        {key:"id", label:"ID", formatter:"text"},
        {key:"code", label:"Control", formatter:"text"},
        {key:"enhancement", label:"Enhancement", formatter:"text"},
        {key:"number", label:"Procedure", formatter:"text"}];

    // A function which builds the query string
    var myRequestBuilder = function(oState, oSelf) {
        // Get states or use defaults
        oState = oState || {pagination:null, sortedBy:null};
        var startIndex = oState.pagination.recordOffset;
        var count = oState.pagination.rowsPerPage;
    
        // Build custom request
        var request = "/startIndex/" + startIndex +
                      "/count/" + count + 
                      "<?php echo $this->escape($this->url, 'none') ?>";
        return request;
    };

    var myDataSource = new YAHOO.util.DataSource(
        '/sa/assessment-plan-entry/search/said/<?php echo $this->escape($this->id);?>'
    );
    myDataSource.responseType = YAHOO.util.DataSource.TYPE_JSON;
    myDataSource.responseSchema = {
        resultsList: "table.records",
        metaFields: {
            totalRecords: "table.totalRecords"
        }
    };
    
    // DataTable configuration
    var myConfigs = {
        initialRequest: "/startIndex/0/count/10<?php echo $this->escape($this->url, 'none')?>",
        dynamicData: true, 
        paginator: new YAHOO.widget.Paginator(
            {
                rowsPerPage:10,
                template:"{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
            }
        ),
        generateRequest : myRequestBuilder
    };
    
    var myDataTable = new YAHOO.widget.DataTable("list", myColumnDefs, myDataSource, myConfigs);
    // Update totalRecords on the fly with value from server
    myDataTable.handleDataReturnPayload = function(oRequest, oResponse, oPayload) {
        oPayload.totalRecords = oResponse.meta.totalRecords;
        // display total records in the search results header, if not already present
        var searchResultsHeader = document.getElementById('searchResultsTotalFound');
        if (!searchResultsHeader.firstChild) {
            var totalRecords = oResponse.meta.totalRecords ? oResponse.meta.totalRecords : 0;
            var searchTotalFound = document.createTextNode('(' + totalRecords + ' records found)');
            searchResultsHeader.appendChild(searchTotalFound);
        }
        return oPayload;
    }
    
    myDataTable.subscribe("rowMouseoverEvent", myDataTable.onEventHighlightRow); 
    myDataTable.subscribe("rowMouseoutEvent", myDataTable.onEventUnhighlightRow);
    
    var contextMenuItems = ["View"];
    var contextMenu = new YAHOO.widget.ContextMenu( 
        "contextMenu", 
        { 
            trigger:  myDataTable.getTbodyEl(), 
            itemdata: contextMenuItems, 
            lazyload: true 
        }
    );
    
    contextMenu.subscribe("click", contextMenuHandler);
    
    function contextMenuHandler(event, eventArgs) {
        var targetElement = this.contextEventTarget;
        var rowElement = myDataTable.getTrEl(targetElement);
        var rowRecord = myDataTable.getRecord(rowElement);
        var menuItem = eventArgs[1];
        var actionUrl = '';
        switch (menuItem.index) {
            case 0 :
                actionUrl = "/sa/assessment-plan-entry/view/id/" + rowRecord.getData("id");
                break;
        }
        if (actionUrl != '') {
            window.open(actionUrl);
        }
    }
    
</script>
<?php Fisma_Format_Section::stopSection(); ?>
