<?php 
echo $this->partial('navigation.phtml', array('sa' => $this->sa, 'current' => 'Authorization'));

Fisma_Format_Section::startSection("Authorization");

foreach ($this->buttonbar as $elem) {
    echo $this->escape($elem, 'none');
}

echo $this->escape($this->dataTable, 'none');
Fisma_Format_Section::stopSection();
?>
<script type="text/javascript">
function submitCompleteForm()
{
    document.getElementById('completeForm').submit();
}
</script>

