<?php $this->table = Doctrine::getTable('InformationDataType'); ?>
<div class="buttonBar">
    <?php foreach ($this->toolbarButtons as $button):
        echo $this->escape($button, 'none');
    endforeach; ?>
</div>
<?php Fisma_Format_Section::startSection('Add New Information Data Type', null, null, 'addTypeSection'); ?>
<p>Please select an information data type from the list below:</p>
<table id="addType" class="table table-hover table-bordered">
    <thead>
        <tr>
            <th scope="col"><?php $this->column('category'); ?></th>
            <th scope="col"><?php $this->column('subcategory'); ?></th>
            <th scope="col"><?php $this->column('description'); ?></th>
            <th scope="col"><?php $this->column('confidentiality'); ?></th>
            <th scope="col"><?php $this->column('integrity'); ?></th>
            <th scope="col"><?php $this->column('availability'); ?></th>
        </tr>
    </thead>
    <tbody><?php foreach ($this->availableTypes as $dataType): ?>
        <tr data-type-id='<?php echo $this->escape($dataType->id); ?>'>
            <td><?php echo $this->escape($dataType->category); ?></td>
            <td><?php echo $this->escape($dataType->subcategory); ?></td>
            <td><?php echo $this->escape($dataType->description, 'none'); ?></td>
            <td><?php echo $this->escape($dataType->confidentiality); ?></td>
            <td><?php echo $this->escape($dataType->integrity); ?></td>
            <td><?php echo $this->escape($dataType->availability); ?></td>
        </tr>
    <?php endforeach; ?></tbody>
</table>
<?php Fisma_Format_Section::stopSection(); ?>

<?php Fisma_Format_Section::startSection('Assigned Information Data Types'); ?>
<table id="assignedTypes" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col"><?php $this->column('category'); ?></th>
            <th scope="col"><?php $this->column('subcategory'); ?></th>
            <th scope="col"><?php $this->column('description'); ?></th>
            <th scope="col"><?php $this->column('confidentiality'); ?></th>
            <th scope="col"><?php $this->column('integrity'); ?></th>
            <th scope="col"><?php $this->column('availability'); ?></th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody><?php foreach ($this->assignedTypes as $dataTypeAssignment):
        $dataType = $dataTypeAssignment->denormalizedDataType; ?>
        <tr data-type-id='<?php echo $this->escape($dataTypeAssignment->informationDataTypeId); ?>'>
            <td><?php echo $this->escape($dataType['category']); ?></td>
            <td><?php echo $this->escape($dataType['subcategory']); ?></td>
            <td><?php echo $this->escape($dataType['description'], 'none'); ?></td>
            <td><?php echo $this->escape($dataType['confidentiality']); ?></td>
            <td><?php echo $this->escape($dataType['integrity']); ?></td>
            <td><?php echo $this->escape($dataType['availability']); ?></td>
            <td>
                <a href="#" onclick="Fisma.Sa.removeDataType(event, this)"><i class="icon-remove"></i> Remove</a><br/>
                <a href="#" onclick="Fisma.Sa.refreshDataType(event, this)"><i class="icon-refresh"></i> Refresh</a>
            </td>
        </tr>
    <?php endforeach; ?></tbody>
</table>
<?php Fisma_Format_Section::stopSection(); ?>
<script>
    $(Fisma.Sa.initCat);
</script>
