<?php 

$buttons = array();
$buttons[] = new Fisma_Yui_Form_Button_Link(
    'listButton', 
    array('value' => 'Control List', 
          'imageSrc' => '/images/view_list.png',
          'href' => '/sa/security-authorization/view/id/' . $this->id
    )
);
$buttons[] = new Fisma_Yui_Form_Button_Link(
    'treetButton', 
    array('value' => 'Control Tree',
          'imageSrc' => '/images/view_tree.png', 
          'href' => '/sa/security-authorization/control-tree/id/' . $this->id
    )
);

foreach ($buttons as $button) {
    echo $this->escape($button, 'none');
}
