<?php Fisma_Format_Section::startSection("Organizations: Tree View <span id='searchResultsTotalFound'></span>"); ?>

<div class="buttonBar">
<?php
echo $this->partial('security-authorization/control-nav.phtml', array('id' => $this->id));

$expandAll = new Fisma_Yui_Form_Button('expandAll', 
                                       array('label' => 'Expand All', 
                                             'imageSrc' => '/images/expand.png',
                                             'onClickFunction' => 'expandAll'));
echo $this->escape($expandAll, 'none');

$collapseAll = new Fisma_Yui_Form_Button('collapseAll', 
                                         array('label' => 'Collapse All', 
                                             'imageSrc' => '/images/collapse.png',
                                             'onClickFunction' => 'collapseAll'));
echo $this->escape($collapseAll, 'none');

$addControl = new Fisma_Yui_Form_Button('addControl', 
                                       array('label' => 'Add Control', 
                                             'onClickFunction' => 'addControl'));
echo $this->escape($addControl, 'none');
?>
</div>

<div id="controlTree"></div>

<script type="text/javascript">
YAHOO.util.Event.onDOMReady(function () {
    var controlTree = new Fisma.ControlTree(
        'controlTree',
        '/sa/security-authorization/control-tree-data/id/<?php echo $this->escape($this->id); ?>/format/json'
    );
});
// Expand all tree nodes
function expandAll() {
    tree.getRoot().expandAll();
}

// Collapse all tree nodes
function collapseAll() {
    tree.getRoot().collapseAll();
}

// show Add Control dialog
function addControl() {
    var panel = Fisma.HtmlPanel.showPanel("Add Security Control", null, null, { modal : true });
    var callbacks = {
            success: function(o) {
                var panel = o.argument;
                panel.setBody(o.responseText);
                panel.center();
            },
            failure: function(o) {
                alert('Error getting "add control" form: ' + o.statusText);
                var panel = o.argument;
                panel.destroy();
            },
            argument: panel
        };
    YAHOO.util.Connect.asyncRequest( 'GET', "/sa/security-authorization/add-control/id/<?php echo $this->escape($this->id); ?>/format/html", callbacks, null);

}
</script>

<?php Fisma_Format_Section::stopSection(); ?>
