<?php $this->table = Doctrine::getTable('SecurityControlEnhancement'); ?>
Click on any enhancement in the list below to select or deselect:
<table id="enhancementTable" class="table table-hover table-bordered">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col"><?php $this->column('level'); ?></th>
            <th scope="col"><?php $this->column('description'); ?></th>
        </tr>
    </thead>
    <?php if ($this->enhancements->count()): ?>
    <tbody><?php foreach ($this->enhancements as $enhancement): ?>
        <tr <?php if (in_array($enhancement->id, $this->selectedEnhancements)): ?>class="row_selected"<?php endif; ?>>
            <td class="enhancemendId"><?php echo $this->escape($enhancement->id); ?></td>
            <td><?php echo $this->escape($enhancement->level); ?></td>
            <td><?php echo $this->escape($enhancement->description, 'none'); ?></td>
        </tr>
    <?php endforeach; ?></tbody>
    <?php else: ?>
    <tfoot>
        <tr>
            <td colspan="3">This control does not have enhancements.</td>
        </tr>
    </tfoot>
    <?php endif; ?>
</table>
<script>
$(Fisma.Sa.initGetControlEnhancements);
</script>
