<?php 
echo $this->partial('navigation.phtml', array('sa' => $this->sa, 'current' => 'Implement'));

Fisma_Format_Section::startSection('Implementation ' . $this->progress);
foreach ($this->buttonbar as $item) {
    echo $this->escape($item, 'none');
}
echo $this->escape($this->dataTable, 'none');
Fisma_Format_Section::stopSection();
?>
<script type="text/javascript">
function submitCompleteForm()
{
    document.getElementById('completeForm').submit();
}
</script>
