<?php
Fisma_Format_Section::startSection("Overview");
?>
<div id="overviewContainer"></div>

<script>
YAHOO.util.Event.onDOMReady(function () {
    var overview = new Fisma.SecurityAuthorization.Overview(<?php echo json_encode($this->steps); ?>);
    overview.render(document.getElementById("overviewContainer"));    
    Fisma.SecurityAuthorization.overview = overview;
});
</script>

<?php
Fisma_Format_Section::stopSection();
?>
