<?php
Fisma_Format_Section::startSection("Overview");
?>
<table id="securityAuthorizationOverviewTable">
    <thead>
    <tr>
        <th>Step</th>
        <th>Complete</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->completedSteps as $step => $value): ?>
    <tr>
        <td><a onclick="Fisma.tabView.selectTab(<?php echo $this->escape($step)?>)" href="">
            <?php echo $step ?></a></td>
        <td><?php echo $this->escape($value);?></td></tr>
        <?php endforeach; ?>
    </tbody>
</table>
