<?php $this->table = Doctrine::getTable('SecurityControl'); ?>
<?php if ($this->editable): ?>
<div class="buttonBar">
    <?php foreach ($this->toolbarButtons as $button):
        echo $this->escape($button, 'none');
    endforeach; ?>
</div>
<?php Fisma_Format_Section::startSection('Add New Security Control', null, null, 'addControlSection'); ?>
<p>Please select a security control from the list below:</p>
<table id="addControl" class="table table-hover table-bordered">
    <thead>
        <tr>
            <th scope="col"><?php $this->column('family'); ?></th>
            <th scope="col"><?php $this->column('name'); ?></th>
            <th scope="col"><?php $this->column('control'); ?></th>
            <th scope="col"><?php $this->column('code'); ?></th>
            <th scope="col"><?php $this->column('controlLevel'); ?></th>
        </tr>
    </thead>
    <tbody><?php foreach ($this->availableControls as $control): ?>
        <tr data-type-id='<?php echo $this->escape($control->id); ?>'>
            <td><?php echo $this->escape($control->family); ?></td>
            <td><?php echo $this->escape($control->name); ?></td>
            <td><?php echo $this->escape($control->control, 'none'); ?></td>
            <td><?php echo $this->escape($control->code); ?></td>
            <td><?php echo $this->escape($control->controlLevel); ?></td>
        </tr>
    <?php endforeach; ?></tbody>
</table>
<?php Fisma_Format_Section::stopSection(); ?>
<?php Fisma_Format_Section::startSection('Import Common Controls', null, null, 'importControlSection'); ?>
<?php Fisma_Format_Section::stopSection(); ?>
<?php endif; ?>

<?php Fisma_Format_Section::startSection('Imported Common Controls'); ?>
<table id="importedControls" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col"><?php $this->column('family'); ?></th>
            <th scope="col"><?php $this->column('name'); ?></th>
            <th scope="col"><?php $this->column('control'); ?></th>
            <th scope="col"><?php $this->column('code'); ?></th>
            <th scope="col"><?php $this->column('controlLevel'); ?></th>
            <?php if ($this->editable): ?><th scope="col">Action</th><?php endif; ?>
        </tr>
    </thead>
    <tbody><?php foreach ($this->importedControls as $controlSelection):
        $control = Doctrine::getTable('SecurityControl')->find($controlSelection->securityControlId); ?>
        <tr data-type-id='<?php echo $this->escape($control->id); ?>'>
            <td><?php echo $this->escape($control->family); ?></td>
            <td><?php echo $this->escape($control->name); ?></td>
            <td><?php echo $this->escape($control->control, 'none'); ?></td>
            <td><?php echo $this->escape($control->code); ?></td>
            <td><?php echo $this->escape($control->controlLevel); ?></td>
            <?php if ($this->editable): ?><td>
                <a href="#" onclick="Fisma.Sa.removeControl(event, this)"><i class="icon-trash"></i> Remove</a><br/>
                <a href="#" onclick="Fisma.Sa.selectEnhancements(event, this)"><i class="icon-list-alt"></i>
                    Enhancements
                </a>
            </td><?php endif; ?>
        </tr>
    <?php endforeach; ?></tbody>
</table>
<?php Fisma_Format_Section::stopSection(); ?>

<?php Fisma_Format_Section::startSection('Security Control Requirements'); ?>
<table id="selectedControls" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col"><?php $this->column('family'); ?></th>
            <th scope="col"><?php $this->column('name'); ?></th>
            <th scope="col"><?php $this->column('control'); ?></th>
            <th scope="col"><?php $this->column('code'); ?></th>
            <th scope="col"><?php $this->column('controlLevel'); ?></th>
            <th scope="col"><?php $this->column('common', Doctrine::getTable('SystemSecurityControl')); ?></th>
            <?php if ($this->editable): ?><th scope="col">Action</th><?php endif; ?>
        </tr>
    </thead>
    <tbody><?php foreach ($this->selectedControls as $controlSelection):
        $control = Doctrine::getTable('SecurityControl')->find($controlSelection->securityControlId); ?>
        <tr data-type-id='<?php echo $this->escape($control->id); ?>'>
            <td><?php echo $this->escape($control->family); ?></td>
            <td><?php echo $this->escape($control->name); ?></td>
            <td><?php echo $this->escape($control->control, 'none'); ?></td>
            <td><?php echo $this->escape($control->code); ?></td>
            <td><?php echo $this->escape($control->controlLevel); ?></td>
            <td><?php if ($controlSelection->common):
                ?><i class="common-flag icon-star"></i> YES<?php
                else:
                ?><i class="common-flag icon-star-empty"></i> NO<?php
            endif; ?></td>
            <?php if ($this->editable): ?><td>
                <a href="#" onclick="Fisma.Sa.removeControl(event, this)"><i class="icon-trash"></i> Remove</a><br/>
                <a href="#" onclick="Fisma.Sa.setCommonControl(event, this)"><?php if (!$controlSelection->common):
                    ?><i class="icon-star"></i> Set common<?php
                    else:
                    ?><i class="icon-star-empty"></i> Unset common<?php
                endif; ?></a><br/>
                <a href="#" onclick="Fisma.Sa.selectEnhancements(event, this)"><i class="icon-list-alt"></i>
                    Enhancements
                </a>
            </td><?php endif; ?>
        </tr>
    <?php endforeach; ?></tbody>
</table>
<?php Fisma_Format_Section::stopSection(); ?>

<div
    id="enhancementModal"
    class="modal hide fade" tabindex="-1"
    role="dialog" aria-labelledby="enhancementModal" aria-hidden="true"
>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Enhancements</h3>
    </div>
    <div class="modal-body"></div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <button id="saveEnhancements" class="btn btn-primary">Save changes</button>
    </div>
</div>
<script>
    $(function() {
        Fisma.Sa.initSel(<?php echo $this->escape(($this->editable) ? 'true' : 'false'); ?>);
    });
</script>
