<div class="buttonBar">
<?php
    Fisma_Format_Section::startSection("Select Controls");
foreach ($this->buttons as $button) {
    echo $this->escape($button, 'none');
}
?>
</div>
<div id="myContainer"></div>

<script type="text/javascript">
var dataTable = new Fisma.SecurityControlTable("myContainer", <?php echo $this->escape($this->id); ?>);
// submit the form to mark the selection step as complete

</script>

