<div>
    <?php
    foreach ($this->buttons as $button) {
        echo $this->escape($button, 'none');
    }
    ?>
</div>

<?php
if ($this->controlCount == 0):
?>
    <div id="no-security-controls-warning" class="warning">
        <p>This security plan does not contain any security controls.</p>
        <p>
            You can import the baseline security controls 
            for this <em><?php echo $this->escape($this->systemImpact); ?></em> system by 
            clicking the "Import Baseline Controls" button.
        </p>
    </div>
<?php
endif;

Fisma_Format_Section::startSection("Select Controls");
echo $this->escape($this->dataTable, 'none');
Fisma_Format_Section::stopSection();
?>
