<?php echo $this->partial('navigation.phtml', array('sa' => $this->subject, 'current' => 'Select')); ?>
<div class="buttonBar">
<?php
foreach ($this->buttons as $button) {
    echo $this->escape($button, 'none');
}
?>
</div>
<div id="myContainer"></div>

<script type="text/javascript">
var dataTable = new Fisma.SecurityControlTable("myContainer", <?php echo $this->escape($this->id); ?>);
// submit the form to mark the selection step as complete
function completeSelect()
{
    document.getElementById('completeForm').submit();
}

</script>

