<div>
    <?php
    foreach ($this->buttons as $button) {
        echo $this->escape($button, 'none');
    }
    ?>
</div>

<?php if ($this->controlCount == 0): ?>
    <div class="warning">
        <p>This security plan does not contain any security controls.</p>
        <p>
            You can import the baseline security controls 
            for this <em><?php echo $this->escape($this->systemImpact); ?></em> system by 
            clicking the "Import Baseline Controls" button.
        </p>
    </div>
<?php endif; ?>

<?php
Fisma_Format_Section::startSection("Select Controls");
?>

<div id="selectSecurityControlsContainer"></div>

<script type="text/javascript">
Fisma.SecurityAuthorization.selectControlsTable = new Fisma.SecurityControlTable("selectSecurityControlsContainer",
                                                      <?php echo $this->escape($this->id); ?>);
</script>

<?php
Fisma_Format_Section::stopSection();
?>
