<?php
$sectionTitle = 'Security Authorization';
$sectionTitle .= ' [<a href="/sa/security-authorization/edit/id/' . $this->id . '">Edit</a>]';
$sectionTitle .= ' [<a href="/sa/select-controls/index/id/' . $this->id . '">Select Controls</a>]';
$sectionTitle .= ' [<a href="/sa/security-authorization/assessment-plan/id/' . $this->id . '">Assessment Plan</a>]';
Fisma_Format_Section::startSection($sectionTitle); ?>

<div>
    <?php echo $this->escape($this->form, 'none') ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>

