<?php Fisma_Format_Section::startSection("Plug-in Reports"); ?>

<div id="container">
    <table id='reportTable'>
        <thead>
            <tr>
                <th>Report</th>
                <th>Description</th>
                <th>Roles</th>
            </tr>
        </thead>
        <?php
            foreach ($this->reports as $reportName => $reportParams):
                $rolesString = implode(', ', $reportParams['roles']);
        ?>
            <tr>
                <td class='tdc'>
                    <a href="/finding-report/plugin-report/name/<?php echo $this->escape($reportName)?>">
                        <?php echo $this->escape($reportParams['title'])?>
                    </a>
                </td>
                <td class='tdc'><?php echo $this->escape($reportParams['description'], 'none')?></td>
                <td class='tdc'><?php echo $this->escape($rolesString)?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>

<?php Fisma_Format_Section::stopSection(); ?>

<script type="text/javascript">
// Convert the HTML table above into a YUI table
YAHOO.util.Event.onContentReady('container', function() {
    var myColumnDefs = [
        {key:"report", label:"Report", sortable:true},
        {key:"description", label:"Description", sortable:false},
        {key:"roles", label:"Roles", sortable:false}
    ];

    this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("reportTable"));
    this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
    this.myDataSource.responseSchema = {
        fields: [{key:"report"},
                {key:"description"},
                {key:"roles"}
        ]
    };

    this.myDataTable = new YAHOO.widget.DataTable("container", myColumnDefs, this.myDataSource, {});
});
</script>
