<form
    id="finding_workflow_remove_step"
    name="finding_workflow_remove_step"
    method="post"
    enctype="multipart/form-data"
>
    <div class="messageBox attention">
        WARNING: You are about to remove an approval step. This action cannot be undone.
    </div>
    <p><b>
        There may be items currently associated with the workflow step you are about to delete.
        Please select a workflow step to migrate these items to.
    </b></p>
    <p id="step_list">
    </p>
    <div class="buttonBar">
        <button id='dialog_confirm'>Confirm</button>
        <button id="dialog_close">Cancel</button>
    </div>
</form>
