<?php
if ($this->selectedRoles):
    $selectedRoleIds = $this->selectedRoles->getPrimaryKeys();
endif;
?>
<form name='finding_workflow_select_roles' id='finding_workflow_select_roles'>
<?php foreach ($this->roles as $role): ?>
    <span style='width:100px;float:left;'><input type='checkbox'
        name='<?php echo $this->escape($role->id); ?>'
    />
    <?php echo $this->escape($role->nickname); ?>
    </span>
<?php endforeach; ?>
<div class='buttonBar' style='clear:both'>
    <button id='dialog_confirm'>Confirm</button>
    <button id='dialog_close'>Close</button>
</div>
</form>
