<?php
// Fetch data
$step = (empty($this->step)) ? new Evaluation() : $this->step;
$editMode = $this->editMode;
$list = $this->list;

// Prepare HTML snippets
$disabled = ($editMode) ? "" : "readonly";
$prefix = (empty($this->step->name)) ? $list . "_skeleton_" : uniqid($list . "_") . "_";
?>

<span class='linkBar'>
    <a href='#' onclick='return Fisma.FindingWorkflow.toggleDetailPanel(this);'>[View Details]</a>
<?php if ($editMode): ?>
    <a href='#' onclick='return Fisma.FindingWorkflow.showRemoveStepDialog(this);'>[Delete]</a>
<?php endif; ?>
</span>

<span class='stepName'>
    <?php echo $this->escape($step->name); ?>
</span>

<div class='stepDetail'>
    <input
        type='hidden'
        name='<?php echo $this->escape($prefix); ?>databaseId'
        value='<?php echo $this->escape($step->id); ?>'
    />
    <input
        type='hidden'
        name='<?php echo $this->escape($prefix); ?>destinationId'
    />
    <table>
        <tr>
            <td>Workflow Title:</td>
            <td><input
                type='text'
                <?php echo $this->escape($disabled); ?>
                name='<?php echo $this->escape($prefix); ?>name'
                value='<?php echo $this->escape($step->name); ?>'
                onChange='Fisma.FindingWorkflow.titleChangeHandler(this)'
            /></td>
        </tr>
        <tr>
            <td><?php
                echo $this->escape(new Fisma_Yui_Tooltip(
                    $prefix . "chartlabel",
                    'Chart Label',
                    'This label is shown on chart and also used for searching.'
                ), 'none');
            ?></td>
            <td><input
                type='text'
                <?php echo $this->escape($disabled); ?>
                name='<?php echo $this->escape($prefix); ?>nickname'
                value='<?php echo $this->escape($step->nickname); ?>'
            /></td>
        </tr>
        <tr>
            <td>Status Message:</td>
            <td><div>Awaiting <span class='stepName'><?php echo $this->escape($step->name); ?></span></div></td>
        </tr>
        <tr>
            <td>Description:</td>
            <td>
                <textarea
                    class='plaintext'
                    <?php echo $this->escape($disabled); ?>
                    name='<?php echo $this->escape($prefix); ?>description'
                ><?php echo $this->escape($step->description); ?></textarea>
            </td>
        </tr>
        <tr>
            <td>Assigned role(s):</td>
            <td>
                <div><?php
                $rolesString = "";
                foreach ($step->Privilege->Roles as $role):
                    echo $this->escape($role->nickname);
                    $rolesString .= $role->id . '|';
                    ?><br/><?php
                endforeach;
                ?></div>

                <?php if ($editMode): ?>
                <a href='#' onclick='return Fisma.FindingWorkflow.showRoleDialog(this);'>[Assign roles]</a>
                <input
                    type='hidden'
                    name='<?php echo $this->escape($prefix); ?>roles'
                    value='<?php echo $this->escape($rolesString); ?>'/>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td>On Time:</td>
            <td><div>
                The item remains on time if a decision is made within
                <?php echo $this->escape($step->daysUntilDue); ?> days.
            </div></td>
        </tr>
    </table>
</div>
