<?php
// Fetch data
$step = (empty($this->step)) ? new Evaluation() : $this->step;
$editMode = $this->editMode;
$list = $this->list;

// Prepare HTML snippets
$disabled = ($editMode) ? "" : "readonly";
$prefix = (empty($this->step->name)) ? $list . "_skeleton_" : uniqid($list . "_") . "_";

// Hard-code Tooltips
$workflowTitle = 'The workflow title is used to distinguish the workflow step and to auto-create the status message. '
               . 'The status message adds the word awaiting to the beginning of the workflow title. For example, if '
               . 'you create a workflow step called \\"CISO Approval of Evidence Package\\", the status message '
               . 'becomes \\"Awaiting CISO Approval of Evidence Package\\".';
$chartLabel = 'The chart label is used to designate the workflow step in short notation. The chart label is used for '
            . 'graphs, reports, and searching. For example, if the chart label for workflow step ISSO Approval of '
            . 'Mitigation Strategy is set to \\"MS ISSO\\" then the graph will identify the workflow step as \\"MS ISSO'
            . '\\" and the user will be able to search for items currently in the \\"MS ISSO\\" status.';
$statusMessage = 'The status message is a brief synopsis of the current status used to give additional context to the '
               . 'user rather than showing them an acronym. For example, the status message \\"Awaiting ISSO Approval '
               . 'of Mitigation Strategy\\" informs the user what has to happen before the status is changed.';
$onTime = 'The on time period sets the number of calendar days that the workflow step is considered on time. Once the '
        . 'period has lapsed, the workflow step becomes overdue. For example, if the period is set to 7, then the '
        . 'action will remain on-time for 7 calendar days.';
?>

<span class='linkBar'>
    <a href='#' onclick='return Fisma.FindingWorkflow.toggleDetailPanel(this);'>[View Details]</a>
<?php if ($editMode): ?>
    <a href='#' onclick='return Fisma.FindingWorkflow.showRemoveStepDialog(this);'>[Delete]</a>
<?php endif; ?>
</span>

<span class='stepName'>
    <?php echo $this->escape($step->name); ?>
</span>

<div class='stepDetail'>
    <input
        type='hidden'
        name='<?php echo $this->escape($prefix); ?>databaseId'
        value='<?php echo $this->escape($step->id); ?>'
    />
    <input
        type='hidden'
        name='<?php echo $this->escape($prefix); ?>destinationId'
    />
    <table>
        <tr>
            <td><?php
                echo $this->escape(new Fisma_Yui_Tooltip(
                    $prefix . "workflowtitle",
                    'Workflow Title',
                    $workflowTitle
                ), 'none');
            ?></td>
            <td><input
                type='text'
                <?php echo $this->escape($disabled); ?>
                name='<?php echo $this->escape($prefix); ?>name'
                value='<?php echo $this->escape($step->name); ?>'
                onChange='Fisma.FindingWorkflow.titleChangeHandler(this)'
            /></td>
        </tr>
        <tr>
            <td><?php
                echo $this->escape(new Fisma_Yui_Tooltip(
                    $prefix . "chartlabel",
                    'Chart Label',
                    $chartLabel
                ), 'none');
            ?></td>
            <td><input
                type='text'
                <?php echo $this->escape($disabled); ?>
                name='<?php echo $this->escape($prefix); ?>nickname'
                value='<?php echo $this->escape($step->nickname); ?>'
            /></td>
        </tr>
        <tr>
            <td><?php
                echo $this->escape(new Fisma_Yui_Tooltip(
                    $prefix . "statusmessage",
                    'Status Message',
                    $statusMessage
                ), 'none');
            ?></td>
            <td><div>Awaiting <span class='stepName'><?php echo $this->escape($step->name); ?></span></div></td>
        </tr>
        <tr>
            <td><?php
                echo $this->escape(new Fisma_Yui_Tooltip(
                    $prefix . "ontime",
                    'On Time',
                    $onTime
                ), 'none');
            ?></td>
            <td><input
                type='text'
                <?php echo $this->escape($disabled); ?>
                name='<?php echo $this->escape($prefix); ?>due'
                value='<?php echo $this->escape($step->daysUntilDue); ?>'
            /></td>
        </tr>
        <tr>
            <td>Description</td>
            <td>
                <textarea
                    class='plaintext'
                    <?php echo $this->escape($disabled); ?>
                    name='<?php echo $this->escape($prefix); ?>description'
                ><?php echo $this->escape($step->description); ?></textarea>
            </td>
        </tr>
        <tr>
            <td>Assigned role(s)</td>
            <td>
                <div><?php
                $rolesString = "";
                foreach ($step->Privilege->Roles as $role):
                    echo $this->escape($role->nickname);
                    $rolesString .= $role->id . '|';
                    ?><br/><?php
                endforeach;
                ?></div>

                <?php if ($editMode): ?>
                <a href='#' onclick='return Fisma.FindingWorkflow.showRoleDialog(this);'>[Assign roles]</a>
                <input
                    type='hidden'
                    name='<?php echo $this->escape($prefix); ?>roles'
                    value='<?php echo $this->escape($rolesString); ?>'/>
                <?php endif; ?>
            </td>
        </tr>
    </table>
</div>
