<?php
$editMode = (
    $this->acl()->hasPrivilegeForClass('create', 'Evaluation') ||
    $this->acl()->hasPrivilegeForClass('update', 'Evaluation') ||
    $this->acl()->hasPrivilegeForClass('delete', 'Evaluation')
);

if ($editMode):
    $saveButton = new Fisma_Yui_Form_Button(
        'saveButton',
        array(
            'label' => 'Save',
            'onClickFunction' => 'Fisma.FindingWorkflow.forceSubmit'
        )
    );
    $cancelButton = new Fisma_Yui_Form_Button_Link(
        'cancelButton',
        array(
            'value' => 'Cancel',
            'href' => '/finding/workflow/view'
        )
    );
endif;
?>

<form
    id='finding-workflow'
    name='finding-workflow'
    action='/finding/workflow/modify'
    onsubmit='Fisma.FindingWorkflow.submitHandler'
    method='post'
>
<input type='hidden' name='forceSubmit' value='false' />

<?php if ($editMode): ?>
<div class='buttonBar'>
    <?php echo $this->escape($saveButton, 'none'); ?>
    <?php echo $this->escape($cancelButton, 'none'); ?>
    <img style='display:none' src='/images/loading_bar.gif' />
</div>
<?php endif; ?>

<?php Fisma_Format_Section::startSection('Finding Workflow'); ?>

<?php if ($editMode): ?>
<div id='changeQueue'>
    <div class='messageBox attention'>
        <ul>
            <li>You are editing a workow, your changes may affect other users of the application.</li>
            <li>Changes you make cannot be undone.</li>
            <li>Changes will not take affect until you click the "Save" button.</li>
            <li>You may cancel your changes if you do not wish to save them.</li>
        </ul>
    </div>

    <div class='approvalHeader'><b>Change Window</b></div>
    <div class='approval'>
        <div class='approvalStep highlight'>
            <input type='hidden' name='changeQueue' />
            You have made the following change(s), please review before saving:
        </div>

    </div>
</div>
<?php endif; ?>

<div class='stepBlock incidentStep completedIncidentStep'>
    <div class='incidentCardinality'>1</div><h1>NEW</h1>
    <table>
        <tr><td>Status Message:</td><td>Awaiting Mitigation Strategy</td></tr>
        <tr>
            <td>Description:</td>
            <td>The finding has been created, but nobody has started composing a mitigation strategy for it.</td>
        </tr>
    </table>
</div>

<div class='stepBlock incidentStep completedIncidentStep'>
    <div class='incidentCardinality'>2</div>
    <h1>DRAFT</h1>
    <table>
        <tr><td>Status Message:</td><td>Awaiting Mitigation Strategy Submission</td></tr>
        <tr>
            <td>Description:</td>
            <td>A mitigation strategy is being composed and has not yet submitted.</td>
        </tr>
    </table>
</div>

<div class='stepBlock incidentStep currentIncidentStep'>
    <div class='incidentCardinality'>3</div>
    <h1>MSA - Mitigation Strategy Approval</h1>
    <?php
        echo $this->escape(new Fisma_Yui_InteractiveOrderedList(
            "action",
            "finding",
            "workflow/step.phtml",
            $this->msList,
            $editMode,
            array(
                'onAppend' => "Fisma.FindingWorkflow.appendHandler",
                'endDrag' => "Fisma.FindingWorkflow.endDragHandler"
            )
        ), 'none');
    ?>
</div>

<div class='stepBlock incidentStep completedIncidentStep'>
    <div class='incidentCardinality'>4</div>
    <h1>EN - Evidence Needed</h1>
    <table>
        <tr><td>Status Message:</td><td>Awaiting Evidence Package Submission</td></tr>
        <tr>
            <td>Description:</td>
            <td>
                The mitigation strategy has been approved. Evidence is now gathered to either support the decision
                of the mitigation strategy or to prove that the strategy has been implemented.
            </td>
        </tr>
    </table>
</div>

<div class='stepBlock incidentStep currentIncidentStep'>
    <div class='incidentCardinality'>5</div>
    <h1>EA - Evidence Approval</h1>
    <?php
        echo $this->escape(new Fisma_Yui_InteractiveOrderedList(
            "evidence",
            "finding",
            "workflow/step.phtml",
            $this->evList,
            $editMode,
            array(
                'onAppend' => "Fisma.FindingWorkflow.appendHandler",
                'endDrag' => "Fisma.FindingWorkflow.endDragHandler"
            )
        ), 'none');
    ?>
</div>

<div class='stepBlock incidentStep completedIncidentStep'>
    <div class='incidentCardinality'>6</div>
    <h1>CLOSED</h1>
    <table>
        <tr><td>Status Message:</td><td>Finding Officially Closed</td></tr>
        <tr>
            <td>Description:</td>
            <td>
                The mitigation strategy has been approved and implemented.
                Evidence has been submitted and approved.
                No further changes can be made to this finding anymore.
            </td>
        </tr>
    </table>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
</form>
