<div class="searchBox">
    <div class="left">
        <?php 
        $listButton = new Fisma_Yui_Form_Button_Link('listButton', 
                                               array('value' => 'IR Category List', 
                                                     'imageSrc' => '/images/view_list.png',
                                                     'href' => '/ir-category/list'));
        echo $this->escape($listButton, 'none');
        ?>
    
        <?php 
        $listButton = new Fisma_Yui_Form_Button_Link('treetButton', 
                                               array('value' => 'IR Category Tree',
                                                     'imageSrc' => '/images/view_tree.png', 
                                                     'href' => '/ir-category/tree'));
        echo $this->escape($listButton, 'none');
        ?>

        <?php 
        if ($this->createIrCategoryPrivilege):
            $createButton = new Fisma_Yui_Form_Button_Link('createSubcategoryButton', 
                                                   array('value' => 'Add IR Sub Category', 
                                                         'imageSrc' => '/images/add.png',
                                                         'href' => '/ir-category/sub_create'));
            echo $this->escape($createButton, 'none');
        endif;
        ?>
    </div>
    <div class="clear"></div>
</div>
