<?php Fisma_Format_Section::startSection("Approve Pending Findings"); ?>
<form method="POST" action="/panel/finding/sub/process-approval">
    <table class="tipframe" style="width:70%" cellpadding="0" cellspacing="0">
        <tr>
            <th class="tdc">Select</th>
            <th class="tdc">Id</th>
            <th class="tdc">System</th>
            <th class="tdc">Description</th>
            <th class="tdc">Duplicate POAM ID</th>
            <th class="tdc">Duplicate POAM System</th>
            <th class="tdc">Duplicate POAM Mitigation Type</th>
            <th class="tdc">Duplicate POAM Status</th>
        </tr>
<?php
    if (count($this->findings) > 0) {
        foreach ($this->findings as $finding) {
            print "<tr><td align='center' class='tdc'><input type=\"checkbox\" name=\"findings[]\" value=\"{$finding['id']}\"></td>";
            print "<td align='center' class='tdc'><a target='_blank' href=\"/panel/remediation/sub/view/id/{$finding['id']}\">{$finding['id']}</a></td>";
            print "<td align='center' class='tdc'>{$finding['nickname']}</td>";
            print "<td class='tdc'>{$finding['finding_data']}</td>";
            if (isset($finding['duplicate_poam_id'])) {
                print "<td align='center' class='tdc'>";
                print "<a target='_blank' href=\"/panel/remediation/sub/view/id/{$finding['duplicate_poam_id']}\">{$finding['duplicate_poam_id']}</a>";
                print "</td><td align='center' class='tdc'>{$finding['old_nickname']}</td>";
                print "<td align='center' class='tdc'>{$finding['old_type']}</td>";
                print "<td align='center' class='tdc'>{$finding['old_status']}</td>";
            } else {
                print "<td align='center' class='tdc' colspan='4'><i>No duplicate found</i></td>";
            }
            print "</td>";
            print "</tr>";
        }
    } else {
        print "<tr><td class='tdc' colspan='8'><i>There are no pending findings.</i></td></tr>";
    }
?>
        <tr>
            <td class="tdc" colspan="8">
                <?php 
                    $selectAllButton = new Fisma_Yui_Form_Button('selectAll',
                                                           array('value' => 'Select All', 
                                                                 'onClickFunction' => 'selectAllUnsafe'));
                    echo $selectAllButton;
        
                    $selectNoneButton = new Fisma_Yui_Form_Button('selectNone',
                                                            array('value' => 'Select None', 
                                                                  'onClickFunction' => 'selectNoneUnsafe'));
                    echo $selectNoneButton;
                    
                    echo new Fisma_Yui_Form_Button_Submit('delete_selected', array('value' => 'Delete Selected'));                    
                    echo new Fisma_Yui_Form_Button_Submit('approve_selected', array('value' => 'Approve Selected'));
                ?>
            </td>
        </tr>
    </table>
</form>
<?php Fisma_Format_Section::stopSection(); ?>

