<?php Fisma_Format_Section::startSection("Approve Pending Findings"); ?>
<form method="POST" action="/panel/finding/sub/process-approval">
<div id="list"></div>
<script type="text/javascript">
    var checkboxList = function(elCell, oRecord, oColumn, sData) {
        elCell.innerHTML = "<input type='checkbox' name='findings[]' value='" + oRecord.getData("nId") + "' />";
    };
    
    var link1 = function(elCell, oRecord, oColumn, sData) {
        elCell.innerHTML = "<a href='/panel/remediation/sub/view/id/"
                         + oRecord.getData("nId")
                         + "'>"
                         + oRecord.getData("nId")
                         + "</a>";
    };
    
    var link2 = function(elCell, oRecord, oColumn, sData) {
        elCell.innerHTML = "<a href='/panel/remediation/sub/view/id/"
                         + oRecord.getData("oId")
                         + "'>"
                         + oRecord.getData("oId")
                         + "</a>";
    };
    // Column definitions
    var myColumnDefs = [
        {key:"nId", label:"", hidden: false, formatter: checkboxList}
        ,{key:"nId", label:"ID", hidden: false, formatter: link1}
        ,{key:"nNickname", label:"System", hidden: false, formatter: "text"}
        ,{key:"nDesc", label:"Description", hidden: false}
        ,{key:"oId", label:"Duplicate POAM ID", hidden: false, formatter: link2}
        ,{key:"oNickname", label:"Duplicate POAM System", hidden: false, formatter: "text"}
        ,{key:"oType", label:"Duplicate POAM Mitigation Type", hidden: false}
        ,{key:"oStatus", label:"Duplicate POAM Status", hidden: false}
    ];
     
<?php
    $records = array();

    foreach ($this->findings as $finding) {
        $records[] = array(
            'nId' => $finding->id, 
            'nNickname' => $finding->ResponsibleOrganization->nickname, 
            'nDesc' => $finding->description, 
            'oId' => $finding->DuplicateFinding->id,
            'oType' => $finding->DuplicateFinding->type, 
            'oNickname' => $finding->DuplicateFinding->ResponsibleOrganization->nickname,
            'oStatus' => $finding->DuplicateFinding->status
        );
    }

    $records = json_encode($records);
?>
    var dataSource = { rows: <?php echo $this->escape($records, 'none'); ?> }; 
     
    var myDataSource = new YAHOO.util.DataSource(dataSource.rows);
    
    // DataTable configuration
    var myConfigs = {
        dynamicData: false
    };
    var myDataTable = new YAHOO.widget.DataTable("list", myColumnDefs, myDataSource, myConfigs);
</script>
<table>
        <tr>
            <td height="50px">
                <?php 
                    $selectAllButton = new Fisma_Yui_Form_Button('selectAll',
                                                           array('label' => 'Select All', 
                                                                 'onClickFunction' => 'selectAllUnsafe'));
                    echo $this->escape($selectAllButton, 'none');
        
                    $selectNoneButton = new Fisma_Yui_Form_Button('selectNone',
                                                            array('label' => 'Select None', 
                                                                  'onClickFunction' => 'selectNoneUnsafe'));
                    echo $this->escape($selectNoneButton, 'none');
                    
                    $deleteButton =  new Fisma_Yui_Form_Button_Submit(
                        'delete_selected',
                        array('label' => 'Delete Selected')
                    );
                    echo $this->escape($deleteButton, 'none');
                    $approveButton = new Fisma_Yui_Form_Button_Submit(
                        'approve_selected',
                        array('label' => 'Approve Selected')
                    );
                    echo $this->escape($approveButton, 'none');
                ?>
            </td>
        </tr>
    </table>
</form>
<?php Fisma_Format_Section::stopSection(); ?>

