<?php
    $this->blscr_list[0] = 'NONE';
    $threatLevelList =  array("NONE" => "NONE",
                              "LOW" => "LOW",
                              "MODERATE" => "MODERATE",
                              "HIGH" => "HIGH");
?>
<?php Fisma_Format_Section::startSection("Finding Creation"); ?>

<form name="finding" method="post" action="/panel/finding/sub/create/is/new" >
<table>
    <tr>
        <td>
            <div class="toolbar">
                <?php echo new Fisma_Yui_Form_Button_Submit('createFindingSubmit', array('value' => 'Create Finding')); ?>
                <?php echo new Fisma_Yui_Form_Button_Reset('createFindingReset', array('value' => 'Reset Form')); ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>
        <table border="0" width="100%" cellpadding="5" class="tipframe">
            <tr> <th align="left">General Information</th> </tr>
            <tr> <td>
                    <table border="0" cellpadding="1" cellspacing="1">
                        <tr>
                            <td align="right"><b>Discovered Date:&nbsp;</b></td>
                            <td>
                                <table border="0" cellpadding="0" cellspacing="0">
                                    <tr>
                                        <td><input type="text" class="date" name="poam[discover_ts]" size="12" maxlength="10" value="<?php echo date('Ymd');?>" url=""></td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td align="right"><b>Finding Source:&nbsp;</b></td>
                            <td>
                            <?php 
                                $this->source = array('--Any--') + $this->source;
                                echo $this->formSelect('poam[source_id]', 0, null, $this->source); 
                            ?>
                                
                            </td>
                        </tr>
                    </table>

    $("#search_asset").click(function(){
        searchAsset();
    }).trigger('click');

	function searchAsset( ){
    	var trigger = $("select[name='system_id']");
	    var sys = trigger.children("option:selected").attr('value');
	    var param =  '';
    	if( null != sys){
        	param +=  '/sid/' + sys;
	    }
    	$("input.assets").each(function(){
        	if( $(this).attr('value') ){
            	param += '/' + $(this).attr('name') + '/' + $(this).attr('value');
	        }
    	});
		var url = '/asset/search' + param;
    	$("select[name='asset_id']").load(url,null,function(){
        	asset_detail();
	    });
	}

<?php Fisma_Format_Section::stopSection(); ?>
