<?php
    $threatLevelList =  array("NONE" => "NONE",
                              "LOW" => "LOW",
                              "MODERATE" => "MODERATE",
                              "HIGH" => "HIGH");
?>
<?php Fisma_Format_Section::startSection("Finding Creation"); ?>

<form name="finding" method="post" action="/panel/finding/sub/create/is/new" >
<table>
    <tr>
        <td>
            <div class="toolbar">
                <?php echo new Fisma_Yui_Form_Button_Submit('createFindingSubmit', array('value' => 'Create Finding')); ?>
                <?php echo new Fisma_Yui_Form_Button_Reset('createFindingReset', array('value' => 'Reset Form')); ?>
            </div>
        </td>
    </tr>
    <tr>
        <td>
        <table border="0" width="100%" cellpadding="5" class="tipframe">
            <tr> <th align="left">General Information</th> </tr>
            <tr> <td>
                    <table border="0" cellpadding="1" cellspacing="1">
                        <tr>
                            <td align="right"><b>Discovered Date:&nbsp;</b></td>
                            <td>
                                <table border="0" cellpadding="0" cellspacing="0">
                                    <tr>
                                        <td><input type="text" class="date" id="discover_ts" name="poam[discover_ts]" size="12" maxlength="10" value="<?php echo date('Ymd');?>" url=""><button type="button" id="discover_ts_show" title="Show Calendar"><img src="/images/calendar.gif" width="18" height="18" alt="Calendar" ></button></td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td align="right"><b>Finding Source:&nbsp;</b></td>
                            <td>
                            <?php 
                                $this->source = array('--Any--') + $this->source;
                                echo $this->formSelect('poam[source_id]', 0, null, $this->source); 
                            ?>
                                
                            </td>
                        </tr>
                    </table>
            <tr>
                <td>
                    <table border="0" width="100%" cellpadding="5" class="tipframe">
                        <tr><th align="left">Asset Information
                        </th>
                        <th align="right"><a id="add_asset" href="/asset/create" title="Create New Asset">Create New Asset</a>
                        </th>
                        <tr>
                            <td colspan="2">
                                <table width="100%" border="0" cellpadding="5">
                                    <tr>
                                        <td><b>System:</b></td>
                                        <td>
                            <?php 
                                $this->system = array('--Any--') + $this->system;
                                echo $this->formSelect('poam[system_id]', 0, array('url'=>"/asset/search"), $this->system); 
                            ?>
                                        </td>
                                        <td><b>Asset Name:</b></td>
                                        <td><input class='assets' type="text" name="name" value="<?php echo $this->param['port']; ?>" size="10" />&nbsp;</td>
                                      </tr>
                                    <tr>
                                    <td><b>IP Address:</b></td>
                                    <td><input class='assets' type="text" name="ip" value="<?php echo $this->param['ip']; ?>" maxlength="23" /></td>
                                    <td><b>Port:<b></b></b></td>
                                    <td><input class='assets' type="text" name="port" value="<?php echo $this->param['port']; ?>" size="10" /></td>
                                    </tr>
                                    <tr>
                                      <td>&nbsp;</td>
                                      <td><input id="search_asset" type="button" value="Search Assets" url='/asset/search' /></td>
                                      <td colspan=2 ><input type="reset" name="button2" id="button2" value="Reset" /></td>
                                      </tr>
                                </table><hr/>
                            </td>
                        </tr>
                        <tr>
                            <td width="200" align="center"><b>Asset Name:</b><div>
                                <select id="poam-asset_id" name="poam[asset_id]" size="8" style="width: 190px;" >
                                </select></div>                            </td>
                            <td width="600" align="center" valign="top">
                                <fieldset style="height:115; border:1px solid #44637A; padding:5">
                                <legend><b>Asset Information</b></legend>
                                <div id="asset_info"></div>
                                </fieldset>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
</form>

<?php Fisma_Format_Section::stopSection(); ?>
