<?php Format_Section::startSection("Spreadsheet Upload"); ?>

<div class=>
    <form action="/panel/finding/sub/injection" method="POST" enctype="multipart/form-data">
        <ol>
            <li>Download the Excel <a href="/finding/template">template file</a>.
            <li>Fill out the template file.
            <li>Upload the file here: <br>
            <input type="file" name="excelFile"><br>
            <input type="submit" name="submit">
        </ol>
    </form>
</div>

<?php Format_Section::stopSection(); ?>
