<?php echo '<?xml version="1.0"?>'.
           '<?mso-application progid="Excel.Sheet"?>';
?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">
 <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
  <Title>Finding Injection Template</Title>
  <Subject>Finding Injection Template</Subject>
  <Company>Endeavor Systems, Inc.</Company>
  <Version>11.9999</Version>
 </DocumentProperties>
 <ExcelWorkbook xmlns="urn:schemas-microsoft-com:office:excel">
  <WindowHeight>10875</WindowHeight>
  <WindowWidth>17100</WindowWidth>
  <WindowTopX>120</WindowTopX>
  <WindowTopY>15</WindowTopY>
  <ProtectStructure>False</ProtectStructure>
  <ProtectWindows>False</ProtectWindows>
 </ExcelWorkbook>
 <Styles>
  <Style ss:ID="Default" ss:Name="Normal">
   <Alignment ss:Vertical="Bottom"/>
   <Borders/>
   <Font x:Family="Swiss"/>
   <Interior/>
   <NumberFormat/>
   <Protection/>
  </Style>
  <Style ss:ID="m77975580">
   <Alignment ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font x:Family="Swiss" ss:Size="20" ss:Bold="1"/>
   <Interior ss:Color="#CCFFFF" ss:Pattern="Solid"/>
  </Style>
  <Style ss:ID="s21">
   <Alignment ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
  </Style>
  <Style ss:ID="s22">
   <Alignment ss:Horizontal="Center" ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
  </Style>
  <Style ss:ID="s28">
   <Alignment ss:Horizontal="Center" ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font x:Family="Swiss" ss:Bold="1"/>
   <Interior ss:Color="#FFCC00" ss:Pattern="Solid"/>
  </Style>
  <Style ss:ID="s29">
   <Alignment ss:Horizontal="Center" ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font x:Family="Swiss" ss:Bold="1"/>
   <Interior ss:Color="#FFFF99" ss:Pattern="Solid"/>
  </Style>
  <Style ss:ID="s30">
   <Alignment ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font x:Family="Swiss" ss:Bold="1"/>
   <Interior ss:Color="#FFCC00" ss:Pattern="Solid"/>
  </Style>
  <Style ss:ID="s31">
   <Alignment ss:Horizontal="Center" ss:Vertical="Bottom" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <NumberFormat ss:Format="yyyy/mm/dd;@"/>
  </Style>
  <Style ss:ID="s32">
   <Font x:Family="Swiss" ss:Bold="1"/>
  </Style>
 </Styles>
 <Names>
  <NamedRange ss:Name="controls" ss:RefersTo="=ControlIDs!C1"/>
 </Names>
 <Worksheet ss:Name="Findings">
  <Table ss:ExpandedColumnCount="10" ss:ExpandedRowCount="1000" x:FullColumns="1"
   x:FullRows="1" ss:StyleID="s21">
   <Column ss:StyleID="s22" ss:AutoFitWidth="0" ss:Width="49.5"/>
   <Column ss:StyleID="s22" ss:AutoFitWidth="0" ss:Width="60.75"/>
   <Column ss:StyleID="s22" ss:AutoFitWidth="0" ss:Width="92.25"/>
   <Column ss:StyleID="s22" ss:AutoFitWidth="0" ss:Width="121.5"/>
   <Column ss:StyleID="s22" ss:AutoFitWidth="0" ss:Width="43.5"/>
   <Column ss:StyleID="s22" ss:AutoFitWidth="0" ss:Width="78.75"/>
   <Column ss:StyleID="s21" ss:AutoFitWidth="0" ss:Width="188.25"/>
   <Column ss:StyleID="s21" ss:AutoFitWidth="0" ss:Width="135"/>
   <Column ss:StyleID="s21" ss:AutoFitWidth="0" ss:Width="84.75"/>
   <Column ss:StyleID="s21" ss:AutoFitWidth="0" ss:Width="92.25"/>
   <Row ss:Height="26.25">
    <Cell ss:MergeAcross="9" ss:StyleID="m77975580"><ss:Data ss:Type="String"
      xmlns="http://www.w3.org/TR/REC-html40"><B><?php echo Config_Fisma::readSysConfig('system_name');?> Injection Template&#10;<Font
        html:Size="10">Fill the work sheet with your finding data and save it as CSV format.</Font></B></ss:Data></Cell>
   </Row>
   <Row ss:Height="38.25">
    <Cell ss:StyleID="s28"><Data ss:Type="String">System</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><B><Font
         html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">Note:</Font></B><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">&#10;Field cannot be empty. Please select a value from the list.</Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s28"><Data ss:Type="String">Date Discovered</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><B><Font
         html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">Note:</Font></B><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">&#10;Field cannot be empty. Your date value must in be between  2000-01-01 and 2037-01-01.</Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s29"><Data ss:Type="String">Network</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><B><Font
         html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">Note:</Font></B><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">&#10;Field cannot be empty. Please select a value from the list.</Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s29"><Data ss:Type="String">IP Address</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><B><Font
         html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">Note:</Font></B><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">&#10;This Field may be empty.</Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s29"><Data ss:Type="String">Port</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><B><Font
         html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">Note:</Font></B><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">&#10;This field may be empty. Port must be an integer between 0 and 65535.</Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s28"><Data ss:Type="String">Audit Source</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><B><Font
         html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">Note:</Font></B><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">&#10;Field cannot be empty. Please select a value from the list.</Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s30"><Data ss:Type="String">Finding Description</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><B><Font
         html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">Note:</Font></B><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">&#10;Field cannot be empty.</Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s30"><Data ss:Type="String">Finding Recommendation</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><B><Font
         html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">Note:</Font></B><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">&#10;Field cannot be empty.</Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s30"><Data ss:Type="String">Security Control</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><B><Font
         html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">Note:</Font></B><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">&#10;Field cannot be empty.</Font></ss:Data></Comment></Cell>
    <Cell ss:StyleID="s30"><Data ss:Type="String">Risk Level</Data><Comment
      ss:Author="alix"><ss:Data xmlns="http://www.w3.org/TR/REC-html40"><B><Font
         html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">Note:</Font></B><Font
        html:Face="宋体" x:Family="Swiss" html:Size="9" html:Color="#000000">&#10;Field cannot be empty.</Font></ss:Data></Comment></Cell>
   </Row>
  </Table>
  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
   <Print>
    <ValidPrinterInfo/>
    <Scale>45</Scale>
    <HorizontalResolution>600</HorizontalResolution>
    <VerticalResolution>600</VerticalResolution>
   </Print>
   <PageBreakZoom>60</PageBreakZoom>
   <Selected/>
   <Panes>
    <Pane>
     <Number>3</Number>
     <ActiveRow>2</ActiveRow>
     <ActiveCol>0</ActiveCol>
    </Pane>
   </Panes>
   <ProtectObjects>False</ProtectObjects>
   <ProtectScenarios>False</ProtectScenarios>
  </WorksheetOptions>
  <DataValidation xmlns="urn:schemas-microsoft-com:office:excel">
   <Range>R3C1:R65536C1</Range>
   <Type>List</Type>
   <CellRangeList/>
   <Value>&quot;<?php echo implode(',',array_values($this->systems));?>&quot;</Value>
  </DataValidation>
  <DataValidation xmlns="urn:schemas-microsoft-com:office:excel">
   <Range>R3C2:R65536C2</Range>
   <Type>Date</Type>
   <Min>36526</Min>
   <Max>50041</Max>
  </DataValidation>
  <DataValidation xmlns="urn:schemas-microsoft-com:office:excel">
   <Range>R3C3:R65536C3</Range>
   <Type>List</Type>
   <CellRangeList/>
   <Value>&quot;<?php echo implode(',',array_values($this->networks));?>&quot;</Value>
  </DataValidation>
  <DataValidation xmlns="urn:schemas-microsoft-com:office:excel">
   <Range>R3C4:R1034C4</Range>
   <Type>TextLength</Type>
   <Min>0</Min>
   <Max>63</Max>
  </DataValidation>
  <DataValidation xmlns="urn:schemas-microsoft-com:office:excel">
   <Range>R3C5:R1034C5</Range>
   <Type>Whole</Type>
   <Min>0</Min>
   <Max>65535</Max>
  </DataValidation>
  <DataValidation xmlns="urn:schemas-microsoft-com:office:excel">
   <Range>R3C6:R65536C6</Range>
   <Type>List</Type>
   <CellRangeList/>
   <Value>&quot;<?php echo implode(',',array_values($this->sources));?>&quot;</Value>
  </DataValidation>
  <DataValidation xmlns="urn:schemas-microsoft-com:office:excel">
   <Range>R3C7:R1034C7,R3C8:R1034C8</Range>
   <Type>TextLength</Type>
   <Min>0</Min>
   <Max>655535</Max>
  </DataValidation>
  <DataValidation xmlns="urn:schemas-microsoft-com:office:excel">
   <Range>R3C9:R65536C9</Range>
   <Type>List</Type>
   <Value>controls</Value>
  </DataValidation>
  <DataValidation xmlns="urn:schemas-microsoft-com:office:excel">
   <Range>R3C10:R65536C10</Range>
   <Type>List</Type>
   <CellRangeList/>
   <Value>&quot;<?php echo implode(',', $this->risk) ;?>&quot;</Value>
  </DataValidation>
 </Worksheet>
 <Worksheet ss:Name="ControlIDs">
  <Names>
   <NamedRange ss:Name="_FilterDatabase" ss:RefersTo="=ControlIDs!C1" ss:Hidden="1"/>
  </Names>
  <Table ss:ExpandedColumnCount="1" ss:ExpandedRowCount="1000" x:FullColumns="1"
   x:FullRows="1">
   <Column ss:AutoFitWidth="0" ss:Width="54.75"/>
<?php
    foreach ($this->blscrs as $blscr) {
?>
<Row>
<Cell>
<Data ss:Type="String"><?php echo $blscr; ?></Data>
<NamedCell ss:Name="controls"/>
<NamedCell ss:Name="_FilterDatabase"/>
</Cell>
</Row>
<?php
    }
?>
  </Table>
  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
   <Print>
    <ValidPrinterInfo/>
    <HorizontalResolution>600</HorizontalResolution>
    <VerticalResolution>0</VerticalResolution>
   </Print>
   <Panes>
    <Pane>
     <Number>3</Number>
     <ActiveCol>1</ActiveCol>
    </Pane>
   </Panes>
   <ProtectObjects>True</ProtectObjects>
   <ProtectScenarios>False</ProtectScenarios>
  </WorksheetOptions>
 </Worksheet>
</Workbook>
