ALTER TABLE `<?php echo $this->escape($this->table); ?>`

ADD COLUMN `<?php echo $this->escape($this->column); ?>`

<?php echo $this->escape($this->type); ?>

<?php if ($this->signed === false): ?>
    UNSIGNED
<?php endif; ?>

<?php if ($this->nullable === false): ?>
    NOT NULL
<?php else: ?>
    NULL
<?php endif; ?>

<?php if (isset($this->default)): ?>
    DEFAULT '<?php echo $this->escape($this->default, 'quotes'); ?>'
<?php endif; ?>

<?php if ($this->autoIncrement === true): ?>
    AUTO_INCREMENT
<?php endif; ?>

<?php if ($this->primary === true): ?>
    PRIMARY KEY
<?php elseif ($this->unique === true): ?>
    UNIQUE KEY
<?php endif; ?>

<?php if (isset($this->comment)): ?>
    COMMENT '<?php echo $this->escape($this->comment, 'quotes'); ?>'
<?php endif; ?>

<?php if (isset($this->after)): ?>
    AFTER `<?php echo $this->escape($this->after); ?>`
<?php endif; ?>
