<?php Format_Section::startSection('User Account Information'); ?>

<?php if(!empty($this->requirements)) {?>
<p>The new password must meet the following complexity criteria:</p>
<ul>
<?php
foreach ($this->requirements as $requirement) {
    echo "<li>$requirement";
}
?>
</ul>
<?php } ?>
<div class="form_box">
<?php echo $this->form ?>
</div>

<?php Format_Section::stopSection(); ?>

<script type="text/javascript" src="/javascripts/account.js"></script>
