<?php Format_Section::startSection('User Account Information'); ?>

<?php if(!empty($this->requirements)) {?>
<p>The new password must meet the following complexity criteria:</p>
<ul>
<?php
foreach ($this->requirements as $requirement) {
    echo "<li>$requirement";
}
?>
</ul>
<?php } ?>
<div class="form_box">
<?php echo $this->form ?>
</div>

<?php Format_Section::stopSection(); ?>

<script type="text/javascript">
YAHOO.util.Event.onDOMReady(function () {
    var generatePasswordButton = document.getElementById('generate_password');
    generatePasswordButton.onclick = function () {
        YAHOO.util.Connect.asyncRequest('GET', 
                                        '/account/generatepassword/format/html', 
                                        {
                                            success: function(o) {
                                                document.getElementById('password').value = o.responseText;                                           
                                                document.getElementById('confirmPassword').value = o.responseText;
                                            },
                                            failure: function(o) {alert('Failed to generate password: ' + o.statusText);}
                                        }, 
                                        null);
        return false;
    };
});
</script>
