<div class="barleft">
    <div class="barright">
        <p><b>User Account Information</b> [<a href="<?php echo $this->viewLink ?>">View</a>]</p>
    </div>
</div>
<?php if(!empty($this->requirements)) {?>
<p>The new password must meet the following complexity criteria:</p>
<ul>
<?php
foreach ($this->requirements as $requirement) {
    echo "<li>$requirement";
}
?>
</ul>
<?php } ?>
<div class="form_box">
    <?php echo $this->form ?>
</div>
