<?php Fisma_Format_Section::startSection('User Account List'); ?>
<div id="list"></div>
<script type="text/javascript">
// Column definitions
var myColumnDefs = [
    {key:"id", label:"id",hidden: true}
    ,{key:"name_first", label:"First Name", sortable: true, hidden: false}
    ,{key:"name_last", label:"Last Name", sortable: true, hidden: false}
    ,{key:"phone_office", label:"Office Phone", sortable: true, hidden: false}
    ,{key:"phone_mobile", label:"Mobile Phone", sortable: true, hidden: false}
    ,{key:"email", label:"Email", sortable: true, hidden: false}
    ,{key:"role", label:"Role", sortable: true, hidden: false}
    ,{key:"account", label:"Username", sortable: true, hidden: false}
];

    var dataSource = { rows: [
    <?php foreach ($this->userList as $row) {
          if (!isset($i)) { $i = true; } else { echo ','; } ?>
          {<?php  foreach (array('name_first', 'name_last', 'phone_office',
                                 'phone_mobile', 'email', 'id', 'account', 'role') as $val) { 
                    if (!isset($n)) { $n = true; } else { echo ','; }
                    if ($val != 'role') {
                        echo $val . ":'" . $row[$val] . "'";
                    } else {
                        echo $val . ":'" . $this->roleList[$row['id']] . "'";
                    }
                  }
                unset($n); ?>}
    <?php } unset($i); ?> ] };
    var myDataSource = new YAHOO.util.DataSource(dataSource.rows);
    
    // DataTable configuration
    var myConfigs = {
        dynamicData: false
    };
    var myDataTable = new YAHOO.widget.DataTable("list", myColumnDefs, myDataSource, myConfigs);
    myDataTable.subscribe("rowMouseoverEvent", myDataTable.onEventHighlightRow); 
    myDataTable.subscribe("rowMouseoutEvent", myDataTable.onEventUnhighlightRow);
    <?php if ($this->acl->isAllowed('admin_users','read')) { ?>
    myDataTable.subscribe("rowClickEvent", 
        function (oArgs) {
            var elTarget = oArgs.target;
            var oRecord = this.getRecord(elTarget);
            document.location = "/panel/account/sub/view/v/view/id/" + oRecord.getData("id");
        }
    );
    <?php }?>
</script>
<?php Fisma_Format_Section::stopSection(); ?>
