<?php 
    Format_Section::startSection('User Account Administration'); 
?>
<table class="tipframe" align="center"  width="98%" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <th>[<a id="user_list" href="/panel/account/sub/list">User List</a>] (total: <?php echo $this->total;?>)</th>
            <?php if($this->acl->isAllowed('admin_users', 'create')) { ?>
            <th>[<a id="add_user" href="/panel/account/sub/create" title="add new Users">Add User</a>]</th>
            <?php } ?>
            <th>[<a id="user_log" href="/panel/log/sub/view" title="Review user logs">User Logs</a>]</th>
            <th>
                <table align="center">
                    <tbody>
                        <tr height="22">
                            <td><b>Page:&nbsp;</b></td>
                            <td><?php echo $this->links['all'];?></td>
                        </tr>
                    </tbody>
                </table>
            </th>
            <th>
                
                <form name="query" method="post" action="/panel/account/sub/list">
                    <table align="center">
                        <tr>
                            <td><b>Query:&nbsp;</b></td>
                            <td><input name="qv" value="<?php echo $this->qv;?>" size="20" maxlength="40" type="text"></td>

                             <td><input value="Search" type="submit"></td>
                        </tr>
                    </table>
                </form>
            </th>
        </tr>
    </tbody>
</table>
<?php 
    Format_Section::stopSection();
?>

