<?php
$operation = '';
if ($this->acl->isAllowed('admin_users','update')) {
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
}
if ($this->acl->isAllowed('admin_users','delete')) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}
Fisma_Format_Section::startSection("User Account Information $operation"); ?>

<div>
    <?php echo $this->form ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
