<button
	id = '<?php echo $this->escape($this->id); ?>'
	class = 'btn'
	<?php if ($this->disabled): ?>disabled<?php endif; ?>
	<?php if ($this->tooltip): ?>title = '<?php echo $this->escape($this->tooltip, 'none'); ?>'<?php endif; ?>
>
	<?php if ($this->imageUrl): ?><img src='<?php echo $this->escape($this->imageUrl); ?>' alt='' /><?php endif; ?>
	<?php if ($this->icon): ?><i class='icon-<?php echo $this->escape($this->icon); ?>'></i><?php endif; ?>
	<?php echo $this->escape($this->label); ?>
</button>
<script type='text/javascript'>
$(function() {
	$('#<?php echo $this->escape($this->id); ?>')
	<?php if ($this->function): ?>
		.click(function(e) {
			e.preventDefault();
			<?php echo $this->escape($this->function, 'javascript'); ?>.apply(
				this,
				[e, <?php echo $this->escape($this->arguments, 'json'); ?>]
			);
		})
	<?php endif; ?>
	;
});
</script>
