<div id="<?php echo $this->escape($this->containerId); ?>">
    <table id="<?php echo $this->escape($this->tableId); ?>" border="1">
        <thead>
            <tr>
                <?php foreach ($this->columns as $column): ?>
                    <th><?php echo $this->escape($column->getName()); ?></th>
                <?php endforeach; ?>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($this->data as $row): ?>
                <tr>
                    <?php foreach($row as $cell): ?>
                    <td><?php echo $this->escape($cell) ?></td>
                    <?php endforeach;?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script type="text/javascript">
    YAHOO.util.Event.onContentReady("<?php echo $this->escape($this->containerId, 'javascript'); ?>", function() {

        var columnDefs = <?php echo $this->escape($this->columnDefinitions, 'json'); ?>;

        /* 
         * Column definitions are defined in JSON, which cannot embed object references such as formatters. So 
         * loop over the definitions and convert any names of formatters into references to those actual objects.
         */
        for (index in columnDefs) {
            var columnDef = columnDefs[index];
            
            if (columnDef['formatter']) {
                columnDef['formatter'] = Fisma.Util.getObjectFromName(columnDef['formatter']);
            }
        }

        var dataSource = new YAHOO.util.DataSource(
            YAHOO.util.Dom.get("<?php echo $this->escape($this->tableId, 'javascript'); ?>")
        );
        dataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
        dataSource.responseSchema = <?php echo $this->escape($this->responseSchema, 'json'); ?>;

        var dataTable = new YAHOO.widget.DataTable(
            "<?php echo $this->escape($this->containerId, 'javascript'); ?>", 
            columnDefs, 
            dataSource, 
            {}
        );
        
        // Enable row highlighting for mouse over events
        dataTable.subscribe("rowMouseoverEvent", dataTable.onEventHighlightRow); 
        dataTable.subscribe("rowMouseoutEvent", dataTable.onEventUnhighlightRow);
        
        // Enable other events triggered from the data-table
        var eventListeners = <?php echo $this->escape($this->eventListeners, 'json'); ?>;
        for (var eventName in eventListeners)
        {
            // Each element of eventListeners, has a key of the event-name, and a value of a javascript function name
            var eventHandler = Fisma.Util.getObjectFromName(eventListeners[eventName]);
            dataTable.subscribe(eventName, eventHandler);
        }
        
    });
</script>
