<?php
$enabledStyle = ($this->enabled) ? " enabled" : "";
?>
<ul
    id='<?php echo $this->escape($this->id); ?>Container'
    class='dragList<?php echo $this->escape($enabledStyle); ?>'
>
<?php
$count = 1;
foreach ($this->items as $childHtml):
?>
    <li id='<?php echo $this->escape($this->id . 'Item' . $count); ?>'>
        <?php echo $this->escape($childHtml, 'none'); ?>
    </li>
<?php
        $count++;
    endforeach;
?>
</ul>
<?php if ($this->enabled): ?>
<script type='text/javascript'>
    YAHOO.util.Event.onDOMReady(function() {
        new YAHOO.util.DDTarget(
            '<?php echo $this->escape($this->id); ?>Container',
            '<?php echo $this->escape($this->id); ?>'
        );
<?php
for ($i = 1; $i <= count($this->items); $i++):
?>
        new Fisma.InteractiveOrderedListItem(
            '<?php echo $this->escape($this->id . 'Item' . $i); ?>',
            '<?php echo $this->escape($this->id); ?>',
            {
<?php
    $firstHandler = true;
    foreach ($this->jsHandlers as $event => $handler):
        if (!$firstHandler):
            echo $this->escape(',');
        else:
            $firstHandler = false;
        endif;
        echo $this->escape("'{$event}' : {$handler}", 'none');
    endforeach;
?>
            },
            {
                dragElId : 'dragListProxy'
            }
        );
<?php
endfor;
?>
        // This unfortunate hack is to get around YAHOO DragDrop onMouseDown handler shadowing over onClick
        var inputs = YAHOO.util.Selector.query('div.stepDetail input[type=text]');
        for (var i in inputs) {
            YAHOO.util.Event.on(inputs[i], 'click', function(clickEvent) {
                clickEvent.target.focus()
            });
        }
    });
</script>
<a href='javascript:alert("Feature not yet implemented")'>[Add a Step]</a>
<?php endif; ?>
