<?php
    $roles = !empty($this->roles) ? $this->roles : 'NULL';
    $id = !empty($this->id) ? $this->id : -1;
    $readOnly = !empty($this->readOnly) ? $this->readOnly : '0';
?>
<script type="text/javascript">
YAHOO.util.Event.onDOMReady(
    function() { 
        Fisma.TabView.Roles.init(
            <?php echo $this->escape($roles, 'none') ?>, 
            <?php echo $this->escape($id, 'none') ?>, 
            <?php echo $this->escape($readOnly, 'none') ?>
        )
    }
);
</script>
