<?php
    $name = $this->element->getName();
    $chunks = explode('<select', $this->content);

    // YUI 2.9 fails to generate the submenus when the optgroups have 'id' attribute
    $chunks[1] = preg_replace('/<optgroup id=".*?"/', '<optgroup ', $chunks[1]);

    echo $this->escape($chunks[0], 'none');
?>
<input type='button' id='<?php echo $this->escape($name); ?>-button'/>
<select<?php echo $this->escape($chunks[1], 'none'); ?>
<script>
    YAHOO.util.Event.onContentReady('<?php echo $this->escape($name); ?>-button', function () {
        var selectElement = document.getElementById('<?php echo $this->escape($name); ?>');
        var selectedLabel = selectElement.options[selectElement.selectedIndex].innerHTML;
        var oMenuButton = new YAHOO.widget.Button('<?php echo $this->escape($name); ?>-button', {
            label: selectedLabel,
            type: 'menu',
            menu: '<?php echo $this->escape($name); ?>'
        });
        oMenuButton.getMenu().subscribe('click', function (p_sType, p_aArgs) {
            if (p_aArgs[1]) {
                if (p_aArgs[1].srcElement.value) {
                    oMenuButton.set('label', p_aArgs[1].cfg.getProperty('text'));
                } else {
                    var firstChild = p_aArgs[1].cfg.getProperty('submenu').getItem(0);
                    oMenuButton.set('selectedMenuItem', firstChild);
                    oMenuButton.set('label', firstChild.cfg.getProperty('text'));
                }
            }
        });
    });
</script>
