<?php if ($this->message): ?>
<div class='message'><?php echo $this->escape($this->message); ?></div>
<?php else: ?>
<div id='changeLayout'>
    Sidebar position:
    <span id="menuLayoutSelect">
        <input type="radio" id="layoutLeft" name="layoutSelect" title="Left"/>
        <label for="layoutLeft">Left</label>
        <input type="radio" id="layoutRight" name="layoutSelect" checked="checked" title="Right" />
        <label for="layoutRight">Right</label>
    </span>
</div>

    <?php Fisma_Format_Section::startSection(
        'Unresolved: By ' . $this->escape($this->translate('Finding_Point_of_Contact')),
        null,
        null,
        'byPoc'
    ); ?>
    <div class='column66 left managerAnalystLeft'>
        <?php echo $this->escape($this->byPocTable, 'none'); ?>
    </div>

    <div class='column33 right managerAnalystRight'>
        <div style='text-align: center;' id='chartByPocContainer'>
            <?php
                echo $this->escape($this->chartByPoc, 'none');
            ?>
        </div>
    </div>

    <div class='clear'></div>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php Fisma_Format_Section::startSection('Unresolved: By System', null, null, 'bySystem'); ?>
    <div class='column66 left managerAnalystLeft'>
        <?php echo $this->escape($this->bySystemTable, 'none'); ?>
    </div>
    <div class='column33 right managerAnalystRight'>
        <div style='text-align: center;' id='chartBySystemContainer'>
            <?php
                echo $this->escape($this->chartBySystem, 'none');
            ?>
        </div>
    </div>
    <?php Fisma_Format_Section::stopSection(); ?>
<script>
$(function() {
    Fisma.Finding.initDashboard();
});
</script>
<?php endif; ?>
