<?php if ($this->message): ?>
<div class='message'><?php echo $this->escape($this->message); ?></div>
<?php else: ?>
<div id='changeLayout'>
    <input type="submit" id="menuLayout" name="menuLayout_button" value="Change Layout">
    <div id="menuLayoutSelect" name="menuLayoutSelect" class="yui-overlay">
        <div id='layoutLeft'><img src='/images/left_sidebar.png'/> Left Sidebar</div>
        <div id='layoutRight'><img src='/images/right_sidebar.png'/> Right Sidebar</div>
    </div>
</div>

    <?php Fisma_Format_Section::startSection('Unresolved: By Point of Contact', null, null, 'byPoc'); ?>
    <div class='column66 left managerAnalystLeft'>
        <?php echo $this->escape($this->byPocTable, 'none'); ?>
    </div>

    <div class='column33 right managerAnalystRight'>
        <div style='text-align: center;' id='chartByPocContainer'>
            <?php
                echo $this->escape($this->chartByPoc, 'none');
            ?>
        </div>
    </div>

    <div class='clear'></div>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php Fisma_Format_Section::startSection('Unresolved: By System', null, null, 'bySystem'); ?>
    <div class='column66 left managerAnalystLeft'>
        <?php echo $this->escape($this->bySystemTable, 'none'); ?>
    </div>
    <div class='column33 right managerAnalystRight'>
        <div style='text-align: center;' id='chartBySystemContainer'>
            <?php
                echo $this->escape($this->chartBySystem, 'none');
            ?>
        </div>
    </div>
    <?php Fisma_Format_Section::stopSection(); ?>
<script>
$(function() {
    Fisma.Finding.initDashboard();
});
</script>
<?php endif; ?>