<?php if ($this->message): ?>
<div class='message'><?php echo $this->escape($this->message); ?></div>
<?php else: ?>
    <?php Fisma_Format_Section::startSection(
        'Unresolved: By ' . $this->escape($this->translate('Finding_Point_of_Contact')),
        null,
        null,
        'byPoc'
    ); ?>

<div class='row-fluid'>
    <div class='span7 managerAnalystLeft'>
        <?php echo $this->escape($this->byPocTable, 'none'); ?>
    </div>

    <div class='span5'>
        <div style='text-align: center;' id='chartByPocContainer'>
            <?php
                echo $this->escape($this->chartByPoc, 'none');
            ?>
        </div>
    </div>
</div>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php Fisma_Format_Section::startSection('Unresolved: By System', null, null, 'bySystem'); ?>
<div class='row-fluid'>
    <div class='span7 managerAnalystLeft'>
        <?php echo $this->escape($this->bySystemTable, 'none'); ?>
    </div>
    <div class='span5'>
        <div style='text-align: center;' id='chartBySystemContainer'>
            <?php
                echo $this->escape($this->chartBySystem, 'none');
            ?>
        </div>
    </div>
</div>
    <?php Fisma_Format_Section::stopSection(); ?>
<script>
$(function() {
    Fisma.Finding.initDashboard();
});
</script>
<?php endif; ?>
