<form action="#" onsubmit="addActor();  return false;"> 
    <input type="hidden" name="actor_incident_id" id="actor_incident_id" value="<?php echo $this->id;  ?>" />
    <table class="fisma_crud">
        <tr>
            <td colspan="3" style="text-align: left"><h1>Actors:</h1></td>
        </tr>
        <tr>
            <td>
                Add Actor:
            </td>
            <td>
                <select name="actor_userid" id="actor_userid">
                <?php foreach($this->users as $user) { ?>
                    <option value="<?php echo $user['id']; ?>"><?php echo $user['nameFirst']; ?> <?php echo $user['nameLast'];  ?> (<?php echo $user['username'];  ?>)</option>
                <?php } ?>
                </select>
            </td>
            <td>
                <input type="submit" value="Add Actor" />
            </td>
        </tr>
        <tr><td colspan="3">&nbsp;</td></tr>
            <?php if ($this->actors) { foreach ($this->actors as $key => $user) { ?>
                <tr>
                    <?php if($key == 0 ) { print "<td>Assigned:</td>"; } else { print "<td>&nbsp;</td>"; } ?>
                    <td> 
                        <?php echo $user['nameFirst']; ?> <?php echo $user['nameLast'];  ?> (<?php echo $user['username'];  ?>) 
                    </td>
                    <td>
                        <a  href="#"  onclick="callAJAX('/incident/actorremove/id/<?php echo $this->id; ?>/userid/<?php echo $user['id']; ?>')">Remove</a>
                    </td>
                </tr>
            <?php }} else { ?>
                <tr>
                    <td>Assigned:</td>
                    <td colspan="2"> No actors have been assigned.</td>
                </tr>
            <?php }  ?>
        </tr>
    </table>
</form>

<div class="clear"></div>
<br />
<form action="#" onsubmit="addObserver();  return false;"> 
    <input type="hidden" name="observer_incident_id" id="observer_incident_id" value="<?php echo $this->id;  ?>" />
    <table class="fisma_crud">
        <tr>
            <td colspan="3" style="text-align: left"><h1>Observers:</h1></td>
        </tr>
        <tr>
            <td>
                Add Observer:
            </td>
            <td>
                <select name="observer_userid" id="observer_userid">
                <?php foreach($this->users as $user) { ?>
                    <option value="<?php echo $user['id']; ?>"><?php echo $user['nameFirst']; ?> <?php echo $user['nameLast'];  ?> (<?php echo $user['username'];  ?>)</option>
                <?php } ?>
                </select>
            </td>
            <td>
                <input type="submit" value="Add Observer" />
            </td>
        </tr>
        <tr><td colspan="3">&nbsp;</td></tr>
            <?php if ($this->observers) { foreach ($this->observers as $key => $user) { ?>
                <tr>
                    <?php if($key == 0 ) { print "<td>Assigned:</td>"; } else { print "<td>&nbsp;</td>"; } ?>
                    <td> 
                        <?php echo $user['nameFirst']; ?> <?php echo $user['nameLast'];  ?> (<?php echo $user['username'];  ?>) 
                    </td>
                    <td>
                        <a  href="#"  onclick="callAJAX('/incident/observerremove/id/<?php echo $this->id; ?>/userid/<?php echo $user['id']; ?>')">Remove</a>
                    </td>
                </tr>
            <?php }} else { ?>
                <tr>
                    <td>Assigned:</td>
                    <td colspan="2"> No observers have been assigned.</td>
                </tr>
            <?php }  ?>
        </tr>
    </table>
</form>
