<?php if ($this->association == 'actor' ) { ?>
<form action="#" onsubmit="addActor();  return false;" id="actorForm"> 
    <input type="hidden" name="actor_incident_id" id="actor_incident_id" value="<?php echo $this->id;  ?>" />
<?php } ?>
    <table class="fisma_crud">
        <tr>
            <td colspan="3" style="text-align: left"><h1>Actors:</h1></td>
        </tr>
        <?php if ($this->association == 'actor' ) { ?>
        <tr>
            <td nowrap>
                <span class="tooltip" id="actor_useridTooltip"><label for="actor_userid">Add Actor:</label></span>
            </td>
            <td>
                <select name="actor_userid" id="actor_userid">
                <?php foreach($this->users as $user) { ?>
                    <option value="<?php echo $user['id']; ?>"><?php echo $user['nameFirst']; ?> <?php echo $user['nameLast'];  ?> (<?php echo $user['role'];  ?>)</option>
                <?php } ?>
                </select>
            </td>
            <td>
                <span id="actorButtonContainer"></span>
            </td>
        </tr>
        <?php } ?>
        <tr><td colspan="3">&nbsp;</td></tr>
            <?php if ($this->actors) { foreach ($this->actors as $key => $user) { ?>
                <tr>
                    <?php if($key == 0 ) { print "<td>Assigned:</td>"; } else { print "<td>&nbsp;</td>"; } ?>
                    <td> 
                        <?php echo $user['nameFirst']; ?> <?php echo $user['nameLast'];  ?> (<?php echo $user['role'];  ?>) 
                    </td>
                    <td>
                        <?php if (($this->association == 'actor') && ($this->user_id <> $user['id'])) { ?>
                        <a  href="#"  onclick="callAJAX('/incident/actorremove/id/<?php echo $this->id; ?>/userid/<?php echo $user['id']; ?>')">Remove</a>
                        <?php } ?>
                    </td>
                </tr>
            <?php }} else { ?>
                <tr>
                    <td>Assigned:</td>
                    <td colspan="2"> No actors have been assigned.</td>
                </tr>
            <?php }  ?>
        </tr>
    </table>
<?php if ($this->association == 'actor' ) { ?>
</form>
<?php } ?>

<div class="clear"></div>
<br />

<?php if ($this->association == 'actor' ) { ?>
<form action="#" onsubmit="addObserver();  return false;" id="observerForm"> 
    <input type="hidden" name="observer_incident_id" id="observer_incident_id" value="<?php echo $this->id;  ?>" />
<?php } ?>
    <table class="fisma_crud">
        <tr>
            <td colspan="3" style="text-align: left"><h1>Observers:</h1></td>
        </tr>
        <?php if ($this->association == 'actor' ) { ?>
        <tr>
            <td nowrap>
                <span class="tooltip" id="observer_useridTooltip"><label for="observer_userid">Add Observer:</label></span>
            </td>
            <td>
                <select name="observer_userid" id="observer_userid">
                <?php foreach($this->users as $user) { ?>
                    <option value="<?php echo $user['id']; ?>"><?php echo $user['nameFirst']; ?> <?php echo $user['nameLast'];  ?> (<?php echo $user['role'];  ?>)</option>
                <?php } ?>
                </select>
            </td>
            <td>
                <span id="observerButtonContainer"></span>
            </td>
        </tr>
        <?php } ?>
        <tr><td colspan="3">&nbsp;</td></tr>
            <?php if ($this->observers) { foreach ($this->observers as $key => $user) { ?>
                <tr>
                    <?php if($key == 0 ) { print "<td>Assigned:</td>"; } else { print "<td>&nbsp;</td>"; } ?>
                    <td> 
                        <?php echo $user['nameFirst']; ?> <?php echo $user['nameLast'];  ?> (<?php echo $user['role'];  ?>) 
                    </td>
                    <td>
                        <?php if (($this->association == 'actor') && ($this->user_id <> $user['id'])) { ?>
                        <a  href="#"  onclick="callAJAX('/incident/observerremove/id/<?php echo $this->id; ?>/userid/<?php echo $user['id']; ?>')">Remove</a>
                        <?php } ?>
                    </td>
                </tr>
            <?php }} else { ?>
                <tr>
                    <td>Assigned:</td>
                    <td colspan="2"> No observers have been assigned.</td>
                </tr>
            <?php }  ?>
        </tr>
    </table>
<?php if ($this->association == 'actor' ) { ?>
</form>
<?php } ?>
