<div class="column left">
    <?php
    Fisma_Format_Section::startSection("Actors");
    if ($this->updateIncidentPrivilege):
    ?>
        <form method="post" action="/incident/add-actor/type/actor/id/<?php echo $this->id; ?>">
            <input type="hidden" id="actorId" name="userId" value="">
            <div style="position: relative; top: 0px; width: 200px;">&nbsp;
                <?php echo $this->actorAutocomplete; ?>
            </div>
            <div style="position: relative; top 10px; left: 220px; margin-bottom: 20px; width: 150px;">&nbsp;
                <?php echo $this->addActorButton; ?>
            </div>
        </form>
    <?php
    endif;
    ?>
    <div id="actors">
        <table id="actorsTable">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Remove</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->actors as $actor):
                ?>
                    <tr>
                        <td><?php echo $actor['a_username']; ?></td>
                        <td><?php echo $actor['a_nameFirst']; ?></td>
                        <td><?php echo $actor['a_nameLast']; ?></td>
                        <td>
                            <?php
                            echo "<a href=\"/incident/remove-actor/type/actor"
                               . "/incidentId/{$this->id}/userId/{$actor['a_id']}\">";
                            ?>
                                Remove
                            </a>
                        </td>
                    </tr>                
                <?php
                endforeach;
                ?>
            </tbody>
        </table>
    </div>
    <?php
    Fisma_Format_Section::stopSection();
    ?>
</div>

<div class="column right">
    <?php
    Fisma_Format_Section::startSection("Observers");
    if ($this->updateIncidentPrivilege):
    ?>
    <form method="post" action="/incident/add-actor/type/observer/id/<?php echo $this->id; ?>">
        <input type="hidden" id="observerId" name="userId" value="">
        <div style="position: relative; top: 0px; width: 200px;">&nbsp;
            <?php echo $this->observerAutocomplete; ?>
        </div>
        <div style="position: relative; top 10px; left: 220px; margin-bottom: 20px; width: 150px;">&nbsp;
            <?php echo $this->addObserverButton; ?>
        </div>
    </form>
    <?php
    endif;
    ?>
    <div id="observers">
        <table id="observersTable">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->observers as $observer):
                ?>
                    <tr>
                        <td><?php echo $observer['o_username']; ?></td>
                        <td><?php echo $observer['o_nameFirst']; ?></td>
                        <td><?php echo $observer['o_nameLast']; ?></td>
                    </tr>                
                <?php
                endforeach;
                ?>
            </tbody>
        </table>
    </div>
    <?php
    Fisma_Format_Section::stopSection();
    ?>    
</div>

<script type="text/javascript">
// Convert actors table to YUI table
YAHOO.util.Event.onContentReady('actors', function() {
    var myColumnDefs = [
        {key:'username', label:'Username', sortable:true},
        {key:'nameFirst', label:'First Name', sortable:true},
        {key:'nameLast', label:'Last Name', sortable:true},
<?php if ($this->updateIncidentPrivilege): ?>
        {key:'remove', label:'Remove', sortable:false}
<?php endif; ?>
    ];

    this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("actorsTable"));
    this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
    this.myDataSource.responseSchema = {
        fields: [
            {key:'username'},
            {key:'nameFirst'},
            {key:'nameLast'},
<?php if ($this->updateIncidentPrivilege): ?>
            {key: 'remove'}
<?php endif; ?>
        ]
    };

    this.myDataTable = new YAHOO.widget.DataTable("actors", myColumnDefs, this.myDataSource, {});
});

// Convert observers table to YUI table
YAHOO.util.Event.onContentReady('observers', function() {
    var myColumnDefs = [
        {key:'username', label:'Username', sortable:true},
        {key:'nameFirst', label:'First Name', sortable:true},
        {key:'nameLast', label:'Last Name', sortable:true}
    ];

    this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("observersTable"));
    this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
    this.myDataSource.responseSchema = {
        fields: [
            {key:'username'},
            {key:'nameFirst'},
            {key:'nameLast'}
        ]
    };

    this.myDataTable = new YAHOO.widget.DataTable("observers", myColumnDefs, this.myDataSource, {});
});

</script>
