<div id="incidentAuditLog">
    <table id="incidentAuditLogTable">
        <thead>
            <tr>
                <th>Timestamp</th>
                <th>User</th>
                <th>Message</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->logs as $log) : ?>
        <tr>
            <td><?php echo $this->escape($log['o_createdTs']); ?></td>
            <td><?php echo $this->escape($log['u_username']); ?></td>
            <td><?php echo $this->escape($log['o_message'], 'none'); ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script type="text/javascript">
// Convert the HTML table above into a YUI table
YAHOO.util.Event.onContentReady('incidentAuditLog', function() {
    var myColumnDefs = [
        {key:'timestamp', label:'Timestamp', sortable:true},
        {key:'user', label:'User', sortable:true},
        {key:'message', label:'Message', sortable:false}        
    ];

    this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("incidentAuditLogTable"));
    this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
    this.myDataSource.responseSchema = {
        fields: [
            {key:'timestamp'},
            {key:'user'},
            {key:'message'}
        ]
    };

    this.myDataTable = new YAHOO.widget.DataTable("incidentAuditLog", myColumnDefs, this.myDataSource, {});
});
</script>
