<?php 
Fisma_Format_Section::startSection("Incident Report Canceled");
?>

<h1>The incident report has been canceled</h1>

<p>
    <?php
    echo new Fisma_Yui_Form_Button_Link('returnToHome',
                              array('value' => 'Continue', 
                                    'href' => "/", 
                                    'imageSrc' => '/images/right_arrow.png'));
    ?>
</p>

<?php
Fisma_Format_Section::stopSection();
?>
