<?php Fisma_Format_Section::startSection("Categorize Incident"); ?>

<p>
    The first step in this process is to review and categorize the incident. Once a category has been selected, 
    a workflow will be created for the incident. Alternatively, the incident can be rejected, which will result in no
    workflow.
</p>

<?php 
if ($this->classifyIncidentPrivilege):
    echo $this->form; 
else:
?>
    <p>
        <i>You do not have permission to categorize this incident.</i>
    </p>
<?php
endif;

Fisma_Format_Section::stopSection(); 
?>
