<div id="foo" style="width: 48%; float: left;">
<?php Fisma_Format_Section::startSection("Incident Information"); ?>

<div id="incidentData">Loading...</div>

<script type="text/javascript">

var incidentCallback = {
        success: function(o) {
            document.getElementById('incidentData').innerHTML =  o.responseText;
        },
        failure: function(o) {
            alert("Error loading Incident Data");
        }
    } 

var transaction = YAHOO.util.Connect.asyncRequest('GET', '/incident/incidentdata/id/<?php print $this->id; ?>', incidentCallback, null);

</script>

<?php Fisma_Format_Section::stopSection(); ?>
</div>

<div id="foo" style="width: 48%; float: right;">
<?php Fisma_Format_Section::startSection("Actors/Observers"); ?>

<div id="actors">Loading...</div>

<script type="text/javascript">

var callback = {
        success: function(o) {
            document.getElementById('actors').innerHTML =  o.responseText;
            actor_useridTooltip = new YAHOO.widget.Tooltip("actor_useridTooltipObj", { context:"actor_useridTooltip", showdelay: 150, hidedelay: 150, autodismissdelay: 25000, text:"<b>Actors</b> can add/remove users to/from an incident, complete workflow steps, and submit comments to an incident.", effect:{effect:YAHOO.widget.ContainerEffect.FADE,duration:0.25}, width: "50%"});
            observer_useridTooltip = new YAHOO.widget.Tooltip("observer_useridTooltipObj", { context:"observer_useridTooltip", showdelay: 150, hidedelay: 150, autodismissdelay: 25000, text:"<b>Observers</b> can view an incident, and will be notified when the incident is updated.  They cannot perform any actions on the incident.", effect:{effect:YAHOO.widget.ContainerEffect.FADE,duration:0.25}, width: "50%"});
        },
        failure: function(o) {
            alert("Error loading Actors/Observers");
        }
    } 

var transaction = YAHOO.util.Connect.asyncRequest('GET', '/incident/actor/id/<?php print $this->id; ?>', callback, null);

//this funciton will be called by onclick events defined in actors.phtml
function callAJAX(url) {
    var transaction = YAHOO.util.Connect.asyncRequest('GET', url, callback, null);
}

//this funciton will be called by submitting the add actor form defined in actors.phtml
function addActor() {
    var id = document.getElementById('actor_incident_id').value; 
    var userid = document.getElementById('actor_userid').value;
    
    var url = '/incident/actoradd/id/' + id  + '/userid/' + userid ;

    var transaction = YAHOO.util.Connect.asyncRequest('GET', url, callback, null);
}

//this funciton will be called by submitting the add observer form defined in actors.phtml
function addObserver() {
    var id = document.getElementById('observer_incident_id').value; 
    var userid = document.getElementById('observer_userid').value;
    
    var url = '/incident/observeradd/id/' + id  + '/userid/' + userid ;

    var transaction = YAHOO.util.Connect.asyncRequest('GET', url, callback, null);
}

</script>

<?php Fisma_Format_Section::stopSection(); ?>
</div>

<div class="clear"></div>

<?php Fisma_Format_Section::startSection("Classify/Reject Incident"); ?>

<?php echo $this->form; ?>

<?php Fisma_Format_Section::stopSection(); ?>
