<?php Fisma_Format_Section::startSection("Incident Information"); ?>
<div id="incidentData">Loading...</div>

<script type="text/javascript">

var incidentCallback = {
        success: function(o) {
            document.getElementById('incidentData').innerHTML =  o.responseText;
            var viewDetailsButton = new YAHOO.widget.Button({
                                       type: "submit",
                                       label: "View Details",
                                       id: "viewDetailsButton",
                                       name: "viewDetailsButton",
                                       value: "View Details",
                                       container: "viewDetailsButtonContainer",
                                       disabled: false,
                                       onclick: { fn: onViewButtonClick }
                                   });
            var hideDetails1Button = new YAHOO.widget.Button({
                                       type: "submit",
                                       label: "Hide Details",
                                       id: "hideDetailsButton",
                                       name: "hideDetailsButton",
                                       value: "Hide Details",
                                       container: "hideDetails1ButtonContainer",
                                       disabled: false,
                                       onclick: { fn: onHideButtonClick }
                                   });
            var hideDetails2Button = new YAHOO.widget.Button({
                                       type: "submit",
                                       label: "Hide Details",
                                       id: "hideDetailsButton",
                                       name: "hideDetailsButton",
                                       value: "Hide Details",
                                       container: "hideDetails2ButtonContainer",
                                       disabled: false,
                                       onclick: { fn: onHideButtonClick }
                                   });
            var editDetailsButton = new YAHOO.widget.Button({
                                       type: "link",
                                       href: "/panel/incident/sub/edit/id/<?php print $this->id; ?>", 
                                       label: "Edit",
                                       id: "editDetailsButton",
                                       name: "editDetailsButton",
                                       value: "Edit",
                                       container: "editButtonContainer",
                                       disabled: false,
                                   });
        },
        failure: function(o) {
            alert("Error loading Incident Data");
        }
    } 

var transaction = YAHOO.util.Connect.asyncRequest('GET', '/incident/incidentdata/id/<?php print $this->id; ?>', incidentCallback, null);

function onViewButtonClick() {
    document.getElementById('incident_details').style.display = 'block'; 
    document.getElementById('hideDetails1ButtonContainer').style.display = 'inline'; 
    return false;
}

function onHideButtonClick() {
    document.getElementById('incident_details').style.display = 'none'; 
    document.getElementById('hideDetails1ButtonContainer').style.display = 'none'; 
    return false;
}
</script>
<?php Fisma_Format_Section::stopSection(); ?>

<?php Fisma_Format_Section::startSection("Close Incident"); ?>

<?php echo $this->form; ?>

<?php Fisma_Format_Section::stopSection(); ?>

<?php Fisma_Format_Section::startSection("Incident History"); ?>
<table class="fisma_crud">

    <?php 
        foreach ($this->steps as $key => $step) {
            if ($key < (count($this->steps) - 1)) { 
                print "<tr><td>Workflow Step:</td><td><h2>{$step['name']}</h2></td></tr>";
                print "<tr><td>Completed By:</td> <td><h2>{$step['user']['nameFirst']} {$step['user']['nameLast']} ({$step['user']['username']})</h2></td></tr>";
                print "<tr><td>Completed On:</td> <td><h2>{$step['completeTs']}</h2></td></tr>";
                print "<tr><td>Comments:</td>     <td><h2>{$step['comments']}</h2></td></tr>";
                if ($key < (count($this->steps) - 2)) { 
                    print "<tr><td colspan='2'><hr /></td></tr>";
                }
            }
        }
    ?>
    

</table>
<?php Fisma_Format_Section::stopSection(); ?>
