<?php Fisma_Format_Section::startSection("Incident Information"); ?>
<div id="incidentData">Loading...</div>

<script type="text/javascript">
var viewDetailsButton;

var incidentCallback = {
        success: function(o) {
            document.getElementById('incidentData').innerHTML =  o.responseText;
            viewDetailsButton = new YAHOO.widget.Button({
                                       type: "submit",
                                       label: "Show Details",
                                       id: "viewDetailsButton",
                                       name: "viewDetailsButton",
                                       value: "View Details",
                                       container: "viewDetailsButtonContainer",
                                       disabled: false,
                                       onclick: { fn: onViewButtonClick }
                                   });
            var editDetailsButton = new YAHOO.widget.Button({
                                       type: "link",
                                       href: "/panel/incident/sub/edit/id/<?php print $this->id; ?>", 
                                       label: "Edit",
                                       id: "editDetailsButton",
                                       name: "editDetailsButton",
                                       value: "Edit",
                                       container: "editButtonContainer",
                                       disabled: false,
                                   });
        },
        failure: function(o) {
            alert("Error loading Incident Data");
        }
    } 

var transactionUrl = '/incident/incidentdata/id/<?php print $this->id; ?>';
var transaction = YAHOO.util.Connect.asyncRequest('GET', transactionUrl, incidentCallback, null);

function onViewButtonClick() {
    if ('block' == document.getElementById('incident_details').style.display) {
        document.getElementById('incident_details').style.display = 'none'; 
        viewDetailsButton.set('label', 'Show Details');
    } else {
        document.getElementById('incident_details').style.display = 'block'; 
        viewDetailsButton.set('label', 'Hide Details');
    }
    return false;
}
</script>
<?php Fisma_Format_Section::stopSection(); ?>

<?php Fisma_Format_Section::startSection("Close Incident"); ?>

<?php echo $this->form; ?>

<?php Fisma_Format_Section::stopSection(); ?>

<?php Fisma_Format_Section::startSection("Incident History"); ?>

<?php 
foreach ($this->steps as $key => $step):
    print "<table width='50%' class='fisma_crud' style='margin-bottom: 10px;'>"
        . "<tr><td width='15%'>Workflow Step:</td><td width='35%'><h2>{$step['name']}</h2></td></tr>"
        . "<tr><td>Completed By:</td> <td><h2>{$step['user']['nameFirst']}"
        . " {$step['user']['nameLast']} ({$step['user']['username']})</h2></td></tr>"
        . "<tr><td>Completed On:</td> <td><h2>{$step['completeTs']}</h2></td></tr>"
        . "<tr><td>Comments:</td>     <td><h2>{$step['comments']}</h2></td></tr></table>";
endforeach;
?>  

</table>
<?php Fisma_Format_Section::stopSection(); ?>
