    <table class="fisma_crud">
        <?php 
            if ($this->comments) {
                foreach($this->comments as $comment) {
                    print " <tr>
                                <td style='text-align: left'><b>{$comment['createdTs']}</b></td>
                                <td>{$comment['user']['nameFirst']} {$comment['user']['nameLast']} ({$comment['user']['username']})</td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><h2>{$comment['comment']}</h2></td>
                            </tr>
                            <tr>
                                <td colspan='3'><hr /></td>
                            </tr>";
                }
            } else {
                print "<tr><td>No comments have been added</td></tr>";
            }
        ?>
    </table>
