<?php
if ($this->association == 'actor') {
?>
<form action="#" onsubmit="addcomment(); return false;" id="commentForm">
    <input type="hidden" id="id" name="id" value="<?php print $this->id; ?>">
<?php } ?>
    <table class="fisma_crud">
        <?php 
            if (count($this->comments) > 0) {
                foreach($this->comments as $comment) {
                    print " <tr>
                                <td style='text-align: left'><b>{$comment['c_createdTs']}</b></td>
                                <td>{$comment['u_nameFirst']} {$comment['u_nameLast']}</td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><h2>{$comment['c_comment']}</h2></td>
                            </tr>
                            <tr>
                                <td colspan='3'><hr /></td>
                            </tr>";
                }
            } else {
                print "<tr><td colspan='3'style='text-align: left;'>No comments have been added</td></tr>";
                print "<tr><td colspan='3'><hr /></td></tr>";
            }
        ?>
<?php
if ($this->association == 'actor') {
?>
        <tr>
            <td style="text-align: left" colspan="3"><br /><h1>Add Comment:</h1></td>
        </tr>
        <tr>
            <td colspan="3">
                <textarea name="comments" id="comments" rows="10" cols="60"></textarea>
            </td>
        </tr>
        <tr>
            <td style="text-align: left" colspan="3">
                <span id="commentButtonContainer"></span>
            </td>
        </tr>
<?php } ?>
    </table>
</form>
