<?php
Fisma_Format_Section::startSection('Comments');
?>
    <div class="toolbar">
        <?php echo $this->commentButton; ?>
    </div>
    <div id="comments">
        <table id="commentsTable">
            <thead>
                <tr>
                    <th>Timestamp</th>
                    <th>User</th>
                    <th>Comment</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->comments as $comment):
                ?>
                    <tr>
                        <td><?php echo $comment['createdTs']; ?></td>
                        <td>
                            <?php echo $comment['User']['username']; ?>
                        </td>
                        <td>
                            <?php echo Fisma_String::textToHtml($comment['comment']); ?>
                        </td>
                    </tr>                
                <?php
                endforeach;
                ?>
            </tbody>
        </table>
    </div>
<?php
Fisma_Format_Section::stopSection();
?>

<script type="text/javascript">
// Convert comments table to YUI table
YAHOO.util.Event.onContentReady('comments', function() {
    var myColumnDefs = [
        {key:'timestamp', label:'Timestamp', sortable:true},
        {key:'username', label:'User', sortable:true},
        {key:'comment', label:'Comment', sortable:false}
    ];

    var myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("commentsTable"));
    myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
    myDataSource.responseSchema = {
        fields: [
            {key:'timestamp'},
            {key:'username'},
            {key:'comment'}
        ]
    };

    var commentTable = new YAHOO.widget.DataTable("comments", myColumnDefs, myDataSource, {});
    Fisma.Incident.commentTable = commentTable;
});
</script>