<table class="fisma_crud">
    <?php 
    if ($this->comments):
        foreach($this->comments as $comment):
    ?>
        <tr>
            <td style='text-align: left'><b><?php echo $comment['createdTs']; ?></b></td>
            <td>
                <?php echo $comment['user']['nameFirst']; ?>
                <?php echo $comment['user']['nameLast']; ?> 
                (<?php echo $comment['user']['username']; ?>)
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td><h2><?php echo $comment['comment']; ?></h2></td>
        </tr>
        <tr>
            <td colspan='3'><hr /></td>
        </tr>
    <?php
        endforeach;
    else:
        print "<tr><td>No comments have been added</td></tr>";
    endif;
    ?>
</table>
