<?php Fisma_Format_Section::startSection("Incident Information"); ?>

<div id="incidentData">Loading...</div>

<script type="text/javascript">
var viewDetailsButton;

var incidentCallback = {
        success: function(o) {
            document.getElementById('incidentData').innerHTML =  o.responseText;
            viewDetailsButton = new YAHOO.widget.Button({
                                       type: "submit",
                                       label: "Show Details",
                                       id: "viewDetailsButton",
                                       name: "viewDetailsButton",
                                       value: "View Details",
                                       container: "viewDetailsButtonContainer",
                                       disabled: false,
                                       onclick: { fn: onViewButtonClick }
                                   });
            var cloneDetailsButton = new YAHOO.widget.Button({
                                       type: "link",
                                       href: "/panel/incident/sub/clone/id/<?php print $this->id; ?>", 
                                       label: "Clone",
                                       id: "cloneDetailsButton",
                                       name: "cloneDetailsButton",
                                       value: "Edit",
                                       container: "cloneButtonContainer",
                                       disabled: false,
                                   });
        },
        failure: function(o) {
            alert("Error loading Incident Data");
        }
    } 

var transactionUrl = '/incident/incidentdata/id/<?php print $this->id; ?>';
var transaction = YAHOO.util.Connect.asyncRequest('GET', transactionUrl, incidentCallback, null);

function onViewButtonClick() {
    if ('block' == document.getElementById('incident_details').style.display) {
        document.getElementById('incident_details').style.display = 'none'; 
        viewDetailsButton.set('label', 'Show Details');
    } else {
        document.getElementById('incident_details').style.display = 'block'; 
        viewDetailsButton.set('label', 'Hide Details');
    }
    return false;
}

</script>

<?php Fisma_Format_Section::stopSection(); ?>

<?php 
Fisma_Format_Section::startSection("Incident History");

foreach ($this->steps as $key => $step):
    print "<p><table width='50%' class='fisma_crud'><tr><td>Workflow Step:</td>"
        . "<td><h2>{$step['name']}</h2></td></tr>"
        . "<tr><td>Completed By:</td> <td><h2>{$step['user']['nameFirst']}"
        . " {$step['user']['nameLast']} ({$step['user']['username']})</h2></td></tr>"
        . "<tr><td>Completed On:</td> <td><h2>{$step['completeTs']}</h2></td></tr>"
        . "<tr><td>Comments:</td>     <td><h2>{$step['comments']}</h2></td></tr></table>";
endforeach;

Fisma_Format_Section::stopSection(); 
?>

<?php Fisma_Format_Section::startSection("Incident Comments"); ?>

<div id="comment-container">Loading...</div>

<script type="text/javascript">
    var comCallback = {
        success: function(o) {
            document.getElementById('comment-container').innerHTML =  o.responseText;
        },
        failure: function(o) {
            alert("Error loading Comments");
        }
    } 
    
    var transactionUrl = '/incident/commentsnoform/id/<?php print $this->id; ?>';
    var transaction = YAHOO.util.Connect.asyncRequest('GET', transactionUrl, comCallback, null);

</script>
<?php Fisma_Format_Section::stopSection(); ?>
