<?php 
Fisma_Format_Section::startSection("Review Incident Report");
?>

<h1>Review Report</h1>

<p>
   Please review all of the report details which you have provided. If anything needs to be changed, you can use the
   "Go Back" button to revisit the form. When you are satisfied, click the "Submit Report" button.
</p>

<p>
    <i>Once you click "Submit Report", the report will be submitted and it cannot be modified after that.</i>
</p>

<div style="margin: 10px;">
    <table class="keyValues">
        <?php
        foreach ($this->incidentReview as $key => $value):
        ?>    
            <tr>
                <td><?php echo $this->escape($key); ?>:</td>
                <td><?php echo $this->escape($value); ?></td>
            </tr>
        <?php
        endforeach;
        ?>
    </table>
</div>

    <form method="post"
          action="<?php echo $this->escape($this->actionUrlBase, 'none'); ?>/save-report"
          style="display: inline">
        <?php
        $saveReportButton = new Fisma_Yui_Form_Button_Submit(
                'irReportSave', 
                array(
                    'label' => 'Submit Report', 
                    'imageSrc' => '/images/add.png',
                    'class' => 'left',
                    'onClick' => 'confirmIrSubmit'
                )
            );
        echo $this->escape($saveReportButton, 'none');
        ?>
    </form>
    
    <?php
    $irReportCancelButton = new Fisma_Yui_Form_Button_Submit(
        'irReportCancel', 
        array(
            'label' => 'Cancel Report', 
            'imageSrc' => "/images/del.png",
        )
    );
    echo $this->escape($irReportCancelButton, 'none');

    $formAction = $this->actionUrlBase . '/report/step/' . $this->escape($this->step);
    ?>
    
    <form method="post" 
          action="<?php echo $this->escape($formAction, 'none'); ?>" 
          style="display: inline;">
        <?php
        $backwardButton = new Fisma_Yui_Form_Button_Submit(
                'irReportBackwards', 
                array(
                    'label' => 'Go Back', 
                    'imageSrc' => '/images/left_arrow.png',
                    'class' => 'left'
                )
            );
        echo $this->escape($backwardButton, 'none');
        ?>
    </form>

<?php
Fisma_Format_Section::stopSection();
?>
