<form action="/incident/list" method="post">
    <div class="searchFilters" >
        <div class="right">
            <input type="text" 
                   value="<?php echo $this->escape($this->keywords) ?>" 
                   name="keywords" 
                   id="keywords" 
                   helper="formText" />
            <?php
                $submitButton = new Fisma_Yui_Form_Button_Submit('incidentSearchSubmit', array('label' => 'Search'));
                echo $this->escape($submitButton, 'none');
            ?>
        </div>
        
        <div class="clear"></div>
    </div>
</form>
