<chart>
    <license>FTA9HNF7P2O.H4X5CWK-2XOI1X0-7L</license>
    <link_data url="javascript:pieChartClick(_col_)" target="javascript" />
    <chart_data>
        <row>
            <null />
            <string>CAT0</string>
            <string>CAT1</string>
            <string>CAT2</string>
            <string>CAT3</string>
            <string>CAT4</string>
            <string>CAT5</string>
            <string>CAT6</string>
        </row>
        <row>
            <string>count</string>
            <number tooltip='CAT0: <?php echo $this->summary['CAT0']; ?>'><?php echo $this->summary['CAT0']; ?></number>
            <number tooltip='CAT1: <?php echo $this->summary['CAT1']; ?>'><?php echo $this->summary['CAT1']; ?></number>
            <number tooltip='CAT2: <?php echo $this->summary['CAT2']; ?>'><?php echo $this->summary['CAT2']; ?></number>
            <number tooltip='CAT3: <?php echo $this->summary['CAT3']; ?>'><?php echo $this->summary['CAT3']; ?></number>
            <number tooltip='CAT4: <?php echo $this->summary['CAT4']; ?>'><?php echo $this->summary['CAT4']; ?></number>
            <number tooltip='CAT5: <?php echo $this->summary['CAT5']; ?>'><?php echo $this->summary['CAT5']; ?></number>
            <number tooltip='CAT6: <?php echo $this->summary['CAT6']; ?>'><?php echo $this->summary['CAT6']; ?></number>
        </row>
    </chart_data>

    <chart_grid_h thickness='0' />

    <chart_type>pie</chart_type>
    
    <chart_label font='arial'
                 bold='true'
                 size='12'
                 position='outside'
                 as_percentage='true' />

    <legend layout='vertical'
            bullet='circle'
            font='arial'
            bold='true'
            size='10'
            x='25'
            y='25'
            width='50'
            height='100' />

    <series_color>
        <color>b3b3b3</color>
        <color>ff3333</color>
        <color>ff9933</color>
        <color>eaed1e</color>
        <color>66ff66</color>
        <color>7197e1</color>
        <color>c385f1</color>
    </series_color>
</chart> 
