<chart>
    <license>FTA9HNF7P2O.H4X5CWK-2XOI1X0-7L</license>
    <link_data url="javascript:pieChartClick(_col_)" target="javascript" />
    <chart_data>
        <row>
            <null />
            <string>New</string>
            <string>Open</string>
            <string>Resolved</string>
            <string>Rejected</string>
    	</row>
    	<row>
    	    <string>Incidents</string>  	    
            <number tooltip='<?php echo $this->summary['new']; ?>'>
                <?php echo $this->summary['new']; ?></number>
            <number tooltip='<?php echo $this->summary['open']; ?>'>
                <?php echo $this->summary['open']; ?></number>
            <number tooltip='<?php echo $this->summary['resolved']; ?>'>
                <?php echo $this->summary['resolved']; ?></number>
            <number tooltip='<?php echo $this->summary['rejected']; ?>'>
                <?php echo $this->summary['rejected']; ?></number>
    	</row>
    </chart_data>

    <chart_grid_h thickness='0' />

    <chart_type>bar</chart_type>

    <legend layout='hide' />

    <series bar_gap='50' transfer="true"/>

    <chart_label color="000000"
                 position="outside"
                 />

    <series_color>
        <color>ff3333</color>
        <color>eaed1e</color>
        <color>66ff66</color>
        <color>b3b3b3</color>
    </series_color>
</chart> 
