<div class="column left">
    <?php
    Fisma_Format_Section::startSection("Actors");
    if ($this->updateIncidentPrivilege):
    ?>
        <form method="post" action="/incident/add-user/type/actor/id/<?php echo $this->escape($this->id); ?>">
            <input type="hidden" id="actorId" name="userId" value="">
            <div style="position: relative; top: 0px; width: 200px;">&nbsp;
                <?php echo $this->escape($this->actorAutocomplete, 'none'); ?>
            </div>
            <div style="position: relative; top 10px; left: 220px; margin-bottom: 20px; width: 150px;">&nbsp;
                <?php echo $this->escape($this->addActorButton, 'none'); ?>
            </div>
        </form>
    <?php
    endif;
    ?>
    <div id="actors">
        <table id="actorsTable">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <?php 
                    if ($this->updateIncidentPrivilege): 
                    ?>
                        <th>Remove</th>
                    <?php
                    endif;
                    ?>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->actors as $actor):
                ?>
                    <tr>
                        <td><?php echo $this->escape($actor['a_username']); ?></td>
                        <td><?php echo $this->escape($actor['a_nameFirst']); ?></td>
                        <td><?php echo $this->escape($actor['a_nameLast']); ?></td>
                        <?php 
                        if ($this->updateIncidentPrivilege): 
                            $removeLink  = '/incident/remove-user'
                                         . '/incidentId/' . $this->id
                                         . '/userId/' . $actor['a_id'];
                        ?>
                        <td><a href="<?php echo $this->escape($removeLink, 'none')?>">Remove</a></td>
                        <?php
                        endif;
                        ?>
                    </tr>                
                <?php
                endforeach;
                ?>
            </tbody>
        </table>
    </div>
    <?php
    Fisma_Format_Section::stopSection();
    ?>
</div>

<div class="column right">
    <?php
    Fisma_Format_Section::startSection("Observers");
    if ($this->updateIncidentPrivilege):
    ?>
    <form method="post" action="/incident/add-user/type/observer/id/<?php echo $this->escape($this->id); ?>">
        <input type="hidden" id="observerId" name="userId" value="">
        <div style="position: relative; top: 0px; width: 200px;">&nbsp;
            <?php echo $this->escape($this->observerAutocomplete, 'none'); ?>
        </div>
        <div style="position: relative; top 10px; left: 220px; margin-bottom: 20px; width: 150px;">&nbsp;
            <?php echo $this->escape($this->addObserverButton, 'none'); ?>
        </div>
    </form>
    <?php
    endif;
    ?>
    <div id="observers">
        <table id="observersTable">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <?php 
                    if ($this->updateIncidentPrivilege): 
                    ?>
                        <th>Remove</th>
                    <?php
                    endif;
                    ?>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->observers as $observer):
                ?>
                    <tr>
                        <td><?php echo $this->escape($observer['o_username']); ?></td>
                        <td><?php echo $this->escape($observer['o_nameFirst']); ?></td>
                        <td><?php echo $this->escape($observer['o_nameLast']); ?></td>
                        <?php 
                        if ($this->updateIncidentPrivilege): 
                            $removeLink = '/incident/remove-user'
                                        . '/incidentId/' . $this->id
                                        . '/userId/' . $observer['o_id'];
                        ?>
                             <td><a href="<?php echo $this->escape($removeLink, 'none')?>">Remove</a></td>
                        <?php
                        endif;
                        ?>
                    </tr>                
                <?php
                endforeach;
                ?>
            </tbody>
        </table>
    </div>
    <?php
    Fisma_Format_Section::stopSection();
    ?>    
</div>

<script type="text/javascript">
// Convert actors table to YUI table
YAHOO.util.Event.onContentReady('actors', function() {
    var myColumnDefs = [
        {key:'username', label:'Username', sortable:true},
        {key:'nameFirst', label:'First Name', sortable:true},
        {key:'nameLast', label:'Last Name', sortable:true}
<?php if ($this->updateIncidentPrivilege): ?>
        ,{key:'remove', label:'Remove', sortable:false}
<?php endif; ?>
    ];

    this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("actorsTable"));
    this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
    this.myDataSource.responseSchema = {
        fields: [
            {key:'username'},
            {key:'nameFirst'},
            {key:'nameLast'}
<?php if ($this->updateIncidentPrivilege): ?>
            ,{key: 'remove'}
<?php endif; ?>
        ]
    };

    this.myDataTable = new YAHOO.widget.DataTable("actors", myColumnDefs, this.myDataSource, {});
});

// Convert observers table to YUI table
YAHOO.util.Event.onContentReady('observers', function() {
    var myColumnDefs = [
        {key:'username', label:'Username', sortable:true},
        {key:'nameFirst', label:'First Name', sortable:true},
        {key:'nameLast', label:'Last Name', sortable:true}
        <?php if ($this->updateIncidentPrivilege): ?>
            ,{key:'remove', label:'Remove', sortable:false}
        <?php endif; ?>        
    ];

    this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("observersTable"));
    this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
    this.myDataSource.responseSchema = {
        fields: [
            {key:'username'},
            {key:'nameFirst'},
            {key:'nameLast'}
            <?php if ($this->updateIncidentPrivilege): ?>
                ,{key: 'remove'}
            <?php endif; ?>
        ]
    };

    this.myDataTable = new YAHOO.widget.DataTable("observers", myColumnDefs, this.myDataSource, {});
});

</script>
