<?php 
Fisma_Format_Section::startSection("Workflow Steps"); 

if ('closed' == $this->incident['status']):
?>
    <p>
        <b>
            This workflow has been completed and the incident is now officially closed.
        </b>
    </p>
<?php
endif;

foreach ($this->steps as $step):
    switch ($step['status']):
        case 'current':
            $class = 'currentIncidentStep';
            break;
        case 'completed':
            $class = 'completedIncidentStep';
            break;
        case 'queued':
            $class = 'queuedIncidentStep';
            break;
    endswitch;
?>
    <form method="post" action="/incident/complete-workflow-step/id/<?=$this->escape($this->id)?>">
        <input type="hidden" name="stepId" value="<?php ; ?>">
        <div class="incidentStep <?=$this->escape($class)?>">
            <div class="incidentCardinality">
                <?php echo $this->escape($step['cardinality'] + 1); ?>
            </div>
            <table>
                <tr>
                    <td>Step:</td>
                    <td><?=$this->escape($step['name']) ?></td>
                </tr>
                <tr>
                    <td>Status:</td>
                    <td><?=$this->escape(ucfirst($step['status']))?></td>
                </tr>
                <?php
                if (!is_null($step['userId'])):
                ?>
                    <tr>
                        <td>Completion Date:</td>
                        <td>
                            <?php echo $this->escape(empty($step['completeTs']) ? 'n/a' : $step['completeTs']); ?>
                        </td>
                    </tr>
                <?php
                endif;

                if (!is_null($step['userId'])):
                ?>
                    <tr>
                        <td>Completed By:</td>
                        <td><?=$this->escape($step['User']['username'])?></td>
                    </tr>
                <?php
                endif;

                if (isset($step['Role'])):
                ?>
                    <tr>
                        <td>Role Required:</td>
                        <td>
                            (<?=$this->escape($step['Role']['nickname'])?>) <?=$this->escape($step['Role']['name'])?>
                        </td>
                    </tr>
                <?php
                endif;

                if (!empty($step['description'])):
                ?>
                    <tr>
                        <td>Description:</td>
                        <td><?=$this->escape($step['description'], 'none') ?></td>
                    </tr>
                <?php
                endif;

                if (!empty($step['comments'])):
                ?>
                    <tr>
                        <td>Comments:</td>
                        <td><?=$this->escape(Fisma_String::textToHtml($step['comments']), 'none') ?></td>
                    </tr>
                <?php
                endif;

                if ('current' == $step['status'] && $this->updateIncidentPrivilege):
                ?>
                    <tr>
                        <td>*Comments:</td>
                        <td>
                            <textarea rows="8" cols="60" name="comment"></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>
                            <?php
                            $completeStepButton = new Fisma_Yui_Form_Button_Submit(
                                'completeStep', 
                                array('label' => 'Complete Step')
                            );
                            echo $this->escape($completeStepButton, 'none');
                            ?>
                        </td>
                    </tr>
                <?php
                endif;
                ?>            
            </table>
        </div>
    </form>
<?php 
endforeach;

Fisma_Format_Section::stopSection(); 
?>
