<div id="foo" style="width: 48%; float: left;">
<?php Fisma_Format_Section::startSection("Incident Information"); ?>

<div id="incidentData">Loading...</div>

<script type="text/javascript">
var viewDetailsButton;

var incidentCallback = {
        success: function(o) {
            document.getElementById('incidentData').innerHTML =  o.responseText;
            viewDetailsButton = new YAHOO.widget.Button({
                                       type: "submit",
                                       label: "Show Details",
                                       id: "viewDetailsButton",
                                       name: "viewDetailsButton",
                                       value: "View Details",
                                       container: "viewDetailsButtonContainer",
                                       disabled: false,
                                       onclick: { fn: onViewButtonClick }
                                   });
            var editDetailsButton = new YAHOO.widget.Button({
                                       type: "link",
                                       href: "/panel/incident/sub/edit/id/<?php print $this->id; ?>", 
                                       label: "Edit",
                                       id: "editDetailsButton",
                                       name: "editDetailsButton",
                                       value: "Edit",
                                       container: "editButtonContainer",
                                       disabled: false,
                                   });
        },
        failure: function(o) {
            alert("Error loading Incident Data");
        }
    } 

var transactionUrl = '/incident/incidentdata/id/<?php print $this->id; ?>';
var transaction = YAHOO.util.Connect.asyncRequest('GET', transactionUrl, incidentCallback, null);

function onViewButtonClick() {
    if ('block' == document.getElementById('incident_details').style.display) {
        document.getElementById('incident_details').style.display = 'none'; 
        viewDetailsButton.set('label', 'Show Details');
    } else {
        document.getElementById('incident_details').style.display = 'block'; 
        viewDetailsButton.set('label', 'Hide Details');
    }
    return false;
}
</script>

<?php Fisma_Format_Section::stopSection(); ?>
</div>

<div id="foo" style="width: 48%; float: right;">
<?php Fisma_Format_Section::startSection("Actors/Observers"); ?>

<div id="actors">Loading...</div>

<script type="text/javascript">

var callback = {
        success: function(o) {
            document.getElementById('actors').innerHTML =  o.responseText;
            actor_useridTooltip = new YAHOO.widget.Tooltip("actor_useridTooltipObj", 
                {
                    context:"actor_useridTooltip", 
                    showdelay: 150, 
                    hidedelay: 150, 
                    autodismissdelay: 25000, 
                    text: "<b>Actors</b> can add/remove users to/from an incident, \
                          complete workflow steps, and submit comments to an incident.",    
                    effect:
                        {
                            effect:YAHOO.widget.ContainerEffect.FADE,
                            duration:0.25
                        }, 
                    width: "50%"
                }
            );
            
            observer_useridTooltip = new YAHOO.widget.Tooltip("observer_useridTooltipObj", 
                {
                    context:"observer_useridTooltip", 
                    showdelay: 150, 
                    hidedelay: 150, 
                    autodismissdelay: 25000, 
                    text: "<b>Observers</b> can view an incident, and will be notified when \
                          the incident is updated.  They cannot perform any actions on the incident.",  
                    effect:
                        {
                            effect:YAHOO.widget.ContainerEffect.FADE,
                            duration:0.25
                        }, 
                    width: "50%"
                }
            );
            
            var actorButton = new YAHOO.widget.Button({
                                       type: "submit",
                                       label: "Add Actor",
                                       id: "actorButton",
                                       name: "actorButton",
                                       value: "Add Actor",
                                       container: "actorButtonContainer",
                                       disabled: false
                                       
                                   });
            var observerButton = new YAHOO.widget.Button({
                                       type: "submit",
                                       label: "Add Observer",
                                       id: "observerButton",
                                       name: "observerButton",
                                       value: "Add Observer",
                                       container: "observerButtonContainer",
                                       disabled: false
                                       
                                   });
        },
        failure: function(o) {
            alert("Error loading Actors/Observers");
        }
    } 

var transactionUrl = '/incident/actor/id/<?php print $this->id; ?>';
var transaction = YAHOO.util.Connect.asyncRequest('GET', transactionUrl, callback, null);

//this funciton will be called by onclick events defined in actors.phtml
function callAJAX(url) {
    var transaction = YAHOO.util.Connect.asyncRequest('GET', url, callback, null);
}

//this funciton will be called by submitting the add actor form defined in actors.phtml
function addActor() {
    var id = document.getElementById('actor_incident_id').value; 
    var userid = document.getElementById('actor_userid').value;
    
    var url = '/incident/actoradd/id/' + id  + '/userid/' + userid ;

    var transaction = YAHOO.util.Connect.asyncRequest('GET', url, callback, null);
}

//this funciton will be called by submitting the add observer form defined in actors.phtml
function addObserver() {
    var id = document.getElementById('observer_incident_id').value; 
    var userid = document.getElementById('observer_userid').value;
    
    var url = '/incident/observeradd/id/' + id  + '/userid/' + userid ;

    var transaction = YAHOO.util.Connect.asyncRequest('GET', url, callback, null);
}

</script>

<?php Fisma_Format_Section::stopSection(); ?>
</div>

<div class="clear"></div>

<?php Fisma_Format_Section::startSection("Incident Workflow"); ?>

<div id="workflow-interface">Loading...</div>

<script type="text/javascript">
    var wfCallback = {
            success: function(o) {
                if(o.responseText == 'redirect') {
                    window.location = '/panel/incident/sub/view/id/<?php print $this->id; ?>';
                } else {
                    document.getElementById('workflow-interface').innerHTML =  o.responseText;
                
                    var myTabs = new YAHOO.widget.TabView("workflow-interface-content");
                
                    loadEditor();
                }
            },
            failure: function(o) {
                alert("Error loading Workflow Interface");
            }
        } 

    var transactionUrl = '/incident/workflow/id/<?php print $this->id; ?>';
    var transaction = YAHOO.util.Connect.asyncRequest('GET', transactionUrl, wfCallback, null);
    
    function completestep() {
        var formObject = document.getElementById('stepForm');

        YAHOO.util.Connect.setForm(formObject);

        var transaction = YAHOO.util.Connect.asyncRequest('POST', '/incident/completestep', wfCallback, null);
    }

    function loadEditor() {
        return;
        tinyMCE.init({
            theme : "advanced",
            mode : "textareas",
            cleanup : false,
            element_format : "html",
            plugins : "spellchecker, searchreplace, insertdatetime, print, fullscreen",
            plugin_insertdate_dateFormat : "%Y-%m-%d",
            plugin_insertdate_timeFormat : "%H:%M:%S",
            browsers : "msie,gecko,safari,opera",
            theme_advanced_buttons1 : "bold, italic, underline, |, bullist, numlist, |, outdent, indent, |, \
                                      cut, copy, paste, |, undo, redo, |, spellchecker, |, search, replace, |, \
                                      insertdate, inserttime, link, unlink, |, print, fullscreen",
            theme_advanced_buttons2 : "",
            theme_advanced_buttons3 : "",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_statusbar_location : "bottom",
            theme_advanced_resizing : true,
            spellchecker_languages : "+English=en"
        });
    }
</script>

<?php Fisma_Format_Section::stopSection(); ?>

<?php Fisma_Format_Section::startSection("Comments"); ?>

<div id="comment-container">Loading...</div>

<script type="text/javascript">
    var comCallback = {
        success: function(o) {
            document.getElementById('comment-container').innerHTML =  o.responseText;
            var commentButton = new YAHOO.widget.Button({
                                       type: "submit",
                                       label: "Add Comment",
                                       id: "commentButton",
                                       name: "commentButton",
                                       value: "Add Comment",
                                       container: "commentButtonContainer",
                                       disabled: false
                                       
                                   });
        },
        failure: function(o) {
            alert("Error loading Comments");
        }
    } 
    
    var transactionUrl = '/incident/comments/id/<?php print $this->id; ?>';
    var transaction = YAHOO.util.Connect.asyncRequest('GET', transactionUrl, comCallback, null);

    function addcomment() {
        var formObject = document.getElementById('commentForm');

        YAHOO.util.Connect.setForm(formObject);

        var transaction = YAHOO.util.Connect.asyncRequest('POST', '/incident/addcomment', comCallback, null);
    }

</script>
<?php Fisma_Format_Section::stopSection(); ?>
