<div id="foo" style="width: 48%; float: left;">
<?php Fisma_Format_Section::startSection("Incident Information"); ?>

<table class="fisma_crud">
    <tr>
        <td colspan="3" style="text-align: left"><h1>Incident Information:</h1></td>
    </tr>
    
    <?php foreach($this->incident[0] as $key => $val) { if($val != '') { print "<tr><td>".ucfirst(preg_replace('/([A-Z])/', ' $1', $key)).":</td><td>$val</td></tr>";} } ?>
    
    <tr><td>&nbsp;</td><td><a href="#">View Details</a></td></tr>
</table>

<?php Fisma_Format_Section::stopSection(); ?>
</div>

<div id="foo" style="width: 48%; float: right;">
<?php Fisma_Format_Section::startSection("Actors/Observers"); ?>

<div id="actors">Loading...</div>

<script type="text/javascript">

var callback = {
        success: function(o) {
            document.getElementById('actors').innerHTML =  o.responseText;
        },
        failure: function(o) {
            alert("Error loading Actors/Observers");
        }
    } 

var transaction = YAHOO.util.Connect.asyncRequest('GET', '/incident/actor/id/<?php print $this->id; ?>', callback, null);

//this funciton will be called by onclick events defined in actors.phtml
function callAJAX(url) {
    var transaction = YAHOO.util.Connect.asyncRequest('GET', url, callback, null);
}

//this funciton will be called by submitting the add actor form defined in actors.phtml
function addActor() {
    var id = document.getElementById('actor_incident_id').value; 
    var userid = document.getElementById('actor_userid').value;
    
    var url = '/incident/actoradd/id/' + id  + '/userid/' + userid ;

    var transaction = YAHOO.util.Connect.asyncRequest('GET', url, callback, null);
}

//this funciton will be called by submitting the add observer form defined in actors.phtml
function addObserver() {
    var id = document.getElementById('observer_incident_id').value; 
    var userid = document.getElementById('observer_userid').value;
    
    var url = '/incident/observeradd/id/' + id  + '/userid/' + userid ;

    var transaction = YAHOO.util.Connect.asyncRequest('GET', url, callback, null);
}

</script>

<?php Fisma_Format_Section::stopSection(); ?>
</div>

<div class="clear"></div>

<?php Fisma_Format_Section::startSection("Incident Workflow"); ?>

<div id="workflow-interface">Loading...</div>

<script type="text/javascript">
    var wfCallback = {
            success: function(o) {
                if(o.responseText == 'redirect') {
                    window.location = '/panel/incident/sub/view/id/<?php print $this->id; ?>';
                } else {
                    document.getElementById('workflow-interface').innerHTML =  o.responseText;
                
                    var myTabs = new YAHOO.widget.TabView("workflow-interface-content");
                
                    loadEditor();
                }
            },
            failure: function(o) {
                alert("Error loading Workflow Interface");
            }
        } 

    var transaction = YAHOO.util.Connect.asyncRequest('GET', '/incident/workflow/id/<?php print $this->id; ?>', wfCallback, null);
    
    function completestep() {
        var formObject = document.getElementById('stepForm');

        YAHOO.util.Connect.setForm(formObject);

        var transaction = YAHOO.util.Connect.asyncRequest('POST', '/incident/completestep', wfCallback, null);
    }

    function loadEditor() {
        return;
        tinyMCE.init({
            theme : "advanced",
            mode : "textareas",
            cleanup : false,
            element_format : "html",
            plugins : "spellchecker, searchreplace, insertdatetime, print, fullscreen",
            plugin_insertdate_dateFormat : "%Y-%m-%d",
            plugin_insertdate_timeFormat : "%H:%M:%S",
            browsers : "msie,gecko,safari,opera",
            theme_advanced_buttons1 : "bold, italic, underline, |, bullist, numlist, |, outdent, indent, |, cut, copy, paste, |, undo, redo, |, spellchecker, |, search, replace, |, insertdate, inserttime, link, unlink, |, print, fullscreen",
            theme_advanced_buttons2 : "",
            theme_advanced_buttons3 : "",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_statusbar_location : "bottom",
            theme_advanced_resizing : true,
            spellchecker_languages : "+English=en"
        });
    }
</script>

<?php Fisma_Format_Section::stopSection(); ?>

<?php Fisma_Format_Section::startSection("Comments"); ?>

<div id="comment-container">Loading...</div>

<script type="text/javascript">
    var comCallback = {
        success: function(o) {
            document.getElementById('comment-container').innerHTML =  o.responseText;
        },
        failure: function(o) {
            alert("Error loading Comments");
        }
    } 
    
    var transaction = YAHOO.util.Connect.asyncRequest('GET', '/incident/comments/id/<?php print $this->id; ?>', comCallback, null);

    function addcomment() {
        var formObject = document.getElementById('commentForm');

        YAHOO.util.Connect.setForm(formObject);

        var transaction = YAHOO.util.Connect.asyncRequest('POST', '/incident/addcomment', comCallback, null);
    }

</script>
<?php Fisma_Format_Section::stopSection(); ?>
