<?php 
if ($this->stepCompletedSort):
?>
    <div id="msgbar" 
         style="border-color: green; font-weight: bold; color: green; background-color: lightgreen; display: block;">
        Workflow Step #<?php print $this->stepCompletedSort; ?> has been completed.
    </div>
    <br />
<?php 
endif; 
?>

<div id="workflow-interface-content" class="yui-navset">
    <ul class="yui-nav">
        <?php
        foreach ($this->steps as $key => $step):
            if ($key == 0):
                print "<li><a href='#tab$key'><em>Open Incident</em></a></li>";        
            elseif (($this->stepCompletedSort) and ($key == $this->stepCompletedSort)):
                print "<li class='selected'><a href='#tab$key'><em>Step #$key</em></a></li>";        
            elseif (!($this->stepCompletedSort) && ($step['iw_status'] == 'current')):
                print "<li class='selected'><a href='#tab$key'><em>Step #$key</em></a></li>";        
            elseif ($key < (count($this->steps) - 1)):
                print "<li><a href='#tab$key'><em>Step #$key</em></a></li>";        
            endif;
        endforeach;
        ?>
    </ul>            
    <div class="yui-content">
        <?php
        foreach ($this->steps as $key => $step):
            if ($key == 0):
                print " <table class='fisma_crud'>
                            <tr>
                                <td>Incident Opened By:</td>
                                <td><h2>{$step['u_nameFirst']} {$step['u_nameLast']}</h2></td>
                            </tr>    
                            <tr>
                                <td><br />Incident Opened:</td>
                                <td><br /><h2>{$step['iw_completeTs']}</h2></td>
                            </tr>    
                            <tr>
                                <td><br />Comments:</td>
                                <td><br /><h2>{$step['iw_comments']}</h2></td>
                            </tr>    
                        </table>";
            elseif ($key < (count($this->steps) -1)):
                print " <table class='fisma_crud'> 
                            <tr>
                                <td>Workflow Step:</td>
                                <td><h2>{$step['iw_name']}</h2></td>
                            </tr>";
                                            
                if ($step['iw_description']):
                    print " <tr>
                                <td nowrap valign='top'><br />Workflow Description:</td>
                                <td><br /><h2>{$step['iw_description']}</h2></td>
                            </tr>";
                endif;

                if ($step['iw_status'] == 'current'):
                    $currentStep = $key;
                    if (is_null($step['iw_roleId'])
                        || ($this->userRoleId == $step['iw_roleId']) && ($this->association == 'actor')):
                    print " <tr>
                                <td colspan='2' style='text-align: left;'>
                                        <br />Comments: <br />
                                        <form action='#' onsubmit='completestep(); return false;' id='stepForm'>
                                            <input type='hidden' name='id' id='id' value='{$this->id}' />
                                            <input type='hidden' name='step_id' id='step_id' value='{$step['iw_id']}' />
                                            <textarea name='comments' id='comments' rows='10' cols='60'></textarea>
                                            <br /><br />
                                            <input type='submit' value='Complete Step' />
                                        </form>
                                </td>
                            </tr>";
                    else:
                        print " <tr>
                                    <td nowrap valign='top'><br />Step must be completed by:</td>
                                    <td><br /><h2>{$step['r_nickname']}</h2></td>
                                </tr>";
                    endif;
                endif;
                
                if ($step['iw_status'] == 'completed'):
                    print " <tr>
                                <td><br />Completed By:</td>
                                <td><br /><h2>{$step['u_nameFirst']} {$step['u_nameLast']}</h2></td>
                            </tr>
                            <tr>
                                <td><br />Completed On:</td>
                                <td><br /><h2>{$step['iw_completeTs']}</h2></td>
                            </tr>
                            <tr>
                                <td><br />Comments:</td>
                                <td><br /><h2>{$step['iw_comments']}</h2></td>
                            </tr> ";

                endif;

                if ($step['iw_status'] == 'queued'):
                    print " <tr>
                                <td><br />NOTE:</td>
                                <td><br /><h2> Step #$currentStep must be completed next.</h2></td>
                            </tr>";
                endif;

                print "</table>";
            endif;
        endforeach;
    ?>
    </div>
</div>
