<?php

echo $this->escape($this->searchBox($this->toolbarButtons, $this->searchForm), 'none');

Fisma_Format_Section::startSection("Points Of Contact: Hierarchy View"); 

?>

<p>
    Only POCs can be moved around on this screen. If you want to move around organizations or information systems,
    you will need to do that in the organization hierarchy.
</p>

<p>
    <button type="button" id="expandAllButton">Expand All</button>
    <button type="button" id="collapseAllButton">Collapse All</button>
</p>

<div id="pocTreeContainer" class="draggableTreeContainer"></div>

<script type="text/javascript">
YAHOO.util.Event.onDOMReady(
    function () {
        var treeView = new Fisma.PocTreeView("pocTreeContainer");
        treeView.render();
        
        var expandAllButton = new YAHOO.widget.Button("expandAllButton");
        expandAllButton.on("click", treeView.expandAll, treeView, true);

        var collapseAllButton = new YAHOO.widget.Button("collapseAllButton");
        collapseAllButton.on("click", treeView.collapseAll, treeView, true);
    }
);
</script>

<?php Fisma_Format_Section::stopSection(); ?>
