<?php Fisma_Format_Section::startSection("Incidents By Category"); ?>

<table class="ir_report">
    <tr>
        <th colspan="2" style="border-left: 0px;">&nbsp;</th>
        <th colspan="3">Open Incidents</th>
        <th colspan="3">Resolved Incidents</th>
        <th colspan="3">Closed Incidents</th>
    </tr>
    <tr>
        <th colspan="2" style="border-left: 0px;">&nbsp;</th>
        <th>Week</th>
        <th>Month</th>
        <th>Year</th>
        <th>Week</th>
        <th>Month</th>
        <th>Year</th>
        <th>Week</th>
        <th>Month</th>
        <th>Year</th>
    </tr>

<?php
foreach ($this->cats as $id => $cat ) {
    foreach ($cat['children'] as $key => $subcat) {
        print "<tr><th style='text-align:right; border-left: 0px;'>{$cat['category']}</th><th style='text-align:left;'>{$subcat['name']}</th>";

        print "<td>";
        if( $this->incident_current['week'][$cat['category']][$subcat['id']]['open'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".$this->weeks[date('W')]['start']."/end_date/".$this->weeks[date('W')]['end']."/status/open/category/{$subcat['id']}'>{$this->incident_current['week'][$cat['category']][$subcat['id']]['open']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['month'][$cat['category']][$subcat['id']]['open'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".date('Y')."-".date('m')."-01/end_date/".date('Y')."-".date('m')."-".date('t')."/status/open/category/{$subcat['id']}'>{$this->incident_current['month'][$cat['category']][$subcat['id']]['open']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['year'][$cat['category']][$subcat['id']]['open'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".date('Y')."-01-01/end_date/".date('Y')."-12-31/status/open/category/{$subcat['id']}'>{$this->incident_current['year'][$cat['category']][$subcat['id']]['open']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['week'][$cat['category']][$subcat['id']]['resolved'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".$this->weeks[date('W')]['start']."/end_date/".$this->weeks[date('W')]['end']."/status/resolved/category/{$subcat['id']}'>{$this->incident_current['week'][$cat['category']][$subcat['id']]['resolved']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['month'][$cat['category']][$subcat['id']]['resolved'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".date('Y')."-".date('m')."-01/end_date/".date('Y')."-".date('m')."-".date('t')."/status/resolved/category/{$subcat['id']}'>{$this->incident_current['month'][$cat['category']][$subcat['id']]['resolved']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['year'][$cat['category']][$subcat['id']]['resolved'] == '0') {
            print "0";
        } else {
            print "<a href='panel/irreport/sub/report/start_date/".date('Y')."-01-01/end_date/".date('Y')."-12-31/status/resolved/category/{$subcat['id']}'>{$this->incident_current['year'][$cat['category']][$subcat['id']]['resolved']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['week'][$cat['category']][$subcat['id']]['closed'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".$this->weeks[date('W')]['start']."/end_date/".$this->weeks[date('W')]['end']."/status/closed/category/{$subcat['id']}'>{$this->incident_current['week'][$cat['category']][$subcat['id']]['closed']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['month'][$cat['category']][$subcat['id']]['closed'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".date('Y')."-".date('m')."-01/end_date/".date('Y')."-".date('m')."-".date('t')."/status/closed/category/{$subcat['id']}'>{$this->incident_current['month'][$cat['category']][$subcat['id']]['closed']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['year'][$cat['category']][$subcat['id']]['closed'] == '0') {
            print "0";
        } else {
            print "<a href='panel/irreport/sub/report/start_date/".date('Y')."-01-01/end_date/".date('Y')."-12-31/status/closed/category/{$subcat['id']}'>{$this->incident_current['year'][$cat['category']][$subcat['id']]['closed']}</a>";
        }
        print "</td>";
        
        print "</tr>";
    }
}

?>
</table>
<?php Fisma_Format_Section::stopSection(); ?>
