<?php if (count($this->messages)): ?>
<script type="text/javascript">
<?php foreach ($this->messages as $severity=>$messages):
        if (count($messages)) :
            foreach ($messages as $message) :
                $message = addslashes($message); ?>
    message('<?php echo $message; ?>', '<?php echo $severity; ?>');
<?php       endforeach;
        endif;
    endforeach;?>
</script>
<?php endif; ?>
