<?php
Fisma_Format_Section::startSection("Incident Report Canceled");
?>

<h1>The incident report has been canceled</h1>

<p>
    <?php
    $continueButton = new Fisma_Yui_Form_Button_Link('returnToHome',
                              array('value' => 'Continue',
                                    'href' => "/index/home",
                                    'imageSrc' => '/images/right_arrow.png'));
    echo $this->escape($continueButton, 'none');
    ?>
</p>

<?php
Fisma_Format_Section::stopSection();
?>
