<?php Fisma_Format_Section::startSection("Incident Information"); ?>
<div id="incidentData">Loading...</div>

<script type="text/javascript">
var viewDetailsButton;

var incidentCallback = {
        success: function(o) {
            document.getElementById('incidentData').innerHTML =  o.responseText;
            viewDetailsButton = new YAHOO.widget.Button({
                                       type: "submit",
                                       label: "Show Details",
                                       id: "viewDetailsButton",
                                       name: "viewDetailsButton",
                                       value: "View Details",
                                       container: "viewDetailsButtonContainer",
                                       disabled: false,
                                       onclick: { fn: onViewButtonClick }
                                   });
            var editDetailsButton = new YAHOO.widget.Button({
                                       type: "link",
                                       href: "/incident/edit/id/<?php echo $this->escape($this->id)?>", 
                                       label: "Edit",
                                       id: "editDetailsButton",
                                       name: "editDetailsButton",
                                       value: "Edit",
                                       container: "editButtonContainer",
                                       disabled: false,
                                   });
        },
        failure: function(o) {
            Fisma.Util.showAlertDialog('Error loading Incident Data');
        }
    } 

var transactionUrl = '/incident/incidentdata/id/<?php echo $this->escape($this->id); ?>';
var transaction = YAHOO.util.Connect.asyncRequest('GET', transactionUrl, incidentCallback, null);

function onViewButtonClick() {
    if ('block' == document.getElementById('incident_details').style.display) {
        document.getElementById('incident_details').style.display = 'none'; 
        viewDetailsButton.set('label', 'Show Details');
    } else {
        document.getElementById('incident_details').style.display = 'block'; 
        viewDetailsButton.set('label', 'Hide Details');
    }
    return false;
}
</script>
<?php Fisma_Format_Section::stopSection(); ?>

<?php Fisma_Format_Section::startSection("Close Incident"); ?>

<?php echo $this->escape($this->form, 'none'); ?>

<?php Fisma_Format_Section::stopSection(); ?>

<?php Fisma_Format_Section::startSection("Incident History"); ?>

<?php 
foreach ($this->steps as $key => $step):
?>
    <table width='50%' class='fisma_crud' style='margin-bottom: 10px;'>
        <tr>
            <td width='15%'>Workflow Step:</td>
            <td width='35%'><h2><?php echo $this->escape($step['name'])?></h2></td>
        </tr>
        <tr>
            <td>Completed By:</td>
    <?php if ('completed' == $step['status']): ?>
            <td>
                <?php echo $this->escape($step['user']['nameFirst'])?>
                <?php echo $this->escape($step['user']['nameLast'])?>
                (<?php echo $this->escape($step['user']['username'])?>)
            </td>
        </tr>
        <tr>
            <td>Completed On:</td>
            <td><?php echo $this->escape($step['completeTs'])?></td>
        </tr>
        <tr>
            <td>Comments:</td>
            <td><?php echo $this->escape($step['comments'])?></td>
    <?php else: ?>
            <td>&lt;not completed&gt;</td>
    <?php endif; ?>
        </tr>
    </table>
<?php
endforeach;
?>  

</table>
<?php Fisma_Format_Section::stopSection(); ?>
