<?php $this->table = Doctrine::getTable('Incident'); ?>
<div class="column66 left">
    <?php Fisma_Format_Section::startSection('Summary'); ?>
        <table class="keyValues">
            <tr>
                <th scope='row'><?php $this->column('status'); ?>:</th>
                <td><?php echo $this->escape($this->incident['status']); ?></td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('categoryId'); ?>:</th>
                <td>
                    <span name="incident[categoryId]"
                         id="categoryId"
                         type="select"
                         href="/metainfo/list/o/incidentCategories/format/html/optional/true/"
                         target="categoryId"
                         value="<?php echo $this->escape($this->incident['categoryId']); ?>"
                         <?php if ($this->updateIncidentPrivilege): ?>
                            class="editable"
                         <?php endif; ?>>
                        <?php if (!empty($this->incident['Category'])): ?>
                            <?php echo $this->escape($this->incident['Category']['Category']['category']); ?>:
                            <?php echo $this->escape($this->incident['Category']['Category']['name']); ?>
                            &#9658;
                            <?php echo $this->escape($this->incident['Category']['name']); ?>
                        <?php else: ?>
                            &nbsp;
                        <?php endif; ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('severityLevel'); ?>:</th>
                <td>
                    <span id="severityLevel"
                        <?php if ($this->updateIncidentPrivilege): ?>
                          name="incident[severityLevel]"
                          type="select"
                          href="/incident-severity-level/options/format/html/"
                          target="severityLevel"
                          class="editable"
                         <?php endif; ?>>
                        <?php if (!empty($this->incident['severityLevel'])): ?>
                            <?php echo $this->escape($this->incident['severityLevel']); ?>
                        <?php else: ?>
                            &nbsp;
                        <?php endif; ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('organizationId'); ?>:</th>
                <td>
                    <span id="organization"
                          type="select"
                          name="incident[organizationId]"
                          target="organization"
                          affected="parentOrganization"
                          href="/metainfo/list/o/organization/format/html/optional/true/">
                        <?php if (isset($this->incident['Organization'])): ?>
                            <?php
                                echo $this->escape(
                                    $this->organizationInfo(
                                        $this->incident['Organization']['nickname']
                                            . " - "
                                            . $this->incident['Organization']['name'],
                                        $this->incident['Organization']['id']
                                    ),
                                    'none'
                                );
                            ?>
                        <?php endif; ?>
                    </span>
                        <span class="editable" target="organization">&nbsp;</span>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('denormalizedParentOrganizationId'); ?>:</th>
                <td>
                    <span id="parentOrganization">
                        <?php if (isset($this->incident['ParentOrganization'])): ?>
                            <?php
                                echo $this->escape(
                                    $this->organizationInfo(
                                        $this->incident['ParentOrganization']['nickname']
                                            . " - "
                                            . $this->incident['ParentOrganization']['name'],
                                        $this->incident['ParentOrganization']['id']
                                    ),
                                    'none'
                                );
                            ?>
                        <?php else: ?>
                            &nbsp;
                        <?php endif; ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('source'); ?>:</th>
                <td>
                    <span id="source"
                        <?php if ($this->updateIncidentPrivilege): ?>
                          name="incident[source]"
                          type="select"
                          href="/incident-source/options/format/html/"
                          target="source"
                          class="editable"
                         <?php endif; ?>>
                        <?php if (!empty($this->incident['source'])): ?>
                            <?php echo $this->escape($this->incident['source']); ?>
                        <?php else: ?>
                            &nbsp;
                        <?php endif; ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('impact'); ?>:</th>
                <td>
                    <span id="impact"
                        <?php if ($this->updateIncidentPrivilege): ?>
                          name="incident[impact]"
                          type="select"
                          href="/incident-impact/options/format/html/"
                          target="impact"
                          class="editable"
                         <?php endif; ?>>
                        <?php if (!empty($this->incident['impact'])): ?>
                            <?php echo $this->escape($this->incident['impact']); ?>
                        <?php else: ?>
                            &nbsp;
                        <?php endif; ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('denormalizedResponseStrategies'); ?>:</th>
                <td>
                    <span id="responseStrategies"
                        <?php if ($this->updateIncidentPrivilege): ?>
                          name="incident[responseStrategies]"
                          type="multiselect"
                          value="<?php echo $this->escape(
                                    $this->escape($this->incident['responseStrategies'], 'json')
                                ); ?>"
                          json="/incident-response-strategy/options/format/json/"
                          target="responseStrategies"
                          class="editable"
                         <?php endif; ?>>
                        <?php if (!empty($this->incident['responseStrategies'])): ?>
                            <?php echo $this->escape($this->incident['denormalizedResponseStrategies']); ?>
                        <?php else: ?>
                            &nbsp;
                        <?php endif; ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('piiInvolved'); ?>:</th>
                <td>
                    <div name="incident[piiInvolved]"
                         id="piiInvolved"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="select"
                             href="/metainfo/list/o/yesNo/format/html/"
                             target="piiInvolved"
                         <?php
                         endif;
                         ?>>
                        <?php echo $this->escape($this->incident['piiInvolved']); ?>&nbsp;
                    </div>
                </td>
            </tr>
        </table>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php if ($this->updateIncidentPrivilege):
        Fisma_Format_Section::startSection($this->column('additionalInfo', null, false), 'additionalInfo');
    else:
        Fisma_Format_Section::startSection($this->column('additionalInfo', null, false));
    endif;
    ?>
        <div name="incident[additionalInfo]" id="additionalInfo" type="textarea">
            <?php echo $this->escape($this->incident['additionalInfo'], 'none'); ?>
        </div>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php if ($this->updateIncidentPrivilege):
        Fisma_Format_Section::startSection($this->column('actionsTaken', null, false), 'actionsTaken');
    else:
        Fisma_Format_Section::startSection($this->column('actionsTaken', null, false));
    endif;
    ?>
        <div name="incident[actionsTaken]" id="actionsTaken" type="textarea">
            <?php echo $this->escape($this->incident['actionsTaken'], 'none'); ?>
        </div>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php Fisma_Format_Section::startSection('Attacker Details'); ?>
        <table class="keyValues">
            <tr>
                <th scope='row'><?php $this->column('sourceIp'); ?></th>
                <td>
                    <div name="incident[sourceIp]"
                         id="sourceIp"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="text"
                             target="sourceIp"
                         <?php
                         endif;
                         ?>>
                        <?php echo $this->escape($this->incident['sourceIp']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('sourceAdditional'); ?></th>
                <td>
                    <div name="incident[sourceAdditional]"
                         id="sourceAdditional"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="textarea"
                             target="sourceAdditional"
                         <?php
                         endif;
                         ?>>
                        <?php echo $this->escape($this->incident['sourceAdditional'], 'none'); ?>&nbsp;
                    </div>
                </td>
            </tr>
        </table>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php Fisma_Format_Section::startSection('Personally Identifiable Information'); ?>
        <table class="keyValues">
        <?php if ('YES' != $this->incident['piiInvolved']): ?>
            <tr><td colspan="2">No PII reported in this incident.</td></tr>
        <?php else: ?>
            <tr>
                <th scope='row'><?php $this->column('piiAdditional'); ?>:</th>
                <td>
                    <div name="incident[piiAdditional]"
                         id="piiAdditional"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="textarea"
                             target="piiAdditional"
                         <?php
                         endif;
                         ?>>
                         <?php echo $this->escape($this->incident['piiAdditional'], 'none'); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('piiMobileMedia'); ?>:</th>
                <td>
                    <div name="incident[piiMobileMedia]"
                         id="piiMobileMedia"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="select"
                             href="/metainfo/list/o/yesNo/format/html/optional/true/"
                             target="piiMobileMedia"
                         <?php
                         endif;
                         ?>>
                         <?php echo $this->escape($this->incident['piiMobileMedia']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('piiMobileMediaType'); ?>:</th>
                <td>
                    <div name="incident[piiMobileMediaType]"
                         id="piiMobileMediaType"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="select"
                             href="/metadata/enum/model/Incident/field/piiMobileMediaType/"
                             target="piiMobileMediaType"
                         <?php
                         endif;
                         ?>>
                        <?php echo $this->escape($this->incident['piiMobileMediaType']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('piiEncrypted'); ?>:</th>
                <td>
                    <div name="incident[piiEncrypted]"
                         id="piiEncrypted"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="select"
                             href="/metainfo/list/o/yesNo/format/html/optional/true/"
                             target="piiEncrypted"
                         <?php
                         endif;
                         ?>>
                         <?php echo $this->escape($this->incident['piiEncrypted']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('piiAuthoritiesContacted'); ?>:</th>
                <td>
                    <div name="incident[piiAuthoritiesContacted]"
                         id="piiAuthoritiesContacted"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="select"
                             href="/metainfo/list/o/yesNo/format/html/optional/true/"
                             target="piiAuthoritiesContacted"
                         <?php
                         endif;
                         ?>>
                         <?php echo $this->escape($this->incident['piiAuthoritiesContacted']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('piiPoliceReport'); ?>:</th>
                <td>
                    <div name="incident[piiPoliceReport]"
                         id="piiPoliceReport"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="select"
                             href="/metainfo/list/o/yesNo/format/html/optional/true/"
                             target="piiPoliceReport"
                         <?php
                         endif;
                         ?>>
                         <?php echo $this->escape($this->incident['piiPoliceReport']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('piiIndividualsCount'); ?>:</th>
                <td>
                    <div name="incident[piiIndividualsCount]"
                         id="piiIndividualsCount"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="text"
                             target="piiIndividualsCount"
                         <?php
                         endif;
                         ?>>
                        <?php echo $this->escape($this->incident['piiIndividualsCount']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('piiIndividualsNotified'); ?>:</th>
                <td>
                    <div name="incident[piiIndividualsNotified]"
                         id="piiIndividualsNotified"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="select"
                             href="/metainfo/list/o/yesNo/format/html/optional/true/"
                             target="piiIndividualsNotified"
                         <?php
                         endif;
                         ?>>
                         <?php echo $this->escape($this->incident['piiIndividualsNotified']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('piiShipment'); ?>:</th>
                <td>
                    <div name="incident[piiShipment]"
                         id="piiShipment"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="select"
                             href="/metainfo/list/o/yesNo/format/html/optional/true/"
                             target="piiShipment"
                         <?php
                         endif;
                         ?>>
                         <?php echo $this->escape($this->incident['piiShipment']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('piiShipmentSenderCompany'); ?>:</th>
                <td>
                    <div name="incident[piiShipmentSenderCompany]"
                         id="piiShipmentSenderCompany"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="text"
                             target="piiShipmentSenderCompany"
                         <?php
                         endif;
                         ?>>
                        <?php echo $this->escape($this->incident['piiShipmentSenderCompany']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('piiShipmentSenderContacted'); ?>:</th>
                <td>
                    <div name="incident[piiShipmentSenderContacted]"
                         id="piiShipmentSenderContacted"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="select"
                             href="/metainfo/list/o/yesNo/format/html/optional/true/"
                             target="piiShipmentSenderContacted"
                         <?php
                         endif;
                         ?>>
                         <?php echo $this->escape($this->incident['piiShipmentSenderContacted']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('piiShipmentTimeline'); ?>:</th>
                <td>
                    <div name="incident[piiShipmentTimeline]"
                         id="piiShipmentTimeline"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="textarea"
                             target="piiShipmentTimeline"
                         <?php
                         endif;
                         ?>>
                        <?php echo $this->escape($this->incident['piiShipmentTimeline'], 'none'); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('piiShipmentTrackingNumbers'); ?>:</th>
                <td>
                    <div name="incident[piiShipmentTrackingNumbers]"
                         id="piiShipmentTrackingNumbers"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="textarea"
                             target="piiShipmentTrackingNumbers"
                         <?php
                         endif;
                         ?>>
                        <?php echo $this->escape($this->incident['piiShipmentTrackingNumbers'], 'none'); ?>&nbsp;
                    </div>
                </td>
            </tr>
        <?php endif; ?>
        </table>
    <?php Fisma_Format_Section::stopSection(); ?>
</div>

<div class="column33 right">
    <?php Fisma_Format_Section::startSection('Dates'); ?>
        <table class="keyValues">
            <tr>
                <th scope='row'><?php $this->column('incidentDate'); ?>:</th>
                <td title='UTC: <?php echo $this->escape($this->incidentDateTime); ?>'>
                    <span id="occurred"
                        <?php if ($this->updateIncidentPrivilege): ?>
                          name="incident[incidentDateTime]"
                          type="text"
                          target="occurred"
                          class="editable"
                         <?php endif; ?>>
                        <?php echo $this->escape($this->incidentDateTimeLocal); ?>
                    </span>

                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('reportTs'); ?>:</th>
                <td title='UTC: <?php echo $this->escape($this->createDateTime); ?>'>
                    <?php echo $this->escape($this->createdDateTimeLocal); ?>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('modifiedTs'); ?>:</th>
                <td title='UTC: <?php echo $this->escape($this->updateTs); ?>'>
                    <?php echo $this->escape($this->updateTsLocal); ?>
                </td>
            </tr>
            <?php if (!empty($this->incident['closedTs'])): ?><tr>
                <th scope='row'><?php $this->column('closedTs'); ?>:</th>
                <td title='UTC: <?php echo $this->escape($this->closedTs); ?>'>
                    <?php echo $this->escape($this->closedTsLocal); ?>
                </td>
            </tr><?php endif; ?>
        </table>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php Fisma_Format_Section::startSection('People'); ?>
        <table class="keyValues">
            <tr>
                <th scope='row'><Reporter:</th>
                <td><span id="reportingUser"
                    type="autocomplete"
                    xhr="/user/autocomplete/format/json"
                    queryPrepend="/keyword/"
                    schemaObject="pointsOfContact"
                    schemaField="name"
                    name="incident[reportingUserId]"
                <?php if ($this->acl()->hasPrivilegeForClass('create', 'User')): ?>
                    setupCallback="Fisma.Finding.setupPocAutocomplete"
                <?php endif; ?>
                    value="<?php echo $this->escape($this->incident['reportingUserId']); ?>"
                    defaultValue="<?php echo $this->escape($this->incident['ReportingUser']['displayName']); ?>"><?php
                        if (!empty($this->incident['reportingUserId'])) {
                            echo $this->escape(
                                $this->userInfo(
                                    $this->incident['ReportingUser']['displayName'],
                                    $this->incident['ReportingUser']['id']
                                ),
                                'none'
                            );
                        }
                    ?></span>
                <?php if ($this->updateIncidentPrivilege): ?>
                    <span class="editable" target="reportingUser">&nbsp;</span>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <th scope='row'><?php $this->column('pocId'); ?>:</th>
                <td><span id="pointOfContact"
                    type="autocomplete"
                    xhr="/user/autocomplete/format/json"
                    queryPrepend="/keyword/"
                    schemaObject="pointsOfContact"
                    schemaField="name"
                    name="incident[pocId]"
                <?php if ($this->acl()->hasPrivilegeForClass('create', 'User')): ?>
                    setupCallback="Fisma.Finding.setupPocAutocomplete"
                <?php endif; ?>
                    value="<?php echo $this->escape($this->incident['pocId']); ?>"
                    defaultValue="<?php echo $this->escape($this->incident['PointOfContact']['displayName']); ?>"><?php
                        if (!empty($this->incident['pocId'])) {
                            echo $this->escape(
                                $this->userInfo(
                                    $this->incident['PointOfContact']['displayName'],
                                    $this->incident['PointOfContact']['id']
                                ),
                                'none'
                            );
                        }
                    ?></span>
                <?php if ($this->updateIncidentPrivilege): ?>
                    <span class="editable" target="pointOfContact">&nbsp;</span>
                <?php endif; ?>
                </td>
            </tr>
        </table>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php if (!isset($this->incident['ReportingUser'])): Fisma_Format_Section::startSection('Reported By'); ?>
        <table class="keyValues">
            <tr>
                <th scope='row'><First Name:</th>
                <td>
                    <div name="incident[reporterFirstName]"
                         id="reporterFirstName"
                         <?php if ($this->updateIncidentPrivilege): ?>
                             class="editable"
                             type="text"
                             target="reporterFirstName"
                         <?php endif; ?>>
                         <?php echo $this->escape($this->incident['reporterFirstName']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'><>Last Name:</th>
                <td>
                    <div name="incident[reporterLastName]"
                         id="reporterLastName"
                         <?php if ($this->updateIncidentPrivilege): ?>
                             class="editable"
                             type="text"
                             target="reporterLastName"
                         <?php endif; ?>>
                         <?php echo $this->escape($this->incident['reporterLastName']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'><Organization:</th>
                <td>
                    <div name="incident[reporterOrganization]"
                         id="reporterOrganization"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="text"
                             target="reporterOrganization"
                         <?php
                         endif;
                         ?>>
                         <?php echo $this->escape($this->incident['reporterOrganization']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'>Address 1:</th>
                <td>
                    <div name="incident[reporterAddress1]"
                         id="reporterAddress1"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="text"
                             target="reporterAddress1"
                         <?php
                         endif;
                         ?>>
                         <?php echo $this->escape($this->incident['reporterAddress1']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'>Address 2:</th>
                <td>
                    <div name="incident[reporterAddress2]"
                         id="reporterAddress2"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="text"
                             target="reporterAddress2"
                         <?php
                         endif;
                         ?>>
                         <?php echo $this->escape($this->incident['reporterAddress2']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'>City:</th>
                <td>
                    <div name="incident[reporterCity]"
                         id="reporterCity"
                         <?php if ($this->updateIncidentPrivilege): ?>
                             class="editable"
                             type="text"
                             target="reporterCity"
                         <?php endif; ?>>
                         <?php echo $this->escape($this->incident['reporterCity']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'>State:</th>
                <td>
                    <div name="incident[reporterState]"
                         id="reporterState"
                         <?php if ($this->updateIncidentPrivilege): ?>
                             class="editable"
                             type="text"
                             target="reporterState"
                         <?php endif; ?>>
                         <?php echo $this->escape($this->incident['reporterState']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'>Zip:</th>
                <td>
                    <div name="incident[reporterZip]"
                         id="reporterZip"
                         <?php if ($this->updateIncidentPrivilege): ?>
                             class="editable"
                             type="text"
                             target="reporterZip"
                         <?php endif; ?>>
                         <?php echo $this->escape($this->incident['reporterZip']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'>Phone:</th>
                <td>
                    <div name="incident[reporterPhone]"
                         id="reporterPhone"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="text"
                             target="reporterPhone"
                         <?php
                         endif;
                         ?>>
                         <?php echo $this->escape($this->incident['reporterPhone']); ?>&nbsp;
                    </div>
                </td>
            </tr>
                <td>Fax:</td>
                <td>
                    <div name="incident[reporterFax]"
                         id="reporterFax"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="text"
                             target="reporterFax"
                         <?php
                         endif;
                         ?>>
                         <?php echo $this->escape($this->incident['reporterFax']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'>Email:</th>
                <td>
                    <div name="incident[reporterEmail]"
                         id="reporterEmail"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="text"
                             target="reporterEmail"
                         <?php
                         endif;
                         ?>>
                         <?php echo $this->escape($this->incident['reporterEmail']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'>Reported from IP:</th>
                <td>
                    <?php echo $this->escape($this->incident['reporterIp']); ?>
                </td>
            </tr>
        </table>
    <?php Fisma_Format_Section::stopSection(); endif; ?>

    <?php Fisma_Format_Section::startSection('Location'); ?>
        <table class="keyValues">
            <tr>
                <th scope='row'>Building:</th>
                <td>
                    <div name="incident[locationBuilding]"
                         id="locationBuilding"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="text"
                             target="locationBuilding"
                         <?php
                         endif;
                         ?>>
                        <?php echo $this->escape($this->incident['locationBuilding']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'>Room:</th>
                <td>
                    <div name="incident[locationRoom]"
                         id="locationRoom"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="text"
                             target="locationRoom"
                         <?php
                         endif;
                         ?>>
                        <?php echo $this->escape($this->incident['locationRoom']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'>Host:</th>
                <td>
                    <div name="incident[hostName]"
                         id="hostName"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="text"
                             target="hostName"
                         <?php
                         endif;
                         ?>>
                        <?php echo $this->escape($this->incident['hostName']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'>Host IP:</th>
                <td>
                    <div name="incident[hostIp]"
                         id="hostIp"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="text"
                             target="hostIp"
                         <?php
                         endif;
                         ?>>
                        <?php echo $this->escape($this->incident['hostIp']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'>Host OS:</th>
                <td>
                    <div name="incident[hostOs]"
                         id="hostOs"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="select"
                             href="/metadata/enum/model/Incident/field/hostOs/"
                             target="hostOs"
                         <?php
                         endif;
                         ?>>
                        <?php echo $this->escape($this->incident['hostOs']); ?>&nbsp;
                    </div>
                </td>
            </tr>
            <tr>
                <th scope='row'>Host Description:</th>
                <td>
                    <div name="incident[hostAdditional]"
                         id="hostAdditional"
                         <?php
                         if ($this->updateIncidentPrivilege):
                         ?>
                             class="editable"
                             type="textarea"
                             target="hostAdditional"
                         <?php
                         endif;
                         ?>>
                        <?php echo $this->escape($this->incident['hostAdditional'], 'none'); ?>&nbsp;
                    </div>
                </td>
                </tr>
        </table>
    <?php Fisma_Format_Section::stopSection(); ?>
</div>

<div class="clear"></div>
