<?php
echo $this->escape($this->searchBox($this->toolbarButtons), 'none');
Fisma_Format_Section::startSection("Report A Security Incident");
?>
<p>
    If you would like to report a computer security incident, please complete the following form. Required fields are
    denoted with an asterisk. Please specify as much information as you can. If there are questions that you do not
    know the answer to, you are encouraged to leave those questions blank and to submit the incident report in a timely
    manner. You will be given a chance to review your report before submission. To cancel click the Back button.
</p>
<?php
echo $this->escape($this->form, 'none');
Fisma_Format_Section::stopSection();
?>
<script type="text/javascript">
    $(function() {
        var assetRow = $("table.fisma_crud > tbody > tr:has(#assetInfo)"),
            piiRows = $("table.fisma_crud > tbody > tr:has(input[name=piiMobileMedia], " +
                        "input[name=piiEncrypted], input[name=piiIndividualsCount])"),
            assetInvolved = $("input[name=assetInvolved]"),
            piiInvolved = $("input[name=piiInvolved]");
        assetInvolved.change(function(ev) {
            if (assetInvolved.filter(":checked").val() === "YES") {
                assetRow.show();
            } else {
                assetRow.hide();
            }
        }).change();
        piiInvolved.change(function(ev) {
            if (piiInvolved.filter(":checked").val() === "YES") {
                piiRows.show();
            } else {
                piiRows.hide();
            }
        }).change();
    });
</script>
