<?php
echo $this->escape($this->searchBox($this->toolbarButtons), 'none');
Fisma_Format_Section::startSection("Report A Security Incident");
?>
    <div style="width: 970px;">
        <?php echo $this->escape($this->form, 'none'); ?>
    </div>
<?php Fisma_Format_Section::stopSection(); ?>
<script type="text/javascript">
    $(function() {
        var assetRow = $("table.fisma_crud > tbody > tr:has(#assetInfo)"),
            piiRows = $("table.fisma_crud > tbody > tr:has(input[name=piiMobileMedia], " +
                        "input[name=piiEncrypted], input[name=piiIndividualsCount])"),
            assetInvolved = $("input[name=assetInvolved]"),
            piiInvolved = $("input[name=piiInvolved]");
        assetInvolved.change(function(ev) {
            if (assetInvolved.filter(":checked").val() === "YES") {
                assetRow.show();
            } else {
                assetRow.hide();
            }
        }).change();
        piiInvolved.change(function(ev) {
            if (piiInvolved.filter(":checked").val() === "YES") {
                piiRows.show();
            } else {
                piiRows.hide();
            }
        }).change();
    });
</script>
