<?php
echo $this->escape($this->searchBox($this->toolbarButtons), 'none');
Fisma_Format_Section::startSection("Review Incident Report");
?>

<h1>Review Report</h1>

<p>
   Please review all of the report details which you have provided. If anything needs to be changed, you can use the
   "Go Back" button to revisit the form. When you are satisfied, click the "Submit Report" button.
</p>

<p>
    <i>Once you click "Submit Report", the report will be submitted and it cannot be modified after that.</i>
</p>

<div style="margin: 10px;">
    <table class="keyValues">
        <?php
        foreach ($this->incidentReview as $key => $value):
        ?>
            <tr>
                <td><?php echo $this->escape($key); ?>:</td>
                <?php if(!empty($this->richColumns[$key]) && $this->richColumns[$key] == 'html'): ?>
                <td><?php echo $this->escape($value, 'none'); ?><td>
                <?php else: ?>
                <td><?php echo $this->escape($value); ?></td>
                <?php endif; ?>
            </tr>
        <?php
        endforeach;
        ?>
    </table>
</div>
<?php Fisma_Format_Section::stopSection(); ?>
<form><?php /* dummy form for CSRF token */ ?></form>
