<?php
echo $this->escape($this->searchBox(array()), 'none');
Fisma_Format_Section::startSection("Incident Report Submitted");
?>

<h1>The incident report has been submitted</h1>

<p>Your incident report has been submitted successfully.</p>

<?php
if ($this->viewIncidentButton):
    echo $this->escape($this->viewIncidentButton, 'none');
endif;

echo $this->escape($this->createNewButton, 'none');

Fisma_Format_Section::stopSection();
?>
