<div class="column left">
    <?php
    Fisma_Format_Section::startSection("Actors");
    if ($this->updateIncidentPrivilege):
    ?>
        <input type="hidden" id="actorId" />
        <div style="float: left; margin-right: 15px; margin-bottom: 15px;">
            <?php echo $this->escape($this->addActorButton, 'none'); ?>
        </div>
        <div style="float: left; margin-top: 3px; width: 75%;">
            <?php echo $this->escape($this->actorAutocomplete, 'none'); ?>
        </div>
        <div style="clear: both;"></div>
    <?php
    endif;

    echo $this->escape($this->actorDataTable, 'none');

    Fisma_Format_Section::stopSection();
    ?>
</div>

<div class="column right">
    <?php
    Fisma_Format_Section::startSection("Observers");
    if ($this->updateIncidentPrivilege):
    ?>
        <input type="hidden" id="observerId" />
        <div style="float: left; margin-right: 15px; margin-bottom: 15px;">
            <?php echo $this->escape($this->addObserverButton, 'none'); ?>
        </div>
        <div style="float: left; margin-top: 3px; width: 72%;">
            <?php echo $this->escape($this->observerAutocomplete, 'none'); ?>
        </div>
        <div style="clear: both;"></div>
    <?php
    endif;

    echo $this->escape($this->observerDataTable, 'none');

    Fisma_Format_Section::stopSection();
    ?>
</div>
