<?php
echo $this->partial('document-type/searchbox.phtml');

$operation = '';
if ($this->acl()->hasPrivilegeForObject('update', $this->subject)) {
    $operation .= "[<a href='{$this->escape($this->editLink)}'>Edit</a>]";
}
if ($this->acl()->hasPrivilegeForObject('delete', $this->subject)) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->escape($this->deleteLink)}'>Delete</a>]";
}
Fisma_Format_Section::startSection("Document Type Information $operation"); ?>

<div>
    <?php echo $this->escape($this->form, 'none') ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
