<?php
$operation = '';

if ($this->updateIrWorkflowDefPrivilege):
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
endif;

if ($this->deleteIrWorkflowDefPrivilege):
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
endif;

Fisma_Format_Section::startSection("Workflow Step Information</b> $operation"); 
?>

<div>
    <?php echo $this->form ?>
</div>

<?php 
Fisma_Format_Section::stopSection(); 
?>
