<div id="<?php echo $this->tabViewContainer; ?>">
    <!-- YUI will load the tabview into this div -->
</div>

<script type="text/javascript">
    YAHOO.util.Event.onDOMReady(function () {
        var tabView = new YAHOO.widget.TabView();
    
        var prepareTab = function(args) {
            // Adds the style and event handlers required for editable fields
            setupEditFields();
            
            // Notice that we are eval'ing any script nodes loaded into this tab. This is only safe as long as
            // we know exactly which URLs we are loading into the tabview. Otherwise we might inadertently execute
            // a 3rd party script.
            var tabContainer = document.getElementById('<?php echo $this->tabViewContainer; ?>');
            var scriptNodes = tabContainer.getElementsByTagName('script');
            for (var i=0; i < scriptNodes.length; i++) {
                if (scriptNodes[i].getAttribute('executeFlag') != 'true') {
                    try {
                        eval(scriptNodes[i].text);
                    } catch (e) {
                        alert('Not able to execute one of the scripts embedded in this page: '
                              + e.message);
                    } 
                    // Set a flag that prevents this script from being executed more than once
                    scriptNodes[i].setAttribute('executeFlag', 'true');
                }
            }
        }
        
        // When the active tab changes, store the active tab in a cookie so that it can be restored
        // in between page refreshes.
        var handleTabChange = function(args) {
            YAHOO.util.Cookie.set("<?php echo $this->selectedTabCookie; ?>", args.newValue, { path: '/' });
        }
        
        // Render tabs
        <?php
        foreach ($this->tabs as $tab):
        ?>
            var newTab = new YAHOO.widget.Tab({
                id : "<?php echo $tab['id']; ?>",
                label : "<?php echo $tab['name']; ?>",
                dataSrc : "<?php echo $tab['url']; ?>",
                cacheData : true
            });
            
            newTab.subscribe("dataLoadedChange", prepareTab);
            tabView.addTab(newTab);
        <?php
        endforeach;
        ?>
        
        tabView.subscribe('activeIndexChange', handleTabChange);
        tabView.appendTo('<?php echo $this->tabViewContainer; ?>');
    
        // Tab is selected based on the numerical hash appended to the URL, or if no hash is present,
        // then by the cookie.
        var tab = location.hash.substring(1); // Strip the "#" off of the hash

        if (!tab || tab < 0 || tab >= <?php echo count($this->tabs); ?>) {
            if (YAHOO.util.Cookie.get("<?php echo $this->objectIdCookie; ?>") == <?php echo $this->objectId; ?>) {
                tab = YAHOO.util.Cookie.get("<?php echo $this->selectedTabCookie; ?>");
            } else {
                YAHOO.util.Cookie.set("<?php echo $this->objectIdCookie; ?>", 
                                      <?php echo $this->objectId; ?>, 
                                      {path: '/'});
                YAHOO.util.Cookie.set("<?php echo $this->selectedTabCookie; ?>", 0, {path: '/'}); 
                tab = 0;
            }
        }
        tabView.selectTab(tab);
        Fisma.tabView = tabView;
        Fisma.prepareTab = prepareTab;
    });
</script>
