<b>Contains keyword:</b><br/>
keyword<br/>
<br/>
<b>Contains keyword1 or keyword2:</b><br/>
keyword1 keyword2<br/>
<br/>
<b>Contains keyword1 but not keyword2:</b><br/>
keyword1 -keyword2<br/>
<br/>
<b>Contains keyword in one field:</b><br/>
fieldname:keyword<br/>
<br/>
<b>Contains Multiple character wildcard:</b><br/>
keywo*,  *eyword,  key?ord,  key?or*<br/>
<br/>
<b>Fuzzy searches:</b><br/>
keyword~<br/>