<h1>Searching</h1>

<p>
    The search engine can handle a variety of keyword searches. Here are some sample search terms
    that demonstrate these advanced searching features.
</p>

<p>
    <b>Search for findings containing the words "grant" <i>or</i> "public":</b><br>
    grant public
</p>

<p>
    <b>If you are searching for specific findings and you know their ID numbers:</b><br>
    3214, 3217, 3310
</p>

<p>
    <b>Search for findings containing "database" but <i>not</i> "oracle":</b><br>
    database -oracle
</p>

<p>
    <b>Search for findings against a system named "ABC"</b><br>
    system:ABC
</p>

<p>
    <b>Search for findings against an asset named "PRODSERV01"</b><br>
    asset:PRODSERV01
</p>

<p>
    <b>Search for findings from a source named "CM"</b><br>
    source:CM
</p>

<p>
    <b>Wildcard searches:</b><br>
    keywo*,  *eyword,  key?ord,  key?or*
</p>

<p>
    <b>Search for words similar to "root" (such as "foot", "toot", "roof", etc.):</b><br>
    root~
</p>

<p>
    There are also some advanced search options available if you click on the "Toggle Advanced Search Options" button.
</p>
