<h1>Searching</h1>

<p>
    The search engine can handle a variety of keyword searches. Here are some sample search terms
    that demonstrate these advanced searching features.
</p>

<p>
    <b>Search for findings containing the words "grant" <i>or</i> "public":</b><br>
    grant public
</p>

<p>
    <b>If you are searching for specific findings and you know their ID numbers:</b><br>
    3214, 3217, 3310
</p>

<p>
    <b>Search for findings containing "database" but <i>not</i> "oracle":</b><br>
    database -oracle
</p>

<p>
    <b>Search for any word starting with "res", such as "reset", "restart", etc. in the description field only:</b><br>
    description:res*
</p>

<p>
    <b>Search for words similar to "root" (such as "foot", "toot", "roof", etc.):</b><br>
    root~
</p>

<p>
    There are also some advanced search options available if you click on the "Toggle Advanced Search Options" button.
</p>
