<?php Fisma_Format_Section::startSection('Dashboard'); ?>
<div class="panel">
    <p><em>Alerts</em></p>
    <ul>
        <li>
            There are <b>
            <a href="<?php echo $this->escape($this->newFindingUrl, 'none'); ?>">
                <?php echo $this->escape($this->alert['NEW'])?></a>
            </b> NEW findings (findings that do not have a mitigation strategy).
        </li>
        <li>
            There are <b>
            <a href="<?php echo $this->escape($this->draftFindingUrl, 'none'); ?>">
                <?php echo $this->escape($this->alert['DRAFT'])?></a>
            </b> DRAFT findings (findings that have a mitigation strategy but have not been submitted for approval).
        </li>
        <li>
            There are <b>
            <a href="<?php echo $this->escape($this->evidenceNeededOntimeUrl); ?>">
                <?php echo $this->escape($this->alert['EN']); ?></a>
            </b> findings awaiting evidence.
        </li>
        <li>
            There are <b>
            <a href="<?php echo $this->escape($this->evidenceNeededOverdueUrl); ?>">
                <?php echo $this->escape($this->alert['EO']); ?></a>
            </b> overdue findings awaiting evidence.    
        </li>
    </ul>
</div>
<div class="panel">
    <p><em>Last Login</em></p>
    <?php 
    if (!empty($this->lastLoginIp)) { 
    ?>
        <ul>
            <li>Last Logged in at <b><?php echo $this->escape($this->lastLoginTs)?></b></li>
            <li>From IP address <b><?php echo $this->escape($this->lastLoginIp)?></b></li>
            <?php if ('database' == Fisma::configuration()->getConfig('auth_type')): ?>
                <li>
                    There were 
                    <b><?php echo $this->escape($this->failureCount)?></b>
                    bad login attempts since your last login.
                </li>
            <?php endif; ?>
        </ul>
    <?php 
    } else { 
    ?>
        <p>
            This is the first time you have logged into
            <?php echo $this->escape(Fisma::configuration()->getConfig('system_name'))?>. 
            We will begin tracking your login attempts moving forward.
        </p>
    <?php 
    } 
    ?>
</div>

<?php
if (isset($this->notifications)) {
?>
    <div class="panel clear">
        <p><em>Notifications</em></p>
        <p>
            You have new notifications that you have not received in e-mail yet.
            Click <a href="<?php echo $this->escape($this->dismissUrl, 'none')?>">here</a>
            to dismiss these notifications.
        </p>
        <ol>
            <?php
            foreach ($this->notifications as $notification) {
            ?>
                <li>
                    <?php echo $this->escape($notification['eventText']); ?>
                    at
                    <?php echo $this->escape($notification['createdTs']); ?>
                </li>
            <?php
            }
            ?>
        </ol>
    </div>
<?php
}
?>

<?php 
if ( !empty( $this->alert['TOTAL'] ) ) { 
?>
    <b>Management Overview </b><br/>

    <div class="column left">
        <div style='text-align: center;'>
            <?php echo $this->escape($this->chartTotalStatus, 'none'); ?>
        </div>
    </div>

    <div class="column right">
        <div style='text-align: center;'>
            <?php echo $this->escape($this->chartTotalType, 'none'); ?>
        </div>
    </div>
    
<?php 
} 
?>

<div class="clear"></div>

<?php Fisma_Format_Section::stopSection(); ?>
