<?php if (!empty($this->summary)) : ?>
<chart>
    <license>FTA9HNF7P2O.H4X5CWK-2XOI1X0-7L</license>

    <context_menu about='false'
                  print='false'
                  full_screen='true'
                  save_as_bmp='false'
                  save_as_jpeg='true'
                  save_as_png='true' />

    <link_data url="javascript:barChartClick(_series_)" target="javascript" />
    <chart_data>
        <row>
            <null/>
            <string></string>
        </row>    
        <?php 
        foreach ($this->summary AS $status=>$statusCount) { 
        ?>
        <row>
            <string><?php echo $this->escape($status); ?></string>
            <number tooltip='<?php echo $this->escape("$statusCount $status"); ?>'><?php
                // IMPORTANT: Whitespace not permitted here
                echo $this->escape($statusCount);
            ?></number>
        </row>
        <?php 
        } 
        ?>
    </chart_data>

    <chart_type>3d column</chart_type>

    <chart_grid_h thickness='0' />

    <axis_value alpha='0' />

    <chart_label font='arial'
                 bold='true'
                 size='12'
                 position='over' />

    <chart_pref rotation_x='30'
                rotation_y='40'
                min_x='20'
                max_x='70'
                min_y='30'
                max_y='80' />

    <chart_rect x='0' y='0' width='480' height='240' positive_alpha='0' negative_alpha='25' />

    <filter>
        <shadow id='low' distance='2' angle='45' alpha='50' blurX='2' blurY='2' />
    </filter>

    <legend layout='vertical'
            bullet='square'
            font='arial'
            bold='true'
            size='10'
            x='0'
            y='50'
            width='100'
            height='150' />


    <series_color>
<?php
    // Figure out which colors are MSA colors and which are EA colors
    unset($this->summary['NEW']);
    unset($this->summary['DRAFT']);
    $msaColors = array();
    foreach ($this->summary as $status => $filler) {
        if ($status == 'EN') {
            break;
        }
        $msaColors[] = $status;
        unset($this->summary[$status]);
    }
    unset($this->summary['EN']);
    $epColors = array();
    foreach ($this->summary as $status => $filler) {
        $epColors[] = $status;
    }
    
    // Colors for NEW & DRAFT
    echo $this->escape('<color>cccccc</color>', 'none');
    echo $this->escape('<color>66ff66</color>', 'none');
    
    // Colors for MSA
    define('START_COLOR', 200); // These constants are used for creating a gradient
    define('STOP_COLOR', 25); // The range of these constants sets the high and low gradient value
    if (count($msaColors) > 1) {
        $colorStep = (STOP_COLOR - START_COLOR) / (count($msaColors) - 1);
    } else {
        $colorStep = (STOP_COLOR - START_COLOR) / 2;
    }
    for ($i = 0; $i < count($msaColors); $i++) {
        $hex = dechex(START_COLOR + ($colorStep * $i));
        echo $this->escape("<color>ff{$hex}{$hex}</color>", 'none');
    }
    
    // Color for EN
    echo $this->escape('<color>ff9933</color>', 'none');
    
    // Colors for EA
    if (count($epColors) > 1) {
        $colorStep = (STOP_COLOR - START_COLOR) / (count($epColors) - 1);
    } else {
        $colorStep = (STOP_COLOR - START_COLOR) / 2;
    }
    for ($i = 0; $i < count($epColors); $i++) {
        $hex = dechex(START_COLOR + ($colorStep * $i));
        echo $this->escape("<color>{$hex}{$hex}ff</color>", 'none');
    }
?>
    </series_color>
</chart>
<?php else:
echo $this->partial('chart/nodata.xml.phtml', array('width' => '380', 'height' => '275'));
endif; ?>
