<?php
    $user = $this->user;
    $event = $this->event;
    $url = $this->url;
    $time = $this->time;
    $systemName = $this->systemName;
    $paranoid = !($this->detail);

    $record = $this->record;

    switch ($event->name) {
        case 'USER_CREATED':
            $eventTitle = "User account created by {$user->displayName}";
            break;
        case 'USER_UPDATED':
            $eventTitle = "User account modified by {$user->displayName}";
            break;
        case 'ACCOUNT_LOCKED':
            $eventTitle = "User account locked by {$systemName}";
            break;
        case 'ACCOUNT_DISABLED':
            $eventTitle = "User account disabled by {$user->displayName}";
            break;
        case 'USER_DELETED':
            $eventTitle = "User account deleted by {$user->displayName}";
            break;
        case 'USER_POC':
            $recordClass = get_class($record);
            $assigner = ($user) ? $user->displayName : $systemName;
            $eventTitle = "You're assigned to {$recordClass} {$record->id} by {$assigner}";
            break;
        case 'ACCOUNT_LOGIN_SUCCESS':
            $eventTitle = "{$user->displayName} logged in successfully";
            break;
        case 'ACCOUNT_LOGIN_FAILURE':
            $eventTitle = "Failed login detected with user {$user->displayName}";
            break;
        case 'CONFIGURATION_UPDATED':
            $eventTitle = "Application configuration modified by {$user->displayName}";
            break;
        case 'FINDING_CREATED':
            $eventTitle = "Finding {$record->id} created by {$user->displayName}";
            break;
        case 'FINDING_DELETED':
            $eventTitle = "Finding {$record->id} deleted by {$user->displayName}";
            break;
        case 'FINDING_UPDATED':
            $eventTitle = "Finding {$record->id} modified by {$user->displayName}";
            break;
        case 'FINDING_CLOSED':
            $eventTitle = "Finding {$record->id} resolved by {$user->displayName}";
            break;
        default:
            $eventTitle = "{$event->description} by {$user->displayName}";
    }
?>
<div style="
    margin-top: 10px;
    padding: 3px 8px;
    background-color: #416ed7;
    color: #fff;
    border: 1px solid #416ed7;
    border-bottom: none;
    font-weight: bold;
    text-align: left;
">Overview</div>
<div style="
    border: 1px solid #d3d3d3;
    background-color: #ffffff;
    border-top: none;
    padding: 10px;
    margin-bottom: 0px;
">
<table cellpadding='4' cellspacing='2'>
    <tr>
        <th>Event:</th>
        <td><?php echo $this->escape($eventTitle); ?></td>
    </tr>
    <tr>
        <th>Time:</th>
        <td><?php echo $this->escape($time); ?></td>
    </tr>
<?php if ($url): ?>
    <tr>
        <th>URL:</th>
        <td><a href='<?php echo $this->escape($url); ?>'><?php echo $this->escape($url); ?></a></td>
    </tr>
<?php endif; ?>
</table>
</div>
<?php
    $mail_template = Zend_Registry::get('mail_template');
    $recordClass = get_class($record);
    if (isset($mail_template[$recordClass]) && !$paranoid):
        $template = $mail_template[$recordClass];
        $table = Doctrine::getTable($recordClass);
?>
<div style="
    margin-top: 10px;
    padding: 3px 8px;
    background-color: #416ed7;
    color: #fff;
    border: 1px solid #416ed7;
    border-bottom: none;
    font-weight: bold;
    text-align: left;
"><?php echo $this->escape($recordClass); ?> Summary</div>
<div style="
    border: 1px solid #d3d3d3;
    background-color: #ffffff;
    border-top: none;
    padding: 10px;
    margin-bottom: 0px;
">
    <table cellpadding='4' cellspacing='2'>
    <?php foreach ($template as $field):
        $columnDef = $table->getColumnDefinition($table->getColumnName($field));
        $value = $record->$field;
        $name = $table->getLogicalName($field);
        $purify = (isset($columnDef['extra']) && isset($columnDef['extra']['purify'])) ? 'none' : 'html';
        if (isset($columnDef['extra']) && isset($columnDef['extra']['class']) && isset($columnDef['extra']['field'])):
            $rel = Doctrine::getTable($columnDef['extra']['class']);
            $value = $rel->find($value)->$columnDef['extra']['field'];
        endif;
    ?>
        <tr>
            <th><?php echo $this->escape($this->translate($name)); ?></th>
            <td><?php echo $this->escape($value, $purify); ?></td>
        </tr>
    <?php endforeach; ?>
    </table>
</div>
<?php endif; ?>

<?php if (in_array($event->name, array(
    'CONFIGURATION_UPDATED',
    'USER_UPDATED',
    'ORGANIZATION_UPDATED',
    'SYSTEM_UPDATED',
    'ASSET_UPDATED',
    'FINDING_UPDATED',
    'INCIDENT_UPDATED',
    'VULNERABILITY_UPDATED'
))): ?>
<div style="
    margin-top: 10px;
    padding: 3px 8px;
    background-color: #416ed7;
    color: #fff;
    border: 1px solid #416ed7;
    border-bottom: none;
    font-weight: bold;
    text-align: left;
">Updated Field(s)</div>
<div style="
    border: 1px solid #d3d3d3;
    background-color: #ffffff;
    border-top: none;
    padding: 10px;
    margin-bottom: 0px;
">
    <?php if (!$paranoid): ?>
    <table cellpadding='4' cellspacing='2'>
        <tr>
            <th>Field</th>
            <th>Old value</th>
            <th>New value</th>
        </tr>
        <?php foreach ($this->modifiedFields as $name => $values): ?>
        <tr>
            <th><?php echo $this->escape($this->translate($values[2])); ?></th>
            <td><?php echo $this->escape($values[0], $values[3]); ?></td>
            <td><?php echo $this->escape($values[1], $values[3]); ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
    <?php else: ?>
    <ul>
        <?php foreach ($this->modifiedFields as $name => $values): ?>
        <li><?php echo $this->escape($this->translate($values[2])); ?></li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</div>
<?php endif; ?>
