<?php
$links = array(
    'Overview' => '/sa/security-authorization/view/id/' . $this->sa->id,
    'Select' => '/sa/select-controls/index/id/' . $this->sa->id,
    'Implement' => '/sa/security-authorization/implementation/id/' . $this->sa->id,
    'Assessment' => '/sa/security-authorization/assessment-plan/id/' . $this->sa->id,
    'Authorization' => '/sa/security-authorization/authorization/id/' . $this->sa->id
);
// null value means disabled, disable tabs based on status
switch ($this->sa->status) {
    case 'Select':
        $links['Implement'] = null;
    case 'Implement':
        $links['Assessment'] = null;
    case 'Assessment Plan':
    case 'Assessment':
        $links['Authorization'] = null;
    case 'Authorization':
    case 'Active':
    case 'Retired':
        // do nothing
        break;
    default:
        throw new Fisma_Zend_Exception('Unknown SA status encountered.');
}
?>
Security Authorization <?php echo $this->escape($this->sa->id); ?><br />
<div class="yui-navset yui-navset-top">
    <ul class="yui-nav">
    <?php foreach ($links as $label => &$value): ?>
        <?php if (empty($value)): ?>
            <li class="disabled"><a href="#"><em><?php echo $this->escape($label); ?></em></a></i></li>
        <?php else: ?>
            <li class="<?php echo $this->escape($label == $this->current ? 'selected' : ''); ?>">
                <a href="<?php echo $this->escape($value); ?>"><em><?php echo $this->escape($label); ?></em></a>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
    </ul>
</div>

