{*
Generates the Impact Table grid.
The current impact level is indicated by background cell color,
best generated by calling cell_background_colors().
Input:
 cell_colors (array) - list of cell background HTML colors, with one
                       entry signifying the current value.
                       e.g.: ('FFFFFF', 'FFFFFF', 'CCCCCC', 'FFFFFF'...)
*}

{*<table frame='box' rules='all'>*}
<table class="rafImpact">
 <tr>
  <td colspan='4' align='center'><b>IMPACT LEVEL TABLE</b></td>
 </tr>
 <tr>
  <td>&nbsp;</td>
  <td colspan='3' align='center'><b>MISSION CRITICALITY</b></td>
 </tr>
 <tr>
  <td><b>DATA SENSITIVITY</b></td>
  <td><b>SUPPORTIVE</b></td>
  <td><b>IMPORTANT</b></td>
  <td><b>CRITICAL</b></td>
 </tr>
 <tr>
  <td><b>HIGH</b></td>
  <td bgcolor='{$cell_colors[0]}'>low</td>
  <td bgcolor='{$cell_colors[1]}'>moderate</td>
  <td bgcolor='{$cell_colors[2]}'>high</td>
 </tr>
 <tr>
  <td><b>MODERATE</b></td>
  <td bgcolor='{$cell_colors[3]}'>low</td>
  <td bgcolor='{$cell_colors[4]}'>moderate</td>
  <td bgcolor='{$cell_colors[5]}'>moderate</td>
 </tr>
 <tr>
  <td><b>LOW</b></td>
  <td bgcolor='{$cell_colors[6]}'>low</td>
  <td bgcolor='{$cell_colors[7]}'>low</td>
  <td bgcolor='{$cell_colors[8]}'>low</td>
 </tr>
</table>


