<?php
    $flashVars = 'library_path=/flash/charts_library&xml_source=' . $this->sourceUrl;
?>
<div id="<?php echo $this->escape($this->containerId, 'none')?>">
</div>

<script language="JavaScript" type="text/javascript">
    var hasRightVersion = DetectFlashVer(10, 0, 45);
    if (hasRightVersion) {
        var flashContent = AC_FL_RunContent(
			'codebase', 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,45,2',
            'width', '<?php echo $this->escape($this->width, 'javascript')?>',
            'height', '<?php echo $this->escape($this->height, 'javascript')?>',
            'scale', 'noscale',
            'salign', 'TL',
            'bgcolor', '#FFFFFF',
            'wmode', 'opaque',
            'movie', '/flash/charts',
            'src', '/flash/charts',
            'FlashVars', '<?php echo $this->escape($flashVars, 'javascript')?>',
            'id', 'my_chart',
            'name', 'my_chart',
            'menu', 'true',
            'allowFullScreen', 'true',
            'allowScriptAccess', 'sameDomain',
            'quality', 'high',
            'align', 'middle',
            'pluginspage', 'https://www.macromedia.com/go/getflashplayer',
            'play', 'true',
            'devicefont', 'false'
        );
        var containerEl = document.getElementById('<?php echo $this->escape($this->containerId, 'javascript')?>');
        containerEl.innerHTML = flashContent;
    } else {
        var alternateContent = 'This content requires the Adobe Flash Player.';
        alert(alternateContent);
    }
</script>

<noscript>
    <p>This content requires JavaScript.</p>
</noscript>
