<chart>
    <license>FTA9HNF7P2O.H4X5CWK-2XOI1X0-7L</license>

    <draw>
        <rect 
            x='0' 
            y='0' 
            width='<?php echo $this->escape($this->width) ?>' 
            height='<?php echo $this->escape($this->height) ?>' 
            fill_color='ffffff' />
        <text transition='none' size='45' h_align='center' v_align='middle'>No data available.</text>
    </draw>
    <chart_data>
    </chart_data>
</chart>
