<?php 
echo $this->escape($this->partial('product/searchbox.phtml', array('keywords' => $this->keywords)), 'none');
Fisma_Format_Section::startSection("Product List <span id='searchResultsTotalFound'></span>"); 
?>
<div id="list"></div>
<script type="text/javascript">
// Column definitions
var myColumnDefs = [
    {key:"id", label:"id",hidden: true}
    ,{key:"name", label:"Product Name", sortable: true, hidden: false, formatter: "text"}
    ,{key:"vendor", label:"Vendor", sortable: true, hidden: false, formatter: "text"}
    ,{key:"version", label:"Version", sortable: true, hidden: false, formatter: "text"}
    ,{key:"cpeName", label:"Cpename", sortable: false, hidden: false, formatter: "text"}
];

    // A function which builds the query string
    var myRequestBuilder = function(oState, oSelf) {
        // Get states or use defaults
        oState = oState || {pagination:null, sortedBy:null};
        var sort = (oState.sortedBy) ? oState.sortedBy.key : "id";
        var dir = (oState.sortedBy && oState.sortedBy.dir == 'yui-dt-asc') ? "asc" : "desc";
        var startIndex = oState.pagination.recordOffset;
        var count = oState.pagination.rowsPerPage;

        // Build custom request
        var request = "<?php echo $this->escape($this->link, 'none') ?>" + 
                      "/sortby/" + sort +
                      "/order/" + dir +
                      "/startIndex/" + startIndex +
                      "/count/" + count;
        return request;
    };

    var myDataSource = new YAHOO.util.DataSource('/product/search');
    myDataSource.responseType = YAHOO.util.DataSource.TYPE_JSON;
    myDataSource.responseSchema = {
        resultsList: "table.records",
        metaFields: {
            totalRecords: "table.totalRecords"
        }
    };
    
    // DataTable configuration
    var myConfigs = {
        initialRequest: "<?php echo $this->escape($this->link, 'none') ?>" + 
                        "/sortby/name/dir/asc/startIndex/0/count/" + 
                        "<?php echo $this->escape($this->pageInfo['count'])?>",
        dynamicData: true, 
        sortedBy : {key:"name", dir:YAHOO.widget.DataTable.CLASS_ASC},
        paginator: new YAHOO.widget.Paginator(
            {
                rowsPerPage:<?php echo $this->escape($this->pageInfo['count'])?>,
                template:"{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
            }
        ),
        generateRequest : myRequestBuilder
    };
    
    var myDataTable = new YAHOO.widget.DataTable("list", myColumnDefs, myDataSource, myConfigs);
    // Update totalRecords on the fly with value from server
    myDataTable.handleDataReturnPayload = function(oRequest, oResponse, oPayload) {
        oPayload.totalRecords = oResponse.meta.totalRecords;
        // display total records in the search results header, if not already present
        var searchResultsHeader = document.getElementById('searchResultsTotalFound');
        if (!searchResultsHeader.firstChild) {
            var totalRecords = oResponse.meta.totalRecords ? oResponse.meta.totalRecords : 0;
            var searchTotalFound = document.createTextNode('(' + totalRecords + ' records found)');
            searchResultsHeader.appendChild(searchTotalFound);
        }
        return oPayload;
    }
    
    myDataTable.subscribe("rowMouseoverEvent", myDataTable.onEventHighlightRow); 
    myDataTable.subscribe("rowMouseoutEvent", myDataTable.onEventUnhighlightRow);

    <?php 
    if (Fisma_Zend_Acl::hasPrivilegeForClass('read', 'Product')): 
    ?>
        myDataTable.subscribe("rowClickEvent", 
            function (oArgs) {
                var elTarget = oArgs.target;
                var oRecord = this.getRecord(elTarget);
                document.location = "/panel/product/sub/view/id/" + oRecord.getData("id");
            }
        );
    <?php 
    endif; 
    ?>
    
    var contextMenuItems = ["View"];
    var contextMenu = new YAHOO.widget.ContextMenu( 
        "contextMenu", 
        { 
            trigger:  myDataTable.getTbodyEl(), 
            itemdata: contextMenuItems, 
            lazyload: true 
        }
    );
    
    contextMenu.subscribe("click", contextMenuHandler);
    
    function contextMenuHandler(event, eventArgs) {
        var targetElement = this.contextEventTarget;
        var rowElement = myDataTable.getTrEl(targetElement);
        var rowRecord = myDataTable.getRecord(rowElement);
        var menuItem = eventArgs[1];
        var actionUrl = '';
        switch (menuItem.index) {
            case 0 :
                actionUrl = "/panel/product/sub/view/id/" + rowRecord.getData("id");
                break;
        }
        if (actionUrl != '') {
            window.open(actionUrl);
        }
    }
    
</script>
<?php Fisma_Format_Section::stopSection(); ?>
