<?php Format_Section::startSection("Product Administration"); ?>
<table class="tipframe" align="center"  width="98%" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <th>[<a href="/panel/product/sub/list">Products List</a>] (total: <?php echo 
$this->total;?>)</th>
            <?php if($this->acl->isAllowed('admin_products', 'create')) { ?>
            <th>[<a href="/panel/product/sub/create" title="Add New Product">Add 
Product</a>]</th>
            <?php } ?>
            <th>
                <table align="center">
                    <tbody>
                        <tr height="22">
                            <td><b>Page:&nbsp;</b></td>
                            <td><?php echo $this->links['all'];?></td>
                            <td>|</td>
                        </tr>
                    </tbody>
                </table>
            </th>
            <th>
                <table align="center">
                <form name="query" method="post" action="/panel/product/sub/list">
                    <tbody>
                        <tr>
                            <td><b>Query:&nbsp;</b></td>
                            <td><input name="qv" value="<?php echo $this->qv;?>" title="Input your query value" size="20" maxlength="40" type="text"></td>

                             <td><input value="Search" title="submit your request" type="submit"></td>
                        </tr>
                    </tbody>
                </form>
                </table>
            </th>
        </tr>
    </tbody>
</table>
<?php Format_Section::stopSection(); ?>
