<table class="searchFilters">
    <tbody>
        <tr>
            <th>[<a href="/panel/product/sub/list">Products List</a>] (total: <?php echo 
$this->total;?>)</th>
            <?php if($this->acl->isAllowed('admin_products', 'create')) { ?>
            <th>[<a href="/panel/product/sub/create" title="Add New Product">Add 
Product</a>]</th>
            <?php } ?>
            <th>
                <table align="center">
                        <tr>
                            <td><b>Page:&nbsp;</b></td>
                            <td><?php echo $this->links['all'];?></td>
                            <td>|</td>
                        </tr>
                </table>
            </th>
            <?php if (is_dir(Fisma_Controller_Front::getPath('data') . '/index/product')) { ?>
            <th>
                <table align="center">
                <form name="query" method="post" action="/panel/product/sub/list">
                        <tr>
                            <td><b>Query:&nbsp;</b></td>
                            <td><input name="qv" value="<?php echo $this->qv;?>" title="Input your query value" size="20" maxlength="40" type="text"></td>

                             <td><input value="Search" title="submit your request" type="submit"></td>
                        </tr>
                </form>
                </table>
            </th>
            <?php } ?>
        </tr>
</table>
