<div class="searchFilters">
    <div class="left">
        <?php
        $listButton = new Fisma_Yui_Form_Button_Link('listButton', 
                                               array('value' => 'Product List', 
                                                     'href' => '/panel/product/sub/list'));
        echo $listButton;
        ?>

        <?php if(Fisma_Acl::hasPrivilege('product', 'create')) {
        $createButton = new Fisma_Yui_Form_Button_Link('createButton', 
                                               array('value' => 'Add Product', 
                                                     'href' => '/panel/product/sub/create'));
        echo $createButton;
        } ?>
    </div>
    <div class="right">
    <?php if (is_dir(Fisma::getPath('index') . '/product')) { ?>
        <form name="query" method="post" action="/panel/product/sub/list" style="display:inline">
        <b>Search:&nbsp;</b>
        <input id="keywords" name="keywords" value="<?php echo $this->keywords;?>" title="Input your query value" size="20" maxlength="40" type="text">
        <span id="searchContainer"></span>
        <script type='text/javascript'>
           var save = new YAHOO.widget.Button({
               type: "submit",
               label: "Search",
               value: "Search",
               container: "searchContainer",
               disabled: false
           });
        </script>
        </form>
    <?php } else {
        echo '<b>The search index needs to be built</b>';
    } ?>
    </div>
    <div class="clear"></div>
</div>
