<table width="810" align="center"><tr><td>
<form id="form1" name="form1" method="post" action="" >
<table border="0" align="center" cellpadding="3" class="tipframe">
    <tr>
        <th colspan="2" align="left">Product Search</th>
        <th width="183" align="left">Product Select</th>
        <?php 
        if ($this->acl->isAllowed('admin_products', 'create')) { 
        ?>
            <th width="249" align="left">
                [<a id="add_product" 
                    href="/panel/product/sub/create" 
                    title="Create New Product">Create New Product</a>]
            </th>
        <?php 
        } 
        ?>
    </tr>
    <tr>
        <td width="161"><b> <label for="prodName">Product:</label></b></td>
        <td width="167">
            <input type="text" class="product" name="prodName" id="prodName"
                value="<?=$this->escape($this->prodName); ?>" 
                size="20" />
        </td>
        <td colspan="2" rowspan="4">
            <div style="width:400px">
                <select name="prodList" size="8" style="width: 100%;">
                <?php 
                foreach ($this->prodList as $key) {
                    echo $this->escape('<option value=', 'none');
                    echo $this->escape($key['id']);
                    echo $this->escape('>', 'none');
                    $label = implode(' | ', array($key['id'], $key['name'], $key['vendor'], $key['version']));
                    echo $this->escape($label);
                    echo $this->escape('</option>', 'none');
                } 
                ?>
                </select>
            </div>
        </td>
    </tr>
    <tr>
        <td><b><label for="prodVendor">Vendor:</label></b></td>
        <td>
            <input type="text" class="product" name="prodVendor" id="prodVendor"
                value="<?=$this->escape($this->prodVendor)?>"
                size="20" />
        </td>
    </tr>
    <tr>
        <td><b><label for="prodVersion">Version:</label></b></td>
        <td>
            <input type="text" class="product" name="prodVersion" id="prodVersion" 
                value="<?=$this->escape($this->prodVersion)?>" size="20" />
        </td>
    </tr>
    <tr>
        <td>
            <input id="search_product" type="button" value="Search Product" url="/product/search/format/html" />
        </td>
        <td><input type="reset" name="button2" id="button" value="Reset" /></td>
    </tr>
</table>
</form></td></tr></table>

<?php Fisma_Format_Section::stopSection(); ?>
