<form id="form1" name="form1" method="post" action="" >
    <div class="form">
        <div class="subform">
            <table class="fisma_crud">
                <tr>
                    <th align="left">Product Search</th>
                    <th align="right">
                    <?php 
                    if (Fisma_Acl::hasPrivilege('product', 'create')) { 
                    ?>
                    [<a id="add_product" href="/panel/product/sub/create" title="Add Product">Add Product</a>]
                    <?php 
                    } 
                    ?>
                    </th>
                </tr>
                <tr>
                    <td><b> <label for="prodName">Product:</label></b></td>
                    <td>
                        <input type="text" 
                               class="product" 
                               name="prodName" 
                               id="prodName"
                               value="<?php echo $this->prodName; ?>" 
                               size="20" />
                    </td>
                </tr>
                <tr>
                    <td><b><label for="prodVendor">Vendor:</label></b></td>
                    <td>
                        <input type="text" 
                               class="product" 
                               name="prodVendor" 
                               id="prodVendor"
                               value="<?php echo $this->prodVendor; ?>" 
                               size="20" />
                    </td>
                </tr>
                <tr>
                    <td><b><label for="prodVersion">Version:</label></b></td>
                    <td>
                        <input type="text" 
                               class="product" 
                               name="prodVersion" 
                               id="prodVersion"
                               value="<?php echo $this->prodVersion; ?>" 
                               size="20" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <input id="search_product" 
                               type="button" 
                               value="Search Product" 
                               url="/product/advancesearch/format/html" />
                    </td>
                    <td><input type="reset" name="button2" id="button" value="Reset" /></td>
                </tr>
            </table>
        </div>
    </div>
</form>
