<div class="barleft">
<div class="barright">
<p><b>Administration: Products List</b>
</div>
</div>
<table width="98%" align="center" border="0" cellpadding="0" cellspacing="0" class="tbframe">
<tr align="center">
    <th>Product Name</th>
    <th>Vendor</th>
    <th>Version</th>
    <?php if($this->acl->isAllowed('admin_products','update')){
              echo'<th>Edit</th>';
          } 
          if($this->acl->isAllowed('admin_products','delete')){
              echo'<th>Del</th>';
          }
          if($this->acl->isAllowed('admin_products','read')){
              echo'<th>View</th>';
          }
    ?>
</tr>
<?php foreach($this->product_list as $product){ ?>
<tr>
    <td class="tdc">&nbsp;<?php echo $product['name'];?></td>
    <td class="tdc">&nbsp;<?php echo $product['vendor'];?></td>
    <td class="tdc">&nbsp;<?php echo $product['version'];?></td>
    <?php if($this->acl->isAllowed('admin_products','update')){ ?>
    <td class="tdc" align="center">
        <a href="/panel/product/sub/view/v/edit/id/<?php echo $product['id'];?>" title="edit the Products">
        <img src="/images/edit.png" border="0"></a>
    </td>
    <?php } if($this->acl->isAllowed('admin_products','delete')){ ?>
    <td class="tdc" align="center">
        <a href="/panel/product/sub/delete/id/<?php echo $product['id'];?>" title="delete the Products, then no restore after deleted" onclick="return delok('Product');">
        <img src="/images/del.png" border="0"></a>
    </td>
    <?php } if($this->acl->isAllowed('admin_products','read')){ ?>
    <td class="tdc" align="center">
        <a href="/panel/product/sub/view/id/<?php echo $product['id'];?>" title="display the Products">
        <img src="/images/view.gif" border="0"></a>
    </td>
    <?php }?>
</tr>
<?php }?>
</table>
