<?php
Fisma_Format_Section::startSection("Account Log List <span id='searchResultsTotalFound'></span>"); 
?>
<div id="list"></div>
<script type="text/javascript">
// Column definitions
var myColumnDefs = [
    {key:"id", label:"id",hidden: true}
    ,{key:"createdTs", label:"TimeStamp", sortable: true, hidden: false}
    ,{key:"username", label:"User", sortable: true, hidden: false}
    ,{key:"ip", label:"Address Ip", sortable: true, hidden: false}
    ,{key:"event", label:"Event", sortable: true, hidden: false}
    ,{key:"message", label:"Message", sortable: false, hidden: false}
];

    // A function which builds the query string
    var myRequestBuilder = function(oState, oSelf) {
        // Get states or use defaults
        oState = oState || {pagination:null, sortedBy:null};
        var sort = (oState.sortedBy) ? oState.sortedBy.key : "id";
        var dir = (oState.sortedBy && oState.sortedBy.dir == 'yui-dt-asc') ? "asc" : "desc";
        var startIndex = oState.pagination.recordOffset;
        var count = oState.pagination.rowsPerPage;

        // Build custom request
        var request = "<?php echo $this->escape($this->link, 'none') ?>" + 
                      "/sortby/" + sort +
                      "/order/" + dir +
                      "/startIndex/" + startIndex +
                      "/count/" + count;
        return request;
    };

    var myDataSource = new YAHOO.util.DataSource('/log/search');
    myDataSource.responseType = YAHOO.util.DataSource.TYPE_JSON;
    myDataSource.responseSchema = {
        resultsList: "table.records",
        metaFields: {
            totalRecords: "table.totalRecords"
        }
    };
    
    // DataTable configuration
    var myConfigs = {
        initialRequest: "<?php echo $this->escape($this->link, 'none') ?>"
                      + "/sortby/id/order/desc/startIndex/0/count/"
                      + "<?php echo $this->escape($this->pageInfo['count']) ?>",
        dynamicData: true, 
        sortedBy : {key:"id", dir:YAHOO.widget.DataTable.CLASS_ASC},
        paginator: new YAHOO.widget.Paginator(
            {
                rowsPerPage:<?php echo $this->escape($this->pageInfo['count'])?>,
                template:"{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
            }
        ),
        generateRequest : myRequestBuilder
    };
    
    var myDataTable = new YAHOO.widget.DataTable("list", myColumnDefs, myDataSource, myConfigs);
    // Update totalRecords on the fly with value from server
    myDataTable.handleDataReturnPayload = function(oRequest, oResponse, oPayload) {
        oPayload.totalRecords = oResponse.meta.totalRecords;
        // display total records in the search results header, if not already present
        var searchResultsHeader = document.getElementById('searchResultsTotalFound');
        if (!searchResultsHeader.firstChild) {
            var totalRecords = oResponse.meta.totalRecords ? oResponse.meta.totalRecords : 0;
            var searchTotalFound = document.createTextNode('(' + totalRecords + ' records found)');
            searchResultsHeader.appendChild(searchTotalFound);
        }
        return oPayload;
    }
    
    myDataTable.subscribe("rowMouseoverEvent", myDataTable.onEventHighlightRow); 
    myDataTable.subscribe("rowMouseoutEvent", myDataTable.onEventUnhighlightRow);
</script>
<?php Fisma_Format_Section::stopSection(); ?>
