<?php $this->table = $this->securityControl->getTable(); ?>
<table class="keyValues table-hover">
    <tr>
        <th scope='row' width="200">
            <div>
                <?php $this->column('code'); ?>:
            </div>
        </th>
        <td>
            <?php echo $this->escape($this->securityControl->code); ?>
        </td>
    </tr>
    <tr>
        <th scope='row'><?php $this->column('catalogId'); ?>:</th>
        <td><?php echo $this->escape($this->securityControl->Catalog->name)?></td>
    </tr>
    <tr>
        <th scope='row'><?php $this->column('family'); ?>:</th>
        <td><?php echo $this->escape($this->securityControl->family)?></td>
    </tr>
    <tr>
        <th scope='row'><?php $this->column('name'); ?>:</th>
        <td><?php echo $this->escape($this->securityControl->name)?></td>
    </tr>
    <tr>
        <th scope='row'><?php $this->column('control'); ?>:</th>
        <td><?php echo $this->escape($this->securityControl->control, 'none')?></td>
    </tr>
    <?php if (!empty($this->securityControl->Enhancements)): ?>
    <tr>
        <th scope='row'>Enhancements:</th>
        <td>
            <ol>
            <?php foreach ($this->securityControl->Enhancements as $enhancement): ?>
                <li><?php echo $this->escape($enhancement->description, 'none')?></li>
            <?php endforeach; ?>
            </ol>
        </td>
    </tr>
    <?php endif; ?>
    <?php if (!empty($this->securityControl->supplementalGuidance)): ?>
    <tr>
        <th scope='row'><?php $this->column('supplementalGuidance'); ?>:</th>
        <td>
            <?php echo $this->escape($this->securityControl->supplementalGuidance, 'none'); ?>
        </td>
    </tr>
    <?php endif; ?>
    <?php if (!empty($this->securityControl->externalReferences)): ?>
    <tr>
        <th scope='row'><?php $this->column('externalReferences'); ?>:</th>
        <td>
            <?php echo $this->escape($this->securityControl->externalReferences); ?>
        </td>
    </tr>
    <?php endif; ?>
    <?php if (!empty($this->securityControl->priorityCode)): ?>
    <tr>
        <th scope='row'><?php $this->column('priorityCode'); ?>:</th>
        <td>
            <?php echo $this->escape($this->securityControl->priorityCode); ?>
        </td>
    </tr>
    <?php endif; ?>
    <tr>
        <th scope="row">Low Baseline:</th>
        <td>
            <?php
            if ('LOW' == $this->securityControl->controlLevel):
                echo $this->escape($this->securityControl->code);

                $i = 0;
                foreach ($this->securityControl->Enhancements as $enhancement):
                    $i++;

                    if ('LOW' == $enhancement->level):
                        echo $this->escape(" ($i)");
                    endif;
                endforeach;
            else:
            ?>
                Not Selected
            <?php
            endif;
            ?>
        </td>
    </tr>
    <tr>
        <th scope="row">Moderate Baseline:</th>
        <td>
            <?php
            if ('LOW' == $this->securityControl->controlLevel ||
                'MODERATE' == $this->securityControl->controlLevel):

                echo $this->escape($this->securityControl->code);

                $i = 0;
                foreach ($this->securityControl->Enhancements as $enhancement):
                    $i++;

                    if ('LOW' == $enhancement->level ||
                        'MODERATE' == $enhancement->level):

                        echo $this->escape(" ($i)");
                    endif;
                endforeach;
            else:
            ?>
                Not Selected
            <?php
            endif;
            ?>
        </td>
    </tr>
    <tr>
        <th scope='row'>High Baseline:</th>
        <td>
            <?php
            if ('LOW' == $this->securityControl->controlLevel ||
                'MODERATE' == $this->securityControl->controlLevel ||
                'HIGH' == $this->securityControl->controlLevel):

                echo $this->escape($this->securityControl->code);

                $i = 0;
                foreach ($this->securityControl->Enhancements as $enhancement):
                    $i++;

                    if ('LOW' == $enhancement->level ||
                        'MODERATE' == $enhancement->level ||
                        'HIGH' == $enhancement->level):

                        echo $this->escape(" ($i)");
                    endif;
                endforeach;
            else:
            ?>
                Not Selected
            <?php
            endif;
            ?>
        </td>
    </tr>
</table>
