<?php
Fisma_Format_Section::startSection($this->cacheType . ' Cache Summary');
?>

    <table class="keyValues">
        <?php
        foreach ($this->cacheSummary as $key => $value):
        ?>
            <tr>
                <td><?=$this->escape($key)?></td>
                <td><?=$this->escape($value)?></td>
            </tr>
        <?php
        endforeach;
        ?>
    </table>
    
<?php
Fisma_Format_Section::stopSection();
Fisma_Format_Section::startSection($this->cacheType . ' Cache Items');

if (isset($this->cacheItems)):
?>
    <table class="keyValues">
        <tr>
            <?php
            foreach ($this->cacheItemHeaders as $header):
            ?>
                <th><?=$this->escape($header)?></th>
            <?php
            endforeach;
            ?>
        </tr>
        
        <?php
        foreach ($this->cacheItems as $cacheItem):
        ?>
            <tr>
                <?php
                foreach ($cacheItem as $itemValue):
                ?>
                    <td><?=$this->escape($itemValue) ?></td>
                <?php
                endforeach;
                ?>
            </tr>
        <?php
        endforeach;
        ?>
    </table>
    
<?php
endif;

Fisma_Format_Section::stopSection();
?>
