<?php

echo $this->escape($this->searchBox($this->toolbarButtons, $this->searchForm, $this->searchButtons), 'none');

Fisma_Format_Section::startSection('Create: ' . $this->translate($this->modelName)); ?>

<div>
    Required fields are denoted by an asterisk (*)

    <?php echo $this->escape($this->form, 'none');?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
<script>
YAHOO.util.Event.onDOMReady(function() {
    if ($('.editable').length <= 0) {
        Fisma.Editable.turnAllOn();
    }
});
</script>
