<?php

echo $this->escape($this->searchBox($this->toolbarButtons, $this->searchForm), 'none');

$actions = '';

foreach ($this->links as $label => $url) {
    if ('delete' === strtolower($label)) {
        $deleteUrl = $url;
    }
    $actions .= "&nbsp;&nbsp;[<a href='$url' id = '" . $label . "Link' >$label</a>]";
}

Fisma_Format_Section::startSection('Edit: ' . $this->modelName . $actions); 

?>

<div>
    <?php echo $this->escape($this->form, 'none') ?>
</div>

<?php
Fisma_Format_Section::stopSection(); 

if (!empty($deleteUrl)):
?>
<script type="text/javascript">
    YAHOO.util.Event.onDOMReady(function () {

        var url = {url : '<?php echo $this->escape($deleteUrl) ?>' };
        YAHOO.util.Event.addListener("DeleteLink", "click", Fisma.Util.showDeleteWarning, url);
    });
</script>
<?php
endif;
?>
