<?php 

echo $this->escape(
    $this->searchBox(
        $this->toolbarButtons, 
        $this->searchForm, 
        $this->searchMoreOptionsForm,
        $this->advancedSearchOptions,
        $this->searchResultsTable
    ), 
    'none'
);

Fisma_Format_Section::startSection($this->pluralModelName . " <span id='searchResultsTotalFound'></span>"); 

echo $this->escape($this->searchResultsTable, 'none');

Fisma_Format_Section::stopSection();

?>
