<div class="column left">
    <div style='text-align: center;'>
        <?php
            echo $this->escape($this->statusChart, 'none');
        ?>
    </div>
</div>

<div class="column right">
    <div style='text-align: center;'>
        <?php
            echo $this->escape($this->categoryChart, 'none');
        ?>
    </div>
</div>

<div class="clear"></div>

<div>
    <div style='text-align: center;'>
        <?php
            echo $this->escape($this->bureauChart, 'none');
        ?>
    </div>
</div>

<div class="clear"></div>

<?php
Fisma_Format_Section::startSection('Privileges')
?>
    These graphs are generated based on all finding data available in OpenFISMA, however due to your user
    privileges you may not actually be able to view the details of all of these findings.
<?php
Fisma_Format_Section::stopSection();
?>
