<div class="column left">
    <div style='text-align: center;'>
        <?php
        Fisma_Format_Section::startSection('Incident History');

        echo $this->escape($this->statusChart, 'none');
        ?>
        
        <em>
            Incidents reported, resolved, and rejected each month for the last 6 months.
        </em>

        <?php
        Fisma_Format_Section::stopSection();
        ?>
    </div>
</div>

<div class="column right">
    <div style='text-align: center;'>
        <?php
        Fisma_Format_Section::startSection('Incident Categories');

        echo $this->escape($this->categoryChart, 'none');
        ?>
        
        <em>
            Breakdown of all open incidents by category.
        </em>

        <?php
        Fisma_Format_Section::stopSection();
        ?>
    </div>
</div>

<div class="clear"></div>

<div>
    <div style='text-align: center;'>
        <?php
        Fisma_Format_Section::startSection('Reported Incidents By Bureau');

        echo $this->escape($this->bureauChart, 'none');
        ?>
        
        <em>
            Incidents per bureau reported in the last 90 days.
        </em>

        <?php
        Fisma_Format_Section::stopSection();
        ?>
    </div>
</div>

<div class="clear"></div>

<?php
Fisma_Format_Section::startSection('Privileges')
?>
    These graphs are generated based on all incident data available in OpenFISMA, however due to your user 
    privileges you may not actually be able to view the details of all of these incidents.
<?php
Fisma_Format_Section::stopSection();
?>
