<div id="footerLinks">
    <a href="mailto:<?php echo Fisma::configuration()->getConfig('contact_email');?>?Subject=<?php echo 
    urlencode(Fisma::configuration()->getConfig('contact_subject'));?>">Contact Administrator</a>&nbsp;|&nbsp;
    <a href="/auth/rob/">Rules of Behavior</a>&nbsp;|&nbsp;
    <a href="/auth/privacy/">Privacy Policy</a>&nbsp;|&nbsp;
    <i>Powered by <a href="http://www.openfisma.org" target='_blank'>OpenFISMA</a></i>
</div>
<div class="clear">
