<div id="footerLinks">
    <a href="mailto:<?php echo Fisma_Controller_Front::readSysConfig('contact_email');?>?Subject=<?php echo 
    urlencode(Fisma_Controller_Front::readSysConfig('contact_subject'));?>">Contact Administrator</a>&nbsp;|&nbsp;
    <a href="/panel/user/sub/rob/">Rules of Behavior</a>&nbsp;|&nbsp;
    <a href="/panel/user/sub/privacy/">Privacy Policy</a>&nbsp;|&nbsp;
    <i>Powered by <a href="http://www.openfisma.org" target='_blank'>OpenFISMA</a></i>
</div>
<div class="clear">
