<table width="100%" border="0" cellpadding="0" cellspacing="0">
	<tr><td><img id="logo" src="/images/customer_logo.jpg" /></td>
		<td align="right">
                <form class="button_link" action="/user/logout">
                <input type="submit" value="Logout" /></form>
                <p><b><?php echo $this->identity;  ?></b> is currently logged in.</p>
		</td>
	</tr>
</table>
<div id="menu">
<?php 
    echo '<img src="/images/menu_line.gif" border="0">';
    if($this->acl->isAllowed('dashboard','read')) {
        echo 
        "<ul>
             <li>
             <h2><a href='/panel/dashboard'>Dashboard</a></h2>
             </li>
         </ul>";
        echo '<img src="/images/menu_line.gif" border="0">';
    }
    if($this->acl->isAllowed('asset','read')) {
        echo'<ul><li><h2><a href="/panel/asset/sub/searchbox/s/search">Assets</a></h2></li></ul>';
        echo'<img src="/images/menu_line.gif" border="0">';
    }
    if($this->acl->isAllowed('finding','read')) {
        echo'<ul><li><h2><a>Findings</a></h2>';
        echo'<ul>';
        if($this->acl->isAllowed('remediation', 'read')) {
            echo'<li><a href="/panel/remediation/sub/summary">Summary</a>';
            echo'<li><a href="/panel/remediation/sub/searchbox">Search</a>';
        }
        if($this->acl->isAllowed('finding','create')) {
            echo'<li><a href="/panel/finding/sub/create">Create New Finding</a>';
        }
        if($this->acl->isAllowed('finding','inject')) {
            echo'<li><a href="/panel/finding/sub/injection">Upload Spreadsheet</a>';
            echo'<li><a href="/panel/finding/sub/plugin">Upload Scan Results</a>';
        }
        if ($this->acl->isAllowed('finding', 'approve')) {
            echo'<li><a href="/panel/finding/sub/approve">Approve Pending Findings</a>';
        }
        echo '</ul>
             </li></ul>';
        echo '<img src="/images/menu_line.gif" border="0">';
    }
    if($this->acl->isAllowed('report','read')) { 
        echo'<ul><li><h2><a>Reports</a></h2>';
        echo'<ul>';
        if($this->acl->isAllowed('report', 'generate_poam_report' )) {
            echo'<li><a href="/panel/report/sub/poam">POA&amp;M Report</a>';
        }            
        if($this->acl->isAllowed('report','generate_fisma_report')) {
            echo'<li><a href="/panel/report/sub/fisma">FISMA POA&amp;M Report</a>';
        }
        if($this->acl->isAllowed('report','generate_general_report')) {
            echo'<li><a href="/panel/report/sub/general">General Report</a>';
        }
        if($this->acl->isAllowed('report','generate_system_rafs')) {
            echo'<li><a href="/panel/report/sub/rafs">Generate System RAFs</a>';
        }
        if($this->acl->isAllowed('report','generate_overdue_report')) {
            echo'<li><a href="/panel/report/sub/overdue">Overdue Report</a>';
        }       
        echo '<li><a href="/panel/report/sub/plugin">Plug-in Reports</a>';     
        echo'</ul>
             </li></ul>';
        echo '<img src="/images/menu_line.gif" border="0">';
    }
    if($this->acl->isAllowed('admin','read')) {
        echo'<ul><li><h2><a>Administration</a></h2>';
        echo'<ul>';
        if($this->acl->isAllowed('app_configuration','update')) {
            echo'<li><a href="/panel/config">Configuration</a></li>';
        }
        if($this->acl->isAllowed('admin_sources','read')) {
            echo'<li><a href="/panel/source/sub/list">Finding Sources</a>';
        }
        if($this->acl->isAllowed('admin_networks','read')){
            echo'<li><a href="/panel/network/sub/list">Networks</a>';
        }
        if($this->acl->isAllowed('admin_products','read')) {
            echo'<li><a href="/panel/product/sub/list">Products</a>';
        }
        if($this->acl->isAllowed('admin_roles','read')){
            echo'<li><a href="/panel/role/sub/list">Roles</a>';
        }
        if($this->acl->isAllowed('admin_organizations','read')) {
            echo'<li><a href="/panel/Organization/sub/list">Organization</a>';
        }
        if($this->acl->isAllowed('admin_systems','read')) {
            echo'<li><a href="/panel/system/sub/list">Systems</a>';
        }
        if($this->acl->isAllowed('admin_users','read')) {
            echo'<li><a href="/panel/account/sub/list">Users</a>';
        }
        echo'</ul>
            </li></ul>';
        echo '<img src="/images/menu_line.gif" border="0">';
    }
    echo'<ul><li><h2><a>User Preferences</a></h2>
        <ul>
            <li><a href="/panel/user/sub/profile">Profile</a>
            <li><a href="/panel/user/sub/password">Change Password</a>
            <li><a href="/panel/user/sub/notifications">Notifications</a>
        </ul></ul>';
    echo '<img src="/images/menu_line.gif" border="0">';
?>
</div>
<div id="msgbar"></div>
