<div id="logo">
    <a href="/"><img alt="Logo" src="/images/logo.png"></a>
</div>
<div id="logout">
    <?php 
    echo new Fisma_Yui_Form_Button_Link(
        'logoutButton', 
        array(
            'value' => 'Log Out',
            'imageSrc' => '/images/logout.png',
            'href' => '/auth/logout'
        )
    ); 
    ?>
    <p>
        <b>
            <?php echo User::currentUser()->nameFirst . ' ' . User::currentUser()->nameLast; ?>
        </b>
        is currently logged in
    </p>
</div>

<div id="menubar"><!-- YUI renders the menubar into this div --></div>
<script type="text/javascript">
var jsonMenuDataString = '<?php echo $this->menuData; ?>';

//Constructs menu bar
function buildUpYuiMenuBar(jsonMenuData)
{
    var menuData = YAHOO.lang.JSON.parse(jsonMenuData);
    var oMenuBar = new YAHOO.widget.MenuBar("mainmenu", {autosubmenudisplay: true});
    YAHOO.util.Dom.addClass(oMenuBar.element, "yuimenubarnav");
    oMenuBar.addItems(menuData);
    oMenuBar.render('menubar');
}

buildUpYuiMenuBar(jsonMenuDataString);
</script>
<div id="msgbar"><!-- Any user error messages are rendered into this div --></div>
