<div id="logo">
    <a href="/"><img alt="Logo" src="/images/logo.png"></a>
</div>
<div id="logout">
    <?php 
    echo new Fisma_Yui_Form_Button_Link(
        'logoutButton', 
        array(
            'value' => 'Log Out',
            'imageSrc' => '/images/logout.png',
            'href' => '/auth/logout'
        )
    ); 
    ?>
    <p>
        <b>
            <?php echo User::currentUser()->nameFirst . ' ' . User::currentUser()->nameLast; ?>
        </b>
        is currently logged in
    </p>
</div>

<div id="menubar"><!-- YUI renders the menubar into this div --></div>
<script type="text/javascript">
//Constructs the YUI menu bar for OpenFISMA
var jsonMenuData = '<?php echo Zend_Json_Encoder::encode($this->mainMenuBar->getMenus()); ?>';
var menuData = YAHOO.lang.JSON.parse(jsonMenuData);
var menuBar = new YAHOO.widget.MenuBar("mainmenu", {autosubmenudisplay: true});
YAHOO.util.Dom.addClass(menuBar.element, "yuimenubarnav");
menuBar.addItems(menuData);
menuBar.render('menubar');
</script>
<div id="msgbar"></div>
