<?php

echo $this->escape($this->searchBox($this->toolbarButtons, $this->searchForm), 'none');

Fisma_Format_Section::startSection("Tree View");

?>

<p>
    Only Contacts and Users can be moved around on this screen. If you want to move around organizations or information
    systems, you will need to do that in the organization hierarchy.
</p>

<p>
    <button type="button" id="expandAllButton">Expand All</button>
    <button type="button" id="collapseAllButton">Collapse All</button>
</p>

<input name="csrf" type="hidden" value="<?php echo $this->escape($this->csrfToken); ?>">
<div id="pocTreeContainer" class="draggableTreeContainer"></div>

<script type="text/javascript">
YAHOO.util.Event.onDOMReady(
    function () {
        var treeView = new Fisma.PocTreeView("pocTreeContainer");
        treeView.render();

        var expandAllButton = new YAHOO.widget.Button("expandAllButton");
        expandAllButton._button.style.background = "url('/images/expand.png') 1em 50% no-repeat";
        expandAllButton._button.style.paddingLeft = '3em';
        expandAllButton.on("click", treeView.expandAll, treeView, true);

        var collapseAllButton = new YAHOO.widget.Button("collapseAllButton");
        collapseAllButton._button.style.background = "url('/images/collapse.png') 1em 50% no-repeat";
        collapseAllButton._button.style.paddingLeft = '3em';
        collapseAllButton.on("click", treeView.collapseAll, treeView, true);
    }
);
</script>

<?php Fisma_Format_Section::stopSection(); ?>
