<table class="searchFilters">
    <tbody>
        <tr>
            <th>[<a href="/panel/role/sub/list">Roles List</a>] (total: <?php echo 
$this->total;?>)</th>
            <?php if($this->acl->isAllowed('admin_roles', 'create')) { ?>
            <th>[<a href="/panel/role/sub/create" title="Add New Role">Add 
Role</a>]</th>
            <?php } ?>
            <th>
                <table align="center">
                    <tbody>
                        <tr>
                            <td><b>Page:&nbsp;</b></td>
                            <td><?php echo $this->links['all'];?></td>
                            <td>|</td>
                        </tr>
                    </tbody>
                </table>
            </th>
            <th>
                <table align="center">
                <form name="query" method="post" action="/panel/role/sub/list">
                    <tbody>
                        <tr>
                            <td><b>Query:&nbsp;</b></td>
                            <td><input name="qv" value="<?php echo $this->qv;?>" title="Input your query value" size="20" maxlength="40" type="text"></td>

                             <td><input value="Search" title="submit your request" type="submit"></td>
                        </tr>
                    </tbody>
                </form>
                </table>
            </th>
        </tr>
    </tbody>
</table>
