<div class="searchFilters">
    <div class="left">
        <?php 
        $listButton = new Fisma_Yui_Form_Button_Link('listButton', 
                                               array('value' => 'Role List', 
                                                     'href' => '/panel/role/sub/list'));
        echo $listButton;
        ?>

        <?php if(Fisma_Acl::hasPrivilege('role', 'create')) {
        $createButton = new Fisma_Yui_Form_Button_Link('createButton', 
                                               array('value' => 'Add Role', 
                                                     'href' => '/panel/role/sub/create'));
        echo $createButton;
        } ?>
    </div>
    <div class="right">
        <?php if (is_dir(Fisma::getPath('index') . '/role')) { ?>
        <form name="query" method="post" action="/panel/role/sub/list" style="display:inline">
        <span class="searchField">
            <b>Search:&nbsp;</b>
            <input id="keywords" name="keywords" value="<?php echo $this->keywords;?>" title="Input your query value" size="20" maxlength="40" type="text">
        </span>
        <span id="searchContainer"></span>
        <script type='text/javascript'>
           var save = new YAHOO.widget.Button({
               type: "submit",
               label: "Search",
               value: "Search",
               container: "searchContainer",
               disabled: false
           });
        </script>
        </form>
        <?php } ?>
    </div>
    <div class="clear"></div>
</div>
