<?php
echo $this->partial('role/searchbox.phtml');
$operation = '';
if (Fisma_Acl::hasPrivilege('role', 'assignPrivileges')) {
    $operation .= "[<a href='{$this->rightLink}'>Right</a>]";
}
if (Fisma_Acl::hasPrivilege('role', 'update')) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->editLink}'>Edit</a>]";
}
if (Fisma_Acl::hasPrivilege('role', 'delete')) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}
Fisma_Format_Section::startSection("Role Information $operation"); 
?>

<div>
    <?php echo $this->form ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
