<table class="ir_report ir_report_dash">
    <tr>
        <th style="border-left: 0px;">&nbsp;</th>
        <th colspan="3">Open Incidents</th>
        <th colspan="3">Resolved Incidents</th>
        <th colspan="3">Closed Incidents</th>
    </tr>
    <tr>
        <th style="border-left: 0px;">&nbsp;</th>
        <th>Week</th>
        <th>Month</th>
        <th>Year</th>
        <th>Week</th>
        <th>Month</th>
        <th>Year</th>
        <th>Week</th>
        <th>Month</th>
        <th>Year</th>
    </tr>

<?php

foreach ($this->cats as $id => $cat ) {
        print "<tr><th style='text-align:right; border-left: 0px;'>{$cat['category']}</th>";

        print "<td>";
        if( $this->incident_current['week'][$cat['category']]['open'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".$this->weeks[date('W')]['start']."/end_date/".$this->weeks[date('W')]['end']."/status/open/category/{$cat['category']}'>{$this->incident_current['week'][$cat['category']]['open']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['month'][$cat['category']]['open'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".date('Y')."-".date('m')."-01/end_date/".date('Y')."-".date('m')."-".date('t')."/status/open/category/{$cat['category']}'>{$this->incident_current['month'][$cat['category']]['open']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['year'][$cat['category']]['open'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".date('Y')."-01-01/end_date/".date('Y')."-12-31/status/open/category/{$cat['category']}'>{$this->incident_current['year'][$cat['category']]['open']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['week'][$cat['category']]['resolved'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".$this->weeks[date('W')]['start']."/end_date/".$this->weeks[date('W')]['end']."/status/resolved/category/{$cat['category']}'>{$this->incident_current['week'][$cat['category']]['resolved']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['month'][$cat['category']]['resolved'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".date('Y')."-".date('m')."-01/end_date/".date('Y')."-".date('m')."-".date('t')."/status/resolved/category/{$cat['category']}'>{$this->incident_current['month'][$cat['category']]['resolved']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['year'][$cat['category']]['resolved'] == '0') {
            print "0";
        } else {
            print "<a href='panel/irreport/sub/report/start_date/".date('Y')."-01-01/end_date/".date('Y')."-12-31/status/resolved/category/{$cat['category']}'>{$this->incident_current['year'][$cat['category']]['resolved']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['week'][$cat['category']]['closed'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".$this->weeks[date('W')]['start']."/end_date/".$this->weeks[date('W')]['end']."/status/closed/category/{$cat['category']}'>{$this->incident_current['week'][$cat['category']]['closed']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['month'][$cat['category']]['closed'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".date('Y')."-".date('m')."-01/end_date/".date('Y')."-".date('m')."-".date('t')."/status/closed/category/{$cat['category']}'>{$this->incident_current['month'][$cat['category']]['closed']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['year'][$cat['category']]['closed'] == '0') {
            print "0";
        } else {
            print "<a href='panel/irreport/sub/report/start_date/".date('Y')."-01-01/end_date/".date('Y')."-12-31/status/closed/category/{$cat['category']}'>{$this->incident_current['year'][$cat['category']]['closed']}</a>";
        }
        print "</td>";
        
        print "</tr>";
}

?>
</table>
