<?php Fisma_Format_Section::startSection("Current Incicdents By Cateogry"); ?>

<table class="ir_report">
    <tr>
        <th colspan="2" style="border-left: 0px;">&nbsp;</th>
        <th colspan="3">Open Incidents</th>
        <th colspan="3">Resolved Incidents</th>
        <th colspan="3">Closed Incidents</th>
    </tr>
    <tr>
        <th colspan="2" style="border-left: 0px;">&nbsp;</th>
        <th>Week</th>
        <th>Month</th>
        <th>Year</th>
        <th>Week</th>
        <th>Month</th>
        <th>Year</th>
        <th>Week</th>
        <th>Month</th>
        <th>Year</th>
    </tr>

<?php
foreach ($this->cats as $id => $cat ) {
    foreach ($cat['children'] as $key => $subcat) {
        print "<tr><th style='text-align:right; border-left: 0px;'>{$cat['category']}</th><th style='text-align:left;'>{$subcat['name']}</th>";

        print "<td>";
        if( $this->incident_current['week'][$cat['category']][$subcat['id']]['open'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".$this->weeks[date('W')]['start']."/end_date/".$this->weeks[date('W')]['end']."/status/open/category/{$subcat['id']}'>{$this->incident_current['week'][$cat['category']][$subcat['id']]['open']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['month'][$cat['category']][$subcat['id']]['open'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".date('Y')."-".date('m')."-01/end_date/".date('Y')."-".date('m')."-".date('t')."/status/open/category/{$subcat['id']}'>{$this->incident_current['month'][$cat['category']][$subcat['id']]['open']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['year'][$cat['category']][$subcat['id']]['open'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".date('Y')."-01-01/end_date/".date('Y')."-12-31/status/open/category/{$subcat['id']}'>{$this->incident_current['year'][$cat['category']][$subcat['id']]['open']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['week'][$cat['category']][$subcat['id']]['resolved'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".$this->weeks[date('W')]['start']."/end_date/".$this->weeks[date('W')]['end']."/status/resolved/category/{$subcat['id']}'>{$this->incident_current['week'][$cat['category']][$subcat['id']]['resolved']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['month'][$cat['category']][$subcat['id']]['resolved'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".date('Y')."-".date('m')."-01/end_date/".date('Y')."-".date('m')."-".date('t')."/status/resolved/category/{$subcat['id']}'>{$this->incident_current['month'][$cat['category']][$subcat['id']]['resolved']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['year'][$cat['category']][$subcat['id']]['resolved'] == '0') {
            print "0";
        } else {
            print "<a href='panel/irreport/sub/report/start_date/".date('Y')."-01-01/end_date/".date('Y')."-12-31/status/resolved/category/{$subcat['id']}'>{$this->incident_current['year'][$cat['category']][$subcat['id']]['resolved']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['week'][$cat['category']][$subcat['id']]['closed'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".$this->weeks[date('W')]['start']."/end_date/".$this->weeks[date('W')]['end']."/status/closed/category/{$subcat['id']}'>{$this->incident_current['week'][$cat['category']][$subcat['id']]['closed']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['month'][$cat['category']][$subcat['id']]['closed'] == '0') {
            print "0";
        } else {
            print "<a href='/panel/irreport/sub/report/start_date/".date('Y')."-".date('m')."-01/end_date/".date('Y')."-".date('m')."-".date('t')."/status/closed/category/{$subcat['id']}'>{$this->incident_current['month'][$cat['category']][$subcat['id']]['closed']}</a>";
        }
        print "</td>";
        
        print "<td>";
        if( $this->incident_current['year'][$cat['category']][$subcat['id']]['closed'] == '0') {
            print "0";
        } else {
            print "<a href='panel/irreport/sub/report/start_date/".date('Y')."-01-01/end_date/".date('Y')."-12-31/status/closed/category/{$subcat['id']}'>{$this->incident_current['year'][$cat['category']][$subcat['id']]['closed']}</a>";
        }
        print "</td>";
        
        print "</tr>";
    }
}

?>
</table>
<?php Fisma_Format_Section::stopSection(); ?>



<div id="foo" style="width: 55%; float: left;">
<?php Fisma_Format_Section::startSection("Inicdents by Month (2009)"); ?>
<table class="ir_report">
<?php

print "<tr><td colspan='2' style='border-left: 0px;'>&nbsp;</td>";

$months = array(    '1' => 'Jan', '2' => 'Feb', '3' => 'Mar', '4' => 'Apr', '5' => 'May', '6' => 'Jun', 
                    '7' => 'Jul', '8' => 'Aug', '9' => 'Sept', '10' => 'Oct', '11' => 'Nov', '12' => 'Dec' );

for($x=1;$x<=12;$x+=1) {
    print "<th style='padding-left: 3px; padding-right: 3px;'>{$months[$x]}</th>";
}

print "</tr>";

foreach ($this->cats as $id => $cat ) {
    foreach ($cat['children'] as $key => $subcat) {
        print "<tr><th style='border-left: 0px; text-align: right;'>{$cat['category']}</th><th style='text-align: left;'>{$subcat['name']}</th>";

        for($x=1;$x<=12;$x+=1) {
            print "<td>";

            if ($this->incident_month[$x][$cat['category']][$subcat['id']]['count'] == '0') {
                print "0";
            } else {
                print "<a href='/panel/irreport/sub/report/start_date/2009-".str_pad(($x), 2, "0", STR_PAD_LEFT)."-01/end_date/2009-".str_pad(($x+1), 2, "0", STR_PAD_LEFT)."-01/status/all/category/{$subcat['id']}'>{$this->incident_month[$x][$cat['category']][$subcat['id']]['count']}</a>";
            }

            print "</td>";
        }
        
        print "</tr>";
    }
}



?>
</table>
<?php Fisma_Format_Section::stopSection(); ?>
</div>

<div id="foo" style="width: 43%; float: right;">
<?php Fisma_Format_Section::startSection("Inicdents by Year"); ?>
<table class="ir_report">
<?php

print "<tr><td colspan='2' style='border-left: 0px;'>&nbsp;</td>";

for($x=2008;$x<=2010;$x+=1) {
    print "<th style='padding-left: 3px; padding-right: 3px;'>$x</th>";
}

print "</tr>";

foreach ($this->cats as $id => $cat ) {
    foreach ($cat['children'] as $key => $subcat) {
        print "<tr><th style='border-left: 0px; text-align: right;'>{$cat['category']}</th><th style='text-align: left;'>{$subcat['name']}</th>";

        for($x=2008;$x<=2010;$x+=1) {
            print "<td>";

            if ($this->incident_year[$x][$cat['category']][$subcat['id']]['count'] == '0') {
                print "0";
            } else {
                print "<a href='/panel/irreport/sub/report/start_date/$x-01-01/end_date/".($x+1)."-01-01/status/all/category/{$subcat['id']}'>{$this->incident_year[$x][$cat['category']][$subcat['id']]['count']}</a>";
            }

            print "</td>";
        }
        
        print "</tr>";
    }
}



?>
</table>
<?php Fisma_Format_Section::stopSection(); ?>
</div>

<div class="clear"></div>

<?php Fisma_Format_Section::startSection("Incidents by Week (2009)"); ?>

<table class="ir_report">
<?php

print "<tr><th colspan='2' style='border-left: 0px;'>&nbsp;</th>";

for($x=1;$x<54;$x+=1) {
    print "<th><abbr title='{$this->weeks[$x]['start_nice']} to {$this->weeks[$x]['end_nice']}'>$x</abbr></th>";
}

print "</tr>";

foreach ($this->cats as $id => $cat ) {
    foreach ($cat['children'] as $key => $subcat) {
        print "<tr><th style='border-left: 0px; text-align: right;'>{$cat['category']}</th><th style='text-align: left;'>{$subcat['name']}</th>";

        for($x=1;$x<54;$x+=1) {
            print "<td>";

            if ($this->incident_week[$x][$cat['category']][$subcat['id']]['count'] == '0') {
                print "0";
            } else {
                print "<a href='/panel/irreport/sub/report/start_date/{$this->weeks[$x]['start']}/end_date/{$this->weeks[$x]['end']}/status/all/category/{$subcat['id']}'>{$this->incident_week[$x][$cat['category']][$subcat['id']]['count']}</a>";
            }

            print "</td>";
        }
        
        print "</tr>";
    }
}



?>
</table>

<?php Fisma_Format_Section::stopSection(); ?>
