<?php
$operation = '';

if ($this->updateIrCategoryPrivilege):
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
endif;

if ($this->deleteIrCategoryPrivilege):
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
endif;

Fisma_Format_Section::startSection("Sub Category Information</b> $operation"); 
?>

<div>
    <?php echo $this->form ?>
</div>

<?php 
Fisma_Format_Section::stopSection();
?>
