<?php
$operation = '';

if ($this->updateIrCategoryPrivilege):
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
endif;

if ($this->deleteIrCategoryPrivilege):
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
endif;

Fisma_Format_Section::startSection("Category Information</b> $operation"); 
?>

<div>
    <?php echo $this->escape($this->form, 'none'); ?>
</div>

<?php 
Fisma_Format_Section::stopSection(); 
?>
