<?php
    echo $this->escape("{$this->doctype()}\n", 'none');
    $inactivityPeriod = Fisma::configuration()->getConfig('session_inactivity_period') * 60;
    $inactivityNotice = Fisma::configuration()->getConfig('session_inactivity_notice') * 60;
?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <script type="text/javascript">
            window.uniqueCounter = 0;
            window.onerror = function(errorMessage, scriptUrl, lineNumber) {
                this.uniqueCounter++;
                var now     = new Date(),
                    uniqid  = this.uniqueCounter.toString(16) + now.getTime(),
                    xmlhttp = null,
                    params  = 'errorMessage=' + encodeURIComponent(errorMessage)
                            + '&scriptUrl=' + encodeURIComponent(scriptUrl)
                            + '&lineNumber=' + encodeURIComponent(lineNumber);

                if (window.XMLHttpRequest) {
                    xmlhttp = new XMLHttpRequest();
                } else if (window.ActiveXObject) { // Older IE.
                    xmlhttp = new ActiveXObject("MSXML2.XMLHTTP.3.0");
                }

                xmlhttp.onreadystatechange = function() {
                    if (xmlhttp.readyState === 4){
                        console.log('An error has been logged.');
                    }
                };

                xmlhttp.open('POST', '/default/error/jslog/uuid/' + uniqid, true);
                xmlhttp.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
                xmlhttp.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
                xmlhttp.send(params);
            }
        </script>
    <?php
    echo $this->partial('partial/title.phtml');

    $yuiComponents = array('yahoo', 'dom', 'event', 'element', 'container', 'json', 'cookie', 'get', 'dragdrop',
                           'animation', 'menu', 'button', 'json', 'connection', 'logger', 'tabview', 'calendar',
                           'paginator', 'datasource', 'datatable', 'selector', 'treeview', 'uploader',
                           'reset-fonts-grids', 'autocomplete', 'progressbar', 'history', 'swf', 'storage', 'base');

    $yui = new Fisma_Loader();
    $yui->load($yuiComponents);

    $this->headScript()->appendFile('/javascripts/tiny_mce/tiny_mce.js');
    $this->injectAsset('/javascripts/excanvas.js', 'js', false, 'screen', 'IE');
    $this->injectAsset('/javascripts/combined.js', 'js', true);
    $this->injectAsset('/stylesheets/combined.css', 'css', true);
    $this->injectAsset('/stylesheets/print.css', 'css', false, 'print');
    $this->injectAsset('/stylesheets/ie9hacks.css', 'css', false, 'screen', 'IE 9');
    $this->injectAsset('/stylesheets/ie8hacks.css', 'css', false, 'screen', 'IE 8');
    $this->injectAsset('/stylesheets/ie7hacks.css', 'css', false, 'screen', 'IE 7');
    $this->injectAsset('/stylesheets/ie6hacks.css', 'css', false, 'screen', 'IE 6');

    $this->headLink()->headLink(array('rel' => 'icon', 'href' => '/images/favicon.ico'));

    echo $this->escape($yui->css(), 'none');
    echo $this->escape($this->headLink(), 'none');
    echo $this->escape($yui->script(), 'none');
    echo $this->escape($this->headScript(), 'none');
    ?>
    </head>
    <body class="yui-skin-sam">
        <script type="text/javascript">
            Fisma.SessionManager.init(
                <?php echo $this->escape($inactivityPeriod, 'json');?>,
                <?php echo $this->escape($inactivityNotice, 'json'); ?>);
        </script>
        <div id='skip'>
            <a href="#contentStart">Skip to content</a>
        </div>

        <div id='header'>
                <?php
                    if (Zend_Auth::getInstance()->hasIdentity()) {
                        echo $this->partial('partial/header.phtml');
                    }
                ?>
        </div>

        <div class="externalMediaMarking">
            WARNING: This document is for internal, official use only.  This document contains sensitive computer
            security related information. Public disclosure of this information would risk circumvention of the
            law. Recipients of this document must not, under any circumstances, show or release its contents for
            purposes other than official action. This document must be safeguarded to prevent improper disclosure.
            Staff reviewing this document must hold a minimum of Public Trust Level 5C clearance.
        </div>

        <?php echo $this->escape($this->viewAs(), 'none'); ?>
        <?php echo $this->escape($this->breadcrumbs(), 'none'); ?>

        <a name="contentStart"></a>
        <div id='content'>
            <div id="msgbar"></div>

            <?php echo $this->escape($this->layout()->content, 'none'); ?>
        </div>

        <div id='footer'>
                <?php
                    if (Zend_Auth::getInstance()->hasIdentity()) {
                        echo $this->partial('partial/footer.phtml');
                    }
                ?>
        </div>
        <div id="swfstoreContainer"></div>

    </body>
    <?php echo $this->partial('partial/priorityMessage.phtml', array('messages' => $this->priorityMessenger())); ?>
</html>
