<?php
    echo $this->escape("{$this->doctype()}\n", 'none');
?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 
<?php
    $this->headTitle()->prepend(Fisma::configuration()->getConfig('system_name'));
    echo $this->escape($this->headTitle(), 'none');
    $yuiComponents = array('yahoo', 'dom', 'event', 'element', 'container', 'button');

    $yui = new Fisma_Loader();
    $yui->load($yuiComponents);
    $this->injectAsset('/stylesheets/login.css', 'css', false, 'screen,print');
    $this->headLink()->headLink(array('rel' => 'icon', 'href' => '/images/favicon.ico'));

    echo $this->escape($yui, 'none');
    echo $this->escape($this->headScript(), 'none');
    echo $this->escape($this->headLink(), 'none');
?>

<script type="text/javascript">
    YAHOO.util.Event.onAvailable(
        'content',
        function () {
            loginPanel = new YAHOO.widget.Panel(
                "content", 
                {
                    width:"600px", 
                    visible:true, 
                    draggable: false, 
                    close: false, 
                    fixedcenter: true,
                    constraintoviewport: true
                } 
            ); 
            loginPanel.render();
            loginPanel.focusFirst();
        }
    );
</script>

</head>

<body class="yui-skin-sam">
    <div id="content">
        <?php echo $this->escape($this->layout()->content, 'none'); ?>
    </div>
    <div id='footer'>
        <div id='footerLinks'>
            <a href="mailto:<?php
                                echo $this->escape(Fisma::configuration()->getConfig('contact_email'), 'none');
                            ?>?Subject=<?php 
                                echo $this->escape(Fisma::configuration()->getConfig('contact_subject'), 'url');
                            ?>">Contact Administrator</a>&nbsp;|&nbsp;
                            
            <a href="/auth/rob/">Rules of Behavior</a>&nbsp;|&nbsp;
            <a href="/auth/privacy/">Privacy Policy</a>&nbsp;|&nbsp;
            <i>Powered by <a href="http://www.openfisma.org">OpenFISMA</a></i>
        </div>
    </div>
</body>
<?php echo $this->partial('partial/priorityMessage.phtml', array('messages' => $this->priorityMessenger())); ?>
</html>
