<?php echo "{$this->doctype()}\n" ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 
<?php
    echo $this->headTitle()->prepend(Config_Fisma::readSysConfig('system_name'));
    Yui::includeLibrary('yahoo-dom-event');
    Yui::includeLibrary('element');
    Yui::includeLibrary('button');
	echo Yui::printIncludes();
 
    echo $this->headLink()->appendStylesheet('/yui/assets/skins/sam/skin.css')
                          ->appendStylesheet('/stylesheets/login.css', 'screen,print')
                          ->headLink(array('rel' => 'icon', 'href' => '/images/favicon.ico'));
?>
</head>

<body class="yui-skin-sam">
    <div id="header"></div>
    <div id="stripes"></div>
    <div id="content">
        <?php echo $this->layout()->content; ?>
    </div>
    <div id='footer'>
        <hr style="color: #44637A;" size="1">
        <div id='footerLinks'>
            <a href="mailto:<?php echo Config_Fisma::readSysConfig('contact_email');?>?Subject=<?php echo urlencode(Config_Fisma::readSysConfig('contact_subject'));?>">Contact Administrator</a>&nbsp;|&nbsp;
            <a href="/user/rob/">Rules of Behavior</a>&nbsp;|&nbsp;
            <a href="/user/privacy/">Privacy Policy</a>&nbsp;|&nbsp;
            <i>Powered by <a href="http://www.openfisma.org">OpenFISMA</a></i>
        </div>
    </div>
</body>

</html>
