<?php echo "{$this->doctype()}\n" ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
        <?php
            echo $this->headTitle()->prepend(Fisma::configuration()->getConfig('system_name'));
            Fisma_Yui::includeLibrary('yahoo-dom-event');
            Fisma_Yui::includeLibrary('element');
            Fisma_Yui::includeLibrary('button');    
            echo Fisma_Yui::printIncludes();
            echo $this->headLink()->appendStylesheet('/yui/assets/skins/sam/skin.css')
                                  ->appendStylesheet('/stylesheets/main.css', 'screen,print')
                                  ->headLink(array('rel' => 'icon', 'href' => '/images/favicon.ico'));
        ?>
    </head>
    <body class="yui-skin-sam">
        <div id='container'>
            <div id="content">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>
