<?php echo "{$this->doctype()}\n" ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
        <?php
            $this->headTitle()->prepend($this->pageTitle());
            echo $this->escape($this->headTitle(), 'none');

            $yuiComponents = array('yahoo', 'dom', 'event', 'element', 'button');

            $yui = new Fisma_Loader();
            $yui->load($yuiComponents);
            $this->injectAsset('/stylesheets/combined.css', 'css', true);
            $this->headLink()->headLink(array('rel' => 'icon', 'href' => '/images/favicon.ico'));

            echo $yui;
            echo $this->headLink();
            echo $this->headScript();
        ?>
    </head>
    <body class="yui-skin-sam">
        <div id='container'>
            <div id="content">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>
