<?php Fisma_Format_Section::startSection('System Inventory Dashboard'); ?>

<?php foreach ($this->metrics as $name => $metric): ?>
    <div class="dashboardCard <?php echo $this->escape($metric['color']); ?>">
        <div class="title"><?php echo $this->escape($metric['title']); ?></div>
    
        <div class="metric"><?php echo $this->escape($metric['value'] . $metric['suffix']); ?></div>
    </div>
<?php endforeach; ?>

<div class="clear"></div>

<div class="column left">
    <div class='dashboardChart'>
        <?php echo $this->escape($this->fipsCategoryChart, 'none'); ?>
            
        FIPS-199 Categorizations
    </div>
</div>

<div class="column right">
    <div class='dashboardChart'>
        <?php echo $this->escape($this->agencyContractorChart, 'none'); ?>
            
        Agency &amp; Contractor Systems
    </div>
</div>

<div class="clear"></div>

<?php Fisma_Format_Section::stopSection(); ?>
