<?php

/**
 * FindingRelationship
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class FindingRelationship extends BaseFindingRelationship
{
    public function getReverseAction()
    {
        $tags = explode('/', $this->relationship, 2);
        return (empty($tags[1]) ? $tags[0] : $tags[1]);
    }

    public function getDirectAction()
    {
        $tags = explode('/', $this->relationship, 2);
        return $tags[0];
    }

    public static function isDirectAction($relationship)
    {
        $tags = explode(',', Fisma::configuration()->getConfig('finding_link_types'));
        foreach ($tags as $tag) {
            $tagComponents = explode('/', $tag, 2);
            if (count($tagComponents) > 1 && $relationship === $tagComponents[1]) {
                return false;
            }
        }
        return true;
    }

    public static function getFullTag($relationship)
    {
        $tags = explode(',', Fisma::configuration()->getConfig('finding_link_types'));
        foreach ($tags as $tag) {
            if (strpos($tag, $relationship) !== false) {
                return $tag;
            }
        }
        return $relationship; // $relationship outdated, returns itself
    }
}