<?php
/**
 * Copyright (c) 2012 Endeavor Systems, Inc.
 *
 * This file is part of OpenFISMA.
 *
 * OpenFISMA is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * OpenFISMA is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with OpenFISMA.  If not, see
 * {@link http://www.gnu.org/licenses/}.
 */

/**
 * FindingRelationship
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class FindingRelationship extends BaseFindingRelationship
{
    public function getReverseAction()
    {
        $tags = explode('/', $this->relationship, 2);
        return (empty($tags[1]) ? $tags[0] : $tags[1]);
    }

    public function getDirectAction()
    {
        $tags = explode('/', $this->relationship, 2);
        return $tags[0];
    }

    public static function isDirectAction($relationship)
    {
        $tags = explode(',', Fisma::configuration()->getConfig('finding_link_types'));
        foreach ($tags as $tag) {
            $tagComponents = explode('/', $tag, 2);
            if (count($tagComponents) > 1 && $relationship === $tagComponents[1]) {
                return false;
            }
        }
        return true;
    }

    public static function getFullTag($relationship)
    {
        $tags = explode(',', Fisma::configuration()->getConfig('finding_link_types'));
        foreach ($tags as $tag) {
            if (strpos($tag, $relationship) !== false) {
                return $tag;
            }
        }
        return $relationship; // $relationship outdated, returns itself
    }
}
