<?php

/**
 * Finding
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class Finding extends BaseFinding
{
    /**
     * log the behaviors of finding
     *
     * @param User  $userId
     * @param string  $message
     */
    public function log($userId, $message)
    {

    }

    /**
     * get the detailed status of a POAM,
     *
     * @return string
     */
    public function getStatus()
    {

    }

    /**
     * Approve the current evaluation,
     * then update the status to either point to
     * a new Evaluation or else to change the status to DRAFT, EN,
     * or CLOSED as appropriate
     *
     * @return void
     */
    public function approve()
    {

    }

    /**
     * Deny the current evaluation
     * @param string $comment deny comment
     * @return void
     */
    function deny($comment)
    {

    }

}
