<?php

/**
 * IrStep
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 */
class IrStep extends BaseIrStep
{
    /**
     * Override parent to make room for new step
     *
     * @param Doctrine_Query $openGapQuery Optional, default to null, used primarily for testing
     * @param Doctrine_Event $event
     * @param return void
     */
    public function preInsert($event, $openGapQuery = null)
    {
        $this->_openGap($this->workflowId, $this->cardinality, $openGapQuery);
    }

    /**
     * Override parent to implement shuffling over steps around to make room for this step.
     * Should only have an effect when workflowId and/or cardinality are modified
     *
     * @param Doctrine_Event $event
     * @return void
     */
    public function preUpdate($event)
    {
        $oldValues = $this->getModified(true);
        $wfChanged = isset($oldValues['workflowId']);
        $carChanged = isset($oldValues['cardinality']);
        // when the workflow changes, we need to close the gap in the old workflow and open a gap in the new one
        if ($wfChanged || $carChanged) {
            $oldWf = $wfChanged ? $oldValues['workflowId'] : $this->workflowId;
            $oldCar = $carChanged ? $oldValues['cardinality'] : $this->cardinality;
            // first, close the gap
            $this->_closeGap($oldWf, $oldCar);
            // now open a gap in the target workflow
            $this->_openGap($this->workflowId, $this->cardinality);
        }
    }

    /**
     * Override parent to close gap left by removing step
     *
     * @param Doctrine_Event $event
     * @param Doctrine_Query $closeGapQuery Optional, default to null, used primarily for testing
     * @return void
     */
    public function postDelete($event, $closeGapQuery = null)
    {
        $i = $event->getInvoker();
        $this->_closeGap($i->workflowId, $i->cardinality, $closeGapQuery);
    }

    /**
     * Open a gap in a workflow to insert a step
     *
     * @param int $workflowId ID of workflow within which to open the gap
     * @param int $position   Position in workflow where the gap should be created
     * @return void
     * @deprecated pending on the removal of executions from model classes
     */
    protected function _openGap($workflowId, $position, $openGapQuery = null)
    {
        $openGapQuery = (isset($openGapQuery)) ? $openGapQuery : self::openGapQuery($workflowId, $position);
        $openGapQuery->execute(); 
    }

    /**
     * Build the query for _openGap()
     * 
     * @param int $workflowId ID of workflow within which to open the gap
     * @param int $position   Position in workflow where the gap should be created
     * @return Doctrine_Query
     */
    public static function openGapQuery($workflowId, $position)
    {
        $openGapQuery = Doctrine_Query::create()->update('IrStep irstep')
                                                ->set('irstep.cardinality', 'irstep.cardinality + 1')
                                                ->where('irstep.workflowId = ?', $workflowId)
                                                ->andWhere('irstep.cardinality >= ?', $position);
        return $openGapQuery;
    }

    /**
     * Close a gap in a workflow to insert a step
     *
     * @param int $workflowId ID of workflow in which to perform the operation
     * @param int $position   Position of the gap to be closed.
     * @return void
     * @deprecated pending on the removal of executions from model classes
     */
    protected function _closeGap($workflowId, $position, $closeGapQuery = null)
    {
        $closeGapQuery = (isset($closeGapQuery)) ? $closeGapQuery : self::closeGapQuery($workflowId, $position);
        $closeGapQuery->execute(); 
    }
    
    /**
     * Build the query for _closeGap()
     * 
     * @param int $workflowId ID of workflow in which to perform the operation
     * @param int $position   Position of the gap to be closed.
     * @return Doctrine_Query
     */
    public static function closeGapQuery($workflowId, $position)
    {
        $closeGapQuery = Doctrine_Query::create()->update('IrStep irstep')
                                                 ->set('irstep.cardinality', 'irstep.cardinality - 1')
                                                 ->where('irstep.workflowId = ?', $workflowId)
                                                 ->andWhere('irstep.cardinality >= ?', $position);
        return $closeGapQuery;
    }
}
