<?php

/**
 * IrWorkflowDef
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id$
 */
class IrWorkflowDef extends BaseIrWorkflowDef
{
    /**
     * preDelete 
     * 
     * @param Doctrine_Event $event 
     * @access public
     * @return void
     */
    public function preDelete($event)
    {
        if (count($this->Steps) > 0) {
            throw new Fisma_Zend_Exception_User(
            /** @todo english */
                'This workflow can not be deleted because it is already associated with one or more steps'
            );
        }

        if (count($this->SubCategories) > 0) {
            throw new Fisma_Zend_Exception_User(
            /** @todo english */
                'This workflow can not be deleted because it is already associated with one or more sub-categories'
            );
        }
    }
}
