<?php

/**
 * LdapConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class LdapConfig extends BaseLdapConfig
{
    private $_mapLdap = array(
            'host' => 'host',
            'port' => 'port',
            'username' => 'username',
            'password' => 'password',
            'useSsl' => 'useSsl',
            'bindRequiresDn' => 'bindRequiresDn',
            'baseDn' => 'basedn',
            'accountFilterFormat' => 'accountFilter',
            'accountCanonicalForm' => 'accountCanonical',
            'accountDomainNameShort' => 'domainShort',
            'accountDomainName' => 'domainName'
    );
    
    /**
     *  Retrive the ldap configuration(s)
     *
     *  @param numeric $id default null the group id of ldap config
     *  @return array all the configurations of LDAP servers. One configuration 
     *      if the $id is specified. 
     */
    public function getLdaps($id = null)
    {
        if (is_array($id)) {
            $q = Doctrine_Query::create()
                           ->from('LdapConfig lc')
                           ->whereIn('lc.id', $id);
            $ldapConfigs = $q->execute();
        } elseif (is_numeric($id)) {
            $ldapConfigs[] = Doctrine::getTable('LdapConfig')->find($id);
        } else {
            $ldapConfigs = Doctrine::getTable('LdapConfig')->findAll();
        }
        $ldapData = array();
        $i = 0;
        foreach ($ldapConfigs as $ldapConfig) {
            foreach ($this->_mapLdap as $k => $v) {
                $ldapData[$i][$k] = $ldapConfig->$v;
            }
            $i ++;
        }
        return $ldapData;
    }
}