<?php
/**
 * Copyright (c) 2008 Endeavor Systems, Inc.
 *
 * This file is part of OpenFISMA.
 *
 * OpenFISMA is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenFISMA is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenFISMA.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author    Ryan Yang <ryanyang@users.sourceforge.net>
 * @copyright (c) Endeavor Systems, Inc. 2008 (http://www.endeavorsystems.com)
 * @license   http://www.openfisma.org/mw/index.php?title=License
 * @version   $Id$
 * @package   Model
 */
 
/**
 * LdapConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package   Model
 * @copyright (c) Endeavor Systems, Inc. 2008 (http://www.endeavorsystems.com)
 * @license   http://www.openfisma.org/mw/index.php?title=License
 */
class LdapConfig extends BaseLdapConfig
{
    /**
     *  Retrive the ldap configuration(s)
     *
     *  @return array all the configurations of LDAP servers. One configuration if the $id is specified.
     */
    public function getLdaps()
    {
        $ldapConfigs = Doctrine::getTable('LdapConfig')->findAll()->toArray();
        
        //Remove the id field from each LDAP configuration item
        foreach ($ldapConfigs as &$ldapConfig) {
            unset($ldapConfig['id']);
        }

        return $ldapConfigs;
    }
}
