<?php

/**
 * Network
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class Network extends BaseNetwork
{
    public function preSave()
    {
        Doctrine_Manager::connection()->beginTransaction();   
    }
    
    public function preDelete()
    {
         Doctrine_Manager::connection()->beginTransaction();       
    }

    public function postInsert()
    {
        $notification = new Notification();
        $notification->add(Notification::NETWORK_CREATED, $this, User::currentUser());
        Doctrine_Manager::connection()->commit();

        Fisma_Lucene::updateIndex('network', $this);
    }

    public function postUpdate()
    {
        $notification = new Notification();
        $notification->add(Notification::NETWORK_MODIFIED, $this, User::currentUser());
        Doctrine_Manager::connection()->commit();

        Fisma_Lucene::updateIndex('network', $this);
    }

    public function postDelete()
    {
        $notification = new Notification();
        $notification->add(Notification::NETWORK_DELETED, $this, User::currentUser());
        Doctrine_Manager::connection()->commit();

        Fisma_Lucene::deleteIndex('network', $this->id);
    }
}
