<?php

/**
 * Privilege
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 * 
 * @todo Make sure that we have privileges for all parts of a finding
 */
class Privilege extends BasePrivilege
{

}