<?php

/**
 * Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class Product extends BaseProduct
{
    public function postInsert()
    {
        Notification::notify(Notification::PRODUCT_CREATED, $this, User::currentUser());
        Fisma_Lucene::updateIndex('source', $this);

    }

    public function postUpdate()
    {
        Notification::notify(Notification::PRODUCT_MODIFIED, $this, User::currentUser());
        Fisma_Lucene::updateIndex('product', $this);

    }

    public function postDelete()
    {
        Notification::notify(Notification::PRODUCT_DELETED, $this, User::currentUser());
        Fisma_Lucene::deleteIndex('product', $this->id);
    }
}
