<?php

/**
 * Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class Product extends BaseProduct
{
    public function preInsert()
    {
        Notification::notify(Notification::PRODUCT_CREATED, $this, User::currentUser());
    }

    public function preUpdate()
    {
        Notification::notify(Notification::PRODUCT_MODIFIED, $this, User::currentUser());
    }

    public function preDelete()
    {
        Notification::notify(Notification::PRODUCT_DELETED, $this, User::currentUser());
    }

    public function postSave(Doctrine_Event $event)
    {
        $product  = $event->getInvoker();
        $modified = $product->getModified($old=false, $last=true);
        Fisma_Lucene::updateIndex('product', $product->id, $modified);
    }

    public function postDelete(Doctrine_Event $event)
    {
        $product  = $event->getInvoker();
        Fisma_Lucene::deleteIndex('product', $product->id);
    }
}
