<?php

/**
 * Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class Role extends BaseRole
{
    /**
     * Implements the interface for Zend_Acl_Role_Interface
     */
    public function getRoleId()
    {
        return $this->id;
    }
}
