<?php

/**
 * Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class Role extends BaseRole
{
    /**
     * Implements the interface for Zend_Acl_Role_Interface
     */
    public function getRoleId()
    {
        return $this->id;
    }

    public function preSave()
    {
        Doctrine_Manager::connection()->beginTransaction();   
    }
    
    public function preDelete()
    {
         Doctrine_Manager::connection()->beginTransaction();       
    }

    public function postInsert()
    {
        Notification::notify(Notification::ROLE_CREATED, $this, User::currentUser());
        Doctrine_Manager::connection()->commit();

        Fisma_Lucene::updateIndex('role', $this);
    }

    public function postUpdate()
    {
        Notification::notify(Notification::ROLE_MODIFIED, $this, User::currentUser());
        Doctrine_Manager::connection()->commit();

        Fisma_Lucene::updateIndex('role', $this);
    }

    public function postDelete()
    {
        Notification::notify(Notification::ROLE_DELETED, $this, User::currentUser());
        Doctrine_Manager::connection()->commit();

        Fisma_Lucene::deleteIndex('role', $this->id);
    }
}
