<?php

/**
 * Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class Role extends BaseRole
{
    /**
     * Implements the interface for Zend_Acl_Role_Interface
     */
    public function getRoleId()
    {
        return $this->id;
    }

    public function preInsert()
    {
        Notification::notify(Notification::ROLE_CREATED, $this, User::currentUser());
    }

    public function preUpdate()
    {
        Notification::notify(Notification::ROLE_MODIFIED, $this, User::currentUser());
    }

    public function preDelete()
    {
        Notification::notify(Notification::ROLE_DELETED, $this, User::currentUser());
    }

    public function postSave(Doctrine_Event $event)
    {
        $role  = $event->getInvoker();
        $modified = $role->getModified($old=false, $last=true);
        Fisma_Lucene::updateIndex('role', $role->id, $modified);
    }

    public function postDelete(Doctrine_Event $event)
    {
        $role  = $event->getInvoker();
        Fisma_Lucene::deleteIndex('role', $role->id);
    }
}
