<?php

/**
 * SaSecurityControlEnhancement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class SaSecurityControlEnhancement extends BaseSaSecurityControlEnhancement
{
    /**
     * Hook to add assessment plan entries for inserted control enhancements
     *
     * @param mixed $event
     * @return void
     */
    public function postInsert($event)
    {
        $procedures = Doctrine_Query::create()
            ->from('AssessmentProcedure ap')
            ->where('ap.controlCode = ?', $this->SaSecurityControl->SecurityControl->code)
            ->andWhere('ap.enhancement = ?', $this->SecurityControlEnhancement->number)
            ->execute();
        foreach ($procedures as $ap) {
            $ape = new AssessmentPlanEntry();
            $ape->SaSecurityControlAggregate = $this;
            $ape->number = $ap->number;
            $ape->objective = $ap->objective;
            $ape->examine = $ap->examine;
            $ape->interview = $ap->interview;
            $ape->test = $ap->test;
            $ape->save();
        }
    }

    /**
     * Hook to remove assessment plan entries before deleting
     *
     * @param mixed $event
     * @return void
     */
     public function preDelete($event)
     {
         foreach ($this->AssessmentProcedures as $ape) {
             $ape->delete();
         }
     }
}
