<?php

/**
 * SecurityControlCatalog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 */
class SecurityControlCatalog extends BaseSecurityControlCatalog
{

}