<?php

/**
 * SystemDocument
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class SystemDocument extends BaseSystemDocument
{
    /**
     * Return the physical path to this document
     * 
     * @return string
     */
    public function getPath() 
    {
        $path = Fisma::getPath('systemDocument')
              . '/'
              . $this->systemId
              . '/'
              . $this->fileName;
              
        return $path;
    }
    
    /**
     * Returns a URL for an icon which represents this document
     * 
     * @return string
     */
    public function getIconUrl()
    {
        $pi = pathinfo($this->fileName);
        $extension = strtolower($pi['extension']);
        $imagePath = Fisma::getPath('image');
        if (file_exists("$imagePath/mimetypes/$extension.png")) {
            return "/images/mimetypes/$extension.png";
        } else {
            return "/images/mimetypes/unknown.png";
        }
    }
}
