<?php Format_Section::startSection("Organization List"); ?>

<table width="98%" align="center" border="0" cellpadding="0" cellspacing="0" class="tbframe">
<tr align="center">
    <th>Organization Name</th>
    <th>Organization Nickname</th>
    <?php if($this->acl->isAllowed('admin_organizations','update')){
              echo'<th>Edit</th>';
          } 
          if($this->acl->isAllowed('admin_organizations','read')){
              echo'<th>View</th>';
          }
          if($this->acl->isAllowed('admin_organizations','delete')){
              echo'<th>Del</th>';
          }
    ?>
</tr>
<?php foreach($this->organization_list as $organization){ ?>
<tr>
    <td class="tdc">&nbsp;<?php echo $organization['name'];?></td>
    <td class="tdc">&nbsp;<?php echo $organization['nickname'];?></td>
    <?php if($this->acl->isAllowed('admin_organizations','update')){ ?>
    <td class="tdc" align="center">
        <a href="/panel/organization/sub/view/v/edit/id/<?php echo $organization['id'];?>" title="edit the Organizations">
        <img src="/images/edit.png" border="0"></a>
    </td>
    <?php } if($this->acl->isAllowed('admin_organizations','read')){ ?>
    <td class="tdc" align="center">
        <a href="/panel/organization/sub/view/id/<?php echo $organization['id'];?>" title="display the Organizations">
        <img src="/images/view.gif" border="0"></a>
    </td>
    <?php } if($this->acl->isAllowed('admin_organizations','delete')){ ?>
    <td class="tdc" align="center">
        <a href="/panel/organization/sub/delete/id/<?php echo $organization['id'];?>" title="delete the Organizations, then no restore after deleted" onclick="return delok('Organization');">
        <img src="/images/del.png" border="0"></a>
    </td>
    <?php }?>
</tr>
<?php }?>
</table>

<?php Format_Section::stopSection(); ?>
