<table class="searchFilters">
    <tbody>
        <tr>
            <th>[<a href="/panel/organization/sub/list">Organization List</a>] 
            <?php if (!empty($this->total)) { ?>(total: <?php echo $this->total;?>) <?php } ?></th>
            <?php //if($this->acl->isAllowed('admin_organizations', 'create')) { ?>
            <th>[<a href="/panel/organization/sub/create" title="add new Organizations">Add Organization</a>]</th>
            <?php //} ?>
            </th>
            <?php if (is_dir(Fisma_Controller_Front::getPath('data') . '/index/organization')) { ?>
            <th>
                <table align="center">
                <form name="query" method="post" action="/panel/organization/sub/list">
                    <tbody>
                        <tr>
                            <td><b>Query:&nbsp;</b></td>
                            <td><input name="keywords" value="<?php echo $this->keywords;?>" title="Input your query value" size="20" maxlength="40" type="text"></td>

                             <td><input value="Search" title="submit your request" type="submit"></td>
                        </tr>
                    </tbody>
                </form>
                </table>
            </th>
            <?php } ?>
        </tr>
    </tbody>
</table>
