<div class="searchFilters">
    <span id='listButton'></span>
    <script type='text/javascript'>
        YAHOO.util.Event.onDOMReady(function() {
            var button = new YAHOO.widget.Button({  
                 type: "link",  
                 label: "Organization List",  
                 href: "/panel/organization/sub/list",
                 id: "listButton",
                 disabled: false,
                 container: "listButton"
            });
        
    });</script>
    <?php //if(Fisma_Acl::hasPrivilege('admin_organizations', 'create')) { ?>
    <span id='createButton'></span>
    <script type='text/javascript'>
        YAHOO.util.Event.onDOMReady(function() {
            var button = new YAHOO.widget.Button({  
                 type: "link",  
                 label: "Add Organization",  
                 href: "/panel/organization/sub/create",
                 id: "createButton",
                 disabled: false,
                 container: "createButton"
            });
    });</script>
    <?php //} ?>
    <?php if (is_dir(Fisma_Controller_Front::getPath('data') . '/index/organization')) { ?>
    <form name="query" method="post" action="/panel/organization/sub/list" style="display:inline">
    <b>Query:&nbsp;</b>
    <input id="keywords" name="keywords" value="<?php echo $this->keywords;?>" title="Input your query value" size="20" maxlength="40" type="text">
    <span id="searchContainer"></span>
    <script type='text/javascript'>
       var save = new YAHOO.widget.Button({
           type: "submit",
           label: "Search",
           value: "Search",
           container: "searchContainer",
           disabled: false
       });
    </script>
    </form>
    <?php } ?>
</div>