<?php
$operation = '';
if (Fisma_Zend_Acl::hasPrivilegeForObject('update', $this->organization)) {
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
}
if (Fisma_Zend_Acl::hasPrivilegeForObject('delete', $this->organization)) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}
Fisma_Format_Section::startSection("Organization Information</b> $operation"); ?>

<div>
    <?php echo $this->escape($this->form, 'none'); ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
