<div class="searchBox">
    <div class="left" id='toolbarLeft'>
        <?php
        foreach ($this->toolbarButtons as $button):
            echo $this->escape($button, 'none');
        endforeach;
        ?>
    </div>

    <div class="right" id='toolbarRight'>
        <?php if(isset($this->searchButtons)):
            foreach ($this->searchButtons as $button):
                echo $this->escape($button, 'none');
            endforeach;
        endif; ?>
    </div>

    <?php if(isset($this->searchForm)): ?>
        <div
            id='toolbarForm'
            class="<?php echo $this->escape(($this->searchFormLeft) ? 'left' : 'right'); ?>" style='margin-left:5px;'
        >
            <?php if ($this->searchForm->getElement('keywords')): ?>
            <label for='keywords' style='display:none'>Keywords</label>
            <?php endif; ?>
            <?php echo $this->escape($this->searchForm, 'none'); ?>
        </div>
    <?php endif; ?>

    <div class="clear"></div>
</div>