<div class="searchBox">
    <div class="left">
        <?php
        foreach ($this->toolbarButtons as $button):
            echo $this->escape($button, 'none');
        endforeach;
        ?>
    </div>
    
    <div class="right">
        <?php
        echo $this->escape($this->searchForm, 'none');
        ?>
    </div>

    <div class="clear"></div>
</div>

<div id="searchColumns" class="searchBox">
    <div id="searchColumnsButtons"></div>
</div>

<div id="advancedSearch" class="searchBox"  style="display: none;"></div>

<script>
    YAHOO.util.Event.onContentReady (
        "searchColumns", 
        function () {
            var advancedSearchOptions = <?php echo $this->escape($this->advancedSearchOptions, 'none'); ?>;
        
            Fisma.Search.initializeSearchColumnsPanel(
                document.getElementById('searchColumnsButtons'), 
                advancedSearchOptions
            );
        }
    );

    YAHOO.util.Event.onContentReady (
        "advancedSearch", 
        function () {
            var advancedSearchOptions = <?php echo $this->escape($this->advancedSearchOptions, 'none'); ?>;

            var searchPanel = new Fisma.Search.Panel(advancedSearchOptions);
            
            Fisma.Search.advancedSearchPanel = searchPanel;

            searchPanel.render(document.getElementById('advancedSearch'));
        }
    );
</script>
