<div class="searchBox">
    <div class="left">
        <?php
        foreach ($this->toolbarButtons as $button):
            echo $this->escape($button, 'none');
        endforeach;
        ?>
    </div>
    
    <?php if(isset($this->searchButtons)): ?>
        <div class="right">
            <?php
                foreach ($this->searchButtons as $button):
                    echo $this->escape($button, 'none');
                endforeach;
            ?>
        </div>
    <?php endif; ?>

    <?php if(isset($this->searchForm)): ?>
        <div class="right">
            <?php
            echo $this->escape($this->searchForm, 'none');
            ?>
        </div>
    <?php endif; ?>

    <div class="clear"></div>
</div>

