<?php if (!empty($this->userId)): ?>
    <span
        class='userInfo<?php echo $this->escape($this->status); ?>'
        title='User<?php echo $this->escape($this->status); ?>'
    >
        <span
            onclick="Fisma.User.displayUserInfo(this, '<?php echo $this->escape($this->userId, 'javascript'); ?>');"
            title="Click to show user information">
            <?php echo $this->escape($this->displayText); ?>
        </span>
    </span>
<?php endif; ?>
