<?php Fisma_Format_Section::startSection('An Error Has Occurred&hellip;'); ?>
<?php
    if (Fisma::debug()) {
?>
    <p><i>Application is currently in debugging mode:</i></p>
    <p class="stacktrace"><?=$this->escape($this->content, 'none') ?></p>
<?php    
    } else {
        echo $this->escape($this->message);
    }
?>
<p>
    Technical Support Contact: <?=$this->escape(Fisma::configuration()->getConfig('contact_name'))?><br>
    Contact Phone: <?=$this->escape(Fisma::configuration()->getConfig('contact_phone'))?><br>
    Contact E-mail: <a href="mailto:<?=$this->escape(Fisma::configuration()->getConfig('contact_email'), 'none')?>">
            <?php echo $this->escape(Fisma::configuration()->getConfig('contact_email'));?></a>
</p>

<?php Fisma_Format_Section::stopSection(); ?>
