<?php Fisma_Format_Section::startSection('An Error Has Occurred&hellip;'); ?>
<?php
    if (Fisma::debug()) {
?>
    <p><i>Application is currently in debugging mode:</i></p>
    <p class="stacktrace"><?php echo $this->content; ?></p>
<?php    
    } else {
        echo $this->message;
    }
?>
<p>
    Technical Support Contact: <?php echo Fisma::configuration()->getConfig('contact_name');?><br>
    Contact Phone: <?php echo Fisma::configuration()->getConfig('contact_phone');?><br>
    Contact E-mail: <a href="mailto:<?php echo Fisma::configuration()->getConfig('contact_email');?>">
            <?php echo Fisma::configuration()->getConfig('contact_email');?></a>
</p>

<?php Fisma_Format_Section::stopSection(); ?>
