<?php
echo $this->escape($this->addInformationTypeButton, 'none');
?>
<div id="addInformationTypes">
    <div class="sectionHeader">
        <span>Add Information Types</span>
    </div>
    <div class="section">
<?php
echo $this->escape($this->availableInformationTypesTable, 'none');
?>
    </div>
</div>
<?php
Fisma_Format_Section::startSection('Assigned Information Types');
echo $this->escape($this->informationTypesTable, 'none');
Fisma_Format_Section::stopSection();
Fisma_Format_Section::startSection('FIPS-199 Security Categorization');
?>
<table class="keyValues">
    <tr>
        <td>FIPS-199 Categorization: </td>
        <td>
            <?php echo $this->escape($this->system->fipsCategory); ?>
        </td>
    </tr>
</table>
<?php
Fisma_Format_Section::stopSection();
?>
