<?php
Fisma_Format_Section::startSection('Information Types');
echo $this->escape($this->informationTypesTable, 'none');
Fisma_Format_Section::stopSection();
Fisma_Format_Section::startSection('FIPS-199 Security Categorization');
?>
<table class="keyValues">
    <tr>
        <td>FIPS-199 Categorization: </td>
        <td>
            <?php echo $this->escape($this->system->fipsCategory); ?>
        </td>
    </tr>
</table>
<?php
Fisma_Format_Section::stopSection();
?>
