<div class="column66 left">
<?php
Fisma_Format_Section::startSection('Details');
?>
<table class="keyValues">
    <tr>
        <td>System Name: </td>
        <td>
            <?php
            if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
            ?>
            <span id="name" class="editable" target="name" name="name" type="text">
                <?php echo $this->escape($this->organization->name); ?>
            </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->escape($this->organization->name); ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>System Nickname: </td>
        <td>
            <?php
            if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
            ?>
            <span id="nickname" class="editable" target="nickname" name="nickname" type="text">
                <?php echo $this->escape($this->organization->nickname); ?>
            </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->escape($this->organization->nickname); ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>System Type: </td>
        <td>
            <?php
            if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
            ?>
                <span id="type"
                      class="editable"
                      target="type"
                      name="systemTypeId"
                      type="select"
                      href="/metainfo/list/o/systemType/format/html/">
                    <?php echo $this->escape($this->organization->System->SystemType->name); ?>
                </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->escape($this->organization->System->SystemType->name); ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>SDLC Phase: </td>
        <td>
            <?php
            if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
            ?>
                <span id="sdlcPhase"
                      class="editable"
                      target="sdlcPhase"
                      name="sdlcPhase"
                      type="select"
                      value="<?php echo $this->escape($this->organization->System->sdlcPhase);?>"
                      href="/metainfo/list/o/systemSdlcPhase/format/html/">
                    <?php echo $this->escape($this->organization->System->getSdlcPhaseLabel()); ?>
                </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->escape($this->organization->System->getSdlcPhaseLabel()); ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>Parent Organization/System: </td>
        <td>
        <?php
            $parentOrganization = $this->organization->getNode()->getParent();
            if (!empty($parentOrganization)) {
                $organizationTypeNickname = $parentOrganization->OrganizationType->nickname;
                $parentOrganizationName = $parentOrganization->nickname . ' - ' . $parentOrganization->name;
                if ($this->acl()->hasPrivilegeForObject('read', $parentOrganization)) {
                    $parentOrgType = 'system' == $organizationTypeNickname ? 'system' : 'organization';
                    $parentOrganizationId = 'system' == $parentOrgType ?
                                            $parentOrganization->systemId : $parentOrganization->id;
                    echo $this->escape('<a href="/' . $parentOrgType . '/view/id/', 'none');
                    echo $this->escape($parentOrganizationId, 'url');
                    echo $this->escape('">', 'none');
                    echo $this->escape($parentOrganizationName);
                    echo $this->escape('</a>', 'none');
                } else {
                    echo $this->escape($parentOrganizationName);
                }
            } else {
                echo $this->escape('<i>None</i>', 'none');
            }

        ?>
        </td>
    </tr>
    <tr>
        <td>Aggregate System</td>
        <td>
        <?php if (!empty($this->aggregateSystem)): ?>
            <a href="/system/view/id/<?php echo $this->escape($this->aggregateSystem->id); ?>">
                <?php echo $this->escape($this->aggregateSystem->Organization->nickname); ?>
                -
                <?php echo $this->escape($this->aggregateSystem->Organization->name); ?>
            </a>
        <?php else: ?>
            <i>None</i>
        <?php endif; ?>
        </td>
    </tr>
</table>
<?php
Fisma_Format_Section::stopSection();

if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
    Fisma_Format_Section::startSection('System Description', 'system_description');
} else {
    Fisma_Format_Section::startSection('System Description');
}
?>
<div name="description" id="system_description" type="textarea" rows="3" cols="120">
    <?php echo $this->escape($this->organization->description, 'none'); ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>
</div>

<div class="column33 right">
    <?php Fisma_Format_Section::startSection('Dates'); ?>
        <table class="keyValues">
            <tr>
                <td>Created:</td>
                <td>
                    <?php echo $this->escape($this->createdDate)?>
                </td>
            </tr>
            <tr>
                <td>Updated:</td>
                <td>
                    <?php echo $this->escape($this->updatedDate)?>
                </td>
            </tr>
        </table>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php Fisma_Format_Section::startSection('People'); ?>
        <table class="keyValues">
            <tr>
                <td>Point of Contact:</td>
                <td class="autocomplete-width"><span id="pointOfContact"
                    type="autocomplete"
                    xhr="/contact/autocomplete/format/json"
                    queryPrepend="/keyword/"
                    schemaObject="pointsOfContact"
                    schemaField="name"
                    name="pocId"
                <?php if ($this->acl()->hasPrivilegeForClass('create', 'Poc')): ?>
                    setupCallback="Fisma.Finding.setupPocAutocomplete"
                <?php endif; ?>
                    value="<?php echo $this->escape($this->organization->Poc->username); ?>"
                    defaultValue="<?php echo $this->escape($this->organization->Poc->username); ?>"><?php
                        echo $this->escape($this->userInfo($this->organization->Poc->username), 'none');
                    ?></span>
                <?php if ($this->editable): ?>
                    <span class="editable" target="pointOfContact">&nbsp;</span>
                <?php endif; ?>
                </td>
            </tr>
        </table>
    <?php Fisma_Format_Section::stopSection(); ?>
</div>
