<div class="column left">
<?php
Fisma_Format_Section::startSection('General Information');
?>
<table class="keyValues">
    <tr>
        <td>
            <?php
                $systemNameTooltip = new Fisma_Yui_Tooltip('name', 'System Name: ',
                    "<p><b>System Name</b></p><p>Please select a unique Information System Name."
                  . " The Name will be the human readable identifier of the information system"
                  . " and used throughout OpenFISMA.</p>");
                echo $this->escape($systemNameTooltip, 'none');
            ?>
        </td>

        <td>
            <?php
            if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
            ?>
            <span id="name" class="editable" target="name" name="name" type="text">
                <?php echo $this->escape($this->organization->name); ?>
            </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->escape($this->organization->name); ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>
            <?php
                $nicknameTooltip = new Fisma_Yui_Tooltip('nickname', 'System Nickname: ',
                    "<p><b>Acronym or Nickname</b></p><p>Please select a short unique identifier"
                  . " for the information system. The short nickname will be used on reports and"
                  . " other areas of OpenFISMA to display large amounts of data in short column space.</p>");
                echo $this->escape($nicknameTooltip, 'none');
            ?>
        </td>

        <td>
            <?php
            if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
            ?>
            <span id="nickname" class="editable" target="nickname" name="nickname" type="text">
                <?php echo $this->escape($this->organization->nickname); ?>
            </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->escape($this->organization->nickname); ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>
            <?php
                $systemTypeTooltip = new Fisma_Yui_Tooltip('type', 'System Type: ',
                    "<p><b>GSS stands for General Support System</b></p><p>Definition: An interconnected set of"
                  . " information resources under the same direct management control which shares common functionality."
                  . " A General Support System may be, for example, a local area network (LAN) or an agency-wide"
                  . " backbone, or a communications network, or a departmental data processing center including its"
                  . " operating system and utilities. The term General Support System is used in context of security."
                  . " Individual applications supporting different business-related functions may run on a single GSS."
                  . " </p><p><b>Major stands for Major Application</b></p><p>Definition: An IT system that requires"
                  . " special management attention because of its importance to the organization; or its significant"
                  . " role in the administration of the organizations programs, finances, property, or other"
                  . " significant resources. An adverse impact on a major system would constitute serious, severe, or"
                  . " catastrophic harm due to the loss of confidentiality, integrity, or availability, as determined"
                  . " through conducting a system risk assessment. Major systems would be classified as either moderate"
                  . " or high impact as defined in FIPS 199. Those systems identified as Critical Infrastructure"
                  . " Protection (CIP) assets would clearly fall in this category as a major system.</p><p><b>Minor"
                  . " stands for Minor Application</b></p><p>Definition: An IT system that does not require special"
                  . " attention as it mainly provides mission supportive information to the organization and usually"
                  . " relies on another General Support System for the majority of its security controls.</p>");
                echo $this->escape($systemTypeTooltip, 'none');
            ?>
        </td>
        <td>
            <?php
            if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
            ?>
                <span id="type" 
                      class="editable" 
                      target="type" 
                      name="type" 
                      type="select" 
                      href="/metainfo/list/o/systemType/format/html/">
                    <?php echo $this->escape($this->organization->getOrgTypeLabel()); ?>
                </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->escape($this->organization->getOrgTypeLabel()); ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>
            <?php
                $missionCriticalityTooltip = new Fisma_Yui_Tooltip('missionCriticality', 'Mission Criticality: ',
                    "<p><b>Mission Criticality</b></p><p>Mission criticality, or how integral the application is to"
                  . " carrying out the mission of the agency will impact decisions regarding the implementation of"
                  . " controls and the risks posed to the agency to known vulnerabilities. Each system should be"
                  . " assigned a mission criticality of supportive, important, or critical.</p>");
                echo $this->escape($missionCriticalityTooltip, 'none');
            ?>
        </td>
        <td>
            <?php
            if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
            ?>
                <span id="missionCriticality" 
                      class="editable" 
                      target="missionCriticality" 
                      name="missionCriticality" 
                      type="select" 
                      value="<?php echo $this->escape($this->organization->System->missionCriticality);?>"
                      href="/metainfo/list/o/missionCriticality/format/html/">
                    <?php echo $this->escape($this->organization->System->missionCriticality); ?>
                </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->escape($this->organization->System->missionCriticality); ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>
            <?php
                $sdlcPhaseTooltip = new Fisma_Yui_Tooltip('sdlcPhase', 'SDLC Phase: ',
                    "<p><b>SDLC Phase</b></p>"
                  . " <p>A typical SDLC includes five phases: initiation, development/acquisition,"
                  . " implementation/assessment, operations/maintenance, and disposal. Each phase includes a minimum"
                  . " set of security tasks needed to effectively incorporate security in the system development"
                  . " process. Note that phases may continue to be repeated throughout a system's life prior to"
                  . " disposal.</p><p>This publication does not provide an exhaustive description of the acquisition"
                  . " processes. Organizations should refer to the appropriate Federal Acquisition Regulations (FAR)"
                  . " and organization-specific policies and procedures for detailed acquisition information.</p><p>"
                  . " <ul><li>Initiation. During the initiation phase, the need for a system is expressed and the"
                  . " purpose of the system is documented.</li><li>Development/Acquisition. During this phase,"
                  . " the system is designed, purchased, programmed, developed, or otherwise constructed. </li><li>"
                  . " Implementation/Assessment. After system acceptance testing, the system is installed or fielded."
                  . " </li><li> Operation/Maintenance. During this phase, the system performs its work. The system is"
                  . " almost always modified by the addition of hardware and software and by numerous other events."
                  . " </li><li>Disposal. Activities conducted during this phase ensure the orderly termination of"
                  . " the system, safeguarding vital system information, and migrating data processed by the system"
                  . " to a new system, or preserving it in accordance with applicable records management regulations"
                  . " and policies.</li></ul></p>");
                echo $this->escape($sdlcPhaseTooltip, 'none');
            ?>
        </td>
        <td>
            <?php
            if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
            ?>
                <span id="sdlcPhase" 
                      class="editable" 
                      target="sdlcPhase" 
                      name="sdlcPhase" 
                      type="select" 
                      value="<?php echo $this->escape($this->organization->System->sdlcPhase);?>"
                      href="/metainfo/list/o/systemSdlcPhase/format/html/">
                    <?php echo $this->escape($this->organization->System->getSdlcPhaseLabel()); ?>
                </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->escape($this->organization->System->getSdlcPhaseLabel()); ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>
            <?php
                $eAuthLevelTooltip = new Fisma_Yui_Tooltip('eAuthLevel', 'E-Auth Level: ',
                    "<p><b>E-Auth Level</b></p><p>Electronic authentication (E-authentication) is the process of"
                  . " establishing confidence in user identities electronically presented to an information system."
                  . " Every agency is required by the Office of Management and Budget (OMB) in Memorandum 04-04 to"
                  . " establish E-Authentication assurance levels and impacts. OMB defines four levels of"
                  . " authentication Levels 1 to 4, in terms of the consequences of the authentication errors and"
                  . " misuse of credentials. Level 1 is the lowest assurance and Level 4 is the highest. You may also"
                  . " refer to NIST Special Publication 800-63 for more guidance on Electronic Authentication"
                  . " guidelines.</p>");
                echo $this->escape($eAuthLevelTooltip, 'none');
            ?>
        </td>
        <td>
            <?php
            if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
            ?>
                <span id="eAuthLevel" 
                      class="editable" 
                      target="eAuthLevel" 
                      name="eAuthLevel" 
                      type="select" 
                      value="<?php echo $this->escape($this->organization->System->eAuthLevel);?>"
                      href="/metainfo/list/o/eAuthLevel/format/html/">
                    <?php echo $this->escape($this->organization->System->getEAuthLevelLabel()); ?>
                </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->escape($this->organization->System->getEAuthLevelLabel()); ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>Parent Organization: </td>
        <td>
        <?php
            $parentOrganization = $this->organization->getNode()->getParent();
            $organizationTypeNickname = $parentOrganization->OrganizationType->nickname;  
            if (isset($parentOrganization)) {
                $parentOrganizationName = $parentOrganization->nickname . ' - ' . $parentOrganization->name;
                if ($this->acl()->hasPrivilegeForObject('read', $parentOrganization)) {
                    $parentOrgType = 'system' == $organizationTypeNickname ? 'system' : 'organization';
                    $parentOrganizationId = 'system' == $parentOrgType ? 
                                            $parentOrganization->systemId : $parentOrganization->id;
                    echo $this->escape('<a href="/' . $parentOrgType . '/view/id/', 'none');
                    echo $this->escape($parentOrganizationId, 'url');
                    echo $this->escape('">', 'none');
                    echo $this->escape($parentOrganizationName);
                    echo $this->escape('</a>', 'none');
                } else {
                    echo $this->escape($parentOrganizationName);
                }
            } else {
                echo $this->escape('<i>None</i>', 'none');
            }

        ?>
        </td>
    </tr>
</table>
</div>
<?php
Fisma_Format_Section::stopSection();?>

<div class="column right">
    <?php Fisma_Format_Section::startSection('Points of Contact'); ?>
    <?php Fisma_Format_Section::stopSection();?>
</div>

<div class="clear"></div>

<?php
$systemDescriptionText = "<p><b>System Description</b></p>"
                         . "<p>Prepare a brief description (one to three paragraphs) of the function and purpose of"
                         . " the system (e.g., economic indicator, network support for an agency, business census"
                         . " data analysis, crop reporting support).</p>";
$systemDescriptionTooltip = new Fisma_Yui_Tooltip('systemDescription', 'System Description', $systemDescriptionText);

if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
    Fisma_Format_Section::startSection($systemDescriptionTooltip, 'system_description');
} else {
    Fisma_Format_Section::startSection($systemDescriptionTooltip);
}
?>
<div name="description" id="system_description" type="textarea" rows="3" cols="120"> 
    <?php echo $this->escape($this->organization->description, 'none'); ?>
</div>
<?php Fisma_Format_Section::stopSection();

$environmentText = "Provide a general description of the technical system. Include the primary hardware,"
    . "software, and communications equipment. Include any environmental or technical factors that raise special"
    . "security concerns, such as use of Personal Digital Assistants, wireless technology, etc.";
$environmentTooltip = new Fisma_Yui_Tooltip('systemEnvironment', 'System Environment', $environmentText);

Fisma_Format_Section::startSection($environmentTooltip, 'system_environment');?>
<div name="environment" id="system_environment" type="textarea" rows="3" cols="120">
    <?php echo $this->escape($this->organization->System->environment, 'none'); ?>
</div>
<?php Fisma_Format_Section::stopSection();

Fisma_Format_Section::startSection('System Architecture', 'system_architecture');?>
<div name="architecture" id="system_architecture" type="textarea" rows="3" cols="120">
    <?php echo $this->escape($this->system->architecture, 'none'); ?>
</div>
<?php Fisma_Format_Section::stopSection();

$interconnectionText = "System interconnection is the direct connection of two or more IT systems for "
    . "the purpose of sharing information resources. System interconnection, if not appropriately protected, "
    . "may result in a compromise of all connected systems and the data they store, process, or transmit. It "
    . "is important that system owners, information owners, and management obtain as much information as possible "
    . "regarding vulnerabilities associated with system interconnections and information sharing. This is essential "
    . "to selecting the appropriate controls required to mitigate those vulnerabilities. An Interconnection Security "
    . "Agreement (ISA), Memorandum of Understanding (MOU), or Memorandum of Agreement (MOA) is needed between systems "
    . "(not between workstations/desktops or publicly accessed systems) that share data that are owned or operated by "
    . "different organizations. An ISA is not needed with internal agency systems if an agency manages and enforces "
    . "a rigid system development life cycle, which requires approvals and sign-offs ensuring compliance with security "
    . "requirements. For additional information on interconnections, see NIST SP 800-47, Security Guide for "
    . "Interconnecting Information Technology Systems.<br /><br />"
    . "In this section, for each interconnection between systems that are owned or operated by different organizations, "
    . "provide the following information concerning the authorization for the connection to other systems or the sharing "
    . "of information: (1) Name of system; (2) Organization; (3) Type of interconnection (Internet, Dial-Up, etc.); "
    . "(4) Authorizations for interconnection (MOU/MOA, ISA); (5) Date of agreement; (6) FIPS 199 Category; "
    . "(7) Certification and accreditation status of system; and (8) Name and title of authorizing official(s). For "
    . "agencies with numerous interconnections, a table format including the above information may be a good way to "
    . "present the information.";

$interconnectionTooltip = new Fisma_Yui_Tooltip('systemInterconnection',
    'System Interconnections & Information Sharing', $interconnectionText);
Fisma_Format_Section::startSection($interconnectionTooltip, 'iis');?>
<div name="iis" id="iis" type="textarea" rows="3" cols="120">
    <?php if (is_null($this->system->iis)):
    echo '<table><tr><td>System Name</td><td>Organization</td><td>Type</td><td>Agreement</td><td>Date</td>'
        . '<td><p>FIPS 199</p><p>Category</p></td><td><p>C&amp;A</p><p>Status</p></td><td><p>Auth.</p><p>Official</p>'
        . '</td></tr><tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr><tr><td></td>'
        . '<td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td><td></td>'
        . '<td></td><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td>'
        . '<td></td></tr><tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr></table>';
    else:
        echo $this->escape($this->system->iis, 'none');
    endif;?>
</div>

<?php Fisma_Format_Section::stopSection();?>
