<div id="leftPane">
<?php
    Fisma_Format_Section::startSection('Current User Access');

    if ($this->acl()->hasPrivilegeForClass('update', 'User')) :
        echo $this->escape($this->currentUserAccessForm, 'none');
    else :
        echo $this->escape($this->tree, 'none');
    endif;
    Fisma_Format_Section::stopSection();
?>
</div>
<?php if ($this->acl()->hasPrivilegeForClass('update', 'User')) : ?>
<div id="rightPane">
    <div id="addUserAccess">
    <?php Fisma_Format_Section::startSection('Add User Access');
        echo $this->escape($this->addUserAccessForm, 'none');
     Fisma_Format_Section::stopSection(); ?>
    </div>
    <div id="copyUserAccess">
    <?php Fisma_Format_Section::startSection('Copy User Access'); ?>
    <?php echo $this->escape($this->copyUserAccessForm, 'none'); ?>
    <span id="copyUserAccessTree">
    </span>
    <?php Fisma_Format_Section::stopSection(); ?>
    </div>
</div>
<?php endif; ?>
<script type="text/javascript">
$('input[name="copySystemId"]').change(function() {
    $("#copyUserAccessTree").load('/system/get-user-access-tree/id/' + $('input[name="copySystemId"]').val());
})
</script>
