<div class="searchFilters">
    <?php
    $listButton = new Fisma_Yui_Form_Button_Link('listButton', 
                                           array('value' => 'Network List', 
                                                 'href' => '/panel/network/sub/list'));
    echo $listButton;
    ?>

    <?php if(Fisma_Acl::hasPrivilege('network', 'create')) {
    $createButton = new Fisma_Yui_Form_Button_Link('createButton', 
                                           array('value' => 'Add Network', 
                                                 'href' => '/panel/network/sub/create'));
    echo $createButton;
    } ?>
    <?php if (is_dir(Fisma::getPath('index') . '/network')) { ?>
    <form name="query" method="post" action="/panel/network/sub/list" style="display:inline">
    <b>Search:&nbsp;</b>
    <input id="keywords" name="keywords" value="<?php echo $this->keywords;?>" title="Input your query value" size="20" maxlength="40" type="text">
    <span id="searchContainer"></span>
    <script type='text/javascript'>
       var save = new YAHOO.widget.Button({
           type: "submit",
           label: "Search",
           value: "Search",
           container: "searchContainer",
           disabled: false
       });
    </script>
    </form>
    <?php } ?>
</div>
