<?php
$this->placeholder('prepend')->captureStart();
?>
<div class="barleft">
<div class="barright">
<p><b> Network Administration</b>
</div>
</div>
<table class="tipframe" align="center"  width="98%" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <th>[<a id="network_list" href="/panel/network/sub/list"> Network List</a>] (total: <?php echo $this->total;?>)</th>
            <?php if($this->acl->isAllowed('admin_networks', 'create')) { ?>
            <th>[<a id="add_network" href="/panel/network/sub/create" title="Add  Network">Add 
 Network</a>]</th>
            <?php } ?>
            <th>
                <table align="center">
                    <tbody>
                        <tr height="22">
                            <td><b>Page:&nbsp;</b></td>
                            <td><?php echo $this->links['all'];?></td>
                            <td>|</td>
                        </tr>
                    </tbody>
                </table>
            </th>
            <th>
                <table align="center">
                <form name="query" method="post" action="/panel/network/sub/list">
                    <tbody>
                        <tr>
                            <td><b>Query:&nbsp;</b></td>
                            <td><input name="qv" value="<?php echo $this->qv;?>" title="Input your query value" size="20" maxlength="40" type="text"></td>

                             <td><input value="Search" title="submit your request" type="submit"></td>
                        </tr>
                    </tbody>
                </form>
                </table>
            </th>
        </tr>
    </tbody>
</table>
<?php $this->placeholder('prepend')->captureEnd() ?>
