<?php
$operation = '';
if (Fisma_Acl::hasPrivilege('admin_networks','update')) {
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
}
if (Fisma_Acl::hasPrivilege('admin_networks','delete')) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}
Fisma_Format_Section::startSection("Network Information $operation"); ?>
<div>
    <?php echo $this->form ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
