<?php echo $this->partial('object/view.phtml', $this->getVars()); ?>
<div id="stepTemplate" style="display:none;">
<table><tbody>
    <tr class="incidentStep">
        <td></td>
        <td>
            <p>Name:&nbsp;<input size="80" name="stepName[]" type="text" /></p>
            <p>
                Role:
                <input type='button' />
                <select name="stepRole[]"></select>
            </p>
            <p>Description:&nbsp;<span class="templateDescription"></span></p>
            <p>
                <button>Add Step Above</button>
                <button>Add Step Below</button>
                <button>Delete Step</button>
            </p>
        </td>
    </tr>
</tbody></table>
</div>
<script type="text/javascript">
YAHOO.util.Event.onDOMReady(function() {
    new Fisma.IncidentWorkflow(<?php echo $this->escape($this->stepsData, 'json'); ?>, "stepTemplate");
});
</script>
