<?php echo $this->partial('object/view.phtml', $this->getVars()); ?>
<div id="stepTemplate" style="display:none;">
<table><tbody>
    <tr class="incidentStep">
        <td></td>
        <td>
            <p>Name:&nbsp;<input size="80" name="stepName[]" type="text" /></p>
            <p><input name="stepRole[]" type="hidden" value="" /></p>
            <p>
                Role:
                <input type='button' />
                <select></select>
            </p>
            <p>Description:&nbsp;<span class="templateDescription"></span></p>
            <p><div class="button"></div><div class="button"></div><div class="button"></div></p>
        </td>
    </tr>
</tbody></table>
</div>
<script type="text/javascript">
YAHOO.util.Event.onDOMReady(function() {
    Fisma.TinyMCE.registerInitCallback(function() {
        new Fisma.IncidentWorkflow(<?php echo $this->escape($this->stepsData, 'json'); ?>, "stepTemplate");
    });
});
</script>
