<?php echo $this->escape($this->searchBox($this->toolbarButtons), 'none'); ?>
<?php Fisma_Format_Section::startSection("Technical Contact Information"); ?>

<p>
    The technical contact information will be used to provide the end-users with contact information if they experience
    a problem or if they would like additional support.
</p>

<div class="block">
    <?php echo $this->escape($this->form->setAttrib('class', 'cform'), 'none'); ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
