<?php echo $this->escape($this->searchBox($this->toolbarButtons), 'none'); ?>
<?php Fisma_Format_Section::startSection('LDAP Configurations'); ?>
<p>OpenFISMA can authenticate to multiple LDAP servers, please create a New LDAP connection for each server you would
like to authenticate against.<br/>Multiple LDAP connections are usually only used when you have users from multiple
domains such as acme.corp and anothercompany.com.</P>
<?php echo $this->escape($this->dataTable, 'none'); ?>

<?php Fisma_Format_Section::stopSection(); ?>

<?php Fisma_Format_Section::startSection('Automatic Synchronization'); ?>
<p>Specify how often you would like to synchronize with the LDAP connections.<br/>Information obtained from LDAP will
overwrite existing user information such as phone numbers, email addresses, etc.<br/>You should choose this option if
you would like to ensure that LDAP is the only source of accurate user information.<br/>Please note this is a one way
synchronization, OpenFISMA will not provide user profile updates to LDAP.</p>
<form method='POST' action='/config/list-ldap'>
    <p>
        <input type='checkbox' name='autorun' id='autorunCheckbox' <?php
        if ($this->task['enabled']):
            ?>checked<?php
        endif;
    ?>/>
        <label for='autorunCheckbox'>Run every</label> <input size='1' name='day' id='dayTextbox' value='<?php
            echo $this->escape($this->task['number']);
        ?>' /> <label for='dayTextbox'>day(s)</label> <label for='timeTextbox'>at</label>
        <input size='6' name='time' id='timeTextbox' value='<?php
            echo $this->escape($this->task['time']);
        ?>'/>.
    </p>
    <p>Last ran: <i><?php
        if (isset($this->task['lastRunTs'])):
            echo $this->escape($this->task['lastRunTs']);
        else:
            ?>never<?php
        endif;
    ?></i>.</p>
    <blockquote><pre><?php
        $filePath = Fisma::getPath('log') . '/refresh-user.log';
        if (file_exists($filePath)):
            $logs = explode("\n\n", trim(file_get_contents($filePath)));
            echo $this->escape(array_pop($logs));
        endif;
    ?></pre></blockquote>
    <p><input type='checkbox' name='notification' id='notificationCheckbox'<?php
        $user = Doctrine::getTable('User')->find(CurrentUser::getAttribute('id'));
        $event = Doctrine::getTable('Event')->findOneByName('LDAP_SYNC');
        if (in_array($user, $event->Users->getData())):
            ?>checked<?php
        endif;
    ?>/> <label for='notificationCheckbox'>Receive a notification when synchronization completes.</label></p>
</form>
<?php Fisma_Format_Section::stopSection(); ?>