<?php
Fisma_Format_Section::startSection('Installed Modules');
?>

<table class="modules">
<input name="csrf" type="hidden" value="<?php echo $this->escape($this->csrfToken); ?>">
    <?php
    foreach ($this->modules as $module):
    ?>
        <tr>
            <td><?php echo $this->escape($module['name']) ?></td>
            <td><?php echo $this->escape($module['control'], 'none') ?></td>
        </tr>
    <?php
    endforeach;
    ?>
</table>
