<?php echo $this->escape($this->searchBox($this->toolbarButtons), 'none'); ?>
<?php Fisma_Format_Section::startSection("Password Policies"); ?>

<p>
    The password policy only applies when the application is using local authentication, if you have configured the
    application to use an external authentication provider the password policies will be provided by that
    provider. Example, if you have configured the application to use Microsoft Active Directory, the password
    complexity will be defined and managed by Active Directory and not the application.
</p>

<div class="block">
    <?php echo $this->escape($this->form->setAttrib('class', 'cform'), 'none'); ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
