<?php /* Customized header based on Fisma_Format_Section::startSection */ ?>

<div class="sectionHeader">
    <span $editableText>
        <table width="100%">
            <tr>
                <td align="left">
                    <?php echo $this->escape($this->chartParamArr['title'], 'none'); ?>
                </td>
                <td align=right>
                    <a 
                        href="JavaScript: // Click to show chart options" 
                        style ="text-decoration: none" 
                        onClick="setChartSettingsVisibility('<?php 
                            echo $this->escape($this->chartId, 'none'); 
                        ?>', 'toggle');">
                        <img src="/images/gear.png" alt="Click to edit chart options" width="20" />
                    </a>
                </td>
            </tr>
        </table>
    </span>
</div>
<div class="section">

<div class="yui-navset">

    <div id="<?php echo $this->escape($this->chartId, 'none'); ?>loader" class="loading">
        <div>
        </div>
    </div>
    
    <div id="<?php echo $this->escape($this->chartId, 'none'); ?>holder" <?php
                    echo $this->escape($this->divContainerArgs, 'none'); ?> >
    
            <div id="<?php echo $this->escape($this->chartId, 'none'); ?>toplegend">
            </div>
            
            <div id="<?php echo $this->escape($this->chartId, 'none'); ?>" >
                Loading chart data...
            </div>
    </div>
    
    <div
        id="<?php echo $this->escape($this->chartId, 'none'); ?>table"
        style="display: none; width: 100%;"
        width="100%"
    >
    </div>   
    
    <br/>
    <div 
        id="<?php echo $this->escape($this->chartId, 'none');?>WidgetSpaceHolder" 
        class="yui-navset" 
        style="display: none; width: 400px; margin-left: auto; margin-right: auto; text-align: left;"
    >
        <ul class="yui-nav">
            <li class="selected">
                <a href="#tab1" onClick="showSetingMode(true);">
                    <em>Chart Parameters</em>
                </a>
            </li>
            <li>
                <a href="#tab1" onClick="showSetingMode(false);">
                    <em>Global Settings</em>
                </a>
            </li>
        </ul>
        <div class="yui-content">
            <div id="tab1" >
                <div id="<?php echo $this->escape($this->chartId, 'none');?>WidgetSpace">
                    <!-- chart params and widgets placed here by JavaScript -->
                </div>
                
                <div style="width: 100%; text-align: right;">
                    <input 
                        type="button" value="Hide Settings" 
                        onClick="setChartSettingsVisibility('<?php 
                            echo $this->escape($this->chartId, 'none');
                            ?>', false);"
                        id="<?php echo $this->escape($this->chartId, 'none'); ?>BtnMainSet"
                    />
                </div>
                
            </div>
            <div id="tab2">
                
                <div 
                    id="<?php echo $this->escape($this->chartId, 'none');?>GlobSettings" 
                    onClick="globalSettingUpdate('<?php echo $this->escape($this->chartId, 'none');?>');" 
                    style="text-align: left; ">
                <input type="checkbox" id="pointLabels" />
                    <label for="pointLabels">
                        Draw data labels (numbers on top of bars)
                    </label><br/>
                <span class="hideFromIE">
                    <input type="checkbox" id="pointLabelsOutline" />
                        <label for="pointLabelsOutline">
                            Outline data labels* 
                        </label><br/>
                </span>
                <input type="checkbox" id="barShadows" />
                    <label for="barShadows">
                        Draw shadows behind bars 
                    </label><br/>
                <input type="textbox" id="barShadowDepth" value="3" style="width:10px" />
                    <label for="barShadowDepth">
                        Depth of shadows behind bars (in pixels) 
                    </label><br/>
                <input type="checkbox" id="dropShadows" />
                    <label for="dropShadows">
                        Draw shadows behind charts 
                    </label><br/>
                <input type="checkbox" id="gridLines"/>
                    <label for="gridLines">
                        Draw grid-lines 
                    </label><br/>
                <span class="hideFromIE">
                    <input type="checkbox" id="fadingEnabled"/>
                        <label for="fadingEnabled">
                            Enable fading effects* 
                        </label><br/>
                </span>
                <input type="checkbox" id="showDataTable"/>
                    <label for="showDataTable">
                        Show table of raw numbers instead of chart 
                    </label><br/>
                <label class="hideFromIE">
                    * = This option is not supported in IE
                </label>
                </div>
                
                <div style="width: 100%; text-align: right;">
                    <input type="button" value="Hide Settings"
                        onClick="setChartSettingsVisibility('<?php 
                            echo $this->escape($this->chartId, 'none'); 
                            ?>', false);"
                        id="<?php echo $this->escape($this->chartId, 'none'); ?>BtnGlobSet"
                    />
                    
                </div>
                
            </div>
        </div>
        
    </div>    
    
</div>

<script>
    var thisChartObjData = <?php echo $this->escape($this->chartParamArr, 'json'); ?>;
    createJQChart(thisChartObjData);
</script>

<div class='clear'></div>

</div>
<script type="text/javascript">
    /* YUI TabView */
    var thisName = '<?php echo $this->escape($this->chartId, 'none');?>WidgetSpaceHolder';
    var tabView = new YAHOO.widget.TabView(thisName);
    /* YUI buttons */
    var thisChartId = "<?php echo $this->escape($this->chartId, 'none'); ?>";
    var yuiBtnEventObj1 = {onclick: {fn: hideButtonClick, obj:thisChartId } };
    var yuiBtnEventObj2 = {onclick: {fn: hideButtonClick, obj:thisChartId } };
    var thisBtnGlob = new YAHOO.widget.Button(thisChartId + "BtnGlobSet", yuiBtnEventObj1);
    var thisBtnMain = new YAHOO.widget.Button(thisChartId + "BtnMainSet", yuiBtnEventObj2);
</script>
