<div class="chartContainer">
<?php if (!$this->hideHeader): ?>
    <div class="sectionHeader">
        <table width="100%">
            <tr>
                <td align="left">
                    <?php echo $this->escape($this->chartParamArr['title'], 'html'); ?>
                </td>
                <td align=right>
                    <img
                        src="/images/gear.png"
                        alt="Click to edit chart options"
                        onClick="Fisma.Chart.setChartSettingsVisibility('<?php
                            echo $this->escape($this->chartId, 'none');
                            ?>', 'toggle');"
                        class="chartGear"
                    />
                </td>
            </tr>
        </table>
    </div>
<?php endif; ?>
    <div class="section chartSection">
        <div class="yui-navset">

            <div id="<?php echo $this->escape($this->chartId); ?>title" class="jqplot-title"></div>

            <div id="<?php echo $this->escape($this->chartId); ?>loader" class="loading">
                <div>
                </div>
            </div>

            <div id="<?php echo $this->escape($this->chartId, 'none'); ?>holder" <?php
                            echo $this->escape($this->divContainerArgs, 'none'); ?> >

                    <div id="<?php echo $this->escape($this->chartId); ?>toplegend">
                    </div>

                    <div id="<?php echo $this->escape($this->chartId); ?>pieTooltip"
                        class="jqplot-highlighter-tooltip pieToolTip">
                    </div>

                    <div id="<?php echo $this->escape($this->chartId); ?>" >
                        Loading chart data...
                    </div>
            </div>

            <div class="screenReaderTable" id="<?php echo $this->escape($this->chartId, 'none'); ?>table">
            </div>

            <br/>
            <div
                id="<?php
                    echo $this->escape($this->chartId, 'none');
                ?>WidgetSpaceHolder" class="widgetSpaceHolder yui-navset" style="display: none;">
                <ul class="yui-nav">
                    <li class="selected">
                        <a href="#tab1" onClick="Fisma.Chart.showSetingMode(true);">
                            <em>Chart Parameters</em>
                        </a>
                    </li>
                    <li>
                        <a href="#tab1" onClick="Fisma.Chart.showSetingMode(false);">
                            <em>Global Settings</em>
                        </a>
                    </li>
                </ul>
                <div class="yui-content">
                    <div id="tab1" >
                        <div id="<?php echo $this->escape($this->chartId, 'none');?>WidgetSpace">
                            <!-- chart params and widgets placed here by JavaScript -->
                        </div>

                        <div style="width: 100%; text-align: right;">
                            <input
                                type="button" value="Hide Settings"
                                onClick="setChartSettingsVisibility('<?php
                                    echo $this->escape($this->chartId, 'none');
                                    ?>', false);"
                                id="<?php echo $this->escape($this->chartId, 'none'); ?>BtnMainSet"
                            />
                        </div>

                    </div>
                    <div id="tab2">

                        <div
                            id="<?php echo $this->escape($this->chartId, 'none');?>GlobSettings"
                            style="text-align: left; ">
                        <label for="pointLabels" class='checkbox'>
                            <input type="checkbox" id="pointLabels" />
                                Show data labels
                        </label>
                        <label for="pointLabelsOutline" class="hideFromIE checkbox">
                            <input type="checkbox" id="pointLabelsOutline" class="hideFromIE" />
                                Outline data labels
                        </label>
                        <label for="barShadows" class='checkbox'>
                            <input type="checkbox" id="barShadows" />
                                Draw shadows behind bars
                        </label>
                        <div class="input-prepend input-append">
                            <label class="add-on" for="barShadowDepth" class='inline'>
                                Depth of shadows behind bars:
                            </label>
                            <input type="textbox" id="barShadowDepth" value="3" class="span1" />
                            <span class="add-on">px</span>
                        </div>
                        <label for="dropShadows" class='checkbox'>
                            <input type="checkbox" id="dropShadows" />
                                Draw shadows behind charts
                        </label>
                        <label for="gridLines" class='checkbox'>
                            <input type="checkbox" id="gridLines"/>
                                Draw grid-lines
                        </label>
                        <label for="fadingEnabled" class="hideFromIE checkbox">
                            <input type="checkbox" id="fadingEnabled" class="hideFromIE"/>
                                Enable fading effects
                        </label>
                        <label for="showDataTable" class='checkbox'>
                            <input type="checkbox" id="showDataTable"/>
                                Show data table
                        </label>
                        </div>

                        <div>
                            <div style="float: right; text-align: right;">
                                <input type="button" value="Hide Settings"
                                    onClick="Fisma.Chart.setChartSettingsVisibility('<?php
                                        echo $this->escape($this->chartId, 'none');
                                        ?>', false);"
                                    id="<?php echo $this->escape($this->chartId, 'none'); ?>BtnGlobSet"
                                />
                            </div>
                            <div style="float: right; text-align: right;">
                                <input type="button" value="Apply Settings"
                                    onClick="Fisma.Chart.globalSettingUpdate('<?php
                                        echo $this->escape($this->chartId, 'none');
                                        ?>');"
                                    id="<?php echo $this->escape($this->chartId, 'none'); ?>BtnApplySet"
                                />
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class='clear'></div>
    <script type="text/javascript">
        var thisChartObjData = <?php echo $this->escape($this->chartParamArr, 'json'); ?>;
        Fisma.Chart.createJQChart(thisChartObjData);
        YAHOO.util.Event.onContentReady('<?php echo $this->escape($this->chartId, 'none');?>', function () {
            var thisChartId = "<?php echo $this->escape($this->chartId, 'none'); ?>";
            /* YUI TabView */
            var thisName = '<?php echo $this->escape($this->chartId, 'none');?>WidgetSpaceHolder';
            var tabView = new YAHOO.widget.TabView(thisName);
            /* YUI buttons */
            var thisChartId = "<?php echo $this->escape($this->chartId, 'none'); ?>";
            var yuiBtnEventObj1 = {onclick: {fn: Fisma.Chart.hideButtonClick, obj:thisChartId } };
            var yuiBtnEventObj2 = {onclick: {fn: Fisma.Chart.hideButtonClick, obj:thisChartId } };
            var yuiBtnEventApplySetts = {onclick: {fn: Fisma.Chart.globalSettingUpdate, obj:thisChartId } };
            var thisBtnGlob = new YAHOO.widget.Button(thisChartId + "BtnGlobSet", yuiBtnEventObj1);
            var thisBtnMain = new YAHOO.widget.Button(thisChartId + "BtnMainSet", yuiBtnEventObj2);
            var thisBtnApplySettings = new YAHOO.widget.Button(thisChartId + "BtnApplySet", yuiBtnEventApplySetts);
            /* YUI button - add references from DOM to YUI object */
            document.getElementById(thisChartId + 'BtnApplySet').yuiObjRef = thisBtnApplySettings;
        });
    </script>
</div>
