<?php if ($this->message): ?>
<div class='message'><?php echo $this->escape($this->message); ?></div>
<?php else:
$threatType = Fisma::configuration()->getConfig('threat_type') == 'residual_risk' ? 'residualRisk' : 'threatLevel';
$this->table = Doctrine::getTable('Finding');
?>
<div class='row-fluid'>
<div class='span7 findingAnalystLeft' id='findingAnalystLeft'>
    <?php Fisma_Format_Section::startSection(
        'Unresolved: By ' . $this->escape($this->translate('Finding_Point_of_Contact')),
        null,
        null,
        'byPoc'
    ); ?>
    <?php echo $this->escape($this->byPocTable, 'none'); ?>
    <?php if ($this->byPocTable->countData() > 8): ?>
        <a href='#' onclick='return Fisma.Finding.restrictTableLengthClickHandler(this, 0, "<?php
            echo $this->escape($this->byPocTable->getRegistryName());
        ?>")'>Show all
            <?php echo $this->escape($this->byPocTable->countData()); ?> records</a>
        <a href='#' onclick='return Fisma.Finding.restrictTableLengthClickHandler(this, 8, "<?php
            echo $this->escape($this->byPocTable->getRegistryName());
        ?>")'>Show first 8 records only</a>
    <?php endif; ?>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php Fisma_Format_Section::startSection('Unresolved: By System', null, null, 'bySystem'); ?>
    <?php echo $this->escape($this->bySystemTable, 'none'); ?>
    <?php if ($this->bySystemTable->countData() > 8): ?>
        <a href='#' onclick='return Fisma.Finding.restrictTableLengthClickHandler(this, 0, "<?php
            echo $this->escape($this->bySystemTable->getRegistryName());
        ?>")'>Show all
            <?php echo $this->escape($this->bySystemTable->countData()); ?> records</a>
        <a href='#' onclick='return Fisma.Finding.restrictTableLengthClickHandler(this, 8, "<?php
            echo $this->escape($this->bySystemTable->getRegistryName());
        ?>")'>Show first 8 records only</a>
    <?php endif; ?>
    <?php Fisma_Format_Section::stopSection(); ?>
</div>
<div class='span5 findingAnalystRight' id='findingAnalystRight'>
    <?php Fisma_Format_Section::startSection(
        'Unresolved: By ' . $this->column($threatType, null, false), null, null, 'byThreat'); ?>
    <table class='table table-striped no-border'>
    <?php foreach($this->byThreat as $statistic): ?>
        <tr>
            <td class='criteria'><?php echo $this->escape($statistic['criteria']); ?></td>
            <td class='value'><?php echo $this->escape($statistic['count']); ?></td>
            <td width='55%'>
                <a href='/finding/remediation/list?q=isResolved/booleanNo/<?php
                    echo $this->escape($threatType); ?>/enumIs/<?php
                    echo $this->escape($statistic['criteria'], 'url');
                ?>'><span
                class='bar <?php echo $this->escape($statistic['criteria']); ?>'
                style='width:<?php echo $this->escape($statistic['count']/$this->total*80); ?>%;'
                >
                </span></a>
                <span class='percentage'><?php
                    echo $this->escape(
                        ($statistic['count']/$this->total*100 < 1 && $statistic['count']/$this->total*100 > 0)
                        ? 'less than 1' : round($statistic['count']/$this->total*100)
                    );
                ?>%</span>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php Fisma_Format_Section::startSection('Unresolved: By Workflow', null, null, 'byType'); ?>
    <table class='table table-striped no-border'>
    <?php foreach($this->byType as $statistic):
        $criteria = new Fisma_Yui_Tooltip('type_' . uniqid(), $statistic['criteria'], $statistic['tooltip']);
    ?>
        <tr>
            <td class='criteria'><?php echo $this->escape($criteria, 'none'); ?></td>
            <td class='value'><?php echo $this->escape($statistic['count']); ?></td>
            <td width='55%'>
                <a href='/finding/remediation/list?q=isResolved/booleanNo/workflow/textExactMatch/<?php
                    echo $this->escape($statistic['criteria'], 'url');
                ?>'><span class='bar normal' style='width:<?php
                        echo $this->escape($statistic['count']/$this->total*80);
                    ?>%;'>
                </span></a>
                <span class='percentage'><?php
                    echo $this->escape(
                        ($statistic['count']/$this->total*100 < 1 && $statistic['count']/$this->total*100 > 0)
                        ? 'less than 1' : round($statistic['count']/$this->total*100)
                    );
                ?>%</span>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php Fisma_Format_Section::startSection('Unresolved: By Workflow Step', null, null, 'byStatus'); ?>
    <table class='table table-striped no-border'>
    <?php foreach($this->byStatus as $statistic):
        $criteria = new Fisma_Yui_Tooltip('status_' . uniqid(), $statistic['criteria'], $statistic['tooltip']);
    ?>
        <tr>
            <td class='criteria'><?php echo $this->escape($criteria, 'none'); ?></td>
            <td class='value'><?php echo $this->escape($statistic['count']); ?></td>
            <td width='55%'>
                <a href='/finding/remediation/list?q=isResolved/booleanNo/workflowStep/textExactMatch/<?php
                    echo $this->escape($statistic['criteria'], 'url');
                ?>'><span class='bar normal' style='width:<?php
                        echo $this->escape($statistic['count']/$this->total*80);
                    ?>%;'>
                </span></a>
                <span class='percentage'><?php
                    echo $this->escape(
                        ($statistic['count']/$this->total*100 < 1 && $statistic['count']/$this->total*100 > 0)
                        ? 'less than 1' : round($statistic['count']/$this->total*100)
                    );
                ?>%</span>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
    <?php Fisma_Format_Section::stopSection(); ?>

    <?php Fisma_Format_Section::startSection('Unresolved: By Source', null, null, 'bySource'); ?>
    <table class='table table-striped no-border'>
    <?php foreach($this->bySource as $statistic):
        $criteria = new Fisma_Yui_Tooltip('source_' . uniqid(), $statistic['criteria'], $statistic['tooltip']);
    ?>
        <tr>
            <td class='criteria'><?php echo $this->escape($criteria, 'none'); ?></td>
            <td class='value'><?php echo $this->escape($statistic['count']); ?></td>
            <td width='55%'>
                <a href='/finding/remediation/list?q=isResolved/booleanNo/source/textContains/<?php
                    echo $this->escape($statistic['criteria'], 'url');
                ?>'><span class='bar normal' style='width:<?php
                        echo $this->escape($statistic['count']/$this->total*80);
                    ?>%;'>
                </span></a>
                <span class='percentage'><?php
                    echo $this->escape(
                        ($statistic['count']/$this->total*100 < 1 && $statistic['count']/$this->total*100 > 0)
                        ? 'less than 1' : round($statistic['count']/$this->total*100)
                    );
                ?>%</span>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
    <?php Fisma_Format_Section::stopSection(); ?>
</div>
</div>
<script>
$(function() {
    Fisma.Finding.initDashboard();
});
</script>
<?php endif; ?>
