<div class='row-fluid'>
    <div class="span7">
        <div style='text-align: center;' id='chartTotalStatusContainer'>
            <?php
                echo $this->escape($this->chartTotalStatus, 'none');
            ?>
        </div>
        <div id='findingOrgChartContainer'>
            <?php echo $this->escape($this->findingOrgChart, 'none'); ?>
        </div>

        <div id='controlDeficienciesChartContainer'>
            <?php echo $this->escape($this->controlDeficienciesChart, 'none'); ?>
        </div>
    </div>

    <div class="span5">
        <div style='text-align: center;' id='chartFindForecastContainer'>
            <?php
                echo $this->escape($this->chartFindForecast, 'none');
            ?>
        </div>
        <div style='text-align: center;' id='chartOverdueFindingContainer'>
            <?php
                echo $this->escape($this->chartOverdueFinding, 'none');
            ?>
        </div>
        <div style='text-align: center;' id='chartNoMitContainer'>
            <?php
                echo $this->escape($this->chartNoMit, 'none');
            ?>
        </div>
    </div>
</div>
