<div class="column left">
    <div style='text-align: center;'>
        <?php
            echo $this->escape($this->chartFindForecast, 'none');
        ?>
    </div>
</div>

<div class="column right">
    <div style='text-align: center;'>
        <?php
            echo $this->escape($this->chartOverdueFinding, 'none');
        ?>
    </div>
</div>

<div class="clear"></div>

<div class="column left">
    <div style='text-align: center;'>
        <?php
            echo $this->escape($this->chartTotalStatus, 'none');
        ?>
    </div>
</div>

<div class="column right">
    <div style='text-align: center;'>
        <?php
            echo $this->escape($this->chartNoMit, 'none');
        ?>
    </div>
</div>

<div class="clear"></div>

<div class='dashboardChart'>
    <?php echo $this->escape($this->findingOrgChart, 'none'); ?>
</div>

<div class="clear"></div>

<div class='dashboardChart'>
    <?php echo $this->escape($this->controlDeficienciesChart, 'none'); ?>
</div>

