<?php 
Fisma_Format_Section::startSection('Artifacts (' . $this->finding->Evidence->count() . ')');
$organization = $this->finding->ResponsibleOrganization->nickname;

if (count($this->finding->Evidence) == 0):
    echo $this->escape('<p><i>There are no artifacts for this finding.</i></p>', 'none');
endif;

foreach ($this->finding->Evidence as $evidence):
?>
    <div class="approvalHeader">
        <b>File: </b>
        <a href='/remediation/downloadevidence/id/<?php echo $this->escape($evidence->id)?>' target='_blank'>
            <?php echo $this->escape($evidence->filename); ?>
        </a>
        (submitted by 
        <?php echo $this->escape($evidence->User->nameFirst) . ' ' . $this->escape($evidence->User->nameLast); ?> 
        on 
        <?php echo $this->escape($evidence->createdTs); ?>)
    </div>
    <div class="approval">
        <?php
        $completedEvaluations = array();
        
        foreach ($evidence->FindingEvaluations as $findingEvaluation):
            $completedEvaluations[] = $findingEvaluation->Evaluation->id;

            $userName = $findingEvaluation->User->nameFirst . ' ' . $findingEvaluation->User->nameLast;
            $decision = $findingEvaluation->decision;
            $spanClass = strtolower($decision);
        ?>
            <div class="approvalStep">
                <p>
                    <b><?php echo $this->escape($findingEvaluation->Evaluation->name); ?>:</b>
                    <span class="<?php echo $this->escape($spanClass)?>">
                        <b><?php echo $this->escape($decision)?></b>
                        (<?php echo $this->escape($userName)?> 
                        at <?php echo $this->escape($findingEvaluation->createdTs)?>)
                    </span>
                </p>
            <?php 
                if (!empty($findingEvaluation->comment)):
                        echo $this->escape($this->textToHtml($findingEvaluation->comment), 'none');
                endif;
            ?>
            </div>
        <?php
        endforeach;
        ?>

        <?php
        $activeEvaluation = $this->finding->CurrentEvaluation;
        if ($activeEvaluation->id != null 
            && $activeEvaluation->approvalGroup == 'evidence'
            && !in_array($activeEvaluation->id, $completedEvaluations)):
        ?>
            <div class="approvalStep">
                <p>
                    <b><?php echo $this->escape($activeEvaluation->name)?></b>
                    <?php 
                    if ($this->acl()->hasPrivilegeForObject($activeEvaluation->Privilege->action, $this->finding)): 
                    ?>
                        <input type="hidden" name="comment" value="" />
                        <input type="hidden" name="decision" value="APPROVED" />
                        <input name="submit_ea" type="button" value="APPROVED"
                            onclick="ev_approve(document.finding_detail);"/>&nbsp;
                        <input type="button" value="DENIED" onclick="ev_deny(document.finding_detail);" />
                    <?php 
                    else: 
                    ?>
                        PENDING
                    <?php 
                    endif; 
                    ?>
                </p>
            </div>
        <?php
        endif;

        $disableEvaluations = array();
        $currentEvaluation  = $this->finding->CurrentEvaluation;
        if ($currentEvaluation->approvalGroup == 'evidence'):
            while (null != $currentEvaluation->nextId):
                $currentEvaluation = $currentEvaluation->NextEvaluation;
                $disableEvaluations[] = $currentEvaluation;
            endwhile;
        endif;

        foreach ($disableEvaluations as $evaluation):
            if (!in_array($evaluation->id, $completedEvaluations)):
        ?>
                <div class='approvalStep'>
                   <p><b><?php echo $this->escape($evaluation->name)?></b>N/A</p>
                </div>
        <?php
            endif;
        endforeach;
        ?>
    </div>
<?php
endforeach;
?>
    
<?php
$uploadEvidenceButton = new Fisma_Yui_Form_Button('uploadEvidenceButton',
                                            array('label' => 'Upload Evidence', 
                                                  'onClickFunction' => 'upload_evidence'));

if ('EN' != $this->finding->status || !$this->acl()->hasPrivilegeForObject('upload_evidence', $this->finding)):
    $uploadEvidenceButton->readOnly = true;
endif;
?>

<p>Evidence can only be uploaded if the finding is in 'EN' status and if you have the required role.</p>

<div class='toolbar'>
    <?php echo $this->escape($uploadEvidenceButton, 'none');?>
</div>
