<?php 
Fisma_Format_Section::startSection('Artifacts (' . $this->artifacts->count() . ')');

if (count($this->artifacts) == 0):
    echo $this->escape('<p><i>There are no artifacts for this finding.</i></p>', 'none');
else:
    // Each artifact block is rendered in a partial view.
    foreach ($this->artifacts as $index => $artifact):
    
        /*
         * Each partial is passed an 'activeArtifact' boolean which is true if the artifact passed is one that is 
         * currently under review (and false otherwise).
         */
        $activeArtifact = (0 == $index && 'EA' == $this->finding->status);
        
        echo $this->partial(
            'remediation/artifact-detail.phtml', 
            array(
                'finding' => $this->finding,
                'artifact' => $artifact,
                'activeArtifact' => $activeArtifact
            )
        );
    endforeach;
endif;

$uploadEvidenceButton = new Fisma_Yui_Form_Button('uploadEvidenceButton',
                                            array('label' => 'Upload Evidence', 
                                                  'onClickFunction' => 'upload_evidence'));

if ('EN' != $this->finding->status || !$this->acl()->hasPrivilegeForObject('upload_evidence', $this->finding)):
    $uploadEvidenceButton->readOnly = true;
endif;
?>

<p>Evidence can only be uploaded if the finding is in 'EN' status and if you have the required role.</p>

<div class='buttonBar'>
    <?php echo $this->escape($uploadEvidenceButton, 'none');?>
</div>
