<div class="approvalHeader">
    <b>File: </b>

    <a href='/remediation/downloadevidence/id/<?php echo $this->escape($this->artifact->id)?>' target='_blank'>
        <?php echo $this->escape($this->artifact->filename); ?>
    </a>

    submitted by 

    <?php 
        $user = $this->artifact->User;
        $fullName = $user->nameFirst . ' ' . $user->nameLast;
        
        echo $this->escape($this->userInfo($fullName, $user->username), 'none');
    ?> 
    on 
    <?php echo $this->escape($this->artifact->createdTs); ?>
</div>

<div class="approval">
    <?php
    /*
     * This is used to track which evaluations have been completed for this artifact. After the first loop completes,
     * any evaluation (i.e. the Evaluation table) which is not on this list can be inferred to be pending or skipped.
     */
    $completedEvaluations = array();
    
    // First: display all of the completed evaluations for the artifact.
    foreach ($this->artifact->FindingEvaluations as $findingEvaluation):
        $completedEvaluations[] = $findingEvaluation->Evaluation->id;

        $user = $findingEvaluation->User;
        $fullName = $user->nameFirst . ' ' . $user->nameLast;
        
        $decision = $findingEvaluation->decision;
        $spanClass = strtolower($decision);
    ?>
        <div class="approvalStep">
            <p>
                <b><?php echo $this->escape($findingEvaluation->Evaluation->name); ?></b>
                
                <span class="<?php echo $this->escape($spanClass)?>">
                    <b><?php echo $this->escape($decision)?></b>
                    <?php echo $this->escape($this->userInfo($fullName, $user->username), 'none'); ?> 
                    at <?php echo $this->escape($findingEvaluation->createdTs)?>
                </span>
            </p>
        <?php 
            if (!empty($findingEvaluation->comment)):
                    echo $this->escape($this->textToHtml($findingEvaluation->comment), 'none');
            endif;
        ?>
        </div>
    <?php
    endforeach;
    ?>

    <?php
    $activeEvaluation = $this->finding->CurrentEvaluation;

    /*
     * Second: display the current evaluation, if any. This evaluation will show approval buttons for users with the 
     * privileges, or 'PENDING' for unprivileged users.
     */
    if ($this->activeArtifact):
        if ($this->acl()->hasPrivilegeForObject($activeEvaluation->Privilege->action, $this->finding)):
    ?>
            <div class="approvalStep">
                <p>
                    <b><?php echo $this->escape($activeEvaluation->name)?></b>
                    <input type="hidden" name="comment" value="" />
                    <input type="hidden" name="decision" value="APPROVED" />
                    <input name="submit_ea" type="button" value="APPROVED"
                        onclick="ev_approve(document.finding_detail);"/>&nbsp;
                    <input type="button" value="DENIED" onclick="ev_deny(document.finding_detail);" />
                </p>
            </div>
        <?php
        else:
        ?>
            <div class="approvalStep">
                <p>
                    <b><?php echo $this->escape($activeEvaluation->name)?></b>
                    PENDING
                </p>
            </div>
    <?php
        endif;
    endif;

    /*
     * Third: If there are any evaluations beyond the current one, then they are listed here. For artifacts which are 
     * already denied, the status is listed as 'SKIPPED' because those evaluation will never be performed. For artifacts
     * which are still under review, the status is listed as 'PENDING'.
     */
    $disableEvaluations = array();
    $currentEvaluation  = $this->finding->CurrentEvaluation;

    if ($decision == 'DENIED') {
        $status = 'SKIPPED';
    } else {
        $status = 'PENDING';
    }

    if ($currentEvaluation->approvalGroup == 'evidence'):
        while (null != $currentEvaluation->nextId):
            $currentEvaluation = $currentEvaluation->NextEvaluation;
            $disableEvaluations[] = $currentEvaluation;
        endwhile;
    endif;

    foreach ($disableEvaluations as $evaluation):
        if (!in_array($evaluation->id, $completedEvaluations)):
    ?>
        <div class='approvalStep'>
           <p><b><?php echo $this->escape($evaluation->name)?></b><?php echo $this->escape($status); ?></p>
        </div>
    <?php
        endif;
    endforeach;
    ?>
</div>
