<table class="auditLog">
    <tr>
        <th>Timestamp</th>
        <th>User</th>
        <th>Description</th>
    </tr>
    <?php foreach ($this->finding->AuditLogs as $log) { ?>
        <tr>
            <td><?php echo $log->createdTs; ?></td>
            <td><?php echo $log->User->username; ?></td>
            <td><?php echo str_replace("\n","<br>",$log->description); ?></td>
        </tr>
    <?php } ?>
</table>
