<table class="auditLog">
    <tr>
        <th>Timestamp</th>
        <th>User</th>
        <th>Event</th>
        <th>Description</th>
    </tr>
    <?php foreach ($this->logs as $logItem) { ?>
        <tr>
            <td><?php echo $logItem['timestamp']; ?></td>
            <td><?php echo $logItem['username']; ?></td>
            <td><?php echo $logItem['event']; ?></td>
            <td><?php echo str_replace("\n","<br>",$logItem['description']); ?></td>
        </tr>
    <?php } ?>
</table>
