<?php
Fisma_Format_Section::startSection('Comments');
    if ($this->showAddCommentForm):
?>
    <form action="/remediation/add-comment/id/<?php echo $this->id; ?>" method="post">
        <p>
            <b>Add a comment:</b>
        </p>
        <p>
            <textarea name="comment" rows="5" cols="60"></textarea>
        </p>
        <p>
            <?php echo new Fisma_Yui_Form_Button_Submit('addComment', array('label' => 'Add Comment')); ?>
        </p>
    </form>
    <?php
    endif;
    ?>
    <div id="comments">
        <table id="commentsTable">
            <thead>
                <tr>
                    <th>Timestamp</th>
                    <th>User</th>
                    <th>Comment</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->comments as $comment):
                ?>
                    <tr>
                        <td><?php echo $comment['createdTs']; ?></td>
                        <td>
                            <?php echo $comment['User']['username']; ?>
                        </td>
                        <td>
                            <?php echo Fisma_String::textToHtml($comment['comment']); ?>
                        </td>
                    </tr>                
                <?php
                endforeach;
                ?>
            </tbody>
        </table>
    </div>
<?php
Fisma_Format_Section::stopSection();
?>

<script type="text/javascript">
// Convert comments table to YUI table
YAHOO.util.Event.onContentReady('comments', function() {
    var myColumnDefs = [
        {key:'timestamp', label:'Timestamp', sortable:true},
        {key:'username', label:'User', sortable:true},
        {key:'comment', label:'Comment', sortable:false}
    ];

    this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("commentsTable"));
    this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
    this.myDataSource.responseSchema = {
        fields: [
            {key:'timestamp'},
            {key:'username'},
            {key:'comment'}
        ]
    };

    this.myDataTable = new YAHOO.widget.DataTable("comments", myColumnDefs, this.myDataSource, {});
});
</script>