<?php 
    $evidence = $this->ev;
    $evaluation = $this->eval;
    $comment = new Comments();
?>
<form action="/remediation/evidence/id/<?php echo $evidence['id'];?>" method="post"
 name='eval_ev<?php echo $evidence['id'];?>' >
    <table cellpadding='3' cellspacing='1' class='tipframe' >
    <tr><th colspan=2 align='left'>Evidence Submitted by 
    <?php echo $evidence['submitted_by'];?> on <?php echo $evidence['submit_ts'];?>
    </th></tr>

    <tr> 
        <td colspan=2><b>Evidence:&nbsp;</b>
        <?php 
            $url = $evidence['submission'];
            $ev_path[] = $evidence['submission'];
            $ev_path[] ='evidence' . '/' . $evidence['poam_id']. '/'. $evidence['submission'];
            $link = '%filename%';
            foreach( $ev_path as $path ) {
                if(file_exists($path) ) {
                    $url = str_replace('\\', '/',$path);
                    $link = "<a href='/{$url}' target='_blank'>%filename%</a>";
                }
            }
            echo str_replace('%filename%',basename($url),$link);

        ?>
        </td>
    </tr>
    <?php 
    $value = 'NONE';
    $editable = true;
    $eval_model = new Evaluation();
    $ev_evallist = $eval_model->getEvalList('EVIDENCE');
    foreach($ev_evallist as $k=>$v) {
        $name = &$v['name'];
        if(isset($evaluation[$name])) {
            if( $evaluation[$name]['group'] != 'EVIDENCE' ) {
                var_dump($evaluation[$name]);
                continue;
            }
            $value = &$evaluation[$v['name']]['decision'];
            $username = isset($evaluation[$name]['username'])?$evaluation[$name]['username']:'...';
            $date = isset($evaluation[$name]['date'])?$evaluation[$name]['date']:'';
        }else{
            if($value == 'DENIED' ){
                $value = 'EXCLUDED';
            }else if($value == 'APPROVED') {
                $value = 'NONE';
            }
        }
        echo  "<tr><td><b>$name:&nbsp;</b>";
        if($value=='NONE' && $editable){
            if($this->isAllow('remediation',$v['function'])){
                echo '<input type="hidden" name="evaluation" value="'.$v['id'].'"/>';
                echo '<input type="hidden" name="precedence" value="'.$v['precedence_id'].'"/>';
                echo '<input type="hidden" name="topic" value="" />';
                echo '<input type="hidden" name="reject" value="" />';
                echo '<input type="hidden" name="decision" value="APPROVE" />';
                echo '<input type="submit" value="APPROVE" />';
                echo '<input type="button" value="DENY" '.
                    'onclick="comment(document.eval_ev'.$evidence['id'].');" />';
            }else{
                echo "$value </td>";
            }
            $editable=false;
        }else{
            echo "$value </td>";
            if( $value == 'APPROVED' ) {
                echo "<td> -- <i> by $username ON $date </i></td>";
            }else if($value == 'DENIED') {
                $row = $comment->fetchRow('poam_evaluation_id = '.$evaluation[$name]['eval_id']);
                echo "<td>";
                if( !empty($row) ) {
                    echo "<b>{$row->topic}</b>";
                }
                echo " -- <i> by $username ON $date </i></td>";
            }
        }
        echo "</tr>";
    }
    ?>
    </table>
</form>

<div id='comment_dialog' style="display:none">
Justification:
<input type="text" name="topic" size=80 value="" />
</div>
