<?php
    $finding = $this->finding;
    $orgId = $finding->ResponsibleOrganization->nickname;
    $status  = $finding->getStatus();
?>
<div class="column left">
    <?php Fisma_Format_Section::startSection("Details"); ?>
    <table class="keyValues">
        <tr>
            <td>Finding ID:</td>
            <td><?php echo $finding->id;?></td>
        </tr>
        <tr>
            <td>Date Discovered:</td>
            <td><?php echo $finding->discoveredDate;?></td>
        </tr>
        <tr>
            <td>Date Opened:</td>
            <td><?php echo $finding->createdTs;?></td>
        </tr>
        <tr>
            <td>Date Closed:</td>
            <td>
                <?php 
                if (!is_null($finding->closedTs)) {
                    echo $finding->closedTs;
                } else {
                    echo "<i>Not closed</i>";
                }
                ?>
            </td>
        </tr>
        <tr>
            <td>Source:</td>
            <td>(<?php echo $finding->Source->nickname;?>) <?php echo $finding->Source->name;?>
            <?php 
                if ($finding->uploadId) {
                    echo '<br>' . $finding->Upload->fileName;
                }
            ?>
            </td>
        </tr>
        <tr>
            <td>Status:</td>
            <td><?php echo $status;?></td>
        </tr>
        <?php 
        if ($status != 'CLOSED') { 
        ?>
        <tr>
            <td>On Time:</td>
            <td>
            <?php
                if (is_null($finding->nextDueDate)) {
                    echo 'N/A';
                } else {
                    echo date('Ymd', time()) <= date('Ymd', strtotime($finding->nextDueDate)) ? 'On Time' : 'Overdue';
                }
            ?>
            </td>
        </tr>
        <?php 
        } 
        ?>
        <tr>
            <td>
                <div>
                    Responsible Organization:
                </div>
            </td>
            <td>
                <div name="finding[responsibleOrganizationId]" 
                     id="organization" 
                     type="select" 
                     href="/metainfo/list/o/organization/format/html/"
                     <?php
                     if (('NEW' == $status || 'DRAFT' == $status)
                         && Fisma_Acl::hasPrivilege('finding', 'update_assignment', $orgId)) {
                         echo 'class="editable" target="organization"'; 
                     }
                     ?>>
                    <?php echo $finding->ResponsibleOrganization->nickname;?> 
                    - <?php echo $finding->ResponsibleOrganization->name;?>
                </div>
            </td>
        </tr>
    </table>
    <?php Fisma_Format_Section::stopSection(); ?>
</div>

<div class="column right">
    <?php 
        Fisma_Format_Section::startSection("Asset");
        if (Fisma_Acl::hasPrivilege('asset', 'read', '*')):
    ?>
    <table class="keyValues">
        <tr>
            <td>
                Asset Owner:
            </td>
            <td>
                <?php echo isset($finding->Asset->Organization->name) ? $finding->Asset->Organization->name : 'n/a';?>
            </td>
        </tr>
        <tr>
            <td>
                Asset Name:
            </td>
            <td>
                <?php echo isset($finding->Asset->name) ? $finding->Asset->name : 'n/a';?>
            </td>
        </tr>
        <tr>
            <td>
                Network:
            </td>
            <td>
                <?php echo isset($finding->Asset->Network->name) ? $finding->Asset->Network->name : 'n/a';?>
            </td>
        </tr>
        <tr>
            <td>
                IP Address:
            </td>
            <td>
                <?php echo isset($finding->Asset->Network->name) 
                      ? ($finding->Asset->addressIp . ':' . $finding->Asset->addressPort) : 'n/a'; ?>
            </td>
        </tr>
        <tr>
            <td>
                Product Information:
            </td>
            <td>
                <?php  
                    if (!empty($finding->Asset->Product->name)) {
                        echo $finding->Asset->Product->vendor . ' ' .
                             $finding->Asset->Product->name . ' ' .
                             $finding->Asset->Product->version;
                    } else {
                        echo 'n/a';
                    }
                ?>
            </td>
        </tr>
    </table>
    <?php 
        else:
            print "<i>Asset information cannot be displayed because you do not have the privileges required.</i>";
        endif;
        Fisma_Format_Section::stopSection(); 
    ?>
</div>

<div class="clear"></div>

<?php 
if (Fisma_Acl::hasPrivilege('finding', 'update_description', $orgId)
    && ('NEW' == $status || 'DRAFT' == $status)) {
    Fisma_Format_Section::startSection('Description', 'finding_description');
} else {
    Fisma_Format_Section::startSection('Description');
}
?>
<div name="finding[description]" id="finding_description" type="textarea" rows="3" cols="160"> 
    <?php echo $finding->description; ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>

<?php
if (('NEW' == $status || 'DRAFT' == $status)
    && Fisma_Acl::hasPrivilege('finding', 'update_recommendation', $orgId)) {
    Fisma_Format_Section::startSection('Recommendation', 'recommendation');
} else {
    Fisma_Format_Section::startSection('Recommendation');
}
?>
<div name="finding[recommendation]" id="recommendation" type="textarea" rows="3" cols="160">
    <?php echo $finding->recommendation; ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>
