<div class="column left">
    <?php Format_Section::startSection("Details"); ?>
    <table class="keyValues">
        <tr>
            <td>POAM ID:</td>
            <td><?php echo $this->poam['id'];?></td>
        </tr>
        <tr>
            <td>Date Discovered:</td>
            <td><?php echo $this->poam['discover_ts'];?></td>
        </tr>
        <tr>
            <td>Date Opened:</td>
            <td><?php echo $this->poam['create_ts'];?></td>
        </tr>
        <tr>
            <td>Source:</td>
            <td>(<?php echo $this->poam['source_nickname'];?>) <?php echo $this->poam['source_name'];?></td>
        </tr>
        <tr>
            <td>Status:</td>
            <td><?php echo $this->poam['status'];?></td>
        </tr>
        <?php if ($this->poam['status'] != 'CLOSED') { ?>
        <tr>
            <td>On Time:</td>
            <td><?php echo $this->isOnTime($this->poam['duetime']);?></td>
        </tr>
        <?php } ?>
        <tr>
            <td>
                <div 
                    <?php
                    if('NEW' == $this->poam['status'] || 'DRAFT' == $this->poam['status']
                        && $this->acl->isAllowed('remediation', 'update_finding_assignment')) {
                        echo 'class="editable" target="action_owner"'; 
                    }
                    ?>>Responsible System:
                </div>
            </td>
            <td>
                <div name="poam[system_id]" 
                     id="action_owner" 
                     type="select" 
                     href="/metainfo/list/o/system/format/html/">
                    <?php echo $this->system_list[$this->poam['system_id']]; ?>
                </div>
            </td>
        </tr>
    </table>
    <?php Format_Section::stopSection(); ?>
</div>

<div class="column right">
    <?php Format_Section::startSection("Asset"); ?>
    <table class="keyValues">
        <tr>
            <td>
                Asset Owner:
            </td>
            <td>
                <?php
                    echo isset($this->system_list[$this->poam['asset_owner']]) ? 
                        $this->system_list[$this->poam['asset_owner']] : "n/a";
                ?>
            </td>
        </tr>
        <tr>
            <td>
                Asset Name:
            </td>
            <td>
                <?php 
                    echo isset($this->poam['asset_name']) ? $this->poam['asset_name'] : 'n/a';
                ?>
            </td>
        </tr>
        <tr>
            <td>
                Network:
            </td>
            <td>
                <?php 
                    echo isset($this->network_list[$this->poam['network_id']]) ?
                         $this->network_list[$this->poam['network_id']] : '(n/a)';
                ?>
            </td>
        </tr>
        <tr>
            <td>
                IP Address:
            </td>
            <td>
                <?php 
                    echo isset($this->network_list[$this->poam['network_id']]) ?
                         ($this->poam['ip'] . ':' . $this->poam['port']) : '(n/a)';
                ?>
            </td>
        </tr>
        <tr>
            <td>
                Product Information:
            </td>
            <td>
                <?php  
                    if(!empty($this->poam['product'])) {
                        echo $this->poam['product']['prod_vendor'] . ' ' .
                             $this->poam['product']['prod_name'] . ' ' .
                             $this->poam['product']['prod_version'];
                    } else {
                        echo 'n/a';
                    }
                ?>
            </td>
        </tr>
    </table>
    <?php Format_Section::stopSection(); ?>
</div>

<div class="clear"></div>

<?php 
if ($this->acl->isAllowed('remediation','update_finding_description')) {
    Format_Section::startSection('Description', 'finding_description');
} else {
    Format_Section::startSection('Description');
}
?>
<div name="poam[finding_data]" id="finding_description" type="textarea" rows="3" cols="160"> 
    <?php echo $this->poam['finding_data']; ?>
</div>
<?php Format_Section::stopSection(); ?>

<?php
if ('NEW' == $this->poam['status'] || 'DRAFT' == $this->poam['status']
    && $this->acl->isAllowed('remediation', 'update_finding_recommendation')) {
    Format_Section::startSection('Recommendation', 'recommendation');
} else {
    Format_Section::startSection('Recommendation');
}
?>
<div name="poam[action_suggested]" id="recommendation" type="textarea" rows="3" cols="160">
    <?php echo $this->poam['action_suggested']; ?>
</div>
<?php Format_Section::stopSection(); ?>

<?php
Format_Section::startSection('NIST 800-53 Control Mapping');
?>
<table class="keyValues">
    <tr>
        <td>
            <div
                <?php
                if ($this->acl->isAllowed('remediation', 'update_control_assignment')) {
                    echo "class='editable' target='blscr'";
                }
                ?>>
                Control ID:
            </div>
        </td>
        <td>
            <span id="blscr" type="select" name="poam[blscr_id]" href="/metainfo/list/o/blscr/format/html/"> 
                <?php echo $this->poam['blscr_id']; ?>
            </span>
        </td>
    </tr>
    <?php if( !empty($this->poam['blscr']) ) { 
        $blscr = $this->poam['blscr']; ?>
        <tr>
            <td>
                <table>
                    <tr>
                        <th class="tdc">Control Number</th>
                        <th class="tdc">Class</th>
                        <th class="tdc">Family</th>
                        <th class="tdc">Subclass</th>
                        <th class="tdc">Low</th>
                        <th class="tdc">Moderate</th>
                        <th class="tdc">High</th>
                    </tr>
                    <tr>
                        <td class="tdc"><?php echo $blscr['code'];?></td>
                        <td class="tdc"><?php echo $blscr['class'];?></td>
                        <td class="tdc"><?php echo $blscr['family'];?></td>
                        <td class="tdc"><?php echo $blscr['subclass'];?></td>
                        <td class="tdc" align="center">
                            <?php 
                                echo 'LOW' == $blscr['control_level']? 'Control Required' : 'Control Not Required';
                            ?>
                        </td>
                        <td class="tdc" align="center">
                            <?php 
                                echo 'LOW' == $blscr['control_level'] ||
                                         'MODERATE' == $blscr['control_level'] ? 'Control Required' : 'Control Not Required';
                            ?>
    
                        </td>
                        <td class="tdc" align="center">
                            <?php
                                echo 'LOW' == $blscr['control_level'] ||
                                         'MODERATE' == $blscr['control_level'] ||
                                         'HIGH' == $blscr['control_level'] ? 'Control Required' : 'Control Not Required';
                            ?>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td><b>Control:</b></td>
            <td><?php echo $blscr['control'];?></td>
        </tr>
        <tr>
            <td><b>Guidance:</b></td>
            <td><?php echo $blscr['guidance'];?></td></tr>
        <tr>
            <td><b>Enhancements:</b></td>
            <td>
                <?php echo isset($blscr['enhancements'])?$blscr['enhancements']:'<i>(none given)</i>'; ?>
            </td>
        </tr>
        <tr>
            <td><b>Supplement:</b></td>
            <td>
                <?php echo isset($blscr['supplement'])?$blscr['supplement']:'<i>(none given)</i>'; ?>
            </td>
        </tr>
    <?php } ?>
</table>
<?php Format_Section::stopSection(); ?>