<?php Format_Section::startSection("Mitigation Strategy"); ?>
<p>
    <b>
        Type:
    </b>
    <span name="poam[type]" id="type" type="select" href="/metainfo/list/o/type/format/html/"
        <?php
            if(('NEW' == $this->poam['status'] || 'DRAFT' == $this->poam['status'])&& $this->acl->isAllowed('remediation','update_finding_course_of_action')){
                echo 'class="editable" target="type"';
            }
        ?>>
        <?php echo $this->poam['type']; ?>
    </span>
</p>
            
<p>
    <b
        <?php 
            if(in_array($this->poam['status'],array('NEW','DRAFT'))
                && $this->acl->isAllowed('remediation','update_finding_course_of_action')){
               echo 'class="editable" target="action_planned"';
            }
        ?>>
        Description:
    </b>
</p>
<p name="poam[action_planned]" id="action_planned" type="textarea">
    <?php echo $this->poam['action_planned']; ?> 
</p>

<p>
    <b
        <?php
            if(in_array($this->poam['status'], array('NEW', 'DRAFT'))
                && $this->acl->isAllowed('remediation', 'update_finding_resources')) {
                echo 'class="editable" target="action_resources"';
            } 
        ?>>
        Resources Required:
    </b>
</p>
<p name="poam[action_resources]" id="action_resources" type="textarea"> 
    <?php echo $this->poam['action_resources']; ?> 
</p>

<?php
    if(!empty($this->poam['action_est_date'])
        && $this->poam['action_est_date'] != $this->poam['action_current_date']) {
?>

    <p>
        The "Original ECD" is used for FISMA reporting to OMB and may not be changed.<br>
        The "Current ECD" is used for agency purposes and may be modified.
    </p>
            
    <p>
        <b target="est_date">Original Expected Completion Date:</b>
        <?php echo $this->poam['action_est_date']; ?>
    </p>
<?php } ?>
<p>
    <b>Current Expected Completion Date:</b>
    <span name="poam[action_current_date]" id="action_est_date" type="text"
        <?php 
            if ($this->acl->isAllowed('remediation', 'update_finding_course_of_action')
                && in_array($this->poam['status'], array('NEW', 'DRAFT'))) {
                echo ' class="date editable" target="action_est_date">';
            }
            
            if (!isset($this->poam['action_current_date'])) {
                $this->poam['action_current_date'] = '0000-00-00';
            }
            echo $this->poam['action_current_date'] ;
         ?>
    </span>
    <?php 
    if (!empty($this->poam['ecd_justification'])) {
        echo '<b>Justification:</b> '
           . $this->poam['ecd_justification']
           . ' ('
           . $this->justification['account']
           . ' on '
           . $this->justification['time']
           . ')';
    }
    
    if (!empty($this->poam['action_est_date'])) { 
    ?>
        <div id="ecd_justification" style="display:none">
            <i>Input ECD change justification here:</i>
            <input type="text" 
                   name="poam[ecd_justification]" 
                   value="<?php echo $this->poam['ecd_justification'];?>" 
                   size="100px">
        </div>
        <span name="poam[ecd_justification]" id="ecd_justification" type="text" size="100px"></span>
    <?php } ?>
</p>
<p>
    <b>Actual Completion Date:</b>
    <?php 
    if (!isset($this->poam['action_actual_date'])) {
        echo '<i>(not completed)</i>';
    }
    echo $this->poam['action_actual_date'] ;
     ?>
</p>
<?php Format_Section::stopSection(); ?>

<script language="javascript">
    function delok()
    {
        var str = "The revised mitigation strategy must be fully approved before evidence can be re-submitted. Are you sure that you want to continue?";
        if(confirm(str) == true){
            return true;
        }
        return false;
    }
</script>

<?php 
Format_Section::startSection("Mitigation Strategy Approval");
$postAction = "/remediation/msa/id/" . $this->poam['id'];
$array = array('description'   => $this->poam['finding_data'],
               'recommendation'=> $this->poam['action_suggested'],
               'description'   => $this->poam['action_planned'],
               'resources'     => $this->poam['action_resources'],
               'blscr'         => $this->poam['blscr_id'],
               'threat_level'  => $this->poam['threat_level'],
               'threat_source' => $this->poam['threat_source'],
               'cmeasure_effectiveness' => $this->poam['cmeasure_effectiveness'],
               'cmeasure' => $this->poam['cmeasure']);
$complete = 0;
foreach ($array as $row) {
    if($row == '' || $row == 'NONE'){
        $complete++;
    }
}
if ('NEW' == $this->poam['status'] || 'DRAFT' == $this->poam['status']) {
    echo "<script type=\"text/javascript\">
                function submitMitigationStrategy(event, obj) {
                    if (form_confirm(document.finding_detail, \"Submit Mitigation Strategy\")) {
                        document.location = \"$postAction/is_msa/1\";
                    }
                }
          </script>";
          
    echo '<p><i>The mitigation strategy, security control, and risk analysis sections must
          be fully completed before this can be submitted for approval.</i></p>';

    $submitMitigationButton = new Yui_Form_Button('Submit Mitigation Strategy', 'submitMitigation');
    $submitMitigationButton->onClick('submitMitigationStrategy');
    if (0 != $complete || !$this->acl->isAllowed('remediation', 'mitigation_strategy_submit')) {
        $submitMitigationButton->readOnly = true;
    }
    echo "<div>$submitMitigationButton</div>";
    
    if ('EN' == $this->poam['status'] && $this->acl->isAllowed('remediation', 'mitigation_strategy_revise')) {
        echo "<a class=\"button\" href=\"$postAction/is_msa/0\" onclick=\"return delok();\">Revise Mitigation Strategy</a><br><br>";
    }  
}

if ($this->poam['status'] != 'NEW' && ($this->poam['status'] != 'DRAFT' || !empty($this->ms_evaluation))) {
    $i = 0;
    foreach ($this->ms_evals as $v) {
        $k = $i++;
        echo "<form action=\"$postAction\" method=\"post\" name=\"ms_approval_{$k}\">
              <div class=\"approval\">";
        $editable = true;
        $comment = new Comments();
        foreach ($v as $precedenceId=>$row) {
            $value = 'NONE';
            if (isset($row['decision'])) {
                $value = $row['decision'];
            }
            echo "<p><b>" . $row['name'] . ":</b>";
            if ('NONE' == $value && $editable) {
                if ($this->acl->isAllowed('remediation', $row['function'])) {
                    echo '<input type="hidden" name="eval_id" value="' . $row['id'] . '"/>';
                    echo '<input type="hidden" name="comment" value="" />';
                    echo '<input type="hidden" name="decision" value="APPROVED" />';
                    echo '<input type="submit" value="APPROVE" 
                        onclick="return form_confirm(document.poam_detail,\'approve ' . $row['name'] . '\');"/>';
                    echo '<input type="button" value="DENY" onclick="ms_comment(document.ms_approval_' . $k.');" />';
                } else {
                    echo 'PENDING...';
                }
                $editable = false;
            } else {
                echo $value;
                if ($value == 'APPROVED') {
                    echo "<span class=\"approved\">({$row['username']} on {$row['date']})</span>";
                } else if ($value == 'DENIED') {
                    $ret = $comment->fetchRow('poam_evaluation_id = ' . $row['pev_id']);
                    echo "<span class=\"denied\">";
                    if (!empty($ret)) {
                        echo "<b>\"{$ret->content}\"</b>";
                    }
                    echo "({$row['username']} on {$row['date']})</span>";
                }
            }
            echo "</p>";
        }
        echo "</div></form>";
    } 
}
Format_Section::stopSection(); 
?>
