<?php
    Fisma_Format_Section::startSection("Mitigation Strategy"); 
    $finding = $this->finding;
    $organization = $finding->ResponsibleOrganization->nickname;
?>
<p>
    <b>Type:</b>

    <span type="select" name="finding[type]" href="/metainfo/list/o/type/format/html/" id="type"
        <?php 
            if (('NEW' == $finding->status || 'DRAFT' == $finding->status) 
                && Fisma_Acl::hasPrivilege('finding', 'update_course_of_action', $organization)) {
                echo 'class="editable" target="type"';
            }
        ?>>
        <?php echo $finding->type;?>&nbsp;&nbsp;
    </span>
</p>
            
<p>
    <b target="mitigation_strategy"
        <?php 
            if (in_array($finding->status, array('NEW', 'DRAFT'))
                && Fisma_Acl::hasPrivilege('finding', 'update_course_of_action', $organization)) {
               echo 'class="editable"';
            }
        ?>>
        Description:
    </b>
</p>
<div name="finding[mitigationStrategy]" id="mitigation_strategy" type="textarea">
    <?php echo $finding->mitigationStrategy; ?> 
</div>

<p>
    <b
        <?php
            if(in_array($finding->status, array('NEW', 'DRAFT'))
                && Fisma_Acl::hasPrivilege('finding', 'update_resources', $organization)) {
                echo 'class="editable" target="resources_required"';
            } 
        ?>>
        Resources Required:
    </b>
</p>
<div name="finding[resourcesRequired]" id="resources_required" type="textarea"> 
    <?php echo $finding->resourcesRequired; ?> 
</div>

<?php 
if ($finding->originalEcd == $finding->currentEcd) {
?>
<p>
    <b>Expected Completion Date:</b>
    <span name="finding[currentEcd]" id="currentEcd" type="text"
        <?php 
            if (Fisma_Acl::hasPrivilege('finding', 'update_course_of_action', $organization)
                && in_array($finding->status, array('NEW', 'DRAFT'))) {
                echo ' class="date editable" target="currentEcd"';
                if ($finding->ecdLocked) {
                    echo 'onclick="document.getElementById(\'ecdChangeDescription\').style.display = \'block\';"';
                }
                echo '>';
            } else {
                echo '>';
            }
            echo (empty($finding->currentEcd) ? 'NONE' : $finding->currentEcd);
        ?>
    </span>
</p>
<p style="display: none;" id='ecdChangeDescription'>
    <b>Enter a justification for the date change: </b>
    <input type="text" 
           style="visibility:none" 
           name="finding[ecdChangeDescription]"
           size="80">
</p>
<?php
} else {
?>
<p>
    <i>
        The original ECD indicates the estimated completion date that was agreed upon when the finding 
        was first approved, and it cannot be changed.
        The current ECD can be changed, but you must provide a written justification for the change.
    </i>
</p>
<p>
    <b>Original ECD:</b>
    <span><?php echo $finding->originalEcd; ?></span>
</p>
<p>
    <b>Current ECD:</b>
    <span name="finding[currentEcd]" id="currentEcd" type="text"
        <?php 
            if (Fisma_Acl::hasPrivilege('finding', 'update_course_of_action', $organization)
                && in_array($finding->status, array('NEW', 'DRAFT'))) {
                echo ' class="date editable" target="currentEcd"';
                if ($finding->ecdLocked) {
                    echo 'onclick="document.getElementById(\'currentChangeDescription\').style.display = \'none\';
                          document.getElementById(\'ecdChangeDescription\').style.display = \'inline\'"';
                }
                echo '>';
            } else {
                echo '>';
            }
            echo (empty($finding->currentEcd) ? 'NONE' : $finding->currentEcd);
        ?>
    </span>
    <input type="text" style="display:none" 
           name="finding[ecdChangeDescription]"
           value="<?php echo $finding->ecdChangeDescription; ?>">
</p>
<p>
    <b>Justification for changing the ECD: </b>
    <span id="currentChangeDescription"><?php echo $finding->ecdChangeDescription; ?></span>
    <input type="text" style="display:none" 
           id='ecdChangeDescription'
           name="finding[ecdChangeDescription]"
           value="<?php echo $finding->ecdChangeDescription; ?>">
    
</p>
<?php
}
?>

<p>
    <b>Actual Completion Date: </b>
    <span>
        <?php 
            if (empty($finding->actualCompletionDate)) {
                echo '(not completed)';
            } else {
                echo $finding->actualCompletionDate;
            }
        ?>
    </span>
</p>
    
<?php Fisma_Format_Section::stopSection(); ?>

<?php 
Fisma_Format_Section::startSection("Mitigation Strategy Approval");
$postAction = "/panel/remediation/sub/msa/id/" . $finding->id;

$array = array('type'                   => $finding->type,
               'description'            => $finding->description,
               'recommendation'         => $finding->recommendation,
               'resources'              => $finding->resourcesRequired,
               'ECD'                    => $finding->currentEcd,
               'blscr'                  => $finding->securityControlId,
               'threat_level'           => $finding->threatLevel,
               'threat_source'          => $finding->threat,
               'cmeasure_effectiveness' => $finding->countermeasuresEffectiveness,
               'cmeasure'               => $finding->countermeasures);
$complete = true;
foreach ($array as $row) {
    if ($row == '' || $row == 'NONE' || $row == '0000-00-00') {
        $complete = false;
        continue;
    }
}
if ('NEW' == $finding->status || 'DRAFT' == $finding->status) {
    echo "<script type=\"text/javascript\">
                function submitMitigationStrategy(event, obj) {
                    if (form_confirm(document.finding_detail, \"Submit Mitigation Strategy\")) {
                        document.location = \"$postAction/do/submitmitigation\";
                    }
                }
          </script>";
          
    echo '<p><i>The mitigation strategy, security control, and risk analysis sections must
          be fully completed before this can be submitted for approval.</i></p>';

    $submitMitigationButton = new Fisma_Yui_Form_Button('submitMitigation', 
                                                  array('label' => 'Submit Mitigation Strategy', 
                                                        'onClickFunction' => 'submitMitigationStrategy')    );
    if (false == $complete
        || !Fisma_Acl::hasPrivilege('finding', 'mitigation_strategy_submit', $organization)) {
        $submitMitigationButton->readOnly = true;
    }
    echo "<div class='toolbar'>$submitMitigationButton</div>";
}

if ('EN' == $finding->status && Fisma_Acl::hasPrivilege('finding', 'mitigation_strategy_revise', $organization)) {
    echo "<script language=\"javascript\">
            function reviseMitigationStrategy()
            {
                var str = \"The revised mitigation strategy must be fully approved before evidence can be re-submitted. Are you sure that you want to continue?\";
                if(confirm(str) == true){
                    location.href = \"$postAction/do/revisemitigation\";
                }
                return false;
            }
          </script>";
    $reviseMitigationButton = new Fisma_Yui_Form_Button('reviseMitigationButton',
                                                  array('label' => 'Revise Mitigation Strategy', 
                                                        'onClickFunction' => 'reviseMitigationStrategy'));
    echo "<div class='toolbar'>$reviseMitigationButton</div>";
}  

if ($finding->status != 'NEW' 
    && ($finding->status != 'DRAFT' || $finding->FindingEvaluations->count() > 0)) {
    echo '<div class="approval">';
    foreach ($finding->getFindingEvaluations('action') as $findingEvaluation) {
        $userName = $findingEvaluation->User->nameFirst . ' ' . $findingEvaluation->User->nameLast;
        $decision = $findingEvaluation->decision;
        echo '<p><b>' . html_entity_decode($findingEvaluation->Evaluation->name) . '</b>';
        if ('APPROVED' == $decision) {
            echo "<span class=\"approved\">$decision ";
            if (!empty($findingEvaluation->comment)) {
                echo "&mdash; \"{$findingEvaluation->comment}\" ";
            }
            echo "($userName on $findingEvaluation->createdTs)</span>";
        } elseif ('DENIED' == $decision) {
            echo "<span class=\"denied\">$decision ";
            if (!empty($findingEvaluation->comment)) {
                echo "&mdash; \"{$findingEvaluation->comment}\" ";
            }
            echo "($userName on $findingEvaluation->createdTs)</span>";
        }
        echo "</p>";
        if ($findingEvaluation->Evaluation->nextId == null || 'DENIED' == $decision) {
            echo '</div><div class="approval">';
        }
    }

    $activeEvaluation = $finding->CurrentEvaluation;
    if ($activeEvaluation->id != null && $activeEvaluation->approvalGroup == 'action') {
        echo '<p><b>' . html_entity_decode($activeEvaluation->name) . '</b>';
        if (Fisma_Acl::hasPrivilege('finding', $activeEvaluation->Privilege->action, $organization)) {
            echo '<input type="hidden" name="comment" value="" />';
            echo '<input type="hidden" name="decision" value="APPROVED" />';
            echo '<input name="submit_msa" type="button" value="APPROVED"
                onclick="ms_approve(document.finding_detail);"/>&nbsp;';
            echo '<input type="button" value="DENIED" onclick="ms_deny(document.finding_detail);" />';
        } else {
            echo "PENDING";
        }
    }

    $disableEvaluations = array();
    $currentEvaluation  = $finding->CurrentEvaluation;
    if ($currentEvaluation->approvalGroup == 'action') {
        while ($currentEvaluation->nextId != null)  {
            $currentEvaluation    = $currentEvaluation->NextEvaluation;
            $disableEvaluations[] = $currentEvaluation;
        }
    }

    foreach ($disableEvaluations as $evaluation) {
        echo "<p><b>{$evaluation->name}</b>";
        echo "EXCLUDED";
    }
    echo "</div>";
}
Fisma_Format_Section::stopSection(); 
?>
