<script language="javascript">
function delok()
{
    var str = "The revised mitigation strategy must be fully approved before evidence can be re-submitted. Are you sure that you want to continue?";
    if(confirm(str) == true){
        return true;
    }
    return false;
}
</script>
<div class="barleft">
    <div class="barright">
        <p><b>Mitigation Strategy Approval</b></p>
    </div>
</div>
<!-- BEGIN MITIGATION STRATEGY APPROVAL TABLE -->
<?php
    $postAction = "/remediation/msa/id/".$this->poam['id'];
    $array = array('description'   =>$this->poam['finding_data'],
                   'recommendation'=>$this->poam['action_suggested'],
                   'desciption'    =>$this->poam['action_planned'],
                   'resources'     =>$this->poam['action_resources'],
                   'blscr'         =>$this->poam['blscr_id'],
                   'threat_level'  =>$this->poam['threat_level'],
                   'threat_source' =>$this->poam['threat_source'],
                   'cmeasure_effectiveness'=>$this->poam['cmeasure_effectiveness'],
                   'cmeasure'=>$this->poam['cmeasure']);
    $complete = 0;
    foreach($array as $row){
        if($row == '' || $row == 'NONE'){
            $complete++;
        }
    }
    if (0 == $complete) {
?>

<?php if ('DRAFT' == $this->poam['status'] && $this->acl->isAllowed('remediation', 'mitigation_strategy_submit')) { ?>
    <a class="button" href="<?php echo $postAction;?>/is_msa/1">Submit Mitigation Strategy</a><br><br>
<?php } if ('EN' == $this->poam['status'] && $this->acl->isAllowed('remediation', 'mitigation_strategy_revise')) { ?>
    <a class="button" href="<?php echo $postAction;?>/is_msa/0" onclick="return delok();">Revise Mitigation Strategy</a><br><br>
<?php }  } else { ?>
    <p><i>The mitigation strategy, security control, and risk analysis sections must
    be fully completed before this can be submitted for approval.</i></p>
    <p></p>
<?php }
    if ($this->poam['status']!='NEW' && ($this->poam['status']!='DRAFT' || !empty($this->ms_evaluation))) {
        $i = 0;
        foreach ($this->ms_evals as $v) {
            $k = $i++;
?>
<form action="<?php echo $postAction;?>" method="post" name="ms_approval_<?php echo $k;?>">
<table border="0" cellpadding="5" cellspacing="1" class="tipframe">
    <th align='left' colspan="2">Approval</th>
<?php
    $editable = true;
    if ('DRAFT' == $this->poam['status']) {
        $editable = false; // Mitigation strategy can not be approved while in DRAFT status
    }
    $comment = new Comments();
    foreach ($v as $precedenceId=>$row) {
        $value = 'NONE';
        if (isset($row['decision'])) {
            $value = $row['decision'];
        }
        echo "<tr><td><b>".$row['name']."&nbsp;</b>";
        if ('NONE' == $value && $editable) {
            if($this->acl->isAllowed('remediation', $row['function'])){
                echo '<input type="hidden" name="eval_id" value="'.$row['id'].'"/>';
                echo '<input type="hidden" name="comment" value="" />';
                echo '<input type="hidden" name="decision" value="APPROVED" />';
                echo '<input type="submit" value="APPROVE" />';
                echo '<input type="button" value="DENY" onclick="ms_comment(document.ms_approval_'.$k.');" />';
                $editable = false;
            }
        } else {
            echo $value."</td>";
            if ($value == 'APPROVED') {
                echo "<td> -- <i>by {$row['username']} ON {$row['date']}</i></td>";
            } else if ($value == 'DENIED') {
                $ret = $comment->fetchRow('poam_evaluation_id = '.$row['pev_id']);
                echo "<td>";
                if (!empty($ret)) {
                    echo "<b>{$ret->content}</b>";
                }
                echo " -- <i> by {$row['username']} ON {$row['date']}</i></td>";
            }
        }
    }

?>
</table>
</form>
<?php } }?>

<!-- END MITIGATION STRATEGY APPROVAL TABLE -->
