<div class="barleft">
<div class="barright">
<p><b>NIST 800-53 Control Mapping</b><span></span></p>
</div>
</div>
        <!-- BLSCR TABLE -->
        <table border="0" width="95%" align="center" cellpadding="5" class="tipframe">
            <tr>
                <th align="left" ><span target="blscr" <?php
                    if($this->acl->isAllowed('remediation','update_control_assignment')){
                        echo ' class="editable"';
                    }
                ?> >Security Control:&nbsp;</span>
                <span id="blscr" type="select" name="poam[blscr_id]" href="/metainfo/list/o/blscr/format/html/"> 
                <?php echo $this->poam['blscr_id']; ?>
                </span>
                </th>
            </tr>
            <?php  if( !empty($this->poam['blscr']) ) { 
                $blscr = $this->poam['blscr']; ?>
            <tr>
                <td>
                <table align="left" border="0" cellpadding="5" cellspacing="0" class="tipframe">
                <tr>
                    <th class="tdc">Control Number</th>
                    <th class="tdc">Class</th>
                    <th class="tdc">Family</th>
                    <th class="tdc">Subclass</th>
                    <th class="tdc">Low</th>
                    <th class="tdc">Moderate</th>
                    <th class="tdc">High</th>
                </tr>
                <tr>
                    <td class="tdc"><?php echo $blscr['code'];?></td>
                    <td class="tdc"><?php echo $blscr['class'];?></td>
                    <td class="tdc"><?php echo $blscr['family'];?></td>
                    <td class="tdc"><?php echo $blscr['subclass'];?></td>
                    <td class="tdc" align="center">
                        <?php echo 'LOW' == $blscr['control_level']? 'Control Required' : 'Control Not Required';?>
                    </td>
                    <td class="tdc" align="center">
                        <?php echo 'LOW' == $blscr['control_level'] ||
                                   'MODERATE' == $blscr['control_level'] ? 'Control Required' : 'Control Not Required';?>

                    </td>
                    <td class="tdc" align="center">
                        <?php echo 'LOW' == $blscr['control_level'] ||
                                   'MODERATE' == $blscr['control_level'] ||
                                   'HIGH' == $blscr['control_level'] ? 'Control Required' : 'Control Not Required';?>

                    </td>
                </tr>
                </table>
                </td>
            </tr>
            <tr><td><b>Control:&nbsp;</b> <?php echo $blscr['control'];?></td></tr>
            <tr><td><b>Guidance:&nbsp;</b> <?php echo $blscr['guidance'];?></td></tr>
            <tr><td><b>Enhancements:&nbsp;</b>
                <?php echo isset($blscr['enhancements'])?$blscr['enhancements']:'<i>(none given)</i>'; ?>
            </td></tr>
            <tr><td><b>Supplement:&nbsp;</b>
                <?php echo isset($blscr['supplement'])?$blscr['supplement']:'<i>(none given)</i>'; ?>
            </td></tr>
            <?php  }  ?>
        </table>
<!-- Heading Block -->
<div class="barleft">
<div class="barright">
<p><b>Risk Analysis</b><span></span></p>
</div>
</div>
<?php
if ($this->acl->isAllowed('report','generate_system_rafs')) {
?>
            <table class="tipframe">
                <tr>
                <th align="left" > Risk Analysis Form </th>
                </tr>
                <tr>
                    <td >
                        The following section will be used to generate the overall risk level of this finding as it pertains to the organization. Risk is calculated by evaluating the security categorization of the information system along with the threat and existence of current countermeasures. 
                    </td>
                </tr>
                <tr><td>
        <?php 
            // Check to see if the threat level/description and countermeasure level/description is set. If so, allow the user to generate a RAF
            if( $this->poam['threat_source'] != '' &&
                $this->poam['threat_level'] != 'NONE' &&
                $this->poam['cmeasure'] != '' &&
                $this->poam['cmeasure_effectiveness'] != 'NONE'){
        ?>
                <ul class='linwise' >
                    <li>
                    <a class='button' target='_blank' 
                    href="/remediation/raf/format/pdf/id/<?php echo $this->poam['id'];?>")>
                    <img src="/images/pdf.gif" />&nbsp;View Risk Analysis Form</a>
                    </li>
                </ul>
        <?php } else { ?>
            <i>(Threat and Countermeasure information must be completed to generate a Risk Analysis Form)</i>
        <?php } ?>
            </td>
                </tr>
            </table>
<?php
}
?>

            <!-- THREATS TABLE -->
            <table cellpadding="5" cellspacing="1" class="tipframe" >
                <tr><th align='left'>Threat Information</th></tr>
                <tr>
                    <td>
                        A threat is the potential for a particular threat-source to successfully exercise a particular vulnerability. A vulnerability is a bug, flaw, weakness, or exposure of an application, system, device, or service that could lead to a failure of confidentiality, integrity, or availability. The threat level allows the organization to prioritize security weaknesses based on their level of threat to the information system. Usually, the security level and description are pre-populated from vulnerability scan data, however, manual findings need an assigned threat level and description.   
                    </td>
                </tr>
                <tr>
                    <td>
                    <b target="threat" <?php 
                        if($this->acl->isAllowed('remediation','update_threat')){ 
                            echo ' class="editable"';
                        } ?> >Threat Level:&nbsp;</b>
                    <br><span id ="threat" type="select" name="poam[threat_level]"
                            href="/metainfo/list/o/threat_level/format/html/">
                        <?php echo $this->poam['threat_level']; ?>
                     </span>
                    </td>
                 </tr>
                 <tr>
                     <td>
                     <b target="threat_source" <?php 
                        if($this->acl->isAllowed('remediation','update_threat')){ 
                            echo 'class="editable"';
                        } ?> >Threat Description:&nbsp;</b>
                     <br><span type="textarea" id="threat_source" name="poam[threat_source]" rows="5" cols="160">
                     <?php echo $this->poam['threat_source']; ?>
                     </span>
                     </td>
                 </tr>
                </table>
                 <!-- END THREATS TABLE -->
            <!-- COUNTERMEASURE TABLE -->
            <table border="0" cellpadding="5" cellspacing="1" class="tipframe" width="100%">
                <th align="left" colspan="2">Countermeasure Information</th>
                    <tr>
                        <td>
                            The goal of this step is to analyze the controls that are currently implemented by the organization to minimize or eliminate the likelihood (or probability) of the vulnerability being exercised or exploited. This should not include countermeasures that are planned and are not currently in place. Countermeasures or Security controls can be technical and nontechnical methods. Examples of technical controls would be; access control mechanisms, identification and authentication mechanisms, encryption methods, intrusion detection software, etc. Examples of nontechnical controls would be management and operational controls, such as; security policies, operational procedures, personnel, physical, and environmental security.
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b target="effectiveness" <?php 
                                if($this->acl->isAllowed('remediation','update_countermeasures')){
                                    echo 'class="editable"';
                                }?> >Countermeasures Effectiveness:&nbsp;</b>
                            <br><span type="select" name="poam[cmeasure_effectiveness]"
                            id="effectiveness" href="/metainfo/list/o/cmeasure_effectiveness/format/html/">
                            <?php echo $this->poam['cmeasure_effectiveness']; ?>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b target="cmeasure" <?php 
                                if($this->acl->isAllowed('remediation','update_countermeasures')){
                                    echo 'class="editable"';
                                } ?> >Description of Countermeasures:&nbsp;</b>
                            <br><span type="textarea" id="cmeasure" name="poam[cmeasure]" rows="5" cols="160">
                            <?php echo $this->poam['cmeasure']; ?>
                            </span>
                        </td>
                    </tr>
                </table>
            <!-- END COUNTERMEASURE TABLE -->
