<?php
    include_once ( 'pdf/class.ezpdf.php');

    $headerOptions = array('showHeadings'=>0,
                           'width'=>500);
    $labelOptions = array('showHeadings'=>0,
                          'shaded'=>0,
                          'showLines'=>0,
                          'width'=>500);
    $tableOptions = array('showHeadings'=>0,
                          'shaded'=>0,
                          'showLines'=>2,
                          'width'=>500
                          );

    $p = &$this->poam ; //alias
    $sys = new System();
    $rows = $sys->find($p['system_id']);
    $act_owner = $rows->current()->toArray();

    $organization = new Organization();
    $ret = $organization->find($act_owner['organization_id']);
    $organization = $ret->current()->toArray();

    $columns = $sys->getEnumColumns('security_categorization');
    array_shift($columns);
    $columnsCols = array_reverse($columns);
    $i = 0;
    foreach ($columnsCols as $col) {
        foreach ($columns as $row) {
            $cellidx_lookup[$col][$row] = $i++;
        }
    }

    $availability = &$act_owner['availability'];
    $impact = $sys->calcMin($act_owner['security_categorization'], $availability);
    $threat_likelihood = $sys->calcThreat($this->poam['threat_level'], $this->poam['cmeasure_effectiveness']);

    $threat_index = $cellidx_lookup[$p['threat_level']][$p['cmeasure_effectiveness']];
    $risk_index = $cellidx_lookup[$threat_likelihood][$impact];

    define('FONTS', APPLICATION_ROOT . '/library/pdf/fonts');

    $pdf = new Cezpdf();
    $pdf->selectFont(FONTS . "/Helvetica.afm");

    $pdf->ezSetMargins(50,110,50,50);

    $pdf->ezText('Risk Analysis Form (RAF)', 20, array('justification'=>'center'));
    $pdf->ezText('', 12, array('justification'=>'center')); //vertical blank
    $pdf->ezText('', 12, array('justification'=>'center'));

    $data = array(array('<b>Finding Information</b>'));
    $pdf->ezTable($data, null, null, $headerOptions);
    $pdf->ezText('', 12, array('justification'=>'center'));

    $data = array(array("<b>Finding Number:</b>", $p['id'],
                        "<b>Finding Source:</b>", strip_tags($p['source_name'])),
                  array("<b>Date Opened</b>", $p['create_ts'],
                        "<b>Date Discovered:</b>", $p['discover_ts']),
                  array("<b>Organization</b>", $organization['name'],
                        "<b>Infomation System:</b>", $this->system_list[$p['system_id']]),
                  array("<b>Asset(s) Affected:</b>", $p['asset_name'],"",""),
                  array("<b>Finding Description:</b>", strip_tags($p['finding_data']),"",""),
                  array("<b>Recommendation:</b>",  strip_tags($p['action_suggested']),"",""),
                  array("<b>Risk Level:</b>",  $p['threat_level'],"",""));
    $pdf->ezTable($data, null, null, $labelOptions);

    $pdf->ezText('', 12, array('justification'=>'center'));
    $data = array(array('<b>Mitigation Strategy</b>'));
    $pdf->ezTable($data, null, null, $headerOptions);
    $pdf->ezText('', 12, array('justification'=>'center'));
    $data = array(array("<b>Course of Action:</b>", strip_tags($p['action_planned']), "", ""),
                  array("<b>Course of Description:</b>", strip_tags($p['action_resources']), "", ""),
                  array("<b>Estimated Completion Date:</b>", $p['action_current_date'], "", "")); 
    $pdf->ezTable($data, null, null, $labelOptions);

    $pdf->ezText('', 12, array('justification'=>'center'));
    $data = array(array('<b>Risk Analysis</b>'));
    $pdf->ezTable($data, null, null, $headerOptions);
    $pdf->ezText('', 12, array('justification'=>'center'));
    if ($act_owner['security_categorization'] == $columns['2']) {
        $effect = 'severe or catastrophic';
    } elseif ($act_owner['security_categorization'] == $columns['1']) {
        $effect = 'serious';
    } elseif ($act_owner['security_categorization'] == $columns['0']) {
        $effect = 'limited';
    } else {
        $effect = '';
    }
    $data = array(array("", "<b><i>Security Categorization</i></b>"),
                  array("<b>Security Categorization:</b>", $act_owner['security_categorization']),
                  array("<b>Security Categorization Description:</b>", !empty($effect)?"The loss of confidentiality, integrity, or availability could be expected to have a ".$effect." adverse effect on organizational operations, organizational assets, or individuals. This is the maximum level of risk exposure based on the Information System Security Categorization data.":"This system's Confidentiality, Integrity, and Availability are not defined; therefore, the system security categorization is also undefined."));
    $pdf->ezTable($data, null, null, $labelOptions);

    $data = array(array("", "<b><i>Overall likelihood Rating</i></b>"));
    $pdf->ezTable($data, null, null, $labelOptions);
    $data = array(array("To derive an overall likelihood rating that indicates the probability that a potential vulnerability may be exercised within the construct of the associated threat environment, the following governing factors must be considered: Threat-source motivation and capability, Nature of the vulnerability, and Existence and effectiveness of current controls."));
    $pdf->ezTable($data, null, null, $labelOptions);

    $data = array(array("<b>Threat:</b>", strip_tags($p['threat_source']), "", ""),
                  array("<b>Threat Level:</b>", $p['threat_level'], "", ""),
                  array("<b>Countermeasures:</b>", strip_tags($p['cmeasure']), "", ""),
                  array("<b>Countermeasures Effectiveness:</b>", strip_tags($p['cmeasure_effectiveness']), "", ""));
    $pdf->ezTable($data, null, null, $labelOptions);

    $data = array(array("<b>                                               Overall Threat Likelihood Table</b>"),
                  array("<b>                                                                       Countermeasure</b>")
);
    $pdf->ezTable($data, null, null, $tableOptions);
    
    $data = array();
    $i = 0;
    $data[0][0] = "<b>THREAT SOURCE</b>";
    foreach ($columns as $countermeasures) {
        $i++;
        $data[0][$i] = "<b>$countermeasures</b>";
    }
    $j = 0;
    $k = 0;
    $i = 0;
    foreach (array_reverse($columns) as $threat) {
        $i++;
        $data[$i][] = $threat;
        foreach ($columns as $countermeasures) {
            $value = $sys->calcThreat($threat, $countermeasures);
            $data[$i][] = $threat_index == $k++?'<b>'.$value.'</b>':$value;
        }
    }
    
    $pdf->ezTable($data, null, null, $tableOptions);
    $overall_threat = $sys->calcMin($p['threat_level'], $p['cmeasure_effectiveness']);
    $data = array(array("Based on the threat likelihood and security categorization of the information system, the finding presents a <b>".$overall_threat."</b> level of risk to agency operations. "));
    $pdf->ezTable($data, null, null, $labelOptions);
    $pdf->ezText('', 12, array('justification'=>'center'));

    $data = array(array("", "<b><i>Overall Risk Level</i></b>"));
    $pdf->ezTable($data, null, null, $labelOptions);

    $data = array(array("<b>                                                Overall Risk Level Analysis</b>"),
                  array("<b>                                                            Security Categorization of Information System</b>")
);
    $pdf->ezTable($data, null, null, $tableOptions);

    $data = array();
    $i = 0;
    $data[0][0] = "<b>THREAT Likelihood</b>";
    foreach ($columns as $security) {
        $i++;
        $data[0][$i] = "<b>$security</b>";
    }
    $j = 0;
    $k = 0;
    $i = 0;
    foreach (array_reverse($columns) as $threat) {
        $i++;
        $data[$i][] = $threat;
        foreach ($columns as $security) {
            $value = $sys->calcMin($threat, $security);
            $data[$i][] = $risk_index == $k++?'<b>'.$value.'</b>':$value;
        }
    }
     
    $pdf->ezTable($data, null, null, $tableOptions);
    $overall_risk = $sys->calcMin($threat_likelihood, $impact);
    $data = array(array("Based on the threat likelihood and security categorization of the information system, the finding presents a <b>".$overall_risk."</b> level of risk to agency operations. "));
    $pdf->ezTable($data, null, null, $labelOptions);
    $pdf->ezText('', 12, array('justification'=>'center'));

    $data = array(array('<b>Risk Level</b>', 'Risk Description and Necessary Actions'),
                  array('<b>'.$columns[2].'</b>', 'If an observation or finding is evaluated as a high risk, there is a strong need for corrective measures. An existing system may continue to operate, but a corrective action plan must be put in place as soon as possible.'),
                  array('<b>'.$columns[1].'</b>', 'If an observation is rated as medium risk, corrective actions are needed and a plan must be developed to incorporate these actions within a reasonable period of time.'),
                  array('<b>'.$columns[0].'</b>', 'If an observation is described as low risk, the system’s AO must determine whether corrective actions are still required or decide to accept the risk.'));

    $pdf->ezTable($data, null, null, $tableOptions);
    $pdf->ezText('', 12, array('justification'=>'center'));

    $pdf->ezText('', 12, array('justification'=>'center'));
    $footer = 'WARNING: This report is for internal, official use only.  This report contains sensitive computer security related information. Public disclosure of this information would risk circumvention of the law. Recipients of this report must not, under any circumstances, show or release its contents for purposes other than official action. This report must be safeguarded to prevent improper disclosure. Staff reviewing this document must hold a minimum of Public Trust Level 5C clearance.';
    $pdf->ezText($footer, 9, array('justification'=>'left'));

// IE has a bug where it can't display certain mimetypes if a no-cache header is sent,
// so we need to switch the header right before we stream the PDF.
    header('Pragma: private');
    header('Cache-Control: private');
    echo $pdf->ezOutput();
