<?php
    $sys = new System();
    $rows = $sys->find($this->poam['system_id']);
    $act_owner = $rows->current()->toArray();

    $organization = new Organization();
    $ret = $organization->find($act_owner['organization_id']);
    $organization = $ret->current()->toArray();

    $columns = $sys->getEnumColumns('availability');
    $columnsCols = array_reverse($columns);
    $i = 0;
    foreach ($columnsCols as $col) {
        foreach ($columns as $row) {
            $cellidx_lookup[$col][$row] = $i++;
        }
    }
?>
<html>
<head>
    
<title>Risk Analysis Form (RAF)</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<style>
p.pageHeader {
  font-size: 20pt;
  font-family: sans-serif; 
  text-align: center;
  margin: auto auto;
}

div.raf {
  text-align: center;
  margin: auto;
  width: 900px;
}

div.rafHeader {
  padding: 2px;
  border: 2px solid black;
  width: 100%;
  text-align: left;
  font-family: sans-serif;
  font-size: 10pt;
  margin-top: 20px;
  margin-bottom: 20px;
}

table.rafContent {
  width: 100%;
}

table.rafContent td {
  vertical-align: top;
  font-family: sans-serif;
  font-size: 10pt;
}

table.rafImpact {
  margin: auto auto;
  border: none;
  border-collapse: collapse;
  width: 100%;
  color: black;
}

table.rafImpact td {
  padding: 2px;
  border: 2px solid black;
}

</style>
</head>
<body>

<p style="text-align:right"><button onclick="javascript:window.print();">Print</button> </p>

<div class="raf">
<table class="rafContent">
    <tr>
        <td colspan="4"><p class="pageHeader">Risk Analysis Form (RAF)</p></td>
    </tr>
    <tr>
        <td colspan="4">
            <table class="rafImpact">
                <tr>
                    <td><b>Finding Information</b></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td width="25%"><b>Finding Number:</b></td><td width="25%"><?php echo $this->poam['id'];?></td>
        <td width="25%"><b>Finding Source:</b></td><td width="25%"><?php echo $this->poam['source_name'];?></td>
    </tr>
    <tr>
        <td><b>Date Opened:</b></td><td ><?php echo $this->poam['create_ts'];?></td>
        <td><b>Date Discovered:</b></td><td ><?php echo $this->poam['discover_ts'];?></td>
    </tr>
    <tr>
        <td ><b>Organization:</b></td><td><?php echo $organization['name'];?></td>
        <td ><b>Information System:</b></td><td><?php echo $this->system_list[$this->poam['system_id']];?></td>
    </tr>
</table>

<table class="rafContent">
    <tr>
        <td width="25%"><b>Asset Affected:</b></td><td width="75%"><?php echo $this->poam['asset_name'];?></td>
    </tr>
    <tr>
        <td ><b>Finding Description:</b></td><td colspan="2"><?php echo $this->poam['finding_data'];?></td>
    </tr>
    <tr>
        <td ><b>Recommendation:</b></td><td colspan="2"><?php echo $this->poam['action_suggested'];?></td>
    </tr>
    <tr>
        <td ><b>Risk Level:</b></td><td colspan="2"><?php echo $this->poam['threat_level'];?></td>
    </tr>

    <tr>
        <td colspan="2">
            <table class="rafImpact">
                <tr>
                    <td><b>Mitigation Strategy</b></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td ><b>Type:</b></td><td ><?php echo $this->poam['type'];?></td>
    </tr>
    <tr>
        <td ><b>Description:</b></td><td><?php echo $this->poam['action_resources'];?></td>
    </tr>
    <tr>
        <td ><b>Estimated Completion Date:</b></td><td><?php echo $this->poam['action_current_date'];?></td>
    </tr>
</table>

<table class="rafContent">
    <tr>
        <td colspan="2">
            <table class="rafImpact">
                <tr>
                    <td><b>Risk Analysis</b></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="2" align="center"><b><i><b>Security Categorization</b></i></b></td>
    </tr>
    <tr>
        <td width="33%"><b>Security Categorization:</b></td><td width="67%"><?php echo $this->securityCategorization;?></td>
    </tr>
    <?php
        if ($this->securityCategorization == $columns[2]) {
            $effect = 'severe or catastrophic';
        } elseif ($this->securityCategorization == $columns[1]) {
            $effect = 'serious';
        } elseif ($this->securityCategorization == $columns[0]) {
            $effect = 'limited';
        } else {
            $effect = '';
        }
    ?>
    <tr>
        <td><b>Security Categorization Description:</b></td>
        <td>
        <?php if (!empty($effect)) { ?>
        The loss of confidentiality, integrity, or availability could be expected to have a <?php echo $effect;?> adverse effect on organizational operations,
        organizational assets, or individuals. This is the maximum level of risk exposure based on the Information System Security Categorization data.
        <?php } else { ?>
        This system's Confidentiality, Integrity, and Availability are not
        defined; therefore, the system security categorization is also undefined.
        <?php }?>
        </td>
    </tr>
    <tr>
        <td colspan="2" align="center"><b><i>LIKELIHOOD DETERMINATION</i></b></td>
    </tr>
    <tr>
        <td colspan="2">The likelihood determination defines the likelihood or frequency of a harmful event occurring. The likelihood determination evaluates the severity of the vulnerability along with the existence and effectiveness of current controls.</td>
    </tr>
    <tr>
        <td><b>Severity Description:</b></td><td><?php echo $this->poam['threat_source'];?></td>
    </tr>
    <tr>
        <td><b>Severity Level:</b></td><td><?php echo $this->poam['threat_level'];?></td>
    </tr></p>
    <tr>
        <td><b>Description of Countermeasures:</b></td><td><?php echo $this->poam['cmeasure'];?></td>
    </tr>
    <tr>
        <td><b>Countermeasures Effectiveness:</b></td><td><?php echo $this->poam['cmeasure_effectiveness'];?></td>
    </tr>
    <?php
        $threat_likelihood = $sys->calcThreat($this->poam['threat_level'],
                                              $this->poam['cmeasure_effectiveness']);

        echo $this->partial('remediation/raf_tl.phtml', array('act_owner'=>$act_owner,
                                                            'poam'=>&$this->poam,
                                                            'table_lookup'=>&$cellidx_lookup,
                                                            'threat_likelihood'=>&$threat_likelihood,
                                                            'columns'=>$columns,
                                                            'sys'=>$sys));
    ?>
    <tr>
       <td colspan="2" align="center"><b><i>Overall Risk Level</i></b></td>
    </tr>
    <?php
        echo $this->partial('remediation/raf_risk.phtml', array('act_owner'=>$act_owner,
                                                              'impact'=>&$this->securityCategorization,
                                                              'table_lookup'=>&$cellidx_lookup,
                                                              'threat_likelihood'=>&$threat_likelihood,
                                                              'columns'=>$columns,
                                                              'sys'=>$sys));
    ?>
    <tr><td colspan="2">Agency Recommendations based on Risk Levels:</td></tr>
    <tr><td colspan="2">
        <table class="rafImpact">
            <tr>
                <td width="20%"><b>Risk Level</b></td>
                <td>Risk Description and Necessary Actions</td>
            </tr>
            <tr>
                <td><?php echo $columns[2];?></td>
                <td>If an observation or finding is evaluated as a high risk, there is a strong need for corrective measures. An existing system may continue to operate, but a corrective action plan must be put in place as soon as possible.</td>
            </tr>
            <tr>
                <td><?php echo $columns[1];?></td>
                <td>If an observation is rated as medium risk, corrective actions are needed and a plan must be developed to incorporate these actions within a reasonable period of time.</td>
            </tr>
            <tr>
                <td><?php echo $columns[0];?></td>
                <td>If an observation is described as low risk, the system's AO must determine whether corrective actions are still required or decide to accept the risk.</td>
            </tr>
        </table>
    </td></tr>
    <tr>
        <td colspan="2"><br>WARNING: This report is for internal, official use only.  This report contains sensitive computer security related information. Public disclosure of this information would risk circumvention of the law. Recipients of this report must not, under any circumstances, show or release its contents for purposes other than official action. This report must be safeguarded to prevent improper disclosure. Staff reviewing this document must hold a minimum of Public Trust Level 5C clearance.
        </td>
  </tr>
</table>
</div>

</body>
</html>
