<?php
    $threat_index = $this->table_lookup[$this->poam['threat_level']]
                                       [$this->poam['cmeasure_effectiveness']]; 
    $cell_colors_tl = array_fill(0, 9, 'FFFFFF');
    $cell_colors_tl[$threat_index] = 'CCCCCC';
?>
<tr>
    <td colspan='2'>
        <table class="rafImpact">
            <tr>
                <td colspan='4' align='center'><b> Overall Threat Likehood Table</b></td>
            </tr>
            <tr>
                <td align='center'></td>
                <td colspan='3' align='center'><b>Countermeasure Effectiveness</b></td>
            </tr>
            <?php
                echo '<tr>';
                echo '<td width="25%"><b>THREAT SOURCE</b></td>';
                foreach ($this->columns as $countermeasures) {
                    echo '<td width="25%"><b>'.$countermeasures.'</b></td>';
                }
                echo '</tr>';
                $i = 0;
                foreach (array_reverse($this->columns) as $threat) {
                    echo '<tr>';
                    echo '<td><b>'.$threat.'</b></td>';
                    foreach ($this->columns as $countermeasures) {
                        echo '<td bgcolor= '.$cell_colors_tl[$i++].'>';
                        echo $this->sys->calcThreat($threat, $countermeasures);
                        echo '</td>';
                    }
                    echo '</tr>';
                }
            ?>
        </table>
    </td>
</tr>
<tr>
    <td colspan="2">
        Based on the threat level and countermeasures currently in place, the finding presents a <b><?php echo $this->threat_likelihood;?></b> level of risk to the information system.
    </td>
</tr>
