<?php
    $risk_index = $this->table_lookup[$this->threat_likelihood][$this->impact];
    $cell_colors_rl = array_fill(0, 9, 'FFFFFF');
    $cell_colors_rl[$risk_index] = 'CCCCCC';
    $overall_risk = $this->sys->calcMin($this->threat_likelihood, $this->impact);
?>
<tr>
    <td colspan="2">
        <table class="rafImpact">
            <tr>
                <td colspan='4' align='center'><b>Overall Risk Level Analysis</b></td>
            </tr>
            <tr>
                <td align='center'>&nbsp;</td>
                <td colspan='3' align='center'><b>Security Categorization of Information System</b></td>
            </tr>
            <?php
                echo '<tr>';
                echo '<td width="25%"><b>Threat Likelihood</b></td>';
                foreach ($this->columns as $countermeasures) {
                    echo '<td width="25%"><b>'.$countermeasures.'</b></td>';
                }
                echo '</tr>';
                $i = 0;
                foreach (array_reverse($this->columns) as $threat) {
                    echo '<tr>';
                    echo '<td><b>'.$threat.'</b></td>';
                    foreach ($this->columns as $countermeasures) {
                        echo '<td bgcolor= '.$cell_colors_rl[$i++].'>';
                        echo $this->sys->calcMin($threat, $countermeasures);
                        echo '</td>';
                    }
                    echo '</tr>';
                }
            ?>
        </table>
    </td>
</tr>
<tr>
    <td colspan="2">
        Based on the threat likelihood and security categorization of the information system, the finding presents a <b><?php echo $overall_risk;?></b> level of risk to agency operations.
    </td>
</tr>

