<?php
    $filter_type = array(0  =>'--- Any Type ---',
                    'NONE' =>'(NONE) Unclassified',
                    'CAP'  =>'(CAP) Corrective Action Plan',
                    'AR'   =>'(AR) Accepted Risk',
                    'FP'   =>'(FP) False Positive');
    $onTimes    = array(0 =>'--- Any ---',
                        'ontime'=>'On Time',
                        'overdue'=>'Overdue');

    $eval = new Evaluation();
    $mpEvalList = $eval->getEvalList('ACTION');
    $epEvalList = $eval->getEvalList('EVIDENCE');

    foreach ($mpEvalList as $row) {
        $mpStatus[$row['nickname']] = '('.$row['nickname'].')'.$row['name'];
    }
    foreach ($epEvalList as $row) {
        $epStatus[$row['nickname']] = '('.$row['nickname'].')'.$row['name'];
    }

    $filter_status = array(  0   =>'--- Any Status ---',
                           'NEW' =>'(NEW) Awaiting Mitigation Type and Approval',
                           'DRAFT'=>'(DRAFT) Awaiting Mitigation Approval');
    $filter_status = array_merge($filter_status, $mpStatus);
    $filter_status['EN'] = '(EN) Evidence Needed';
    $filter_status = array_merge($filter_status, $epStatus);
    $filter_status['CLOSED'] = '(CLOSED) Officially Closed';
    $filter_status['NOT-CLOSED'] = '(NOT-CLOSED) Not Closed';
    $filter_status['NOUP-30']   = '(NOUP-30) 30+ Days Since Last Update';
    $filter_status['NOUP-60']   = '(NOUP-60) 60+ Days Since Last Update';
    $filter_status['NOUP-90']   = '(NOUP-90) 90+ Days Since Last Update';

    $this->systems[0] ='--Any--';
    $this->sources[0] ='--Any--';
?>
<div class="barleft">
<div class="barright">
<p><b>Remediation Search</b><span></p>
</div>
</div>
<form name="filters" method="post" action="/panel/remediation/sub/searchbox/s/search">

<!-- Begin Filter Table -->
<table align="center" border="0" cellpadding="3" cellspacing="1" width="95%" class="tipframe">
    <tr>
        <td><b>Finding Source: </b><br>
            <?php echo $this->formSelect('source_id',
                                         $this->params['source_id'],
                                         null,
                                         $this->sources);?>
        </td>
        <td>
        <b>ID: </b><i>(You may select multiple IDs by using a comma separated list - x,y,z)</i><br>
        <input type="text" size="70" name="ids" value="<?php echo $this->params['ids'];?>">
        </td>
    </tr>
    <tr>
        <td ><b> Mitigation Strategy:</b><br>
        <?php echo $this->formSelect('type',
                                     $this->params['type'],
                                     null,
                                     $filter_type);?>
        </td>
        <td width="318" valign="top"><b> Finding Status:</b><br>
        <?php echo $this->formSelect('status', 
                                     $this->params['status'], 
                                     array('id'=>'poamSearchStatus'),
                                     $filter_status);?>
        </td>
    </tr>
    <tr>
        <td ><b>Asset Owners: </b> <br/>
            <?php echo $this->formSelect('asset_owner',
                                         $this->params['asset_owner'],
                                         null,
                                         $this->systems);?>
        </td>
        <td ><b>Action Owners: </b><br>
            <?php echo $this->formSelect('system_id',
                                         $this->params['system_id'],
                                         null,
                                         $this->systems);?>
        </td>
    </tr>
    <tr>
        <td ><b>OnTime:</b><br>
            <?php echo $this->formSelect('ontime',
                                         $this->params['ontime'],
                                         array('disabled'=>'disabled', 'id'=>'poamSearchOnTime'),
                                         $onTimes);?>
        </td>
        <td></td>
    </tr>

    <tr>
        <td colspan='2'>
            <table border="0" cellpadding="3" cellspacing="1" width="98%">
                <tr>
                    <td ><b>Estimated Completion Date:</b></td>
                    <td > From: <input type="text" class="date" name="est_date_begin" value="<?php
                        echo isset($this->params['est_date_begin'])?$this->params['est_date_begin']:'';
                        ?>" size="12" maxlength="10"></td>
                    <td > To: <input type="text" class="date" name="est_date_end" value="<?php
                        echo isset($this->params['est_date_end'])?$this->params['est_date_end']:'';
                        ?>" size="12" maxlength="10"></td>
                    <td ><b>Date Created: </b></td>
                    <td > From: <input type="text" class="date" name="created_date_begin" value="<?php
                       echo isset($this->params['created_date_begin'])?$this->params['created_date_begin']:'';
                        ?>" size="12" maxlength="10"></td>
                    <td > To: <input type="text" class="date" name="created_date_end" value="<?php
                        echo isset($this->params['created_date_end'])?$this->params['created_date_end']:'';
                        ?>" size="12" maxlength="10"></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td align="left"><input type='submit' value='Search'></td>
    </tr>
</table>
