<?php
$cols = array (
    'id' => 'ID#',
    'source_name' => 'Source',
    'system_name' => 'System',
    'asset_name'  => 'Asset',
    'type' => 'Type',
    'status' => 'Status',
    'duetime' => 'On Time?',
    'finding_data' => 'Description',
    'action_suggested' => 'Recommendation',
    'action_planned' =>'Corrective Action',
    'blscr_id' => 'Blscr',
    'threat_level' => 'Threat Level',
    'threat_source' => 'Threat Description',
    'cmeasure_effectiveness' => 'Cmeasures Effectiveness',
    'cmeasure' => 'Cmeasures Description',
    'attachments' => 'Attachments',
    'action_current_date' => 'ECD'
    );

define('REPORT_FOOTER_WARNING', "WARNING: This report is for internal, official use only.  This report contains sensitive computer security related information. Public disclosure of this information would risk circumvention of the law. Recipients of this report must not, under any circumstances, show or release its contents for purposes other than official action. This report must be safeguarded to prevent improper disclosure. Staff reviewing this document must hold a minimum of Public Trust Level 5C clearance.");

define('ORIENTATION', 'orient');
define('PAPERTYPE', 'pagesz');
define('PGWIDTH', 'pgwidth');
define('PGHEIGHT', 'pgheight');
define('FONTS', Fisma_Controller_Front::getPath('library') . '/pdf/fonts');

$poam_config = array( ORIENTATION => 'landscape', PAPERTYPE => 'LEGAL', PGWIDTH => 1000);

require_once( 'pdf/class.ezpdf.php');

$pdf =& new Cezpdf($poam_config[PAPERTYPE], $poam_config[ORIENTATION]);
$pdf->selectFont(FONTS . "/Helvetica.afm");//needs modify to the real font file path
$horiz_margin = 50;
$bottom_margin = 100;
$top_margin = 50;
$page_width = $poam_config[PGWIDTH];
$warning_size = 8;

$left_top = array('x'=>$horiz_margin,'y'=>'585');
$right_bottom = array('x'=>$page_width-$horiz_margin,'y'=>$bottom_margin);
$content_width = $right_bottom['x'] - $left_top['x'];

$all = $pdf->openObject();
$pdf->saveState();

$head_height = 5;

$pdf->addTextWrap($left_top['x'],$left_top['y'],$content_width,8,'Report run time:'.
                                Zend_Date::now()->toString('Y-m-d H:i:s'),
                                'right');
$tmp_y = $left_top['y'] - $head_height;
$pdf->line($left_top['x'],$tmp_y,$right_bottom['x'],$tmp_y);
$pdf->setStrokeColor(0,0,0,1);

$y = $right_bottom['y'];
$pdf->line($left_top['x'],$y,$right_bottom['x'],$y);

// Add footer
$text = REPORT_FOOTER_WARNING;
$x = $left_top['x'];
$line_height = 8;
$y -= $line_height;
while(!empty($text)){
    $y -= $line_height;
    $text = $pdf->addTextWrap($x,$y,$content_width,$line_height,$text,'left');  
}

$pdf->restoreState();
$pdf->closeObject();

$pdf->addObject($all,'all');
$pdf->ezSetMargins($top_margin,$bottom_margin,$horiz_margin,$horiz_margin);

//Add title
$title = '[System] : ';
if( isset($this->criteria['system_id']) ) {
    $title .= $this->system_list[$this->criteria['system_id']];
}else{
    $title .= 'All systems';
}

if( isset($this->criteria['source_id']) ) {
    $title .= " [Source] : {$this->source_list[$this->criteria['source_id']]}";
}

$pdf->ezText('Plans of Actions And Milestones Report Administration',16,array('justification'=>'center'));
$i = 0;
$columnPreference = $_COOKIE['search_columns_pref'];
foreach ($cols as $key=>$row) {
    if (!($columnPreference & (1 << $i))) {
        unset($cols[$key]);
    }
    $i++;
}
$pdf->ezTable($this->list,$cols,$title,
    array('fontSize'=>8,'maxWidth'=>$content_width, 'titleFontSize'=>'12' ));

echo $pdf->ezOutput();
?>
