<?php
$output_cols = array(
'ID#',
'Source',
'System',
'Asset',
'Type',
'Status',
'On Time?',
'Description',
'Recommendation',
'Corrective Action',
'Blscr',
'Threat Level',
'Threat Description',
'Cmeasures Effectiveness',
'Cmeasures Description',
'Attachments',
'ECD');

$count_cols = count($output_cols);
// Taking Spreadsheet_Excel_Writer to generate the excel file
// Refer to http://pear.php.net/package/Spreadsheet_Excel_Writer
require_once ('Spreadsheet/Excel/Writer.php');
$workbook  = new Spreadsheet_Excel_Writer();
$workbook->setVersion(8); // fixes 255 char truncation issue

$worksheet =& $workbook->addWorksheet();

$format_header =& $workbook->addFormat(array('Size' => 10,
    'Align' => 'center',
    'Color' => 'white',
    'FgColor' => 'black',
    ));
$format_header->setFontFamily('Times New Roman');

$format_times =& $workbook->addFormat(array('Size' => 10,
    'Align' => 'center',
    'Color' => 'black',
    'BorderColor '=> 'blue',
    'Bottom'=>1,'Top'=>1,'Left'=>1,'Right'=>1));
$format_times->setFontFamily('Times New Roman');
$format_times->setAlign('left');
$format_times->setAlign('top');
$format_times->setTextWrap();
$rowi=0;
$worksheet->setColumn(0,0,20);
$worksheet->mergeCells($rowi, 0, $rowi, $count_cols-1);
$headinfo="Report run time: ".date("Y-m-d H:i:s");
$worksheet->write($rowi++, 0, $headinfo,$format_times);

$worksheet->mergeCells($rowi,0,$rowi,$count_cols-1);
$worksheet->write($rowi++, 0, 'Results',$format_header);
// Set the width of a single column or a range of columns.
$worksheet->setColumn(0,0,10);
$worksheet->setColumn(2,2,50);
$worksheet->setColumn(3,8,10);
$worksheet->setColumn(9,10,50);
$worksheet->setColumn(11,14,15);
//inject the titles


$worksheet->writeRow($rowi++,0,$output_cols,$format_times);

foreach( $this->list as $p ) {
    $p['on_time'] = $this->isOnTime($p['duetime']);
    $data = array(
        $p['id'],
        $p['source_id'] != 0 ? $this->source_list[$p['source_id']] : 'n/a',
        $this->system_list[$p['system_id']],
        $p['asset_name'],
        $p['type'],
        $p['status'],
        $p['on_time'],
        $p['finding_data'],
        $p['action_suggested'],
        $p['action_planned'],
        $p['blscr_id'],
        $p['threat_level'],
        $p['threat_source'],
        $p['cmeasure_effectiveness'],
        $p['cmeasure'],
        $p['attachments'],
        $p['action_current_date']);
    $worksheet->writeRow($rowi++,0,$data,$format_times); 
}
$workbook->close();
?>
