<script language="javascript">
    $(document).ready(function(){
        <?php
            foreach (explode(',', $this->keywords) as $keyword) {
        ?>
        highlight(document.getElementById('poam_list'), '<?php echo $keyword;?>');            
        <?php } ?>
    });
</script>
<?php
    $baseUrl =  "/panel/remediation/sub/view";
    if (!empty($this->keywords)) {
        $baseUrl .= '/keywords/' . $this->keywords;
    }
?>
<?php Format_Section::startSection("Search Results"); ?>
    <div class="toolbar">
        <script type="text/javascript">
            function addSearchBookmark() {
                addBookmark('Search',
                            '<?php echo Config_Fisma::readSysConfig("hostUrl").$this->url; ?>');
            }
            
            var columnOptionsShowing = false;
            var columnOptionsPanel;
            function showColumnOptions() {
                if (!columnOptionsPanel) {
                    columnOptionsPanel = newPanel('columnOptionsPanel', '/yada/yada');
                }

                columnOptionsPanel.show();
            }
        </script>
        <?php 
            $addBookmarkButton = new Yui_Form_Button_Link('Bookmark This Search', 'addBookmark', '#', '/images/favorite.gif');
            $addBookmarkButton->onClick('addSearchBookmark');
            echo $addBookmarkButton;
            echo new Yui_Form_Button_Link('Export PDF', 'exportPdf', "{$this->attachUrl}/format/pdf", '/images/pdf.gif');
            echo new Yui_Form_Button_Link('Export Excel', 'exportExcel', "{$this->attachUrl}/format/xls", '/images/xls.gif');
            $columnOptionsButton = new Yui_Form_Button_Link('Options', 'columnOptions', '#', '/images/options.png');
            $columnOptionsButton->onClick('showColumnOptions');
            echo $columnOptionsButton;
        ?>
        <span>
            <?php echo $this->links['all'];?>
        </span>
    </div>

    <table width="100%" class="tbframe" id="poam_rst">
        <tr>
            <th>ID 
                <a href="<?php echo $this->url;?>/sortby/p.id/order/ASC"><img src="/images/up_arrow.gif" border="0"></a>
                <a href="<?php echo $this->url;?>/sortby/p.id/order/DESC"><img src="/images/down_arrow.gif" border="0"></a>
            </th>
            <th>Source 
                <a href="<?php echo $this->url;?>/sortby/s.name/order/ASC"><img src="/images/up_arrow.gif" border="0"></a>
                <a href="<?php echo $this->url;?>/sortby/s.name/order/DESC"><img src="/images/down_arrow.gif" border="0"></a>
            </th>
            <th>System 
                <a href="<?php echo $this->url;?>/sortby/sys.name/order/ASC"><img src="/images/up_arrow.gif" border="0"></a>
                <a href="<?php echo $this->url;?>/sortby/sys.name/order/DESC"><img src="/images/down_arrow.gif" border="0"></a>
            </th>
            <th>Asset 
                <a href="<?php echo $this->url;?>/sortby/as.name/order/ASC"><img src="/images/up_arrow.gif" border="0"></a>
                <a href="<?php echo $this->url;?>/sortby/as.name/order/DESC"><img src="/images/down_arrow.gif" border="0"></a>
            </th>
            <th>Type 
                <a href="<?php echo $this->url;?>/sortby/p.type/order/ASC"><img src="/images/up_arrow.gif" border="0"></a>
                <a href="<?php echo $this->url;?>/sortby/p.type/order/DESC"><img src="/images/down_arrow.gif" border="0"></a>
            </th>
            <th>Status 
                <a href="<?php echo $this->url;?>/sortby/p.status/order/ASC"><img src="/images/up_arrow.gif" border="0"></a>
                <a href="<?php echo $this->url;?>/sortby/p.status/order/DESC"><img src="/images/down_arrow.gif" border="0"></a>
            </th>
            <th>On Time? </th>
            <th>Description </th>
            <th>Recommendation </th>
            <th>Corrective Action </th>
            <th>Blscr 
                <a href="<?php echo $this->url;?>/sortby/p.blscr_id/order/ASC"><img src="/images/up_arrow.gif" border="0"></a>
                <a href="<?php echo $this->url;?>/sortby/p.blscr_id/order/DESC"><img src="/images/down_arrow.gif" border="0"></a>
            </th>
            <th>Threat Level 
                <a href="<?php echo $this->url;?>/sortby/p.threat_level/order/ASC"><img src="/images/up_arrow.gif" border="0"></a>
                <a href="<?php echo $this->url;?>/sortby/p.threat_level/order/DESC"><img src="/images/down_arrow.gif" border="0"></a>
            </th>
            <th>Threat Description </th>
            <th>Cmeasures Effectiveness 
                <a href="<?php echo $this->url;?>/sortby/p.cmeasure_effectiveness/order/ASC"><img src="/images/up_arrow.gif" border="0"></a>
                <a href="<?php echo $this->url;?>/sortby/p.cmeasure_effectiveness/order/DESC"><img src="/images/down_arrow.gif" border="0"></a>
            </th>
            <th>Cmeasures Description </th>
            <th>Attachments </th>
            <th>ECD 
               <a href="<?php echo $this->url;?>/sortby/p.action_est_date/order/ASC"><img src="/images/up_arrow.gif" border="0"></a>
               <a href="<?php echo $this->url;?>/sortby/p.action_est_date/order/DESC"><img src="/images/down_arrow.gif" border="0"></a>
            </th>
            <th>View</th>
        </tr>
        <!-- REMEDIATION ROWS -->
        <tbody id = "poam_list">
        <?php
            foreach($this->list as $row){
        ?>
        <tr>
            <td align='center' class='tdc'><?php echo $row['id'];?></td>
            <td align='center' class='tdc'>
            <?php 
                    if (!isset($row['source_name'])) {
                        echo 'Missing Source id';
                    } else {
                        echo $row['source_name'];
                    }
            ?>
            </td>
            <td align='center' class='tdc'><?php echo '(' . $row['system_nickname'] . ')' . $row['system_name'];?></td>
            <td align='center' class='tdc'><?php echo $row['asset_name'];?></td>
            <td align='center' class='tdc'><?php echo $row['type'];?></td>
            <td align='center' class='tdc'><?php echo $row['status'];?></td>
            <td align='center' class='tdc'>
                <?php echo $this->isOnTime($row['duetime']);?>
            </td>
            <td align='left' class='tdc'><?php echo $this->ShowLongText($row['finding_data'], $this->keywords);?></td>
            <td align='left' class='tdc'><?php echo $this->ShowLongText($row['action_suggested'], $this->keywords);?></td>
            <td align='left' class='tdc'><?php echo $this->ShowLongText($row['action_planned'], $this->keywords);?></td>
            <td align='left' class='tdc'><?php echo $row['blscr_id'];?></td>
            <td align='left' class='tdc'><?php echo $row['threat_level'];?></td>
            <td align='left' class='tdc'><?php echo $this->showLongText($row['threat_source'], $this->keywords);?></td>
            <td align='left' class='tdc'><?php echo $row['cmeasure_effectiveness'];?></td>
            <td align='left' class='tdc'><?php echo $this->ShowLongText($row['cmeasure'], $this->keywords);?></td>
            <td align='center' class='tdc'><?php echo $row['attachments'];?></td>
            <td align='center' class='tdc'><?php echo $row['action_current_date'];?></td> 
            <td align="center" valign='middle' class='tdc'>
        </tr>
        <?php } ?>
        </tbody>
    </table>

<?php Format_Section::stopSection(); ?>
