<?php
/** @codingStandardsIgnoreFile */
$count_cols = count($this->columns);
// Taking Spreadsheet_Excel_Writer to generate the excel file
// Refer to http://pear.php.net/package/Spreadsheet_Excel_Writer
require_once ('Spreadsheet/Excel/Writer.php');
$workbook  = new Spreadsheet_Excel_Writer();
$workbook->setVersion(8); // fixes 255 char truncation issue

$worksheet =& $workbook->addWorksheet();

$format_header =& $workbook->addFormat(array('Size' => 10,
    'Align' => 'center',
    'Color' => 'white',
    'FgColor' => 'black',
    ));
$format_header->setFontFamily('Times New Roman');

$format_times =& $workbook->addFormat(array('Size' => 10,
    'Align' => 'center',
    'Color' => 'black',
    'BorderColor '=> 'blue',
    'Bottom'=>1,'Top'=>1,'Left'=>1,'Right'=>1));
$format_times->setFontFamily('Times New Roman');
$format_times->setAlign('left');
$format_times->setAlign('top');
$format_times->setTextWrap();
$rowi=0;
$worksheet->setColumn(0,0,20);
$worksheet->mergeCells($rowi, 0, $rowi, $count_cols-1);
$headinfo="Report run time: ".date("Y-m-d H:i:s");
$worksheet->write($rowi++, 0, $headinfo,$format_times);

$worksheet->mergeCells($rowi,0,$rowi,$count_cols-1);
$worksheet->write($rowi++, 0, 'Results',$format_header);

$worksheet->writeRow($rowi++,0,$this->columns,$format_times);

$i = 0;
foreach( $this->tableData as $row) {
    $worksheet->writeRow($i++, 0, $row, $format_times); 
}

// IE has a bug where it can't display certain mimetypes if a no-cache header is sent,
// so we need to switch the header right before we stream the PDF.
header('Pragma: private');
header('Cache-Control: private');

$workbook->close();
?>
