<script type="text/javascript">
YAHOO.util.Event.onDOMReady(function () {
    YAHOO.util.Connect.asyncRequest('GET', 
                                    '/remediation/summary-data/format/json', 
                                    {
                                        success: function(o) {
                                            var json = YAHOO.lang.JSON.parse(o.responseText);
                                            YAHOO.fisma.TreeTable.render('findingSummaryTable', json.summaryData);
                                        },
                                        failure: function(o) {
                                            alert('Unable to load finding summary: ' + o.statusText);
                                        }
                                    }, 
                                    null);
});
</script>

<div class="toolbar">
<?php
$expandAll = new Fisma_Yui_Form_Button('expandAll', 
                                       array('value' => 'Expand All', 
                                             'onClickFunction' => 'YAHOO.fisma.TreeTable.expandAll'));
print $expandAll;

$collapseAll = new Fisma_Yui_Form_Button('collapseAll', 
                                         array('value' => 'Collapse All', 
                                               'onClickFunction' => 'YAHOO.fisma.TreeTable.collapseAll'));
print $collapseAll;
?>
</div>

<table id='findingSummaryTable' class="treeTable">
    <tr>
        <th>&nbsp;</th>
        <?php // foreach ?>
        <th>NEW</th>
        <th>DRAFT</th>
        <?php 
            foreach ($this->mitigationEvaluations as $evaluation) {
                print "<th>$evaluation->nickname</th>";
            }
        ?>
        <th>EN</th>
        <?php 
            foreach ($this->evidenceEvaluations as $evaluation) {
                print "<th>$evaluation->nickname</th>";
            }
        ?>        
        <th>CLOSED</th>
        <th>TOTAL</th>
    </tr>
</table>
