<script type="text/javascript">
function backToSearch(event) {
    var location = YAHOO.util.Cookie.get('lastSearchUrl');
    if (location) {
        window.location = location;
    } else {
        window.location = '/panel/remediation/sub/searchbox';
    }
}
</script>
<form enctype="multipart/form-data" action="/panel/remediation/sub/modify/id/<?php echo $this->finding->id;?>" 
      method="post" 
      id="finding_detail"
      name="finding_detail">
    <div class="toolbar">
        <?php
            $backToSearchButton = new Fisma_Yui_Form_Button('backToSearch',
                                                      array('label' => 'Back To Search Results', 
                                                            'onClickFunction' => 'backToSearch'));
            echo $backToSearchButton;
            
            $discardButton = new Fisma_Yui_Form_Button_Link('discardChanges',
                                                 array('value' => 'Discard Changes',
                                                       'href' => '/panel/remediation/sub/view/id/'.$this->finding->id));
            echo $discardButton;
            
            echo new Fisma_Yui_Form_Button_Submit('saveChanges', 
                                            array('label' => 'Save Changes'));
        ?>
    </div>
    <div id="tabContainer">
        <!-- YUI will load the tabview into this div -->
    </div>
    <script type="text/javascript">
        /* Configuration for the tabview */
        YAHOO.util.Event.onDOMReady(function () {
            var tabView = new YAHOO.widget.TabView();
        
            // When a tab is loaded for the first time, this function is called to set up highlighting, editable fields,
            // and executing scripts that are loaded inside the tab (YUI does not execute these script nodes on its own)
            var prepareTab = function(args) {
                highlight(document.getElementById("tabContainer"), 
                          "<?php echo $this->keywords; ?>");
                
                setupEditFields();
                
                // Notice that we are eval'ing any script nodes loaded into this tab. This is only safe as long as
                // we know exactly which URLs we are loading into the tabview. Otherwise we might inadertently execute
                // a 3rd party script.
                var tabContainer = document.getElementById('tabContainer');
                var scriptNodes = tabContainer.getElementsByTagName('script');
                for (var i=0; i < scriptNodes.length; i++) {
                    if (scriptNodes[i].getAttribute('executeFlag') != 'true') {
                        try {
                            eval(scriptNodes[i].text);
                        } catch (e) {
                            alert('Not able to execute one of the scripts embedded in this page: '
                                  + e.message);
                        } 
                        // Set a flag that prevents this script from being executed more than once
                        scriptNodes[i].setAttribute('executeFlag', 'true');
                    }
                }
            }
            
            // When the active tab changes, store the active tab in a cookie so that it can be restored
            // in between page refreshes.
            var handleTabChange = function(args) {
                YAHOO.util.Cookie.set("activeTab", args.newValue, { path: '/' });
            }
            
            // Finding tab
            var findingTab = new YAHOO.widget.Tab({
                label: 'Finding #<?php echo $this->finding->id; ?>',
                dataSrc: '/remediation/finding/id/<?php echo $this->finding->id; ?>',
                cacheData: true
            });
            findingTab.subscribe("dataLoadedChange", prepareTab);
            tabView.addTab(findingTab);
        
            var mitigationTab = new YAHOO.widget.Tab({
                label: 'Mitigation Strategy',
                dataSrc: '/remediation/mitigation-strategy/id/<?php echo $this->finding->id; ?>',
                cacheData: true
            });
            mitigationTab.subscribe("dataLoadedChange", prepareTab);        
            tabView.addTab(mitigationTab);
        
            var riskTab = new YAHOO.widget.Tab({
                label: 'Risk Analysis',
                dataSrc: '/remediation/risk-analysis/id/<?php echo $this->finding->id; ?>',
                cacheData: true
            });
            riskTab.subscribe("dataLoadedChange", prepareTab);                
            tabView.addTab(riskTab);

            var securityControlTab = new YAHOO.widget.Tab({
                label: 'Security Control',
                dataSrc: '/remediation/security-control/id/<?php echo $this->finding->id; ?>',
                cacheData: true
            });
            securityControlTab.subscribe("dataLoadedChange", prepareTab);                
            tabView.addTab(securityControlTab);

            var artifactsTab = new YAHOO.widget.Tab({
                label: 'Artifacts (<?php echo $this->finding->Evidence->count(); ?>)',
                dataSrc: '/remediation/artifacts/id/<?php echo $this->finding->id; ?>',
                cacheData: true
            });
            artifactsTab.subscribe("dataLoadedChange", prepareTab);                
            tabView.addTab(artifactsTab);
            
            var auditTab = new YAHOO.widget.Tab({
                label: 'Audit Log',
                dataSrc: '/remediation/audit-log/id/<?php echo $this->finding->id; ?>',
                cacheData: true
            });
            auditTab.subscribe("dataLoadedChange", prepareTab);        
            tabView.addTab(auditTab);
            
            tabView.subscribe('activeIndexChange', handleTabChange);
            tabView.appendTo('tabContainer');
        
            // Tab is selected based on the hash appended to the URL, or if no hash is present,
            // then by the cookie.
            var tab = location.hash.substring(1);
            if (!tab || tab < 0 || tab > 4) {
                if (YAHOO.util.Cookie.get("currentFindingId") == <?php echo $this->finding->id; ?>) {
                    tab = YAHOO.util.Cookie.get("activeTab");
                } else {
                    YAHOO.util.Cookie.set("currentFindingId", <?php echo $this->finding->id; ?>, {path: '/'});
                    YAHOO.util.Cookie.set("activeTab", 0, {path: '/'}); 
                    tab = 0;
                }
            }
            tabView.selectTab(tab);
        });
    </script>
</form>
