<script type="text/javascript">
function backToSearch(event) {
    var location = YAHOO.util.Cookie.get('lastSearchUrl');
    if (location) {
        window.location = location;
    } else {
        window.location = '/panel/remediation/sub/searchbox';
    }
}
</script>
<form enctype="multipart/form-data"
      action="/panel/remediation/sub/modify/id/<?php echo $this->escape($this->finding->id)?>" 
      method="post" 
      id="finding_detail"
      name="finding_detail">
    <div class="toolbar">
        <?php
            $backToSearchButton = new Fisma_Yui_Form_Button('backToSearch',
                                                      array('label' => 'Back To Search Results', 
                                                            'onClickFunction' => 'backToSearch'));
            echo $this->escape($backToSearchButton, 'none');
            
            // The "save" and "discard" buttons are only displayed if the user can update any of the findings fields
            if ($this->acl->hasPrivilegeForObject('update_*', $this->finding)) {
                $discardChangesButtonConfig = array(
                    'value' => 'Discard Changes',
                    'href' => '/panel/remediation/sub/view/id/' . $this->finding->id
                );
                
                $discardChangesButton = new Fisma_Yui_Form_Button_Link('discardChanges', $discardChangesButtonConfig);
                echo $this->escape($discardChangesButton, 'none');
            
                $saveChangesButton = new Fisma_Yui_Form_Button_Submit('saveChanges', array('label' => 'Save Changes'));
                echo $this->escape($saveChangesButton, 'none');
            }
        ?>
    </div>
    
    <?php echo $this->escape($this->tabView, 'none'); ?>
</form>
