<?php
    $urlNamespace = new Zend_Session_Namespace('urlNamespace');
?>
<script language="javascript">
    $(document).ready(function(){
        <?php
            foreach (explode(',', $this->keywords) as $keyword) {
        ?>
        highlight(document.getElementById('poam_detail'), '<?php echo $keyword;?>');
        <?php } ?>
    });
</script>
<br>
<form method="link" class="button_link" action="<?php echo $urlNamespace->lastSearch;?>">
    <input type="submit" value="Back">
</form>

<form action="/panel/remediation/sub/modify/id/<?php echo $this->poam['id'];?>" method="post" class="button_link"
 id="poam_detail">
<input type='submit' title='Save or Submit' value="Save" style="cursor: pointer;">
<?php 
     echo $this->partial('remediation/finding.phtml', array('poam'=>&$this->poam, 'system_list'=>&$this->system_list, 'network_list'=>&$this->network_list, 'acl'=> $this->acl));
     echo $this->partial('remediation/mitigation.phtml', array('poam'=>&$this->poam,'justification'=>$this->justification, 'acl'=> $this->acl));
     echo $this->partial('remediation/nist.phtml', array('poam'=>&$this->poam, 'acl'=> $this->acl));
?>
<input type='submit' title='Save or Submit' value="Save" style="cursor: pointer;">
</form>
<?php echo $this->partial('remediation/msa.phtml', array('poam'=>&$this->poam, 'ms_evals'=>$this->ms_evals, 'ms_evaluation'=>$this->ms_evaluation, 'acl'=> $this->acl));?>

     <?php if($this->poam['status'] != 'NEW' || $this->poam['status'] != 'DRAFT' ) { ?>

<?php Format_Section::startSection("Supporting Evidence (" 
                                   . count($this->ev_evals)
                                   . " total)"); ?>

     <?php 
          echo $this->partialLoop('remediation/evidence.phtml', $this->ev_evals );
          if('EN' == $this->poam['status'] && $this->acl->isAllowed('remediation','update_evidence') ){
              echo 
              '<button id="up_evidence" onclick ="upload_evidence();">Upload Evidence</button>';
          }
     }
     ?>
<?php Format_Section::stopSection(); ?>

<?php Format_Section::startSection("Audit Log"); ?>

     <table align="center" cellpadding="5" cellspacing="1" width="95%" class="tbframe">
         <tr>
             <th>Timestamp</td>
             <th>User</td>
             <th>Event</td>
             <th>Description</td>
         </tr>
<?php 
     echo $this->partialLoop('remediation/log.phtml', $this->logs);
?>
    </table>
<?php Format_Section::stopSection(); ?>

<?php 
     echo $this->partial('remediation/uploadev.phtml',array('id'=>$this->poam['id'], 'acl'=> $this->acl));
?>
