<style>
#product_info tr td
{
	text-align:left;
	padding:3px;
	color:#000000;
	font-weight:normal;
}
</style>
<table border="0" width="100%" cellpadding="3" cellspacing="1">
<tr>
    <td>
    <table border="0"cellpadding="3" cellspacing="1" id="product_info">
    <tr>
        <td><b>System:</b></td>
        <td colspan="5" class="value"> <?php echo $this->asset['sname']; ?> </td>
    </tr>
    <tr>
        <td><b>IP Address:</b></td>
        <td colspan="5" class="value">
        <?PHP echo $this->asset['ip'];?>
        </td>
    </tr>
    <tr>
        <td><b>Product:</b></td>
        <td><?php echo $this->asset['pname']; ?></td>
        <td><b>Vendor:</b></td>
        <td><?php echo $this->asset['pvendor']; ?></td>
        <td><b>Version:</b></td>
        <td><?php echo $this->asset['pversion']; ?></td>
    </tr>
    </table>
    </td>
</tr>
</table>
