<style>
#product_info tr td
{
    text-align:left;
    padding:3px;
    color:#000000;
    font-weight:normal;
}
</style>
<table border="0" width="100%" cellpadding="3" cellspacing="1">
<tr>
    <td>
    <table border="0"cellpadding="3" cellspacing="1" id="product_info">
    <tr>
        <td><b>System:</b></td>
        <td colspan="5" class="value"> <?=$this->escape($this->asset['systemName']); ?> </td>
    </tr>
    <tr>
        <td><b>IP Address:</b></td>
        <td colspan="5" class="value">
        <?=$this->escape($this->asset['addressIp']);?>
        </td>
    </tr>
    <tr>
        <td><b>Product:</b></td>
        <td><?=$this->escape($this->asset['productName']) ?></td>
        <td><b>Vendor:</b></td>
        <td><?=$this->escape($this->asset['vendor']) ?></td>
        <td><b>Version:</b></td>
        <td><?=$this->escape($this->asset['version']) ?></td>
    </tr>
    </table>
    </td>
</tr>
</table>
