<?php 
Fisma_Format_Section::startSection("Asset Inventory <span id='searchResultsTotalFound'></span>"); ?>
<script type="text/javascript" src="/javascripts/selectallselectnone.js"></script>
<script type="text/javascript">
    function deleteSelectedAssets() {
        document.forms.assetresult.submit();
    }
</script>
<form id="assetresult" method="post" action="/panel/asset/sub/multidelete">
<div class="toolbar">
    <?php
        echo new Fisma_Yui_Form_Button_Link('pdf', 
                                      array('value' => 'Export PDF', 
                                            'href' => "/asset/search$this->url/format/pdf",
                                            'imageSrc' => '/images/pdf.gif'));
        echo new Fisma_Yui_Form_Button_Link('xls',
                                      array('value' => 'Export Excel', 
                                            'href' => "/asset/search$this->url/format/xls", 
                                            'imageSrc' => '/images/xls.gif'));
        if(Fisma_Acl::hasPrivilege('asset', 'delete', '*')) {
            $selectAllButton = new Fisma_Yui_Form_Button('selectAll', 
                                                   array('label' => 'Select All', 
                                                         'onClickFunction' => 'selectAllUnsafe'));
            echo $selectAllButton;

            $selectNoneButton = new Fisma_Yui_Form_Button('selectNone',
                                                    array('label' => 'Select None', 
                                                          'onClickFunction' => 'selectNoneUnsafe'));
            echo $selectNoneButton;

            $deleteButton = new Fisma_Yui_Form_Button('deleteSelected',
                                                array('label' => 'Delete Selected', 
                                                      'onClickFunction' => 'deleteSelectedAssets'));
            echo $deleteButton;
        }
        if(Fisma_Acl::hasPrivilege('asset','create', '*')) {
            echo new Fisma_Yui_Form_Button_Link('createAsset', 
                                          array('value' => 'Create Asset', 
                                                'href' => '/panel/asset/sub/create'));
        }
    ?>
</div>
<div id="list"></div>
<script type="text/javascript">
    var checkboxList = function(elCell, oRecord, oColumn, sData) {
        elCell.innerHTML = "<input type='checkbox' name='aid[]' value='" + oRecord.getData("id") + "' />";
    };
    var operation = function(elCell, oRecord, oColumn, sData) {
        elCell.innerHTML = "<a href='/panel/asset/sub/view/id/"+oRecord.getData("id")+"'><img src='/images/view.gif' /></a>";
    };
    // Column definitions
    var myColumnDefs = [{key: 'id', label:'', formatter: checkboxList}
    <?php
    foreach ($this->columns as $k => $v) {
        echo ',{key:"' . $k . '", label:"' . $v . '"}';
    }
    echo ", {key: 'id', label:'View', formatter: operation}];";
    ?>

    // A function which builds the query string
    var myRequestBuilder = function(oState, oSelf) {
        // Get states or use defaults
        oState = oState || {pagination:null, sortedBy:null};
        var startIndex = oState.pagination.recordOffset;
        var count = oState.pagination.rowsPerPage;
    
        // Build custom request
        var request = "<?php echo $this->url; ?>" + 
                      "/startIndex/" + startIndex +
                      "/count/" + count;
        return request;
    };

    var myDataSource = new YAHOO.util.DataSource('/panel/asset/sub/search');
    myDataSource.responseType = YAHOO.util.DataSource.TYPE_JSON;
    myDataSource.responseSchema = {
        resultsList: "table.records",
        metaFields: {
            totalRecords: "table.totalRecords"
        }
    };
    
    // DataTable configuration
    var myConfigs = {
        initialRequest: "<?php echo $this->url ?>/startIndex/0/count/10",
        dynamicData: true, 
        paginator: new YAHOO.widget.Paginator(
            {
                rowsPerPage:10,
                template:"{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
            }
        ),
        generateRequest : myRequestBuilder
    };
    
    var myDataTable = new YAHOO.widget.DataTable("list", myColumnDefs, myDataSource, myConfigs);
    // Update totalRecords on the fly with value from server
    myDataTable.handleDataReturnPayload = function(oRequest, oResponse, oPayload) {
        oPayload.totalRecords = oResponse.meta.totalRecords;
        // display total records in the search results header, if not already present
        var searchResultsHeader = document.getElementById('searchResultsTotalFound');
        if (!searchResultsHeader.firstChild) {
            var totalRecords = oResponse.meta.totalRecords ? oResponse.meta.totalRecords : 0;
            var searchTotalFound = document.createTextNode('(' + totalRecords + ' records found)');
            searchResultsHeader.appendChild(searchTotalFound);
        }
        return oPayload;
    }
    
    myDataTable.subscribe("rowMouseoverEvent", myDataTable.onEventHighlightRow); 
    myDataTable.subscribe("rowMouseoutEvent", myDataTable.onEventUnhighlightRow);
</script>
<?php Fisma_Format_Section::stopSection(); ?>
