<div class="searchFilters">
    <?php
    $listButton = new Fisma_Yui_Form_Button_Link('listButton', 
                                           array('value' => 'Asset List', 
                                                 'href' => '/panel/asset/sub/list'));
    echo $listButton;
    ?>

    <?php if(Fisma_Acl::hasPrivilege('assets', 'create')) {
    $createButton = new Fisma_Yui_Form_Button_Link('createButton', 
                                           array('value' => 'Add Asset', 
                                                 'href' => '/panel/asset/sub/create'));
    echo $createButton;
    } ?>
</div>
