<form action="/panel/asset/sub/list" method="post">
    <table class="searchFilters">
        <tr>
            <td><b>System:</b></td>
            <td><?php echo $this->formSelect('system_id',$this->criteria['system_id'],null, $this->systemList);?></td>
            <td><b>Vendor:</b></td>
            <td><input name="vendor" type="text" id="vendor" value="<?php echo $this->criteria['vendor'];?>"></td>
            <td><b>Product Name:</b></td>
            <td><input type="text" name="product" value="<?php echo $this->criteria['product'];?>"></td>
            <td>&nbsp;</td>
            <td><?php echo new Fisma_Yui_Form_Button_Submit('assetSearchSubmit', array('value' => 'Search')); ?></td>
        </tr>
        <tr>
            <td><b>IP Address:</b></td>
            <td><input type="text" name="ip" value="<?php echo $this->criteria['ip'];?>" maxlength="23"></td>
            <td><b>Port</b></td>
            <td><input type="text" name="port" value="<?php echo $this->criteria['port'];?>" size="10"></td>
            <td><b>Version:</b></td>
            <td><input name="version" type="text" id="version" value="<?php echo $this->criteria['version'];?>"></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
    </table>
</form>
