<?php
/** @codingStandardsIgnoreFile */
foreach ($this->assetColumns as $key=>$column) {
    $outputCols[] = $column;
    $keys[]        = $key;
}

$count_cols = count($outputCols);

require_once ('Spreadsheet/Excel/Writer.php'); // need fix 

$workbook  = new Spreadsheet_Excel_Writer();
$workbook->setVersion(8); // fixes 255 char truncation issue

$worksheet =& $workbook->addWorksheet();

$formatHeader =& $workbook->addFormat(array('Size' => 10,
    'Align' => 'center',
    'Color' => 'white',
    'FgColor' => 'black',
    ));
$formatHeader->setFontFamily('Times New Roman');

$formatTimes =& $workbook->addFormat(array('Size' => 10,
    'Align' => 'center',
    'Color' => 'black',
    'BorderColor '=> 'blue',
    'Bottom'=>1,'Top'=>1,'Left'=>1,'Right'=>1
    ));
$formatTimes->setFontFamily('Times New Roman');

$rowi=0;
$headinfo="Report run time: " . date("Y-m-d H:i:s");
$worksheet->write($rowi++, 0, $headinfo, $formatTimes);
$worksheet->setColumn(0, 0, 20);
$worksheet->setColumn(0, 1, 35);
$worksheet->setColumn(1, 2, 15);
$worksheet->mergeCells(0, 0, 0, $count_cols-1);

$worksheet->writeRow($rowi++, 0, $outputCols, $formatTimes);

foreach ( $this->assetList as $row ) {
    foreach ($keys as $v) {
        $data[] = $row[$v];
    }
    $worksheet->writeRow($rowi++, 0, $data, $formatTimes);
    unset($data);
}

$worksheet->setHeader("                            ".$headinfo);
$workbook->send('assets.xls');
$workbook->close();
