<?php Format_Section::startSection("Asset Inventory"); ?>

<form id="assetresult" method="post" action="/asset/delete">
<table width="98%" align="center" border="0"><tr><td>
    <?php
    //<img src="/images/pdf.gif"> , $this->url.'/format/pdf' , 'document.forms.assetresult.submit();' , '/asset/create'
        echo new Yui_Form_Button_Link('Export PDF', 'pdf', "$this->url/format/pdf", '/images/pdf.gif');
        echo new Yui_Form_Button_Link('Export Excel', 'xls', "$this->url/format/xls", '/images/xls.gif');
        if($this->acl->isAllowed('asset','delete')) {
            echo new Yui_Form_Button_Link('Select All', 'selectAll', '#');
            echo new Yui_Form_Button_Link('Select None', 'selectNone', '#');
            echo new Yui_Form_Button_Link('Delete Selected', 'deleteSelected', '#');
        }
        if($this->acl->isAllowed('asset','create')) {
            echo new Yui_Form_Button_Link('Create Asset', 'createAsset', '/asset/create');
        }
    ?>
        </td><td align="right">
            <b>Page:&nbsp;</b><?php echo $this->links['all'];?>
        </td></tr>
</table>
<table width="98%" align="center" border="0" class="tbframe">
    <tr align="center">
        <th nowrap></th>
        <th>Asset Name</th>
        <th>System</th>
        <th>IP Address</th>
        <th>Port</th>
        <th>Product Name</th>
        <th>Vendor</th>
        <?php if($this->acl->isAllowed('asset','update')){
                 echo'<th nowrap>Edit</th>';
              }
              if($this->acl->isAllowed('asset','read')){
                 echo'<th nowrap>View</th>';
              }
        ?>
    </tr>
    <?php foreach($this->asset_list as $row){ ?>
    <tr>
        <?php if($this->acl->isAllowed('asset','delete')) { ?>
            <td align="center" class="tdc"><input type="checkbox" name="aid[]" 
                value="<?php echo $row['aid'];?>"></td>
        <?php } else { ?>
            <td align="center" class="tdc">&nbsp;</td>
        <?php } ?>
        <td class="tdc">&nbsp;<?php echo $row['asset_name'];?></td>
        <td class="tdc">&nbsp;<?php echo $row['system_name'];?></td>
        <td class="tdc">&nbsp;<?php echo $row['address_ip'];?></td>
        <td class="tdc">&nbsp;<?php echo $row['address_port'];?></td>
        <td class="tdc">&nbsp;<?php echo $row['prod_name'];?></td>
        <td class="tdc">&nbsp;<?php echo $row['prod_vendor'];?></td>
        <?php if($this->acl->isAllowed('asset','update')) { ?>
        <td class="tdc" align="center"><a href="/panel/asset/sub/view/s/edit/id/<?php echo $row['aid'];?>"><img src="/images/edit.png" border="0"></a></td>
        <?php } if($this->acl->isAllowed('asset','read')) { ?>
        <td class="tdc" align="center"><a href="/panel/asset/sub/view/id/<?php echo $row['aid'];?>"><img src="/images/view.gif" border="0"></a></td>
        </tr>
        <?php } ?>
    <?php } ?>
</table>
</form>
<?php Format_Section::stopSection(); ?>