<?php
echo $this->escape($this->partial('asset/navibar.phtml'), 'none');
$operation = '';
$asset = Doctrine::getTable('Asset')->find($this->id);
if (Fisma_Zend_Acl::hasPrivilegeForObject('update', $asset)) {
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
}
if (Fisma_Zend_Acl::hasPrivilegeForObject('delete', $asset)) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}
Fisma_Format_Section::startSection("Asset $operation"); ?>

<div>
    <?php echo $this->escape($this->form, 'none') ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
