<?php Format_Section::startSection("Asset Detail"); ?>

<table width='90%' class='tbframe' cellpadding="5">
    <th align='left' colspan="2">Asset Information</th>
    <tr>
        <td valign='center' align='right'><b>Name: </b></td>
        <td><?php echo $this->asset['name'];?></td>
    </tr>
    <tr>
        <td valign='center' align='right'><b>Created: </b></td>
        <td><?php echo $this->asset['created_date'];?></td>
    </tr>
    <tr>
        <td valign='center' align='right'><b>Source: </b></td>
        <td><?php echo $this->asset['source'];?></td>
    </tr>
    <tr>
        <td valign='center' align='right'><b>System: </b></td>
        <td>(<?php echo $this->asset['sys_nickname'];?>) <?php echo $this->asset['sys_name'];?></td>
    </tr>
    <tr>
        <td valign='center' align='right'><b>Network: </b></td>
        <td>(<?php echo $this->asset['net_nickname']; ?>) <?php echo $this->asset['net_name']; ?></td>
    </tr>
    <tr>
        <td valign='center' align='right'><b>IP Address: </b></td>
        <td><?php echo $this->asset['ip'];?>:<?php echo $this->asset['port'];?></td>
    </tr>
    <tr>
        <td valign='center' align='right'><b>Product: </b></td>
        <td>
            <?php echo $this->asset['prod_vendor'];?>,&nbsp;
            <?php echo $this->asset['prod_name'];?>,&nbsp;
            <?php echo $this->asset['prod_version'];?>
        </td>
    </tr>
</table>

<?php Format_Section::stopSection(); ?>
