<?php if (!empty($this->deficiencies)) : ?>
<chart>
    <license>FTA9HNF7P2O.H4X5CWK-2XOI1X0-7L</license>

    <link_data url="javascript:Fisma.Chart.handleLink('/remediation/searchbox/securityControl/%s', _category_)"
               target="javascript" />

    <context_menu about='false'
                  print='false'
                  full_screen='true'
                  save_as_bmp='false'
                  save_as_jpeg='true'
                  save_as_png='true' />

    <chart_data>
        <row>
            <null />
            <?php
            foreach ($this->deficiencies as $deficiency):
            ?>
                <string><?php echo $this->escape($deficiency['sc_code']); ?></string>
            <?php
            endforeach;
            ?>
        </row>
        <row>
            <string>Open Findings</string>
            <?php
            foreach ($this->deficiencies as $deficiency):
            $tooltip = '1';
                $tooltip = "{$deficiency['sc_code']}: {$deficiency['sc_count']} Finding"
                         . ($deficiency['sc_count'] > 1 ? 's' : '');
            ?>
                <number tooltip="<?php echo $this->escape($tooltip)?>">
                    <?php echo $this->escape($deficiency['sc_count']); ?></number>
            <?php
            endforeach;
            ?>
        </row>
    </chart_data>

    <chart_type>column</chart_type>

    <chart_rect x='10'
                height='165'
                width='785' />

    <axis_value font='arial'
                size='12' />

    <axis_category font='arial'
                   size='10'
                   orientation='vertical_up' />

    <scroll transition='dissolve'
            span='15'
            x='10'
            y='270'
            width='785'
            height='20'
            url_button_1_idle='default'
            url_button_1_over='default'
            url_button_1_press='default'
            url_button_2_idle='default'
            url_button_2_over='default'
            url_button_2_press='default'
            url_slider_body='default'
            url_slider_handle_1='default'
            url_slider_handle_2='default' />

    <legend font='arial'
            size='12'
            layout='vertical'
            bullet='square' />

    <series_color>
        <color>416ed7</color>
    </series_color>
</chart>
<?php else:
echo $this->partial('chart/nodata.xml.phtml', array('width' => '700', 'height' => '300'));
endif; ?>
