<?PHP


/*
** Generate an array of HTML colors to populate table cell backgrounds.
** Array is meant to be passed to the templates driving the generation
** of RAF impact/risk tables.
** Array consists of N-1 default background color values and one 
** highlight value at index M.
**
** Input:
**  num_cells - number of elements in return array
**  highlight_index - zero-based index of cell to receive highlight_color
**  default_color - the color of ordinary cells
**  highlight_color - the color of the highlighted cell
*/

function cell_background_colors ($num_cells, $highlight_index, $default_color='FFFFFF', $highlight_color='CCCCCC') {

  // Initialize array with regular cell color values
  $colors = array_fill(0, $num_cells, $default_color);

  // Set highlighted cell with highlight color value
  $colors[$highlight_index] = $highlight_color;

  return $colors;  
}


/*
** Print the security warning at the bottom of every page of the passed-in
** PDF document.
** Set this as soon as report font has been chosen.
**
** Input:
**  pdf - pdf object generated by Cezpdf or subclass
**  fontsize - size of text font for display
**  xmargin - width of each horizontal margin
**  ymargin - height of each vertical margin
**  pagewidth - width of page in points
**
** Return:
**  None
**2006-2-26 1:57 add print header function by JH, maybe it will be renamed...
*/
function pdfAddWarningFooter($pdf, $text, $fontsize, $xmargin, $ymargin, $pagewidth){
	global $headinfo;
  /*
  ** open document
  */
  $all = $pdf->openObject();

  $pdf->saveState();
  
  $pdf->setStrokeColor(0,0,0,1);
  $linelen = $pagewidth - $xmargin;
  /*
  ** add header line
  ** adjust height from $pagewidth
  */
  
  if ($pagewidth==612) $yoffset=750;
  if ($pagewidth==792) $yoffset=580;
  
	$pdf->line($xmargin,$yoffset,$linelen,$yoffset);
	
  /*
  ** add header info
  */
	$pdf->addText($pagewidth-200,$yoffset+5,$fontsize,$headinfo);

  /* 
  ** add footer line
  */
  
  $pdf->line($xmargin,100,$linelen,100);

  /*
  ** Need to anticipate number of lines that text will split into.
  */
  $LIKELY_NUM_LINES = 5;

  $xoffset = $xmargin;
  $yoffset = $ymargin + ($LIKELY_NUM_LINES * $fontsize) - $fontsize;
  $max_text_width = $pagewidth - (2 * $xmargin);

//  die("ARGH");

  $leftover_text = $text; //$REPORT_FOOTER_WARNING;
  while($leftover_text = $pdf->addTextWrap($xoffset,$yoffset,$max_text_width,$fontsize,$leftover_text,'center') ) {
    $yoffset-=$fontsize;
    }
  $pdf->restoreState();
  
  $pdf->closeObject();
  $pdf->addObject($all,'all');

  /*
  ** Set new bottom margin to leave space for new footer.
  ** Give clearance to bottom line plus an extra line of text.
  */
  $new_bottom_margin = $ymargin + (($LIKELY_NUM_LINES+2) * $fontsize);
  $pdf->ezSetMargins($ymargin,$new_bottom_margin,$xmargin,$xmargin);
}

?>
