<script type="text/javascript" src="/javascripts/account.js"></script>
<?php
echo $this->escape($this->partial('user/searchbox.phtml'), 'none');
Fisma_Format_Section::startSection('User Account Information'); ?>

<?php 
if (!empty($this->requirements)) {
?>
    <p>The password must meet the following complexity criteria:</p>
    <ul>
        <?php foreach ($this->requirements as $requirement): ?>
            <li>
                 <?php echo $this->escape($requirement); ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php 
} 
?>

<div class="form_box">
    <form method="post" action="/panel/User/sub/create">
        <?php 
        echo $this->escape($this->form, 'none');
        echo $this->escape($this->tabView, 'none');
        ?>
    </form>
</div>

<?php 
Fisma_Format_Section::stopSection();
$part = $this->partial('tab-view/roles.phtml', array('roles' => $this->roles, 'id' => $this->id, 'readOnly' => 0));
echo $this->escape($part, 'none');
unset($part);
