<script type="text/javascript" src="/javascripts/account.js"></script>
<?php
echo $this->partial('user/searchbox.phtml');
Fisma_Format_Section::startSection('User Account Information'); ?>

<?php 
if (!empty($this->requirements)) {
?>
    <p>The password must meet the following complexity criteria:</p>
    <ul>
        <?php
        foreach ($this->requirements as $requirement) {
            echo "<li>$requirement";
        }
        ?>
    </ul>
<?php 
} 
?>

<div class="form_box">
    <form method="post" action="/panel/User/sub/edit/id/<?php echo $this->id ?>">
        <?php 
        echo $this->form;
        echo $this->tabView;
        ?>
    </form>
</div>

<?php 
Fisma_Format_Section::stopSection();
echo $this->partial('tab-view/roles.phtml', array('roles' => $this->roles, 'id' => $this->id, 'readOnly' => 0));
?>
