<script type="text/javascript" src="/javascripts/account.js"></script>
<?php 
echo $this->partial('user/searchbox.phtml');
$operation = "[<a href='{$this->viewLink}'>View</a>]";
if (Fisma_Acl::hasPrivilege('account_log', 'read')) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->auditLogLink}'>Audit Log</a>]";
}
Fisma_Format_Section::startSection("User Account Information $operation"); ?>

<?php 
if (!empty($this->requirements)) {
?>
    <p>The password must meet the following complexity criteria:</p>
    <ul>
        <?php
        foreach ($this->requirements as $requirement) {
            echo "<li>$requirement";
        }
        ?>
    </ul>
<?php 
} 
?>

<div class="form_box">
    <?php echo $this->form ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
