<?php 
echo $this->partial('user/searchbox.phtml');
$operation = "[<a href='{$this->viewLink}'>View</a>]";
Fisma_Format_Section::startSection("User Audit Log ($this->username) $operation"); 
?>

<div id="container">
    <table id="reportTable">
        <thead>
            <tr>
                <?php foreach ($this->columns as $column) : ?>
                <th class="tdc"><?php echo $column; ?></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->rows as $row) : ?>
        <tr>
            <?php foreach($row as $cell) : ?>
                <td><?php echo $cell; ?></td>
            <?php endforeach; ?>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php Fisma_Format_Section::stopSection(); ?>

<script type="text/javascript">
// Convert the HTML table above into a YUI table
YAHOO.util.Event.onContentReady('container', function() {
    var myColumnDefs = [
        <?php
        $keys = "";
        foreach ($this->columns as $column) {
            $keys .= "{key:'$column', label:'$column', sortable:true},";
        }
        echo rtrim($keys, ',');
        ?>
    ];

    this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("reportTable"));
    this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
    this.myDataSource.responseSchema = {
        fields: [
            <?php
            $keys = "";
            foreach ($this->columns as $column) {
                $keys .= "{key:'$column'},";
            }
            echo rtrim($keys, ',');
            ?>
        ]
    };

    this.myDataTable = new YAHOO.widget.DataTable("container", myColumnDefs, this.myDataSource, {});
});
</script>
