<?php 
echo $this->escape($this->partial('user/searchbox.phtml'), 'none');
$operation = "[<a href='{$this->viewLink}'>View</a>]";
Fisma_Format_Section::startSection("User Audit Log ($this->username) $operation"); 
?>

<div id="container">
    <table id="reportTable">
        <thead>
            <tr>
                <?php foreach ($this->columns as $column) : ?>
                <th class="tdc"><?php echo $this->escape($column); ?></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->rows as $row) : ?>
        <tr>
            <td><?php echo $this->escape($row['o_createdTs']); ?></td>
            <td><?php echo $this->escape($row['u_username']); ?></td>
            <td><?php echo $this->escape($row['o_message']); ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php Fisma_Format_Section::stopSection(); ?>

<script type="text/javascript">
// Convert the HTML table above into a YUI table
YAHOO.util.Event.onContentReady('container', function() {
    var myColumnDefs = [
        <?php
        $keys = "";
        foreach ($this->columns as $column) {
            $keys .= "{key:'$column', label:'$column', sortable:true},";
        }
        echo $this->escape(rtrim($keys, ','), 'none');
        ?>
    ];

    this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("reportTable"));
    this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
    this.myDataSource.responseSchema = {
        fields: [
            <?php
            $keys = "";
            foreach ($this->columns as $column) {
                $keys .= "{key:'$column'},";
            }
            echo $this->escape(rtrim($keys, ','), 'none');
            ?>
        ]
    };

    this.myDataTable = new YAHOO.widget.DataTable("container", myColumnDefs, this.myDataSource, {});
});
</script>
