<div id='systemUseNotification'>
    <div id="systemName">
        <?php echo Fisma_Controller_Front::readSysConfig('system_name');?>
    </div

    <hr>

    <div><?php echo Fisma_Controller_Front::readSysConfig('use_notification');?></div>

    <hr>

    <p class="message">
        <?php 
            if(isset($this->error) ) {
                $dateString = date('H:i:s');
                echo "$dateString $this->error"; 
            }
        ?>
    </p>

    <form id='loginForm' method="post" action="/user/login">
        <table>
    	    <tr><td>Username:</td><td><input type="text" name="username"
            value="<?php echo isset($this->username)?$this->username:'';?>" ></td></tr>
    	    <tr><td>Password:</td><td><input type="password" name="userpass"
            value="<?php echo isset($this->password)?$this->password:'';?>" ></td></tr>
            <tr><td>&nbsp;</td><td><?php echo new Yui_Form_Button_Submit('loginButton', array('value' => 'Log In')); ?></td>
        </table>
    </form>
</div>




