<style type="text/css">
.block {
	border:1px #44637A solid;
	padding:10px;
}
.block .inline {
	float:left;
	clear:right;
	padding:0 20px;
}
.block #move {
	padding-top:40px;
}
.block #actionButton { padding:10px 20px; clear:left}
.block select {
	width:250px;
}
</style>
<script type="text/javascript">
    function addNotificationEvents(event, obj) {
        var options = YAHOO.util.Selector.query('#availableEvents option');
        for (var i = 0; i < options.length; i ++) {
            if (options[i].selected == true) {
                document.getElementById('existEvents').appendChild(options[i]);
            }
        }
    }
    function removeNotificationEvents(event, obj) {
        var options = YAHOO.util.Selector.query('#existEvents option');
        for (var i = 0; i < options.length; i ++) {
            if (options[i].selected == true) {
                document.getElementById('availableEvents').appendChild(options[i]);
            }
        }
    }
    function saveEvents(event, obj) {
        var options = YAHOO.util.Selector.query('#existEvents option');
        for (var i = 0; i < options.length; i ++) {
            options[i].selected = true;
        }
        document.event_form.submit();
    }
</script>
<?php Fisma_Format_Section::startSection("Notification Events"); ?>

<div class='block'>
    <form name="event_form" id="event_form" enctype="application/x-www-form-urlencoded" method="post">
    <table>
        <tr>
            <td colspan="2" width="700px"><i>You can limit how often the system sends you e-mails:</i></td>
        </tr>
        <tr>
            <td><b>Notify Frequency (hours):</b></td>
            <td><input name="notify_frequency" type="text" value="<?php echo round($this->me->notifyFrequency, 2);?>" size="30"/></td>
        </tr>
        <tr>
            <td colspan="2"><i>If you would like to receive e-mail notifications at an alternate address, enter that address below:</i></td>
        </tr>
        <tr>
            <td><b>Notify E-mail:</b></td>
            <td><input name="notify_email" type="text" value="<?php echo $this->me->notifyEmail;?>" size="30" /></td>
        </tr>
        <tr>
            <td colspan="2"><p>
        <div class="inline"><b>Available events:</b><br/>
            <?php echo $this->formSelect('availableEvents',null, array('multiple'=>"multiple", 'size' => '20'), $this->me->getAvailableEvents())?>        </div>
        <div class="inline" id="move">
            <p>
                <?php echo new Fisma_Yui_Form_Button('addNotificationEvents',
                                              array('label'           => '-->',
                                                    'onClickFunction' => 'addNotificationEvents'));
                ?>
            </p>
            <p>
                <?php echo new Fisma_Yui_Form_Button('removeNotificationEvents',
                                              array('label'           => '<--',
                                                    'onClickFunction' => 'removeNotificationEvents'));
                ?>
            </p>
        </div>
        <div class="inline" id="enable"><b>Selected events:</b><br />
        <?php echo $this->formSelect('existEvents',null, array('multiple' => 'multiple', 'size' => '20'), $this->me->getExistEvents())?></div>
        </td></tr>
        <tr>
            <td colspan="2" align="center">
            <div id="actionButton">
                <?php echo new Fisma_Yui_Form_Button('submit',
                                                array('label' => 'Save',
                                                      'onClickFunction' => 'saveEvents'));?>
            </div>
            </td>
        </tr>
        </table>
    </form>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
