<style type="text/css">
.block {
	border:1px #44637A solid;
	padding:10px;
}
.block .inline {
	float:left;
	clear:right;
	padding:0 20px;
}
.block #move {
	padding-top:40px;
}
.block #actionButton { padding:10px 20px; clear:left}
.block select {
	width:250px;
}
</style>
<script type="text/javascript">
    function addNotificationEvents(event, obj) {
        var options = YAHOO.util.Selector.query('#availableEvents option');
        for (var i = 0; i < options.length; i ++) {
            if (options[i].selected == true) {
                document.getElementById('existEvents').appendChild(options[i]);
            }
        }
    }
    function removeNotificationEvents(event, obj) {
        var options = YAHOO.util.Selector.query('#existEvents option');
        for (var i = 0; i < options.length; i ++) {
            if (options[i].selected == true) {
                document.getElementById('availableEvents').appendChild(options[i]);
            }
        }
    }
    function saveEvents(event, obj) {
        var options = YAHOO.util.Selector.query('#existEvents option');
        for (var i = 0; i < options.length; i ++) {
            options[i].selected = true;
        }
        document.event_form.submit();
    }
</script>
<?php Fisma_Format_Section::startSection("Notification Events"); ?>

<div class='block'>
    <form name="event_form" id="event_form" enctype="application/x-www-form-urlencoded" method="post">
    <table>
        <tr>
            <td colspan="2" width="700px"><i>You can limit how often the system sends you e-mails:</i></td>
        </tr>
        <tr>
            <td><b><label for="notify_frequency">Notify Frequency (hours):</label></b></td>
            <td>
                <input name="notify_frequency" id="notify_frequency" type="text" 
                    value="<?php echo $this->escape(round($this->me->notifyFrequency, 2), 'none')?>" size="30"/>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <i>
                    If you would like to receive e-mail notifications at an alternate address, enter that address below:
                </i>
            </td>
        </tr>
        <tr>
            <td><b><label for="notify_email">Notify E-mail:</label></b></td>
            <td>
                <input name="notify_email" id="notify_email" type="text" 
                    value="<?php echo $this->escape($this->me->notifyEmail);?>" size="30" />
            </td>
        </tr>
        <tr>
            <td colspan="2"><p>
        <div class="left"><b><label for="availableEvents">Available events:</label></b><br/>
            <?php 
            $formSelect = $this->formSelect(
                'availableEvents',
                null, 
                array(
                    'multiple' => 'multiple', 
                    'size' => '20'
                ), 
                $this->me->getAvailableEvents()
            );
            echo $this->escape($formSelect, 'none');
            unset($formSelect);
            ?>
        </div>
        <div class="left" id="move">
            <p>
                <?php 
                $addEvent = new Fisma_Yui_Form_Button('addNotificationEvents',
                                                      array('label' => 'Select',
                                                            'onClickFunction' => 'addNotificationEvents'));
                $addEvent->imageSrc = '/images/right_arrow.png';
                echo $this->escape($addEvent, 'none');
                ?>
            </p>
            <p>
                <?php 
                $removeEvent = new Fisma_Yui_Form_Button('removeNotificationEvents',
                                                         array('label' => 'Remove',
                                                               'onClickFunction' => 'removeNotificationEvents'));
                $removeEvent->imageSrc = '/images/left_arrow.png';
                echo $this->escape($removeEvent, 'none');
                ?>
            </p>
        </div>
        <div class="left" id="enable"><b><label for="existEvents">Selected events:</label></b><br />
        <?php 
            $opts = array('multiple' => 'multiple', 'size' => '20');
            $formSelect = $this->formSelect('existEvents', null, $opts, $this->me->getExistEvents());
            echo $this->escape($formSelect, 'none');
            unset($opts);
            unset($formSelect);
        ?>
        </div>
        </td></tr>
        <tr>
            <td colspan="2" align="center">
            <div id="actionButton">
                <?php
                    $submitButton = new Fisma_Yui_Form_Button(
                        'submit',
                        array('label' => 'Save', 'onClickFunction' => 'saveEvents')
                    );
                    echo $this->escape($submitButton, 'none');
                    unset($submitButton);
                ?>
            </div>
            </td>
        </tr>
        </table>
    </form>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
