<style>
.notice {
    text-align:left;
}
a.button {
    display:inline;
    float:none;
}
</style>
<?php Format_Section::startSection(Config_Fisma::readSysConfig('system_name') . ' Privacy Policy'); ?>

<div class="notice">
<h1>Privacy Policy for <?php echo Config_Fisma::readSysConfig('system_name');?></h1>
<p><?php echo Config_Fisma::readSysConfig('privacy_policy'); ?></p>
</div>

<?php Format_Section::stopSection(); ?>
