<div>
    <i>
        System policy states that you must review and accept the Rules of Behavior
        for <?php echo Config_Fisma::readSysConfig('system_name');?> every
        <?php echo Config_Fisma::readSysConfig('rob_duration');?> days. If you do not accept these
        rules then you will be logged off.
    </i>
</div>

<?php Format_Section::startSection(Config_Fisma::readSysConfig('system_name') . ' Rules of Behavior'); ?>
<div>
    <?php print(Config_Fisma::readSysConfig('behavior_rule')); ?>
</div>

<div>
    <?php
    echo new Yui_Form_Button_Link('cancel', 
                                  array('value' => 'Cancel', 
                                        'href' => '/user/logout'));
    echo new Yui_Form_Button_Link('accept', 
                                  array('value' => 'Accept', 
                                        'href' => '/user/acceptrob'));
    ?>
</div>
<?php Format_Section::stopSection(); ?>

