<div class="searchFilters">
    <div class="left">
        <?php
        $listButton = new Fisma_Yui_Form_Button_Link('listButton', 
                                               array('value' => 'Account List', 
                                                     'href' => '/panel/account/sub/list'));
        echo $listButton;

        if (Fisma_Acl::hasPrivilege('user', 'create')) {
            $createButton = new Fisma_Yui_Form_Button_Link('createButton', 
                                                   array('value' => 'Add Account', 
                                                         'href' => '/panel/account/sub/create'));
            echo $createButton;
        } 
        
        $logsButton = new Fisma_Yui_Form_Button_Link('logsButton', 
                                               array('value' => 'Audit Logs', 
                                                     'href' => '/panel/log/sub/list'));
        echo $logsButton;
        ?>
    </div>
    <div class="right">
        <form name="query" method="post" action="/panel/user/sub/list" style="display:inline">
        <span class="searchField">
            <b><label for="keywords">Search:</label>&nbsp;</b>
            <input id="keywords"
                   name="keywords" 
                   value="<?php echo $this->keywords;?>" 
                   title="Input your query value" 
                   size="20" 
                   maxlength="40" 
                   type="text">
        </span>
        <span id="searchContainer"></span>
        <script type='text/javascript'>
           var save = new YAHOO.widget.Button({
               type: "submit",
               label: "Search",
               value: "Search",
               container: "searchContainer",
               disabled: false
           });
        </script>
        </form>
    </div>
    <div class="clear"></div>
</div>
