<?php
echo $this->partial('user/searchbox.phtml');
$operation = '';
if (Fisma_Acl::hasPrivilegeForObject('update', $this->subject)) {
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
}
if (Fisma_Acl::hasPrivilegeForObject('delete', $this->subject)) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}
if (Fisma_Acl::hasPrivilegeForObject('read', $this->subject)) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->auditLogLink}'>Audit Log</a>]";
}
Fisma_Format_Section::startSection("User Account Information $operation"); ?>

<div>
    <?php echo $this->form; ?>
    <?php echo $this->tabView; ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
