<div class='searchBox'><?php echo $this->escape($this->invalidateCacheButton, 'none'); ?></div>

<?php
Fisma_Format_Section::startSection($this->cacheType . ' Cache Summary');
?>

    <table class="keyValues">
        <?php
        foreach ($this->cacheSummary as $key => $value):
        ?>
            <tr>
                <td><?php echo $this->escape($key)?></td>
                <td>
                    <?php
                    if (is_array($value)):
                        echo $this->escape(print_r($value, true));
                    else:
                        echo $this->escape($value);
                    endif;
                    ?>
                </td>
            </tr>
        <?php
        endforeach;
        ?>
    </table>

<?php
Fisma_Format_Section::stopSection();
Fisma_Format_Section::startSection($this->cacheType . ' Cache Items');

if (isset($this->cacheItems)):
?>
    <table class="keyValues">
        <tr>
            <?php
            foreach ($this->cacheItemHeaders as $header):
            ?>
                <th><?php echo $this->escape($header)?></th>
            <?php
            endforeach;
            ?>
        </tr>

        <?php
        foreach ($this->cacheItems as $cacheItem):
        ?>
            <tr>
                <?php
                foreach ($cacheItem as $itemValue):
                ?>
                    <td><?php echo $this->escape($itemValue) ?></td>
                <?php
                endforeach;
                ?>
            </tr>
        <?php
        endforeach;
        ?>
    </table>

<?php
endif;

Fisma_Format_Section::stopSection();
?>
