<?php Fisma_Format_Section::startSection('Required PHP (version ' . phpversion() . ') Extensions'); ?>
    <div class='approval'>
    <?php foreach ($this->requiredExtensions as $ext):
        $installed = in_array($ext, $this->installedExtensions); ?>
        <div class='approvalStep'>
            <span class='<?php echo $this->escape((($installed) ? "approved" : "denied"), 'none'); ?>'>
                <?php echo $this->escape($ext . " => " . (($installed)
                                                        ? ((strlen(phpversion($ext)) > 0) ? phpversion($ext) : "installed")
                                                        : "missing")); ?>
            </span>
        </div>
    <?php endforeach; ?>
    </div>
<?php Fisma_Format_Section::stopSection(); ?>
</div>
