<?php Fisma_Format_Section::startSection("Finding Source List"); ?>
<div id="list"></div>
<script type="text/javascript">
// Column definitions
var myColumnDefs = [
    {key:"id", label:"id",hidden: true}
    ,{key:"name", label:"Source Name", sortable: true, hidden: false}
    ,{key:"nickname", label:"Nickname", sortable: true, hidden: false}
    ,{key:"desc", label:"Description", sortable: true, hidden: false}
];

    var dataSource = { rows: [
    <?php foreach ($this->source_list as $row) {
          if (!isset($i)) { $i = true; } else { echo ','; } ?>
          {<?php  foreach (array('id', 'name', 'nickname', 'desc') as $val) { 
                    if (!isset($n)) { $n = true; } else { echo ','; }
                    echo $val . ":'" . $row[$val] . "'";
                  }
                unset($n); ?>}
    <?php } unset($i); ?> ] };
    var myDataSource = new YAHOO.util.DataSource(dataSource.rows);
    
    // DataTable configuration
    var myConfigs = {
        dynamicData: false
    };
    var myDataTable = new YAHOO.widget.DataTable("list", myColumnDefs, myDataSource, myConfigs);
    myDataTable.subscribe("rowMouseoverEvent", myDataTable.onEventHighlightRow); 
    myDataTable.subscribe("rowMouseoutEvent", myDataTable.onEventUnhighlightRow);
    <?php if ($this->acl->isAllowed('admin_sources','read')) { ?>
    myDataTable.subscribe("rowClickEvent", 
        function (oArgs) {
            var elTarget = oArgs.target;
            var oRecord = this.getRecord(elTarget);
            document.location = "/panel/source/sub/view/id/" + oRecord.getData("id");
        }
    );
    <?php }?>
</script>
<?php Fisma_Format_Section::stopSection(); ?>
