<?php
$fid_array = array('name'=>'Source Name','nickname'=>'Nickname');
$this->declareVars(array('fid'=>'name'));
?>
<form name="query" method="post" action="/panel/source/sub/list">
    <table class="searchFilters">
            <tr>
                <th>[<a id="finding_source_list" href="/panel/source/sub/list">Finding Source List</a>] (total: <?php echo 
    $this->total;?>)</th>
                <?php if($this->acl->isAllowed('admin_sources', 'create')) { ?>
                <th>[<a id="add_finding_source" href="/panel/source/sub/create" title="Add Finding Source">Add 
    Finding Source</a>]</th>
                <?php } ?>
                <th>
                    <table align="center">
                            <tr height="22">
                                <td><b>Page:&nbsp;</b></td>
                                <td><?php echo $this->links['all'];?></td>
                                <td>|</td>
                            </tr>
                    </table>
                </th>
                <?php if (is_dir(Fisma_Controller_Front::getPath('data') . '/index/source')) { ?>
                <th>
                    <table align="center">
                            <tr>
                                <td><b>Query:&nbsp;</b></td>
                                <td><input name="qv" value="<?php echo $this->qv;?>" title="Input your query value" size="20" maxlength="40" type="text"></td>

                                 <td><input value="Search" title="submit your request" type="submit"></td>
                            </tr>
                    </form>
                    </table>
                </th>
                <?php } ?>
            </tr>
    </table>
</form>
