<?php
echo $this->partial('source/searchbox.phtml');
$operation = '';

if (Fisma_Acl::hasPrivilegeForObject('update', $this->subject)) {
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
}

if (Fisma_Acl::hasPrivilegeForObject('delete', $this->subject)) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}

Fisma_Format_Section::startSection("Finding Source Information $operation"); 
?>

<div>
    <?php echo $this->form ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
