<?php
echo $this->partial('source/searchbox.phtml');
$operation = '';
if (Fisma_Acl::hasPrivilege('finding_sources','update')) {
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
}
if (Fisma_Acl::hasPrivilege('finding_sources','delete')) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}
Fisma_Format_Section::startSection("Finding Source Information $operation"); ?>

<div>
    <?php echo $this->form ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
