<?php if (!empty($this->bureaus)): ?>
<chart>
    <license>FTA9HNF7P2O.H4X5CWK-2XOI1X0-7L</license>
    <link_data url="javascript:pieChartClick(_col_)" target="javascript" />

    <chart_data>
        <row>
            <null />
            <?php foreach ($this->bureaus as $bureau): ?>
                <string><?php echo $this->escape($bureau['bureau_nickname']); ?></string>
            <?php endforeach; ?>
    	</row>

    	<row>
    	    <string>Incidents Reported</string>
    	    <?php
            foreach ($this->bureaus as $bureau):
                $numberTooltip = $bureau['i_count'] . ' Incidents Reported';
            ?>
                <number tooltip='<?php echo $this->escape($numberTooltip); ?>'>
                    <?php echo $this->escape($bureau['i_count']); ?></number>
            <?php
            endforeach;
            ?>	    
    	</row>
    </chart_data>

    <chart_grid_h thickness='1' />

    <chart_type>column</chart_type>

	<series set_gap='10' />

    <chart_rect x='50'
                height='165' 
                width='825' />

    <axis_category font='arial' 
                   orientation='diagonal_up' />

    <legend layout='vertical'
            bullet='square' />

    <series_color>
        <color>416ed7</color>
    </series_color>
</chart>
<?php else:
echo $this->partial('chart/nodata.xml.phtml', array('width' => '900', 'height' => '300'));
endif; ?>
