<chart>
    <license>FTA9HNF7P2O.H4X5CWK-2XOI1X0-7L</license>
    <link_data url="javascript:pieChartClick(_col_)" target="javascript" />

    <chart_data>
        <row>
            <null />
            <?php
            foreach ($this->results as $result):
                print "<string>{$result['month']}</string>";
            endforeach;
            ?>
    	</row>
    	<row>
    	    <string>Incidents Reported</string>
    	    <?php
            foreach ($this->results as $result):
            ?>
                <number tooltip='<?php echo $result['count']; ?> Incidents'>
                    <?php echo $result['count']; ?></number>
            <?php
            endforeach;
            ?>	    
    	</row>
    </chart_data>

    <chart_grid_h thickness='0' />

    <chart_type>column</chart_type>
	<chart_pref rotation_x='20' rotation_y='40' drag='false' />

	<series bar_gap='0' set_gap='20' />

    <chart_label color="000000"
                 position="outside"
                 />

    <series_color>
        <color>ff3333</color>
    </series_color>

</chart> 
