<?php
$sendTestEmailBtn = new Fisma_Yui_Form_Button('columnOptions',
                                           array('label' => 'Test Configuration',
                                                 'onClickFunction' => 'Fisma.ShowRecipientDialog.init'));
Fisma_Format_Section::startSection("E-mail Configuration " . $sendTestEmailBtn); ?>

<div class="block">
<?php
    echo $this->form;
?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>
