<script type="text/javascript">
function discardChanges(event) {
    window.location.reload();
}
</script>
<div class="toolbar">
    <?php
        $discardButton = new Fisma_Yui_Form_Button('discardChanges',
                                             array('label' => 'Discard Changes', 
                                                   'onClickFunction' => 'discardChanges'));
        echo $this->escape($discardButton, 'none');
    ?>
</div>

<?php echo $this->escape($this->tabView, 'none'); ?>
