<script type="text/javascript">
function discardChanges(event) {
    window.location.reload();
}
</script>
<div class="toolbar">
    <?php
        $discardButton = new Fisma_Yui_Form_Button('discardChanges',
                                             array('label' => 'Discard Changes', 
                                                   'onClickFunction' => 'discardChanges'));
        echo $discardButton;
    ?>
</div>
<div id="tabContainer">
    <!-- YUI will load the tabview into this div -->
</div>
<script type="text/javascript">
    /* Configuration for the tabview */
    YAHOO.util.Event.onDOMReady(function () {
        var tabView = new YAHOO.widget.TabView();

        // When a tab is loaded for the first time, this function is called to set up highlighting, editable fields,
        // and executing scripts that are loaded inside the tab (YUI does not execute these script nodes on its own)
        var prepareTab = function(args) {
            setupEditFields();

            // Notice that we are eval'ing any script nodes loaded into this tab. This is only safe as long as
            // we know exactly which URLs we are loading into the tabview. Otherwise we might inadertently execute
            // a 3rd party script.
            var tabContainer = document.getElementById('tabContainer');
            var scriptNodes = tabContainer.getElementsByTagName('script');
            for (var i=0; i < scriptNodes.length; i++) {
                if (scriptNodes[i].getAttribute('executeFlag') != 'true') {
                    try {
                        eval(scriptNodes[i].text);
                    } catch (e) {
                        alert('Not able to execute one of the scripts embedded in this page: '
                              + e.message);
                    } 
                    // Set a flag that prevents this script from being executed more than once
                    scriptNodes[i].setAttribute('executeFlag', 'true');
                }
            }
        }
        
        // When the active tab changes, store the active tab in a cookie so that it can be restored
        // in between page refreshes.
        var handleTabChange = function(args) {
            YAHOO.util.Cookie.set("activeTab", args.newValue, { path: '/' });
        }
        
        // Finding tab
        var generalTab = new YAHOO.widget.Tab({
            label: 'General Policies',
            dataSrc: '/config/general',
            cacheData: true
        });
        generalTab.subscribe("dataLoadedChange", prepareTab);
        tabView.addTab(generalTab);
    
        var privacyTab = new YAHOO.widget.Tab({
            label: 'Privacy Policy',
            dataSrc: '/config/privacy',
            cacheData: true
        });
        privacyTab.subscribe("dataLoadedChange", prepareTab);        
        tabView.addTab(privacyTab);
    
        var contactTab = new YAHOO.widget.Tab({
            label: 'Technical Contact Information',
            dataSrc: '/config/contact',
            cacheData: true
        });
        contactTab.subscribe("dataLoadedChange", prepareTab);                
        tabView.addTab(contactTab);

        var notificationTab = new YAHOO.widget.Tab({
            label: 'E-mail Configuration',
            dataSrc: '/config/notification',
            cacheData: true
        });
        notificationTab.subscribe("dataLoadedChange", prepareTab);                
        tabView.addTab(notificationTab);

        var passwordTab = new YAHOO.widget.Tab({
            label: 'Password Policies',
            dataSrc: '/config/password',
            cacheData: true
        });
        passwordTab.subscribe("dataLoadedChange", prepareTab);                
        tabView.addTab(passwordTab);

        <?php if ('ldap' == Configuration::getConfig('auth_type', true)) { ?>
            var ldapTab = new YAHOO.widget.Tab({
                label: 'LDAP Configurations',
                dataSrc: '/config/ldaplist',
                cacheData: true
            });
            ldapTab.subscribe("dataLoadedChange", prepareTab);                
            tabView.addTab(ldapTab);
        <?php } ?>

        tabView.subscribe('activeIndexChange', handleTabChange);
        tabView.appendTo('tabContainer');

        // Tab is selected based on the hash appended to the URL, or if no hash is present,
        // then by the cookie.
        var tab = location.hash.substring(1);
        if (!YAHOO.util.Cookie.get("activeTab")) {
            YAHOO.util.Cookie.set("activeTab", 0, {path: '/'}); 
        }
        tab = YAHOO.util.Cookie.get("activeTab");
        tabView.selectTab(tab);
    });
</script>
