<?php 
Fisma_Format_Section::startSection('LDAP Configurations</b>&nbsp;[<a href="/config/ldapupdate">New</a>]'); 
?>

<div class="block">
<table width="100%" class="tbframe">
<tr>
    <th>LDAP Connection</th>
    <th>Domain Name</th>
    <th>bindRequiresDn</th>
    <th>accountFilterFormat</th>
    <th>Edit</th>
    <th>Del</th>
</tr>
<?php 
foreach ($this->ldaps as $opt) { 
?>
    <tr>
      <td class="tdc"><?php echo $this->escape($opt['url'])?></td>
      <td class="tdc"><?php echo $this->escape($opt['accountDomainName'])?></td>
      <td class="tdc"><?php echo $this->escape($opt['bindRequiresDn']?'yes':'no', 'none')?></td>
      <td class="tdc"><?php echo $this->escape($opt['accountFilterFormat'])?></td>
      <td class="tdc">
        <a href="/config/ldapupdate/id/<?php echo $this->escape($opt['id'])?>"
           title="edit the LDAP configuration">
        <img src="/images/edit.png" border="0"></a>
    </td>
    <td class="tdc">
        <a href="/config/ldapdel/id/<?php echo $this->escape($opt['id'])?>">
        <img src="/images/del.png" border="0"></a>
    </td>
  </tr>
<?php
}
?>
</table>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
