<script LANGUAGE="JavaScript" type="text/javascript" src="/javascripts/jquery/jquery.form.js"></script>

<script>
    $(document).ready(function(){
        $("#validateLDAP").click(function(){
            $("#ldapUpdate").ajaxSubmit({url:"/config/ldapvalid/format/html",
                                success: ldapResult});
        });
    });

    function ldapResult(responseText, statusText)
    {
        message(responseText);
    }
</script>
<?php Format_Section::startSection("LDAP Configurations <a href="/panel/config/">Back</a>
                                   <button id="validateLDAP">Test the configuration</button>"); ?>

<div class="block">
<?php
    $this->form->setAttrib('id', 'ldapUpdate');
    echo $this->form;
?>
</div>

<button id="validateLDAP">Test the configuration</button>
