<?php 
$validateLDAP = new Fisma_Yui_Form_Button('columnOptions',
                                           array('label' => 'Test Configuration', 
                                                 'onClickFunction' => 'validateLDAP'));

Fisma_Format_Section::startSection('LDAP Configurations <a href="/panel/config/">[Back]</a>' . $validateLDAP); ?>

<div class="block">
<?php
    $this->form->setAttrib('id', 'ldapUpdate');
    echo $this->form;
?>
</div>
<script>
    var validateLDAP = function(){
        var form = document.getElementById('ldapUpdate');
        YAHOO.util.Connect.setForm(form);
        YAHOO.util.Connect.asyncRequest('POST', '/config/ldapvalid/format/html', {
            success:function (o){ldapResult(o.responseText, o.statusText)},
            failure: handleFailure});
    }
    function ldapResult(responseText, statusText)
    {
        message(responseText);
    }
</script>
