<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version58 extends Doctrine_Migration_Base
{
    public function up()
    {
		$this->addColumn('system', 'sdlcphase', 'enum', '', array(
             'values' => 
             array(
              0 => 'initiation',
              1 => 'development',
              2 => 'implementation',
              3 => 'operations',
              4 => 'disposal',
             ),
             'default' => 'operations',
             'notnull' => '1',
             'comment' => 'System Development Life Cycle Phase',
             ));
    }

    public function down()
    {
		$this->removeColumn('system', 'sdlcphase');
    }
}
