<?php
// @codingStandardsIgnoreFile
/**
 * Copyright (c) 2008 Endeavor Systems, Inc.
 *
 * This file is part of OpenFISMA.
 *
 * OpenFISMA is free software: you can redistribute it and/or modify it under the terms of the GNU General Public 
 * License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * OpenFISMA is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more 
 * details.
 *
 * You should have received a copy of the GNU General Public License along with OpenFISMA.  If not, see 
 * {@link http://www.gnu.org/licenses/}.
 */

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version59 extends Doctrine_Migration_Base
{
    public function up()
    {
		$this->addColumn('system', 'sdlcphase', 'enum', '', array(
             'values' => 
             array(
              0 => 'initiation',
              1 => 'development',
              2 => 'implementation',
              3 => 'operations',
              4 => 'disposal',
             ),
             'default' => 'operations',
             'notnull' => '1',
             'comment' => 'System Development Life Cycle Phase',
             ));
    }

    public function down()
    {
		$this->removeColumn('system', 'sdlcphase');
    }
}
