<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version107 extends Doctrine_Migration_Base
{
    public function up()
    {
		$this->addColumn('configuration', 'session_inactivity_notice', 'integer', '2', array(
             'notblank' => '1',
             'unsigned' => '1',
             'default' => '0',
             'comment' => 'Session timeout (seconds)',
             ));
    }

    public function down()
    {
		$this->removeColumn('configuration', 'session_inactivity_notice');
    }
}
