<?php
// @codingStandardsIgnoreFile
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version118 extends Doctrine_Migration_Base
{
    public function up()
    {
		$this->changeColumn('evaluation', 'name', '255', 'string', array(
             'notnull' => '1',
             ));
		$this->changeColumn('evaluation', 'nickname', '255', 'string', array(
             'notnull' => '1',
             ));
		$this->changeColumn('evaluation', 'precedence', '8', 'integer', array(
             'notnull' => '1',
             'comment' => 'The order in which this evaluation is positioned relative to the others in its group, starting at 0',
             ));
		$this->changeColumn('evaluation', 'approvalgroup', '', 'enum', array(
             'values' => 
             array(
              0 => 'action',
              1 => 'evidence',
             ),
             'notnull' => '1',
             'comment' => 'Which approval group this evaluation belongs to. "Action" is short for course of action and "evidence" refers to evidence artifacts.',
             ));
		$this->changeColumn('evaluation', 'eventid', '8', 'integer', array(
             'notnull' => '1',
             ));
		$this->changeColumn('evaluation', 'privilegeid', '8', 'integer', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        // nothing to do
    }
}
