<table  width="778" align="center" cellspacing="0" cellpadding="0">
    <tr>
        <td colspan="2"><div class="installer">
                <h4>Checking File and Directory Permissions</h4>
                <ul class="nolist">
                    <?php
                        foreach ($this->writables as $f) {
                            echo $this->escape('<li class="ok">', 'none');
                            echo $this->escape($f);
                            echo $this->escape(' is writable</li>', 'none');
                        }
                        foreach ($this->notwritables as $f) {
                            echo $this->escape('<li class="failure">', 'none');
                            echo $this->escape($f);
                            echo $this->escape(' is not writable</li>', 'none');
                        }
              ?>
                </ul>
            </div></td>
    </tr>
    <tr>
        <td width='50%'>
            <div class="back"><a class="button" href="<?=$this->escape($this->back, 'none')?>">Back</a></div>
        </td>
        <td width='50%' ><div class="next">
            <?php 
            if ( empty( $this->next ) ) {
                echo $this->escape('<button onclick="javascript:location.reload();">Refresh</button>', 'none');
            } else {
                echo $this->escape('<a class="button" href="', 'none');
                echo $this->escape($this->next, 'none');
                echo $this->escape('">Next</a>', 'none');
            }
            ?>
        </div></td>
    </tr>
</table>
