<table  width="100%" align="center" cellspacing="0" cellpadding="0">
    <tr>
        <td><div class="installer">
                <h4> Install complete </h4>
                <ul class="nolist">
                    <li><u><b>Your site</b></u></li>
                    <li>
                        <p> Click <a href='<?php echo $this->escape($this->next, 'none')?>'>HERE</a> to
                            see the home page of your site. </p>
			<p>You may log in with the
							username "root" and the password that you have set.</p>
                    </li>
                    <li> <u><b>Support</b></u></li>
                    <li>
                        <p> Visit <a href='http://www.openfisma.org/' target='_blank'>OpenFISMA.org</a> </p>
                    </li>
                </ul>
            </div></td>
    </tr>
</table>
