[database]
adapter=mysqli 
params.host=<?php echo $this->escape($this->dsn['host'], 'none')?> 
params.port=<?php echo $this->escape($this->dsn['port'], 'none')?> 
params.username=<?php echo $this->escape($this->dsn['name_c'], 'none')?> 
params.password=<?php echo $this->escape($this->dsn['pass_c'], 'none')?> 
params.dbname=<?php echo $this->escape($this->dsn['dbname'], 'none')?> 

[general]
hostUrl=<?php echo $this->escape($this->hostUrl, 'none')?>
encrypt=<?php echo $this->escape($this->encrypt, 'none')?>
<?php if (isset($this->encryptKey)): ?>
encryptKey=<?php echo $this->escape($this->encryptKey, 'none')?>
<?php endif; ?>

