<form method="post" action="<?php echo $this->escape($this->next, 'none')?>">
    <input type='hidden' name='dsn[encrypt]' value="<?php echo $this->escape($this->dsn['encrypt'])?>" />
    <?php 
    if (!empty($this->dsn['encryptKey'])) { 
    ?>
        <input type='hidden' name='dsn[encryptKey]' value="<?php echo $this->escape($this->dsn['encryptKey'])?>" />
    <?php 
    } 
    ?>
    <input type='hidden' name='dsn[type]' value="<?php echo $this->escape($this->dsn['type'])?>" />
    <input type='hidden' name='dsn[host]' value="<?php echo $this->escape($this->dsn['host'])?>" />
    <input type='hidden' name='dsn[port]' value="<?php echo $this->escape($this->dsn['port'])?>" />
    <input type='hidden' name='dsn[uname]' value="<?php echo $this->escape($this->dsn['uname'])?>" />
    <input type='hidden' name='dsn[upass]' value="<?php echo $this->escape($this->dsn['upass'])?>" />
    <input type='hidden' name='dsn[dbname]' value="<?php echo $this->escape($this->dsn['dbname'])?>" />
    <input type='hidden' name='dsn[adminpwd]' value="<?php echo $this->escape($this->dsn['adminpwd'])?>" />
    <input type='hidden' name='dsn[name_c]' value="<?php echo $this->escape($this->dsn['name_c'])?>" />
    <input type='hidden' name='dsn[pass_c]' value="<?php echo $this->escape($this->dsn['pass_c'])?>" />
    <table width="100%" align="center" cellspacing="0" cellpadding="0">
        <tr>
            <td colspan="2"><div class="installer">
                    <h4>General settings</h4>
                    <table border='0' cellpadding='0' cellspacing='0' valign='top' width='100%'>
                        <tr>
                            <td class='bg2'>
                                <table width='100%' 
                                       border='0' 
                                       cellpadding='4' 
                                       cellspacing='1' 
                                       style="TABLE-LAYOUT:fixed;word-break:break-all;word-wrap:break-word;">
                                    <tr>
                                        <td width="50%" class='bg3'><b>Encrypt Type</b></td>
                                        <td width="50%" class='bg1'>
                                            <?php echo $this->escape($this->dsn['encrypt'])?>
                                        </td>
                                    </tr>
                                    <?php 
                                    if (!empty($this->dsn['encryptKey'])) { 
                                    ?>
                                        <tr>
                                            <td width="50%" class='bg3'><b>Encrypt Key</b></td>
                                            <td width="50%" class='bg1'>
                                                <?php echo $this->escape($this->dsn['encryptKey'])?>
                                            </td>
                                        </tr>
                                    <?php 
                                    } 
                                    ?>
                                    <tr>
                                        <td width="50%" class='bg3'><b>Database</b></td>
                                        <td width="50%" class='bg1'><?php echo $this->escape($this->dsn['type'])?></td>
                                    </tr>
                                    <tr>
                                        <td class='bg3'><b>Database Hostname</b></td>
                                        <td class='bg1' style="word-break:break-all;">
                                            <?php echo $this->escape($this->dsn['host']); ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class='bg3'><b>Database Service Port</b></td>
                                        <td class='bg1' style="word-break:break-all;">
                                            <?php echo $this->escape($this->dsn['port']); ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class='bg3'><b>Database Username</b></td>
                                        <td class='bg1' style="word-break:break-all;">
                                            <?php echo $this->escape($this->dsn['uname']); ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class='bg3'><b>Database Password</b></td>
                                        <td class='bg1' style="word-break:break-all;"> ******     </td>
                                    </tr>
                                    <tr>
                                        <td class='bg3'><b>Database Name</b></td>
                                        <td class='bg1' style="word-break:break-all;">
                                            <?php echo $this->escape($this->dsn['dbname']); ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class='bg3'><b>Create User for new Database</b></td>
                                        <td class='bg1' style="word-break:break-all;">
                                            <?php echo $this->escape($this->dsn['name_c']); ?>

                                        </td>
                                    </tr>
                            </table></td>
                        </tr>
                    </table>
                </div></td>
        </tr>
        <tr>
            <td width='50%'>
                <div class="back">
                    <a class="button" href="<?php echo $this->escape($this->back, 'none')?>" >Back</a>
                </div>
            </td>
            <td width='50%'><div class="next"><input class="button" type='submit' name='submit' value='Next' />
                </div></td>
        </tr>
    </table>
</form>
