
<form method="post" action="<?php echo $this->escape($this->next, 'none')?>">
    <table align="center" cellspacing="0" cellpadding="0">
        <tr>
            <td colspan="2"><div class="installer">
                    <h4>General Settings</h4>
                    <table cellspacing='5' >
                        <tr valign='top' align='left'>
                            <td class='head'><b><label for="encrypt">Encrypt Type</label></b></td>
                            <td class='even'>
                                <select size='1' name='dsn[encrypt]' id='encrypt'>
                                    <option value='sha1'>sha1</option>
                                    <?php 
                                    if (extension_loaded('php_mcrypt')) { 
                                    ?>
                                        <option value='sha256' selected='selected'>sha-256</option>
                                    <?php 
                                    } 
                                    ?>
                                </select>
                            </td>
                        </tr>

                        <tr valign='top' align='left' id="encryptKey" style="display:none">
                            <td class='head'><b><label for="dsn[encryptKey]">Encrypt Key</label></b></td>
                            <?php $encKeyValue = isset($this->dsn['encryptKey']) ? $this->dsn['encryptKey'] : ''; ?>
                            <td class='even'>
                                <input type='text' 
                                       name='dsn[encryptKey]' 
                                       id='dsn[encryptKey]'
                                       size='30' 
                                       maxlength='100' 
                                       value="<?php echo $this->escape($encKeyValue)?>"/>
                                <?php 
                                if (isset($this->message['encryptKey'])) {
                                    echo $this->escape(' <span class="notice">*</span>', 'none');
                                }
                                ?>
                            </td>
                        </tr>
                        <tr valign='top' align='left'>
                            <td class='head'><b><label for="database">Database Product</label></b></td>
                            <td class='even'><select  size='1' name='dsn[type]' id='database'>
                                    <option value='mysql' selected='selected'>mysql</option>
                                </select>                            </td>
                        </tr>
                        <tr valign='top' align='left'>
                            <td class='head'><b> <label for="host">Host Address/Name</label></b><br />
                                <span style='font-size:85%;'>i.e localhost or 192.168.1.1</span> </td>
                            <td class='even'>
                                <input type='text' 
                                       name='dsn[host]' 
                                       id='host'
                                       size='30' 
                                       maxlength='100' 
                                       value="<?php echo $this->escape($this->dsn['host'])?>" />
                                <?php 
                                if (isset($this->message['host'])) {
                                    echo $this->escape(' <span class="notice">*</span>', 'none');
                                }
                                ?>
                            </td>
                        </tr>
                        <tr valign='top' align='left'>
                            <td class='head'><b> <label for="port">Database Port</label></b></td>
                            <td class='even'>
                                <input type='text' 
                                       name='dsn[port]' 
                                       id='port' 
                                       size='30' 
                                       maxlength='100' 
                                       value="<?php echo $this->escape($this->dsn['port'])?>" /> 
                                <?php 
                                if (isset($this->message['port'])) {
                                    echo $this->escape(' <span class="notice">*</span>', 'none');
                                }
                                ?>
                            </td>
                        </tr>
                        <tr valign='top' align='left'>
                            <td class='head'><b><label for="uname">Database Username</label></b><br />
                                <span style='font-size:85%;'>User account must be able to create databases.</span> </td>
                                <td class='even'>
                                    <?php $unameValue = isset($this->dsn['uname'])? $this->dsn['uname']:''?>
                                    <input type='text' 
                                           name='dsn[uname]' 
                                           id='uname' 
                                           size='30' 
                                           maxlength='100' 
                                           value="<?php echo $this->escape($unameValue)?>" />
                                <?php 
                                if (isset($this->message['uname'])) {
                                    echo $this->escape(" <span class='notice'>*</span>", 'none');
                                }
                                ?>
                            </td>
                        </tr>
                        <tr valign='top' align='left'>
                            <td class='head'><b><label for="upass">Database Password</label></b><br />
                                <span style='font-size:85%;'>Password for user account above.</span> </td>
                            <td class='even'>
                                <?php $upassValue = isset($this->dsn['upass'])? $this->dsn['upass']:'';?>
                                <input type='password' 
                                       name='dsn[upass]' 
                                       id='upass' 
                                       size='30' 
                                       maxlength='100'  
                                       value="<?php echo $this->escape($upassValue)?>"/>
                                <?php 
                                if (isset($this->message['upass'])) {
                                    echo $this->escape(" <span class='notice'>*</span>", 'none');
                                }
                                ?>
                            </td>
                        </tr>
                        <tr valign='top' align='left'>
                            <td class='head'><b><label for="dbname">Database Name</label></b><br />
                                <span style='font-size:85%;'> Name of database, the installer will
                                attempt to create the database if it does not exist</span> </td>
                            <td class='even'>
                                <?php $dbnameValue = isset($this->dsn['dbname'])?$this->dsn['dbname']:''; ?>
                                <input type='text' 
                                       name='dsn[dbname]' 
                                       id='dbname' 
                                       size='30' 
                                       maxlength='100'  
                                       value="<?php echo $this->escape($dbnameValue)?>" />
                                <?php 
                                if (isset($this->message['dbname'])) {
                                    echo $this->escape(" <span class='notice'>*</span>", 'none');
                                }
                                ?>                            
                            </td>
                        </tr>
                        <tr valign='top' align='left'>
                            <td class='head'><b><label for="adminpwd">Admin(Root) Pwd</label></b><br />
                                <span style='font-size:85%;'> Pwd of administrator</span> </td>
                            <td class='even'>
                                <input type='password' 
                                       name='dsn[adminpwd]' 
                                       id='adminpwd' 
                                       size='30' 
                                       maxlength='100'  
                                       value="" />
                            </td>
                        </tr>
                    </table>
                </div>
        </tr>
        <tr>
            <td width='50%'>
                <div class="back">
                    <a class="button" href="<?php echo $this->escape($this->back, 'none')?>">Back</a>
                </div>
            </td>
            <td width="50%"><div class="next">
                    <input class="button" type='submit' name='submit' value='Next' />
                </div></td>
        </tr>
    </table>
</form>
