<?php
$class = ($this->checklist['connection']=='ok' || $this->checklist['creation']=='ok') ? 'ok' : 'failure';
?>
<table width="100%" align="center" cellspacing="0" cellpadding="0">
    <tr>
        <td colspan="2"><div class="installer">
                <h4> Initial Database </h4>
                <ul class="nolist">
                    <li class="<?=$this->escape($class, 'none') ?>"> 
                        Database <?=$this->escape($this->dbname) ?>'s <?=$this->escape($this->method) ?> 
                    </li>
                    <?php 
                    if ( $this->dsn['name_c'] != $this->dsn['uname'] ) { 
                    ?>
                    <li class="<?=$this->escape($this->checklist['grant'], 'none')?>"> 
                        Create account <?=$this->escape($this->dsn['name_c']) ?> and grant all privilege
                        of <?=$this->escape($this->dsn['dbname'])?> to it </li>
                    <?php 
                    } 
                    ?>
                    <li class="<?=$this->escape($this->checklist['schema'], 'none')?>"> Creating
                        tables and populating initial data</li> 
                    <li class="<?=$this->escape($this->checklist['savingconfig'], 'none')?>"> Creating
                        config file </li>
                </ul>
                <?php 
                if (!empty($this->message)) { 
                ?>
                    <div class="errorbox"><?=$this->escape($this->message) ?></div>
                <?php 
                } 
                ?>
            </div>
        </td>
    </tr>
    <tr>
        <td width='50%'>
            <div class="back"><a class="button" href="<?=$this->escape($this->back, 'none')?>">Back</a></div>
        </td>
        <td width='50%'>
            <div class="next"><a class="button" href="<?=$this->escape($this->next, 'none')?>">Next</a></div>
        </td>
    </tr>
</table>
