<?php Fisma_Format_Section::startSection('Redirection to External Website'); ?>

<p>
    <b>
    You are leaving our web site. The web site you have selected is an external one located on 
    another server. We have no responsibility for any external web site. We neither endorse the 
    information, content, presentation, or accuracy nor make any warranty, express or implied, 
    regarding any external site.
    </b>
</p>

<p>
    <a href="<?php echo $this->escape($this->url, 'none');; ?>">Click Here To Continue To External Website</a>
</p>

<?php Fisma_Format_Section::stopSection(); ?>
