<div class="searchBox">
    <p>
        <span class="searchField">
            <b>The next quarterly FISMA report is due on: <?php echo $this->escape($this->nextQuarterlyReportDate)?></b>
        </span>
        <?php
            $quarterlyButton = new Fisma_Yui_Form_Button_Link('quarterly',
                                                array('value' => 'Generate Quarterly Report',
                                                      'href' => "/finding/report/fisma-quarterly/format/xls"));
            echo $this->escape($quarterlyButton, 'none');
        ?>
    </p>
    
    <p>
        <span class="searchField">
            <b>The next annual FISMA report is due on: <?php echo $this->escape($this->nextAnnualReportDate) ?></b>
        </span>
        <?php
            $annualButton = new Fisma_Yui_Form_Button_Link('annual',
                                                array('value' => 'Generate Annual Report',
                                                      'href' => "/finding/report/fisma-annual/format/xls"));
            echo $this->escape($annualButton, 'none');
        ?>
    </p>
</div>
