<?php if (isset($this->orgTypeFilter)): ?> 
    <div  class="searchBox">
        <?php echo $this->escape($this->organizationTypeForm, 'none'); ?>
    <div class="clear"></div>        
</div>
<?php endif; ?>

<div class="searchBox">
    <p>
        <span class="searchField">
            <b>The next quarterly FISMA report is due on: <?php echo $this->escape($this->nextQuarterlyReportDate)?></b>
        </span>
        <?php
            $quarterlyButton = new Fisma_Yui_Form_Button_Link('quarterly',
                                                array('value' => 'Generate Quarterly Report',
                                                      'href' => "/finding/report/fisma-quarterly/format/xls"));
            echo $this->escape($quarterlyButton, 'none');
        ?>
    </p>
    
    <p>
        <span class="searchField">
            <b>The next annual FISMA report is due on: <?php echo $this->escape($this->nextAnnualReportDate) ?></b>
        </span>
        <?php
            $annualButton = new Fisma_Yui_Form_Button_Link('annual',
                                                array('value' => 'Generate Annual Report',
                                                      'href' => "/finding/report/fisma-annual/format/xls"));
            echo $this->escape($annualButton, 'none');
        ?>
    </p>
</div>

<?php if (isset($this->orgTypeFilter)): ?>

<script type="text/javascript">

    YAHOO.util.Event.onDOMReady(function () {
        var organizationTypeElement = YAHOO.util.Dom.get('orgTypeFilter');
        var storageNamespace = "<?php echo $this->escape($this->namespace); ?>";
        var orgTypeStorage = new Fisma.PersistentStorage(storageNamespace);
        var orgTypeId = orgTypeStorage.get('orgType');

        if (!YAHOO.lang.isUndefined(orgTypeId) && orgTypeId) {
            for (var i=0; i < organizationTypeElement.options.length; i++) {
                if (organizationTypeElement.options[i].value === orgTypeId) {
                    organizationTypeElement.options[i].selected = true;
                    break;
                }
            }
        }        

        var config = {namespace : storageNamespace, 
                      url : "<?php echo $this->escape($this->url); ?>"}; 
        YAHOO.util.Event.addListener("orgTypeFilter", "change", Fisma.Util.organizationTypeHandle, config);
    });


</script>

<?php endif; ?>
