<?php
echo $this->escape($this->uploadPanelButton, 'none');

Fisma_Format_Section::startSection('System Documentation');
?>

<table border="1" class="systemDocuments">
    <tr>
        <th>File Name</th>
        <th>Size</th>
        <th>Version</th>
        <th>Version Notes</th>
        <th>Last Modified By User</th>
        <th>Last Modified Date</th>
        <th>View History</th>
    </tr>

<?php
foreach ($this->documents as $document) {
?>
    <tr>
        <td>
            <a href="/system/download-document/id/<?=$this->escape($document->id)?>">
                <img src="<?=$this->escape($document->getIconUrl())?>">
                <div><?=$this->escape($document->DocumentType->name)?></div>
            </a>
        </td>
        <td><?=$this->escape($document->getSizeKb())?></td>
        <td align='center'><?=$this->escape($document->version)?></td>
        <td><?=$this->escape($document->description, 'none')?></td>
        <td><?=$this->escape($document->User->username)?></td>
        <td><?=$this->escape($document['updated_at'])?></td>
        <td><a href='/panel/system-document/sub/view/id/<?=$this->escape($document->id)?>'>Version History</a></td>
    </tr>
<?php
}
?>

</table>

<?php
Fisma_Format_Section::stopSection();
?>
