<script type="text/javascript">
function showUploadPanel() {
    panel('Upload Document', document.body, '/system/upload-document-form/id/<?php echo $this->organization->id; ?>', null, executeScript);
}

function executeScript() {
    var scriptEl = document.getElementById('uploadDocumentScript');
    if (scriptEl.getAttribute('executeFlag') != 'true') {
        try {
            eval(scriptEl.text);
        } catch (e) {
            alert('Not able to execute one of the scripts embedded in this page: '
                  + err.description);
        } 
        // Set a flag that prevents this script from being executed more than once
        scriptEl.setAttribute('executeFlag', 'true');
    }
}
</script>

<?php
$uploadPanelButton = new Fisma_Yui_Form_Button('uploadPanelButton', 
                                               array('label' => 'Upload Document', 
                                                     'onClickFunction' => 'showUploadPanel'));
print $uploadPanelButton;

Fisma_Format_Section::startSection('System Documentation');
?>

<table border="1" class="systemDocuments">
    <tr>
        <th>File Name</th>
        <th>Size</th>
        <th>Version</th>
        <th>Version Notes</th>
        <th>Last Modified By User</th>
        <th>Last Modified Date</th>
        <th>View History</th>
    </tr>

<?php
foreach ($this->documents as $document) {
    print "<tr>"
        . "<td><a href='/system/download-document/id/{$document->id}'>"
        . "<img src='{$document->getIconUrl()}'>"
        . "<div>{$document->DocumentType->name}</div></a></td>"
        . "<td>{$document->getSizeKb()}</td>"
        . "<td align='center'>{$document->version}</td>"
        . "<td>{$document->description}</td>"
        . "<td>{$document->User->username}</td>"
        . "<td>{$document->updated_at}</td>"
        . "<td><a href='/panel/system-document/sub/view/id/$document->id'>Version History</a></td>"
        . "</tr>";
}
?>

</table>

<?php
Fisma_Format_Section::stopSection();
?>
