<?php
Fisma_Format_Section::startSection('Confidentiality');
?>
<table class="keyValues">
    <tr>
        <td>Confidentiality: </td>
        <td>
            <?php
            if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
            ?>
            <span id="confidentiality" 
                  class="editable" 
                  target="confidentiality" 
                  name="confidentiality" 
                  type="select" 
                  href="/metainfo/list/o/confidentiality/format/html/">
                <?php echo $this->escape($this->system->confidentiality); ?>&nbsp;
            </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->escape($this->system->confidentiality); ?>&nbsp;
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>Description: </td>
        <td>
            <?php
            if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
            ?>
            <div id="confidentialityDescription" 
                  class="editable" 
                  target="confidentialityDescription" 
                  name="confidentialityDescription" 
                  type="textarea" 
                  rows="4"
                  cols="80">
                <?php echo $this->escape($this->system->confidentialityDescription, 'none'); ?>&nbsp;
            </div>
            <?php
            } else {
            ?>
            <div>
                <?php echo $this->escape($this->system->confidentialityDescription, 'none'); ?>&nbsp;
            </div>
            <?php
            }
            ?>
        </td>
    </tr> 
</table>
<?php
Fisma_Format_Section::stopSection();
Fisma_Format_Section::startSection('Integrity');
?>
<table class="keyValues">   
    <tr>
        <td>Integrity: </td>
        <td>
            <?php
            if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
            ?>
            <span id="integrity" 
                  class="editable" 
                  target="integrity" 
                  name="integrity" 
                  type="select" 
                  href="/metainfo/list/o/integrity/format/html/">
                  <?php echo $this->escape($this->system->integrity); ?>&nbsp;
            </span>
            <?php
            } else {
            ?>
            <span>
                  <?php echo $this->escape($this->system->integrity); ?>&nbsp;
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>Description: </td>
        <td>
            <?php
            if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
            ?>
            <div id="integrityDescription" 
                  class="editable" 
                  target="integrityDescription" 
                  name="integrityDescription" 
                  type="textarea" 
                  rows="4"
                  cols="80">
                  <?php echo $this->escape($this->system->integrityDescription, 'none'); ?>&nbsp;
            </div>
            <?php
            } else {
            ?>
            <div>
                  <?php echo $this->escape($this->system->integrityDescription, 'none'); ?>&nbsp;
            </div>
            <?php
            }
            ?>
        </td>
    </tr>    
</table>
<?php
Fisma_Format_Section::stopSection();
Fisma_Format_Section::startSection('Availability');
?>
<table class="keyValues">    
    <tr>
        <td>Availability: </td>
        <td>
            <?php
            if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
            ?>
            <span id="availability" 
                  class="editable" 
                  target="availability" 
                  name="availability" 
                  type="select" 
                  href="/metainfo/list/o/availability/format/html/">        
            <?php echo $this->escape($this->system->availability); ?>&nbsp;
            </span>
            <?php
            } else {
            ?>
            <span>        
            <?php echo $this->escape($this->system->availability); ?>&nbsp;
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>Description: </td>
        <td>
            <?php
            if ($this->acl()->hasPrivilegeForObject('update', $this->organization)) {
            ?>
            <div id="availabilityDescription" 
                  class="editable" 
                  target="availabilityDescription" 
                  name="availabilityDescription" 
                  type="textarea" 
                  rows="4"
                  cols="80">
                  <?php echo $this->escape($this->system->availabilityDescription, 'none'); ?>&nbsp;
            </div>
            <?php
            } else {
            ?>
            <div>
                  <?php echo $this->escape($this->system->availabilityDescription, 'none'); ?>&nbsp;
            </div>
            <?php
            }
            ?>
        </td>
    </tr>
</table>
<?php
Fisma_Format_Section::stopSection();
Fisma_Format_Section::startSection('FIPS-199 Security Categorization');
?>
<table class="keyValues">
    <tr>
        <td>FIPS-199 Categorization: </td>
        <td>
            <?php echo $this->escape($this->system->fipsCategory); ?>
        </td>
    </tr>
</table>
<?php
Fisma_Format_Section::stopSection();
?>
