<?php
Fisma_Format_Section::startSection('FISMA Data');
?>
<table class="keyValues">
    <tr>
        <td>Agency or Contractor System: </td>
        <td>
            <span 
            <?php
            if ($this->acl->hasPrivilegeForObject('update', $this->organization)) {
            ?>
                  id="controlledBy" 
                  class="editable" 
                  target="controlledBy" 
                  name="controlledBy" 
                  type="select" 
                  href="/metainfo/list/o/controlledBy/format/html/"
            <?php 
            }
            ?>>
                  <?php echo $this->escape($this->system->controlledBy); ?>&nbsp;
            </span>
        </td>
    </tr>
    <tr>
        <td>Last Security Authorization Date: </td>
        <td>
            <span 
                <?php
                if ($this->acl->hasPrivilegeForObject('update', $this->organization)) {
                ?>
                    id="securityAuthorizationDt" 
                    class="editable date" 
                    target="securityAuthorizationDt" 
                    name="securityAuthorizationDt" 
                    type="text"
                <?php 
                }
                ?>>
                <?php echo $this->escape($this->system->securityAuthorizationDt); ?>&nbsp;
            </span>
        </td>
    </tr>    
    <tr>
        <td>Last Contingency Plan Test Date: </td>
        <td>
            <span 
            <?php
            if ($this->acl->hasPrivilegeForObject('update', $this->organization)) {
            ?>
                id="contingencyPlanTestDt" 
                  class="editable date" 
                  target="contingencyPlanTestDt" 
                  name="contingencyPlanTestDt" 
                  type="text"
            <?php 
            }
            ?>>                  
                 <?php echo $this->escape($this->system->contingencyPlanTestDt); ?>&nbsp;
            </span>
        </td>
    </tr>
    <tr>
        <td>Last Self-Assessment Date: </td>
        <td>
            <span 
            <?php
            if ($this->acl->hasPrivilegeForObject('update', $this->organization)) {
            ?>
                id="controlAssessmentDt" 
                  class="editable date" 
                  target="controlAssessmentDt" 
                  name="controlAssessmentDt" 
                  type="text"
            <?php 
            }
            ?>>
                  
                 <?php echo $this->escape($this->system->controlAssessmentDt); ?>&nbsp;
            </span>
        </td>
    </tr>    
    <tr>
        <td>Contains Federal Information in Identifiable Form: </td>
        <td>
            <span 
            <?php
            if ($this->acl->hasPrivilegeForObject('update', $this->organization)) {
            ?>
                id="hasFiif" 
                  class="editable" 
                  target="hasFiif" 
                  name="hasFiif" 
                  type="select" 
                  href="/metainfo/list/o/yesNo/format/html/"
            <?php 
            }
            ?>>                  
                  <?php echo $this->escape($this->system->hasFiif); ?>&nbsp;
            </span>
        </td>
    </tr>
    <tr>
        <td>
            <?php 
                $tooltip = new Fisma_Yui_Tooltip('hasPii', 'Contains Personally Identifiable Information (PII): ',
                    "<p>PII is defined as information which can be used to distinguish or trace an individual's"
                  . " identity, such as their name, social security number, biometric records, etc. alone, or when"
                  . " combined with other personal or identifying information which is linked or linkable to a specific"
                  . " individual, such as date and place of birth, mother’s maiden name, etc.</p>");
                echo $this->escape($tooltip, 'none');
            ?>
        </td>
        <td>
            <span 
            <?php
            if ($this->acl->hasPrivilegeForObject('update', $this->organization)) {
            ?>
                id="hasPii" 
                  class="editable" 
                  target="hasPii" 
                  name="hasPii" 
                  type="select" 
                  href="/metainfo/list/o/yesNo/format/html/"
            <?php 
            }
            ?>>                  
                  <?php echo $this->escape($this->system->hasPii); ?>&nbsp;
            </span>
        </td>
    </tr>        
    <tr>
        <td>Privacy Impact Analysis (PIA) required: </td>
        <td>
            <span 
            <?php
            if ($this->acl->hasPrivilegeForObject('update', $this->organization)) {
            ?>
            id="piaRequired" 
                  class="editable" 
                  target="piaRequired" 
                  name="piaRequired" 
                  type="select" 
                  href="/metainfo/list/o/yesNo/format/html/"
            <?php 
            }
            ?>>                  
                  <?php echo $this->escape($this->system->piaRequired); ?>&nbsp;
            </span>
        </td>
    </tr>
    <tr>
        <td>URL for the PIA: </td>
        <td>
            <span 
            <?php
            if ($this->acl->hasPrivilegeForObject('update', $this->organization)) {
            ?>
                id="piaUrl" 
                  class="editable" 
                  target="piaUrl" 
                  name="piaUrl" 
                  type="text"
            <?php 
            }
            ?>>
                  
                <?php
                    if (!empty($this->system->piaUrl)) {
                        $piaLink = '<a href="/redirect/redirect/?url='
                           . urlencode($this->system->piaUrl)
                           . '">'
                           . $this->system->piaUrl
                           . '</a>';
                        echo $this->escape($piaLink, 'none');
                    }
               ?>&nbsp;
            </span>
        </td>
    </tr>
    <tr>
        <td>System Of Record Notice (SORN) required: </td>
        <td>
            <span 
            <?php
            if ($this->acl->hasPrivilegeForObject('update', $this->organization)) {
            ?>
                id="sornRequired" 
                  class="editable" 
                  target="sornRequired" 
                  name="sornRequired" 
                  type="select" 
                  href="/metainfo/list/o/yesNo/format/html/"
            <?php 
            }
            ?>>                  
                  <?php echo $this->escape($this->system->sornRequired); ?>&nbsp;
            </span>
        </td>
    </tr>
    <tr>
        <td>URL for the SORN: </td>
        <td>
            <span 
            <?php
            if ($this->acl->hasPrivilegeForObject('update', $this->organization)) {
            ?>
                id="sornUrl" 
                  class="editable" 
                  target="sornUrl" 
                  name="sornUrl" 
                  type="text"
            <?php 
            }
            ?>>
                  
                <?php
                    if (!empty($this->system->sornUrl)) {
                        $sornLink = '<a href="/redirect/redirect/?url='
                           . urlencode($this->system->sornUrl)
                           . '">'
                           . $this->system->sornUrl
                           . '</a>';
                        echo $this->escape($sornLink, 'none');
                    }
                ?>&nbsp;
            </span>
        </td>
    </tr>
    <tr>
        <td>
            <?php 
                $tooltip = new Fisma_Yui_Tooltip('ex53upi', 'Exhibit 53 Unique Project Identifier: ',
                    "<p>Each federal agency reports its IT Investment Portfolio annually to the Office of Management"
                  . " and Budget (OMB) via an Exhibit 53. The Exhibit 53 provides budget estimates for all IT"
                  . " investments and identifies those that are major investments.</p><p>By completing an Exhibit 53,"
                  . " the agency meets the Clinger-Cohen Act of 1996 requirements to provide a full and accurate"
                  . " accounting of IT investments for the agency. OMB uses the Exhibit 53 to create an overall"
                  . " \“Federal IT Investment Portfolio\” published"
                  . " as part of the President’s Budget.</p><p>The UPI"
                  . " always has the following format: xxx-xx-xx-xx-xx-xxxx-xx</p><p>OpenFISMA will format the number"
                  . " for your properly if you type it without the dashes.</p>");
                echo $this->escape($tooltip, 'none');
            ?>
        </td>
        <td>
            <span 
            <?php
            if ($this->acl->hasPrivilegeForObject('update', $this->organization)) {
            ?>
                id="uniqueProjectId" 
                  class="editable" 
                  target="uniqueProjectId" 
                  name="uniqueProjectId" 
                  type="text"
            <?php 
            }
            ?>>
                  
                  <?php echo $this->escape($this->system->uniqueProjectId); ?>&nbsp;
            </span>
        </td>
    </tr>
</table>
<?php
Fisma_Format_Section::stopSection();
?>
