<?php Fisma_Format_Section::startSection("System List"); ?>
<div id="list"></div>
<script type="text/javascript">
// Column definitions
var myColumnDefs = [
    {key:"id", label:"id",hidden: true}
    ,{key:"name", label:"System Name", sortable: true, hidden: false}
    ,{key:"nickname", label:"Acronym", sortable: true, hidden: false}
    ,{key:"organization", label:"Organization", sortable: true, hidden: false}
    ,{key:"confidentiality", label:"Confidentiality", sortable: true, hidden: false}
    ,{key:"integrity", label:"Integrity", sortable: true, hidden: false}
    ,{key:"availability", label:"Availability", sortable: true, hidden: false}
    ,{key:"type", label:"Type", sortable: true, hidden: false}
];

    var dataSource = { rows: [
    <?php foreach ($this->system_list as $row) {
          if (!isset($i)) { $i = true; } else { echo ','; } ?>
          {<?php  foreach (array('id', 'name', 'nickname',
                                 'organization', 'confidentiality',
                                 'integrity', 'availability', 'type') as $val) { 
                    if (!isset($n)) { $n = true; } else { echo ','; }
                    echo $val . ":'" . $row[$val] . "'";
                  }
                unset($n); ?>}
    <?php } unset($i); ?> ] };
    var myDataSource = new YAHOO.util.DataSource(dataSource.rows);
    
    // DataTable configuration
    var myConfigs = {
        dynamicData: false
    };
    var myDataTable = new YAHOO.widget.DataTable("list", myColumnDefs, myDataSource, myConfigs);
    myDataTable.subscribe("rowMouseoverEvent", myDataTable.onEventHighlightRow); 
    myDataTable.subscribe("rowMouseoutEvent", myDataTable.onEventUnhighlightRow);
    <?php if ($this->acl->isAllowed('admin_systems','read')) { ?>
    myDataTable.subscribe("rowClickEvent", 
        function (oArgs) {
            var elTarget = oArgs.target;
            var oRecord = this.getRecord(elTarget);
            document.location = "/panel/system/sub/view/v/view/id/" + oRecord.getData("id");
        }
    );
    <?php }?>
</script>
<?php Fisma_Format_Section::stopSection(); ?>
