<?php
$this->placeholder('prepend')->captureStart();
?>
<?php Format_Section::startSection("System Administration"); ?>

<table class="tipframe" align="center"  width="98%" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <th>[<a id="system_list" href="/panel/system/sub/list">System List</a>] (total: <?php echo $this->total;?>)</th>
            <?php if($this->acl->isAllowed('admin_systems', 'create')) { ?>
            <th>[<a id="add_system" href="/panel/system/sub/create" title="add new Systems">Add System</a>]</th>
            <?php } ?>
            <th>
                <table align="center">
                    <tbody>
                        <tr height="22">
                            <td><b>Page:&nbsp;</b></td>
                            <td><?php echo $this->links['all'];?></td>
                            <td>|</td>
                        </tr>
                    </tbody>
                </table>
            </th>
            <th>
                <table align="center">
                <form name="query" method="post" action="/panel/system/sub/list">
                    <tbody>
                        <tr>
                            <td><b>Query:&nbsp;</b></td>
                            <td><input name="qv" value="<?php echo $this->qv;?>" title="Input your query value" size="20" maxlength="40" type="text"></td>

                             <td><input value="Search" title="submit your request" type="submit"></td>
                        </tr>
                    </tbody>
                </form>
                </table>
            </th>
        </tr>
    </tbody>
</table>
<?php Format_Section::stopSection(); ?>
<?php $this->placeholder('prepend')->captureEnd() ?>
