<?php
Fisma_Format_Section::startSection('Details');
?>
<table class="keyValues">
    <tr>
        <td>System Name: </td>
        <td>
            <?php
            if (Fisma_Acl::hasPrivilegeForObject('update', $this->organization)) {
            ?>
            <span id="name" class="editable" target="name" name="name" type="text">
                <?php echo $this->escape($this->organization->name); ?>
            </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->escape($this->organization->name); ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>System Nickname: </td>
        <td>
            <?php
            if (Fisma_Acl::hasPrivilegeForObject('update', $this->organization)) {
            ?>
            <span id="nickname" class="editable" target="nickname" name="nickname" type="text">
                <?php echo $this->escape($this->organization->nickname); ?>
            </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->escape($this->organization->nickname); ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>System Type: </td>
        <td>
            <?php
            if (Fisma_Acl::hasPrivilegeForObject('update', $this->organization)) {
            ?>
                <span id="type" 
                      class="editable" 
                      target="type" 
                      name="type" 
                      type="select" 
                      href="/metainfo/list/o/systemType/format/html/">
                    <?php echo $this->escape($this->organization->getOrgTypeLabel()); ?>
                </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->escape($this->organization->getOrgTypeLabel()); ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>Parent Organization: </td>
        <td>
        <?php
            $parentOrganization = $this->organization->getNode()->getParent();

            if (isset($parentOrganization)) {
                $parentOrganizationName = $parentOrganization->nickname . ' - ' . $parentOrganization->name;
                if (Fisma_Acl::hasPrivilegeForObject('read', $parentOrganization)) {
                    $parentOrgType = 'system' == $parentOrganization->orgType ? 'system' : 'organization';
                    echo $this->escape('<a href="/panel/' . $parentOrgType . '/sub/view/id/', 'none');
                    echo $this->escape($parentOrganization->id, 'url');
                    echo $this->escape('">', 'none');
                    echo $this->escape($parentOrganizationName);
                    echo $this->escape('</a>', 'none');
                } else {
                    echo $this->escape($parentOrganizationName);
                }
            } else {
                echo $this->escape('<i>None</i>', 'none');
            }

        ?>
        </td>
    </tr>
</table>
<?php
Fisma_Format_Section::stopSection();

if (Fisma_Acl::hasPrivilegeForObject('update', $this->organization)) {
    Fisma_Format_Section::startSection('System Description', 'system_description');
} else {
    Fisma_Format_Section::startSection('System Description');
}
?>
<div name="description" id="system_description" type="textarea" rows="3" cols="120"> 
    <?php echo $this->escape($this->organization->description, 'none'); ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>
