<script type="text/javascript">

</script>

<?php Fisma_Format_Section::startSection("Internet Explorer: Upload System Documentation"); ?>

<form method="post" 
      action="/system/upload-document/id/<?php echo $this->organizationId; ?>/browser/ie"
      enctype="multipart/form-data">
	<div>
	    <p><b><label for="documentType">*Document Type:</label></b></p>
		<p>
		    <select id="documentType" name='documentTypeId'>
                <?php
                    foreach ($this->documentTypes as $documentType) {
                        print "<option value='$documentType->id'>$documentType->name</option>";
                    }
                ?>
		    </select>    		    
		</p>
	</div>
	<div>
	    <p><b><label for="versionNotes">*Version Notes:</label></b></p>
	    <p><input type="text" id="versionNotes" name='description' size="80"></textarea></p>
	</div>
	<div>
	    <p><b><label for="systemdoc">*Select a File:</label></b></p>
	    <p><input type="file" name="systemdoc" id="systemdoc" size="40"></p>
	    <p><input type="submit" value="Upload"></p>
	</div>
</form>

<?php Fisma_Format_Section::stopSection(); ?>
