<script type="text/javascript">
function discardChanges(event) {
    window.location.reload();
}
</script>

<form enctype="multipart/form-data" action="/panel/system/sub/edit/id/<?php echo $this->organization->id; ?>" 
      method="post">
    <div class="toolbar">
        <?php            
            $discardButton = new Fisma_Yui_Form_Button('discardChanges',
                                                 array('label' => 'Discard Changes', 
                                                       'onClickFunction' => 'discardChanges'));
            echo $discardButton;
            
            echo new Fisma_Yui_Form_Button_Submit('saveChanges', 
                                            array('label' => 'Save Changes'));
        ?>
    </div>
    <div id="tabContainer">
        <!-- YUI will load the tabview into this div -->
    </div>
    <script type="text/javascript">
        /* Configuration for the tabview */
        YAHOO.util.Event.onDOMReady(function () {
            var tabView = new YAHOO.widget.TabView();
        
            // When a tab is loaded for the first time, this function is called to set up highlighting, editable fields,
            // and executing scripts that are loaded inside the tab (YUI does not execute these script nodes on its own)
            var prepareTab = function(args) {
                //highlight(document.getElementById("tabContainer"), 
                //          "<?php echo $this->keywords; ?>");
                
                setupEditFields();
                
                // Notice that we are eval'ing any script nodes loaded into this tab. This is only safe as long as
                // we know exactly which URLs we are loading into the tabview. Otherwise we might inadertently execute
                // a 3rd party script.
                var tabContainer = document.getElementById('tabContainer');
                var scriptNodes = tabContainer.getElementsByTagName('script');
                for (var i=0; i < scriptNodes.length; i++) {
                    if (scriptNodes[i].getAttribute('executeFlag') != 'true') {
                        try {
                            eval(scriptNodes[i].text);
                        } catch (e) {
                            alert('Not able to execute one of the scripts embedded in this page: '
                                  + e.message);
                        } 
                        // Set a flag that prevents this script from being executed more than once
                        scriptNodes[i].setAttribute('executeFlag', 'true');
                    }
                }
            }
            
            // When the active tab changes, store the active tab in a cookie so that it can be restored
            // in between page refreshes.
            var handleTabChange = function(args) {
                YAHOO.util.Cookie.set("systemActiveTab", args.newValue, { path: '/' });
            }

            // Finding tab
            var systemTab = new YAHOO.widget.Tab({
                label: '<?php echo $this->organization->name; ?>',
                dataSrc: '/system/system/id/<?php echo $this->organization->id; ?>',
                cacheData: true
            });
            systemTab.subscribe("dataLoadedChange", prepareTab);
            tabView.addTab(systemTab);

            var fipsTab = new YAHOO.widget.Tab({
                label: 'FIPS-199',
                dataSrc: '/system/fips/id/<?php echo $this->organization->id; ?>',
                cacheData: true
            });
            fipsTab.subscribe("dataLoadedChange", prepareTab);        
            tabView.addTab(fipsTab);

            var fismaTab = new YAHOO.widget.Tab({
                label: 'FISMA Data',
                dataSrc: '/system/fisma/id/<?php echo $this->organization->id; ?>',
                cacheData: true
            });
            fismaTab.subscribe("dataLoadedChange", prepareTab);        
            tabView.addTab(fismaTab);

            var artifactsTab = new YAHOO.widget.Tab({
                label: 'Documentation',
                dataSrc: '/system/artifacts/id/<?php echo $this->organization->id; ?>',
                cacheData: true
            });
            artifactsTab.subscribe("dataLoadedChange", prepareTab);        
            tabView.addTab(artifactsTab);
            
            tabView.subscribe('activeIndexChange', handleTabChange);
            tabView.appendTo('tabContainer');
        
            // Tab is selected based on the hash appended to the URL, or if no hash is present,
            // then by the cookie.
            var tab = location.hash.substring(1);
            if (!tab || tab < 0 || tab > 4) {
                if (YAHOO.util.Cookie.get("currentSystemId") == <?php echo $this->organization->id; ?>) {
                    tab = YAHOO.util.Cookie.get("systemActiveTab");
                } else {
                    YAHOO.util.Cookie.set("currentSystemId", <?php echo $this->organization->id; ?>, {path: '/'});
                    YAHOO.util.Cookie.set("systemActiveTab", 0, {path: '/'}); 
                    tab = 0;
                }
            }
            tabView.selectTab(tab);
        });
    </script>
</form>
