<?php
echo $this->partial('system/searchbox.phtml');

$operation = '';
if (Fisma_Acl::hasPrivilege('system','update')) {
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
}
if (Fisma_Acl::hasPrivilege('system','delete')) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}
Fisma_Format_Section::startSection("System Information $operation"); 
?>
<div>
    <?php echo $this->form ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
